### ISSUE TITLE
getCenter for map & map.getBounds differ

### ISSUE THREAD

**Issue by vchrisb** [mapbox/mapbox-gl-js#10017]
**mapbox-gl-js version**: 1.12.0

**browser**: Chrome

### Steps to Trigger Behavior

 1.Create map
 2. compare `map.getCenter()` with `map.getBounds().getCenter()`
 3.

### Link to Demonstration

https://jsfiddle.net/f0rg5ymz/

### Expected Behavior

`map.getCenter()` and `map.getBounds().getCenter()` return the same value.

### Actual Behavior

Both LngLat objects differ and especially Lat difference is not just a rounding difference.

e.g.: 
`map.getCenter()`: `LngLat {lng: -65.017, lat: -16.457}`
`map.getBounds().getCenter()`: `LngLat {lng: -65.01700000000892, lat: -16.385704037105853}`

**Comment by mourner** [comment]
This is by design, because these are fundamentally different values. `map.getCenter()` returns the location of the center of the screen. `map.getBounds().getCenter()` returns the arithmetic center of the bounding box, which is different from the map center in that the latter depends on the Web Mercator projection (latitude to pixels on screen is not a linear relationship).
