### ISSUE TITLE
Marker position is moving on high zoom level

### ISSUE THREAD

**Issue by vchrisb** [mapbox/mapbox-gl-js#10022]
**mapbox-gl-js version**: 1.6.0

**browser**: chrome

### Steps to Trigger Behavior

 1. create a map with marker
 2. change zoom level from 20 to 20+
 3. see icon move to the bottom

### Link to Demonstration

http://jsfiddle.net/vy1p0mut/

Even in the official demo for custom marker, the marker is moving around: https://docs.mapbox.com/help/tutorials/custom-markers-gl-js/

### Expected Behavior

Marker stays at the same position on all zoom levels.

### Actual Behavior

Marker moves down slightly with increasing zoom level.

**Comment by arindam1993** [comment]
This isn't a bug, the apparent movement of the marker is caused because the surrounding road-widths are defined in pixels, and not in physical size ( like meters). 
As zoom changes the same size in pixels corresponds to varying geographic sizes. 

I modified your fiddle to place the marker at the corner of a polygon http://jsfiddle.net/9z62fmrc/2/, and you can see that it doesnt seem to mover around anymore. This is because sizes of polygons don't change with zoom.
