### ISSUE TITLE
format expression for text-field not working as expected !

### ISSUE THREAD

**Issue by hanaakhoj** [mapbox/mapbox-gl-js#10051]
Hello, 

I've been using @ol-mapbox-style for rendering the map with mapbox style specification object!

The problem is the format expression  (https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/) is not working as expected following the docs !

Here's my code : 

`{
      "id": "sectors_label",
      "type": "symbol",
      "source": "sectors",
      "layout": {
        "text-field": ["format",
          ["get", "label"], {"text-color": "green"},
          "Italy", { "font-scale": 0.5, "text-color": "#ce2b37"} 
        ],
        "text-size": 13,
        "symbol-z-order": "auto",
        "text-font": ["Open Sans Regular", "Arial Unicode MS Regular"]
      }
    }`

here's the output : 

![image](https://user-images.githubusercontent.com/41376971/97181582-bccf3d00-179b-11eb-9502-21a5926d4fd3.png)

Am-I doing it the wrong way?

Thanks in advance

**Comment by ryanhamley** [comment]
Hi @hanaakhoj It's really hard to say what's wrong because you haven't included a working example of the code. I tried your expression with an example and it worked as expected. I'd suggest ensuring that `sectors_label` and `label` are the correct names. We also don't maintain `ol-mapbox-style` so if the problem lies with that library, you may need to open an issue on that repo. If you have further questions, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).

<img width="133" alt="Screen Shot 2020-10-26 at 11 32 24 AM" src="https://user-images.githubusercontent.com/4523080/97213503-ecbc1780-177e-11eb-99c6-85ec623e017c.png">
