### ISSUE TITLE
Why you don't expose `Transform` class?

### ISSUE THREAD

**Issue by jayarjo** [mapbox/mapbox-gl-js#10063]
Why don't you expose `Transform` class? 

As to me - quite handy utility and more importantly can be used without Map, so basically platform agnostic. I personally require some of the conversions that it can do in NodeJS. 

Another great usage scenario would be in Cypress - imitating polygon drawing (for that one will need to convert LatLng to XY coordinates). Main idea of Cypress and e2e testing is to test the app as a blackbox, so while we can grab the reference to the actual mapbox instance and do transformations through it, this will contradict the main idea of e2e testing.

**Comment by mourner** [comment]
We don't expose it separately in public because this class is very convoluted and has a ton of complex logic that may change at any time and properties/methods that only make sense internally, so exposing it would put a strain on our ability to move swiftly with changes to this part of code without worrying about breaking compatibility in a major way.

I think using the exposed `map.transform` is fine if you have a map instance, we just can't guarantee keeping code compatibility going forward.

**Comment by jayarjo** [comment]
You could expose it as a static method at least, since it doesn't really depend on map instance.
