### ISSUE TITLE
Calculate Accurate meter/pixel

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#10067]
**mapbox-gl-js version**:

### Question
From you documentation, https://docs.mapbox.com/help/glossary/zoom-level/. I can refer to different meter/pixel at different zoom-level. Here is my question, can I get the accurate meter/pixel at a specific latitude and zoom-22, suppose 31.99791317674392?
It's a critical issued in my project, because we need very precise meter/pixel.

Please help me. I DO tried to contact with your technical support, no response. I DO search all the related documents, no answer. And there is no phone or customer service.

Please DO NOT close your users' question so hasty, It's so irresponsible. I spend hundred dollars buying your services. I AM your honest user. You CAN NOT close my issue without even reading it.

**Comment by asheemmamoowala** [comment]
@Aiamjay I am closing this here as a duplicate of #10066, #9893 and #9880. Please see https://github.com/mapbox/mapbox-gl-js/issues/10066#issuecomment-720803252 for clarification on why this is closed and how to participate in this project.

**Comment by Aiamjay** [comment]
> @Aiamjay I am closing this here as a duplicate of #10066, #9893 and #9880. Please see [#10066 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/10066#issuecomment-720803252) for clarification on why this is closed and how to participate in this project.

Yes, those questions are all broung up by MYSELF. See the answers below these questions, you will find the only one that may helpful is to read the source code. Are you kidding me?

**Comment by Aiamjay** [comment]
> @Aiamjay I am closing this here as a duplicate of #10066, #9893 and #9880. Please see [#10066 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/10066#issuecomment-720803252) for clarification on why this is closed and how to participate in this project.

This pic is from your documentation, you only list some estimated values, but I need accurate ones. Please DO read my question and do NOT search related question in history issues. ALL releated questions are raised by myself.
![Screen Shot 2020-11-02 at 11 44 03 AM](https://user-images.githubusercontent.com/13723721/97934020-4a290900-1d29-11eb-9d28-0999b16b94e1.png)

**Comment by Aiamjay** [comment]
> @Aiamjay I am closing this here as a duplicate of #10066, #9893 and #9880. Please see [#10066 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/10066#issuecomment-720803252) for clarification on why this is closed and how to participate in this project.

It is true these questions are duplicated question. Because you never answer my quesiont, even the previous ones.

**Comment by Aiamjay** [comment]
> @Aiamjay I am closing this here as a duplicate of #10066, #9893 and #9880. Please see [#10066 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/10066#issuecomment-720803252) for clarification on why this is closed and how to participate in this project.

The only one answer that maybe helpful is this one. He wants me to read the source code. So, one there is a problem, ask your customer to see the source code????????
![Screen Shot 2020-11-02 at 4 39 09 PM](https://user-images.githubusercontent.com/13723721/97934229-f4a12c00-1d29-11eb-864c-b104a97563c6.png)

**Comment by ryanhamley** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/10005#issuecomment-701531544 walks through a formula for calculating meters per pixel at a given latitude and zoom level. The previous answers to your opened issues pointed out other potential ways to find the answer for this question. There are also answers to this question on sites like Stack Overflow.

This issue tracker is for requesting features for GL JS and reporting bugs. We, as a developer team, don't have the resources to offer guidance on implementation details, which is why we suggest contacting Mapbox Support, where a dedicated team can help our customers. As has previously been noted, we do abide by a [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) that we ask our contributors to follow as well. Thanks for being a Mapbox customer and good luck with your app.
