### ISSUE TITLE
Option for increasing the number of tiles buffered at the border of the viewport

### ISSUE THREAD

**Issue by msschl** [mapbox/mapbox-gl-js#10069]
While zooming out a grey border gets visible at the border of the viewport. See image below:

![image](https://user-images.githubusercontent.com/5054780/98004109-d00f8780-1def-11eb-9ceb-2ac483897b30.png)

It would be nice to have an option to increase the number of tiles that get buffered.
Maybe something similar to the `keepbuffer` of [leaflet](https://leafletjs.com/reference-1.7.1.html#gridlayer-keepbuffer)

**Comment by mourner** [comment]
@msschl `keepbuffer` is not about preloading tiles, it's about keeping already loaded ones. In case of GL JS, we already do a good job of cashing tiles for rendering, but we can't afford preloading tiles around the screen because it will affect performance severely for a very minor benefit. Also consider that you would need to preload a lot of tiles to accommodate rapidly zooming out. There's an alternative proposed in #2826 which might be better suited to address this.

**Comment by msschl** [comment]
You're right. I got something mixed up. #2826 is what I'm looking for. Thanks though 👍🏽
