### ISSUE TITLE
[Geolocate Event] - JumpTo location without Animate

### ISSUE THREAD

**Issue by drambourg** [mapbox/mapbox-gl-js#10077]
Hey,

I try to implement a change center on fire Geolocate control. Default result is Fly To user Location with an animated fly.
I don't want it to reduce requests on basemap layer. Just directly go to my defined position, **without an animated fly.**

I would like to Jump To my user Location without any animation. Just Go to and open maps centered on my coordinates.

I tried to set these methodes on geolocate event :
` geolocate && geolocate.on('geolocate', function(e) {`

- map SetCenter w/ navigation.geolocation coordinates retrieved =>  animation result
`map && map.setCenter({lng:position.coords.longitude, lat:position.coords.latitude});`

- JumpTo, mapbox method =>  animation result
`map && map.jumpTo({center: [position.coords.longitude, position.coords.latitude], duration:0});`

- EaseTo, with animation options =>  animation result
` map && map.easeTo({center: [position.coords.longitude, position.coords.latitude], animate : false, duration:0})`

- FitBounds,with animation options => animation result

- Set animate false on map properties =>  animation result

I read a lot issues, but i don't find my solution
I have any more idea...

Someone could help me on my issue, please?

Thanks in advance

**Comment by ryanhamley** [comment]
There's no need to call `setCenter`/`jumpTo`/`easeTo` or listen for the `geolocate` event in this instance since the `GeolocateControl` calls [`fitBounds` internally](https://github.com/mapbox/mapbox-gl-js/blob/c602230de6665359082dfbde562895a31bcfdb38/src/ui/control/geolocate_control.js#L284-L286). The [`GeolocateControl` accepts a `fitBoundsOptions` object](https://docs.mapbox.com/mapbox-gl-js/api/markers/#geolocatecontrol-parameters) as part of its options and this object is passed through to the `fitBounds` call. You can use all available [`fitBounds` options](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#fitbounds) which includes [`AnimationOptions` parameters](https://docs.mapbox.com/mapbox-gl-js/api/properties/#animationoptions), including `animate`. Putting it all together, you can achieve what you want by passing `animate: false` in the `GeolocateControl#options.fitBoundsOptions`. Note for future "how to" questions such as these, we recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!

```
var geolocate = new mapboxgl.GeolocateControl({
    trackUserLocation: true,
    showUserLocation: true,
    fitBoundsOptions: {
        animate: false
    }
});
```

**Comment by drambourg** [comment]
Ok, sorry for the wrong channel for asking this type of question. Noted.
Thank you for answer.
