### ISSUE TITLE
map wont load 404 error GET /mapbox-gl.js.map 404 0.991 ms

### ISSUE THREAD

**Issue by briantran37** [mapbox/mapbox-gl-js#10086]
when i run tileserver-gl, and try to open a vector tile, the map wont load
i get a 404 error
`GET /mapbox-gl.js.map 404 0.991 ms`

can someone help?

**Comment by mourner** [comment]
Perhaps you should submit an issue to `tileserver-gl`? The 404 seems unrelated — it can't access the source map file which is usually used for debugging, but it shouldn't affect GL JS. Since you haven't provided the necessary details prompted in the issue template, and this does not appear to be an issue with GL JS, I'm going to close this.
