### ISSUE TITLE
How does 'linearity' work in dragPan.enable(options)?

### ISSUE THREAD

**Issue by helenezspeer** [mapbox/mapbox-gl-js#10112]
**mapbox-gl-js version**: 1.9.1

### How do we use "linearity"?

I have tried changing the "linearity" option in the dragPanHandler to both very small and very large numbers; in every case, it appears to have no effect. I expected the number to affect the speed of panning relative to mouse movement. How should this work? Can you provide more detail?

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/handlers/#dragpanhandler#enable

**Comment by mourner** [comment]
We should definitely improve the docs to make these clearer. It affects the panning _inertia_ — the movement of the map after you pan it rapidly and then release.  We don't have options to control the speed of panning relative to mouse movement because to keep panning experience usable, the location under cursor must remain there while you drag (similar to how you would drag objects in the physical world).

**Comment by antadam127** [comment]
Have there been any updates to this functionality. We need a feature that allows acceleration while panning, ie the ability to unlink the cursor from the location under the cursor. Similar to the map featured on the Mapbox careers website here: https://www.mapbox.com/careers
