### ISSUE TITLE
Inconsistent rendering of a coalesced image expression

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#10122]
**mapbox-gl-js version**: `v1.12.0`

**browser**: Chrome latest

### Steps to Trigger Behavior

From the link to the demonstration, refresh the page periodically and visit the console.

### Link to Demonstration

https://jsfiddle.net/tristen/4d0zfv1e

![results](https://user-images.githubusercontent.com/61150/98697995-8c62d380-2343-11eb-83f2-23664f761fa1.gif)

### Expected Behavior

A fallback should always be provided.

### Actual Behavior

Inconsistent results where a fallback (`maki:parking-15`) is sometimes used, other times only (`maki_beta:highway-services`) is looked for, no fallback is provided, and a warning is logged in the console.

From @ryanhamley: it looks like a possible race condition between layer embedding and sprite parsing where `coalesce` isn't properly being re-evaluated.

**Comment by ryanhamley** [comment]
After talking with @ansis about this, there seems to be two main possibilities for dealing with this.

1) Wait for the sprite to load before moving forward with tile parsing.

This is likely the simplest implementation. This issue only shows up when image expressions are embedded in a layer in the style; this means that the image, if available, has to be part of the sprite. If the sprite loads and the image still isn't available, we can be confident that the image isn't available. There's a couple of considerations with this. First, we can't assume that a sprite is necessary for parsing tiles, so we'll have to only wait if a sprite is present. Second, this could impact performance since it might delay tile parsing. I think it's worth trying this out and benchmarking it to get a solid idea of the impact.

2) Keep a list of the possible images that image expressions attempted to access and re-check this list on the worker when a tile is parsed. This approach would potentially have significant complexity involved with tracking the list of possible images. It would require either changing the output of the ResolvedImage type and how it's resolved to a string or changing the `availableImages` from an array to probably an object or a class that includes a list of requested images.

I'm going to try 1 first

**Comment by ryanhamley** [comment]
this is closed by https://github.com/mapbox/mapbox-gl-js/pull/10294
