### ISSUE TITLE
get rid of old keep-upright approach

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1020]
background:
By default line labels have `"text-keep-upright": true`. When you rotate far enough for the label to be upside down, if flips to stay upright. Currently this is implemented by having two versions in the buffers. Each version has an angle properties. That version of the label is hidden or shown based on the angle property.

Now that we are redoing placement every time the map rotates we should only write one version to the buffer and now do an angle check in the shaders.

**Comment by kapadia** [comment]
@ansis https://github.com/mapbox/mapbox-gl-js/pull/1026 should address this issue. Symbols are now filtered based on their global orientation.

This was a little weird since there are various conventions being used for rotation. For instance the `placement.angle` (rotation of the map) is specified between `[-π, π]`, whereas the symbol orientation is specified between `[0, 2π]`. Any reason for these differences?

**Comment by ansis** [comment]
done in #1026
