### ISSUE TITLE
Wrong zoom level when setMaxBounds

### ISSUE THREAD

**Issue by rullymartanto** [mapbox/mapbox-gl-js#10209]
"mapbox-gl": "^1.12.0",

when using setMaxBounds
![image](https://user-images.githubusercontent.com/5577057/102203787-960bc800-3efb-11eb-8d72-111efc2c7224.png)

When using fitBounds 

![image](https://user-images.githubusercontent.com/5577057/102203931-c5bad000-3efb-11eb-9d22-c2c6e432eadd.png)

There is a bug or wrong implementation ?

**Comment by andrewharvey** [comment]
also #6969

**Comment by andrewharvey** [comment]
In short the current implementation say ensure that no part of the map shows something outside of the maxBounds, hence to ensure that remains regardless of your bounds aspect ratio and viewport aspect ratio, you won't usually be able to fitBounds to the maxBounds and have all the maxBounds showing (unless their aspect ratio match).

For many use cases, this is not very useful because you still want to let users zoom out to see a whole country in the one view (for example), but not pan outside that country. The current implementation doesn't allow this.

**Comment by mourner** [comment]
Yes, thanks for summarizing this well @andrewharvey — let's keep the discussion centralized in #6969.
