### ISSUE TITLE
map.unproject doesn't handle points with negative y in 2D mode

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#10215]
**mapbox-gl-js version**: v2.0.0

These two lines will produce equal locations on a 2D map such the [simple map example](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/):

```js
map.unproject([0, -1000]);
map.unproject([0, 0]);
```

This behavior broke in https://github.com/mapbox/mapbox-gl-js/commit/28deff46248c1c0ffceb367b206e1945c0b5aa02 due to horizon clamping in `pointCoordinate`:

https://github.com/mapbox/mapbox-gl-js/blob/2fd29deef4a87f2231405042c55a83fa4550f554/src/geo/transform.js#L903-L905

In 2D mode with a top-down map, `horizonOffset` is `0` when the horizon is not visible, so any negative values are clamped. Would not clamping the horizon offset be a suitable fix (e.g. if the horizon is not visible, this value could be negative)?

In particular, this affects some of the camera methods, e.g. `map.panBy([0, 10000])` will only move by half the screen rather than 10k pixels.

cc @astojilj @karimnaaji

**Comment by karimnaaji** [comment]
That's a good catch.

>In 2D mode with a top-down map, horizonOffset is 0 when the horizon is not visible.

I think we should keep that behavior, e.g. `horizonLineFromTop` returning 0 when the horizon isn't visible. As this function does indeed squash this value to 0 on top-down views:
![2020-12-16 11 40 58](https://user-images.githubusercontent.com/7061573/102398385-11b95380-3f94-11eb-9f62-644835e017e8.png)

>Would not clamping the horizon offset be a suitable fix (e.g. if the horizon is not visible, this value could be negative)?

If we are overly clamping that value, are we missing an explicit check against 0? I would think the following to be correct, as it leaves the code path of v1.x untouched:

```
pointCoordinate(p: Point): MercatorCoordinate {
    const horizonOffset = this.horizonLineFromTop();
    if (horizonOffset === 0) { this.rayIntersectionCoordinate(this.pointRayIntersection(p)) }
    const clamped = horizonOffset > p.y ? new Point(p.x, horizonOffset) : p;
    return this.rayIntersectionCoordinate(this.pointRayIntersection(clamped));
}
```

**Comment by arindam1993** [comment]
Yea I don't think we should clamp the screenspace inputs. This was added to prevent `unproject` from returning points behind the camera when the top plane of the frustum  is above parallel.
I think we should clamp the `ray` constructed inside `pointRayIntersection` instead.
https://github.com/mapbox/mapbox-gl-js/blob/2fd29deef4a87f2231405042c55a83fa4550f554/src/geo/transform.js#L846

and pull it down to the horizon if its missing the map plane.

**Comment by MaxGeldner** [comment]
I don't know if I have an error in my thinking (and the behavior I noted is intended), or if the issue is still there to some extend.
For very high negative y values the unprojected coordinate doesn't change. It does though, when setting the x value to very high negative values.

I tried following:
```
map.unproject([0, 0])
nh {lng: 7.815101940341179, lat: 45.763791961400074}

"Setting x value"
map.unproject([-10000, 0])
nh {lng: 7.802518184472206, lat: 45.763791961400074}
map.unproject([-100000, 0])
nh {lng: 7.689264381651299, lat: 45.763791961400074}

"Setting y value"
map.unproject([0, -10000])
nh {lng: 7.815101940341179, lat: 45.76934739986689}
map.unproject([0, -100000])
nh {lng: 7.815101940341179, lat: 45.76934739986689}
```

The result slightly changes when comparing y=0 and y=-10000. The result doesn't change when comparing y=-10000 and y=-10000000.

**Comment by ryanhamley** [comment]
@MaxGeldner you're correct that the outputs stop changing at a certain point with large negative y values. The reason is that they're being clamped to a minimum y value representing the horizon plane at a given pitch. With pitch 0 in one of our debug maps, I tried `map.unproject([0, -100000])`. The `horizonOffset` in line 925 was calculated as `-2114.221613012171` so the y value is clamped to that in line 926. These calculations became necessary when we unlocked high pitches and this approach maintained backwards-compatibility at the expense of the edge case of very large negative y values. Do you have a specific use case for large negative y values that this is blocking?

https://github.com/mapbox/mapbox-gl-js/blob/af83fa8b8f4d4a20525bbe7d9e3ea572cb623492/src/geo/transform.js#L924-L929

**Comment by MaxGeldner** [comment]
@ryanhamley Alright, I understand the issue.
I have following use case: In our application we can have multiple areas on the map where the user can zoom to. These areas area calculated from objects placed in another coordinate system. So we first convert the poisition of the object from our coordinate system to client coords and then to latitude and longitude coordinates via MapBoxs unproject(), to then use the MapBox fitBounds() function. Since the areas the user can zoom to can be really far from each other in the world, we very quickly run into cases, where the client coordinates of an area can have high negative y values (about -100000 and even lower, depending how far the user zoomed in).

In a very brief description: Calculate Bounding box of objects in another coordinate system --> Convert this bbox to client coords --> unproject the vertices client coordinates --> fitBounds() to latlng rectangle

I implemented a workaround to set the maps zoom to 1 converting the coordinates. This works, but seems a bit hacky and, depending of the execution speed of the program, you can see the maps zoom changing while zooming to another area.
