### ISSUE TITLE
Enable pinch-to-zoom, disable scroll zooming

### ISSUE THREAD

**Issue by Jonatan-r** [mapbox/mapbox-gl-js#10227]
This issue / feature request was originally posted by @AndrejGajdos

> **mapbox-gl-js version**: 1.10.1
> 
> ### Question
> Mapbox GL provides option `scrollZoom` to enable/disable zooming on scroll and pinch-to-zoom events. Is it possible to allow zooming on pinch-to-zoom and disable scrolling on scroll event?
> 
> ### Links to related documentation
> https://docs.mapbox.com/mapbox-gl-js/api/map/#map#scrollzoom

https://github.com/mapbox/mapbox-gl-js/issues/9921#issue-676004626

It was mistakenly closed by @sgolbabaei 10 Aug, and was commented on again by @AndrejGajdos without any response or reopening.

As @AndrejGajdos wrote: 

> @sgolbabaei I was referring pinch-to-zoom on a touchpad, not a touchscreen. TouchZoomHandler enables pinching on a touchscreen, not touchpad.

Put in another way: The touchpad pinch-to-zoom gesture is _**not**_ the same as the touchscreen pinch-to-zoom.
Hence, there should be an option to separately enabling or disabling the two of them.

**Comment by mourner** [comment]
I've looked into this — turns out that modern browsers [translate touchpad pinch-to-zoom gestures into a scroll `wheel` event](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent) with `ctrl` key pressed. So technically the underlying implementation [is the same](https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/handler/scroll_zoom.js), but we can differentiate between the two by checking for `e.ctrlKey` in the handler.

This seems like a good feature for a contribution — would you like to work on a pull request for this? This would like look as a new option for `scrollZoom`, e.g. `new mapboxgl.Map({scrollZoom: {requireCtrl: true})`.

**Comment by charlesharries** [comment]
Hey--it looks like there hasn't been much movement on this in the past couple months but I'd like to take a swing at implementing this, if that's alright?

This'd be my first contribution to Mapbox GL JS; beyond reading the contribution guidelines and appropriate READMEs, is there anything I ought to know to get started?

**Comment by prsmahajan** [comment]
Hey, I would like to work on this issue, Can anyone suggest to get started?

**Comment by rreusser** [comment]
That's great, @prsmahajan! 🙏  For a start, [CONTRIBUTING.md](https://github.com/mapbox/mapbox-gl-js/blob/main/CONTRIBUTING.md) has a pretty good summary of how to clone the repo and get the debug pages up and running. I think the best place to start is just by first aiming to get things up and running, then start working on a solution, even if it's messy, then rethink it and modify if needed. That's pretty general, but if you have more specific question, don't hesitate to ask!

**Comment by charlesharries** [comment]
I took a swing at this feature back in April [here](https://github.com/mapbox/mapbox-gl-js/pull/10614), using the scroll wheel + `Ctrl` key functionality available in modern browsers (except Safari)—is this still something that Mapbox wants to include in the library? Realise it's a bit of an edge case...

**Comment by prsmahajan** [comment]
I have a question @rreusser ? What changes do you want in this mapbox?

**Comment by tylershuster** [comment]
@mourner @rreusser I'm very interested in this feature. We have maps embedded on pages that we don't want people to get scrolljacked by. We've added zoom control buttons but it's annoying to use pinch-to-zoom only to see the whole page zoom in, instead of just the map.

It looks like @charlesharries has a good solution.
