### ISSUE TITLE
When using marker with vue3.0 and mapbox, the marker position is not correct

### ISSUE THREAD

**Issue by aixinaxc** [mapbox/mapbox-gl-js#10225]
When using marker with vue3.0 and mapbox, the marker position is not correct, and the position will be offset from the map. 
But when using vue2.0, the marker has no problem.

**Comment by mourner** [comment]
Thank you for the report! However, it seems unrelated to the GL JS library itself. There might be some CSS conflict between Mapbox and Vue, but we can't tell because you haven't filled the information prompted in the issue template like a live reproducible test case.

**Comment by aixinaxc** [comment]
Build the project with Vue cli without adding any separate styles.

The div of loading map is：

<div id="map" style='width: 1000px; height: 800px;'></div>

**Comment by mourner** [comment]
Still no reproducible test case, and this is not enough to diagnose the issue 🤷‍♂️

**Comment by Gtanghaibo** [comment]
I have the same issue

**Comment by Gtanghaibo** [comment]
when zooms, the marker can't anchor in the map

**Comment by Gtanghaibo** [comment]
I find a way to fix it, because I forget import mapbox-gl.css file

**Comment by yboussadia** [comment]
I have the same issue with vue 3, the markers not in the map

**Comment by bigmathdev** [comment]
![Captura de tela 2024-07-18 191011](https://github.com/user-attachments/assets/8616c43f-b9f9-44a3-95a0-b763c91d7e99)

I was having the same problem, and it seems that @mourner answer is correct. There is a conflict with the CSS import. I resolved it by importing it in the main.js of my application.

`import 'mapbox-gl/dist/mapbox-gl.css';`

Additionally, the map container needs to be in a fixed position; otherwise, the marker will float over the map. You can set the fixed position with the class:

`.mapboxgl-canvas {
    position: fixed !important;
}`
