### ISSUE TITLE
Mapbox GLJS working fine on chrome but not showing in mozilla?

### ISSUE THREAD

**Issue by bigyanpaudel** [mapbox/mapbox-gl-js#10244]
Hello,

The problem I'm facing is I created a mapbox based Fly to a location in scroll. 
I developed it while viewing in chrome and finally when I'm trying to check the cross browser compatibility, it is not working on Mozilla Firefox. Can  anyone help me?

Here is the link to the page: https://www.pumorijourneys.com/tour-page-2

It's under the 'Navigate Your Destination' Section.

**Comment by mourner** [comment]
I'm not seeing a map on that page in Chrome as well, and it generally produces dozens of JavaScript errors in the console. It's very difficult to diagnose a GL JS issue in these conditions, since there's no minimal test case, but I would guess that the issue is somewhere on your app side, especially considering that the official [scroll story example](https://docs.mapbox.com/mapbox-gl-js/example/scroll-fly-to/) works in all browsers including FF.

**Comment by bigyanpaudel** [comment]
Well sir, I can perfectly view the map on mine maybe something's wrong with your device?  

![screencapture-pumorijourneys-tour-page-2-2020-12-27-18_33_28](https://user-images.githubusercontent.com/34052482/103171114-b596df00-4871-11eb-9446-5008c8e04148.png)

and this is how the map is not visible in firefox:

![Annotation 2020-12-27 183704](https://user-images.githubusercontent.com/34052482/103171185-30f89080-4872-11eb-9f26-17a087e5f75d.png)

So being it the same page I think there is a problem here about it not viewing in Firefox . Would be really grateful if you took a look at it again. Also it works fine locally on Firefox as well but not on the browser.
