### ISSUE TITLE
GeolocateControl: Accuracy circle size is inconsistent

### ISSUE THREAD

**Issue by anderswi** [mapbox/mapbox-gl-js#10276]
**mapbox-gl-js version**:
1.13.0

**browser**:
Chrome 87

### Steps to Trigger Behavior

 1. Add a GeolocateControl to your map, with 'showAccuracyCircle' set to true.
 2. Zoom in slowly at high zoom levels.
 3. Notice the circle size is changing for every update, making the circle flicker. 

### Link to Demonstration

![main_large](https://user-images.githubusercontent.com/35194267/104126780-c27dfd00-535e-11eb-9ca9-77b7127c7402.gif)

### Expected Behavior

The circle size is not affected by zooming.

**Comment by anderswi** [comment]
I could take a stab at a PR if its of interest?

**Comment by ryanhamley** [comment]
It seems likely that this is caused by the `metersToPixel` calculation in `_updateCircleRadius`. We welcome PRs but to be transparent, it's unlikely we'll backport this to any pre-2.0 version.

https://github.com/mapbox/mapbox-gl-js/blob/bdfe181df7071aec5f2277866f2e1e3aab80a63b/src/ui/control/geolocate_control.js#L313-L315
