### ISSUE TITLE
How to get information about the clicked marker in a layer?

### ISSUE THREAD

**Issue by Feduch** [mapbox/mapbox-gl-js#10319]
Hi! 

It`s very fine fine project, thanks!

How to get information about the clicked marker in a geojson layer?

Now I get all features in layer when click on one of markers.

**Comment by mourner** [comment]
It's hard to say for sure since you haven't filled the necessary details prompted by the issue template, but I would assume that you didn't pass the coordinates of the mouse pointer to the `queryRenderedFeatures` method which is used for such queries. Here's an example for this: https://docs.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures/
