### ISSUE TITLE
Turn by turn car animation

### ISSUE THREAD

**Issue by abdulk1** [mapbox/mapbox-gl-js#10312]
Are there any code examples or documentation on how to create the turn by turn car animation that's showcased in this 2019 Mapbox blog? https://www.mapbox.com/blog/contextual-guidance-in-navigation

Or is this not possible to do in mapbox-gl-js and can only be done through ios or the navigation sdk?

**Comment by karimnaaji** [comment]
@abdulk1 We have these example that I can think of that come relatively close to what you're asking https://docs.mapbox.com/mapbox-gl-js/example/free-camera-path/ and https://docs.mapbox.com/mapbox-gl-js/example/live-update-feature/. Otherwise for how-to support and other examples I would directly contact [https://support.mapbox.com](https://support.mapbox.com), we try to triage and only keep bugs or feature request in our issue backlog.
