### ISSUE TITLE
Where is the V1 documentation ?

### ISSUE THREAD

**Issue by c-lambert** [mapbox/mapbox-gl-js#10349]
v^1.13.0:

### Question

We use mapbox-gl v1.13.0+ but we cannot find documentation to maintain the application.
Where can i found the V1 documentation ?

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/

**Comment by ansis** [comment]
We only host the documentation for the latest version

We haven't removed any APIs since v1.13.0 so anything in that version should be documented on the site. Some new functionality has been added but unfortunately it isn't labelled. In general, if it isn't related to 3D terrain it probably existed in v1.13.0.

But it's also possible to build the v1.12 docs locally from https://github.com/mapbox/mapbox-gl-js-docs/tree/533acd5385be25a4b82b2cf458c2ce5b579911ac

The process should look something like this (I didn't test it):
```bash
git clone git@github.com:mapbox/mapbox-gl-js-docs.git
cd mapbox-gl-js-docs
git checkout 533acd5385be25a4b82b2cf458c2ce5b579911ac
npm install
git submodule update --init
npm start
# open http://localhost:8080/mapbox-gl-js/api/
```

**Comment by c-lambert** [comment]
Hello @ansis 

thank you for your help. It's working !

**Comment by iBobik** [comment]
Hi,
mapbox/mapbox-gl-js-docs seems removed.

**Comment by ansis** [comment]
The best place for docs for all versions is https://docs.mapbox.com/mapbox-gl-js/api/

Since we're careful about avoiding breaking changes, almost everything since v1.0.0 should still be documented in these docs.

We're considering add notes about which version each method was added in. In the mean time, almost everything not related to Terrain or FreeCamera should be available in a pre-v2 version. You can check https://github.com/mapbox/mapbox-gl-js/blob/main/CHANGELOG.md to see when anything was added.

Consider updating to the latest to get the latest fixes and optimizations!

**Comment by jkgenser** [comment]
Might be useful to look at the maplibre documentation since that is 1.x still.

I suspect a big motivator for upgrading was to distance themselves from maplibre fork, especially if there weren't breaking changes.  

https://maplibre.org/maplibre-gl-js-docs/api/

**Comment by shamrin** [comment]
@richardkazuomiller Forked mapbox-gl-js-docs repository: https://github.com/maplibre/maplibre-gl-js-docs

**Comment by iBobik** [comment]
@shamrin I can not find v1 there. Is it somewhere else?
