### ISSUE TITLE
Control icons missing for us on versions after 1.5.1

### ISSUE THREAD

**Issue by reecealanboyd** [mapbox/mapbox-gl-js#10360]
**mapbox-gl-js versions**:

Experiencing this issue on 1.13.0 and I tried upgrading to 2.1.0 as well

Downgrading to 1.5.1 [as suggested here](https://github.com/visgl/react-map-gl/issues/952) fixed it (see the **Expected Behavior** image but wanted to see if there was a better way and point out that this issue still exists.

**browser**:

chrome on mac os and safari on mac os

### Link to Demonstration

Control icons missing on our map:

<img width="549" alt="Screen Shot 2021-02-05 at 3 17 39 PM" src="https://user-images.githubusercontent.com/9440683/107091182-f239ec80-67c6-11eb-8c66-7af740ed82a3.png">

### Expected Behavior

<img width="75" alt="Screen Shot 2021-02-05 at 10 01 06 AM" src="https://user-images.githubusercontent.com/9440683/107091164-eb12de80-67c6-11eb-9e43-6201a88559d5.png">

### Actual Behavior

See the lack of control icons in the **Link to Demonstration** section

**Comment by ryanhamley** [comment]
@reecealanboyd Do you have a link to a live code example? We can't diagnose this from a picture. Are you including the `mapbox-gl.css` file? And if you are, are you certain that your app's CSS isn't overriding the control button icon CSS?

**Comment by reecealanboyd** [comment]
@ryanhamley, you can see it if you log into instacart.com, and then select a retailer under **Pickup Options**. I am not certain about the css--digging now.

**Comment by ryanhamley** [comment]
@reecealanboyd I see that you are loading the Mapbox GL JS CSS file although it looks like you're also loading a Mapbox.js CSS file. I'm not sure if that could interfere at all, and of course you may need it if you fall back to Mapbox.js when WebGL isn't available. It's really hard to diagnose any issue in a complex, live application like Instacart; you also linked to react-map-gl above, so it's possible there's a bug in their implementation. I'm fairly confident that this isn't a generic Mapbox GL JS issue though since a basic example of the NavigationControl does not show the error, as seen [here](https://jsbin.com/gobunineco/edit?html,output). Since I'm pretty sure this isn't a bug in GL JS, I'm going to close this issue. What I'd suggest for next steps is contacting [Mapbox Support](https://support.mapbox.com/hc/en-us) who can work to resolve technical issues like this. If it does turn out to be some kind of edge-case bug, please update this ticket and we can re-open it. Thanks!

**Comment by reecealanboyd** [comment]
Makes sense @ryanhamley. Thank you! 🙏
