### ISSUE TITLE
Objects in custom layer flicker when using atmosphere sky layer

### ISSUE THREAD

**Issue by nagix** [mapbox/mapbox-gl-js#10372]
When I add a custom layer to show 3D models using three.js and a sky layer with `'sky-type': 'atmosphere'` to the map, 3D objects flicker when calling `setPaintProperty('sky', 'sky-atmosphere-sun', ...)`. This only happens when the horizon is invisible.

<img src="https://user-images.githubusercontent.com/723188/107318786-83b3a200-6ad8-11eb-86b1-713773cfedba.png" width="45%"> <img src="https://user-images.githubusercontent.com/723188/107318814-94641800-6ad8-11eb-8832-76fc7d359a6b.png" width="45%">

See my CodePen below to reproduce the problem.

**mapbox-gl-js version**: v2.1.1
**three.js version**: any
**browser**: Chrome, Safari, Firefox and Edge

### Link to Demonstration

https://codepen.io/nagixx/pen/yLVJEqr

### Expected Behavior

3D models don't flicker.

**Comment by rreusser** [comment]
I'm still working on exactly why, but adding `gl.cullFace(gl.BACK)` into the render loop removes the flickering.

**Comment by rreusser** [comment]
The fundamental problem is that OpenGL/WebGL is extremely stateful, and each library manages state in its own way, so that getting different WebGL libraries to play well together in the same context is a somewhat common problem.

I'm not certain what `renderer.state.reset()` did in r117, but [r124](https://github.com/mrdoob/three.js/tree/r124) – specifically https://github.com/mrdoob/three.js/pull/20859 – introduces [resetState()](https://threejs.org/docs/index.html#api/en/renderers/WebGLRenderer.resetState) for just this purpose. It's a bit heavy-handed as it flushes Three.js's state cache and causes it to reset each piece of state, ensuring that non of Mapbox's state pollutes Three.js's assumptions about that state.

(Additionally, https://github.com/mrdoob/three.js/pull/21281 and https://github.com/mrdoob/three.js/pull/21295 squashed a few more missing pieces of state, so that it looks like [r126](https://github.com/mrdoob/three.js/releases/tag/r126) is the first version of Three.js for which `resetState` fixes your problem.)

Thus, there are two solutions to this problem, I think:
- Apply one-off state changes (e.g. the `gl.cullFace` fix above) which fixes specific problems. This is lower cost and may work, but it also might result in unexpected glitches.
- Call `renderer.resetState()`, which is somewhat higher cost but hopefully ensures correct state.

**Comment by astojilj** [comment]
@rreusser Nice find.

The place we set front face:

https://github.com/mapbox/mapbox-gl-js/blob/63f39e54e889d573ca627eea86114279e2062895/src/render/draw_sky.js#L115

Code resetting state before custom layer rendering

https://github.com/mapbox/mapbox-gl-js/blob/63f39e54e889d573ca627eea86114279e2062895/src/render/painter.js#L758

seems to be resulting with `gl.disable(gl.CULL_FACE)`. 

https://github.com/mapbox/mapbox-gl-js/blob/63f39e54e889d573ca627eea86114279e2062895/src/gl/value.js#L292

and your analysis shows that there it is needed to call setDefault also for Context.cullFaceSide and Context.frontFace (in addition to disabling cull face).

https://github.com/mapbox/mapbox-gl-js/blob/63f39e54e889d573ca627eea86114279e2062895/src/gl/context.js#L248-L255

Didn't run the code to verify it.

**Comment by rreusser** [comment]
Thanks for the additional sleuthing @astojilj! Do you think this requires a change on the Mapbox side? Here is what Three.js is doing to manage culling:

https://github.com/Mugen87/three.js/blob/643b9ad1d33abf76e24188eed8ec3aae243d658d/src/renderers/webgl/WebGLState.js#L669-L673

My concern is that setting a more common default may reduce the likelihood of problems in common scenarios, but that if you rendered a custom layer with *front* face culling twice in Three.js, setting this default before a custom layer would confuse Three.js as it would still expect front face culling to be active on the second call.

It seems like adding setDefault for culling before custom layers may reduce problems in the most common scenarios and is probably worth adding, if only for predictability, but that `three.renderer.resetState()` might be the only way to really ensure that no incorrect assumptions are made about state.

**Comment by astojilj** [comment]
> It sounds like it would benefit from a small change on the Mapbox side, though does that still leave room for problems?

The idea is to reset GL state to default before passing control over to custom layer, regardless the engine used by custom layer. Note that Three.js is just one of the approaches that could be used to render custom layer: similar code we have in gl-native that can use e.g. plain OpenGL, Metal, SceneKit to render custom layer. We cannot make any assumptions on state of custom layer code but to set GL state to default: `gl.CWW` is [default](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/frontFace) for `gl.frontFace`, gl.BACK is default for gl.cullFace.

**Comment by rreusser** [comment]
Got it, thanks. That makes sense. I submitted #10412 which addresses this. I did some equivocating in that ticket since if external libraries maintain their own concept of state, they may or may not expect things to be in a default state, but if the guiding principle here is that Mapbox ought to hand off in a default state, then that seems very clear and still beneficial for consistency.
