### ISSUE TITLE
Add layer z axis height adjustment interface

### ISSUE THREAD

**Issue by N3GIS** [mapbox/mapbox-gl-js#10409]
You write all the pos in the vertex.glsl as 0, causing the layers to fail to adjust its height in 3D space.

Suggest to expose the pos in the vertex.glsl, provide the interface that can js call, easy to adjust the height of the layer.

**Comment by karimnaaji** [comment]
Please review and follow our [Feature Request template](https://github.com/mapbox/mapbox-gl-js/issues/new?assignees=&labels=&template=Feature_request.md), I'm not sure to understand the motivation for what you're proposing. Providing possible use cases illustrating the request would also be helpful. I'll close this issue due to lack of information, but feel free to reopen with more details.

**Comment by N3GIS** [comment]
![image](https://user-images.githubusercontent.com/7942057/109086196-1e051e00-7746-11eb-8c82-586b6fbe4ff2.png)
At the time of combining heatmap  with 3D, the heatmap layer is under the building model. This effect is not good. We need to add "z-offset" height offset attribute" to the layer to achieve the following effect.
![image](https://user-images.githubusercontent.com/7942057/109086544-bb605200-7746-11eb-9435-52351841212b.png)

**Comment by ryanhamley** [comment]
We're already tracking support for controlling the altitude of features in https://github.com/mapbox/mapbox-gl-js/issues/3993. A related request for marker altitude is tracked in https://github.com/mapbox/mapbox-gl-js/issues/9945

**Comment by spencerthayer** [comment]
@ryanhamley where are we in adding altitude to points?
