### ISSUE TITLE
Can not update mapbox-gl.js

### ISSUE THREAD

**Issue by pathfinder007** [mapbox/mapbox-gl-js#10439]
Hey, I follow the link https://github.com/mapbox/mapbox-gl-js/blob/v2.1.1/CONTRIBUTING.md here, and made some changes to src/source/vector_tile_worker_source.js. After  yarn run build-prod-min, I can find my changes in dist/mapbox-gl.js.map, but can not find my changes in dist/mapbox-gl.js, do I made something wrong? Thanks for your response.

**Comment by ryanhamley** [comment]
Are you sure the changes aren't in `mapbox-gl.js`?  Are they minimized/obfuscated so that searching for variable strings may not show up? You can try running `yarn run build-prod` instead if you continue to have trouble. Either way, this isn't a bug in the library so I'm going to close this issue. If you need further help, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).
