### ISSUE TITLE
Advice for animating a lot of objects

### ISSUE THREAD

**Issue by normanrz** [mapbox/mapbox-gl-js#10519]
**mapbox-gl-js version**: 2.2.0

### Question
Hi, my application is rendering locations of athletes on a map. Sometimes, we have a lot of athletes at the same time (up to 50k). This is an example with 20k athletes: https://racemap.com/player/marseille-cassis-2018_2018-10-28. Currently, we are using deck.gl for visualization. However, to make use of the new terrain feature of Mapbox GL, it would be awesome to render it directly with Mapbox. With deck.gl, we can pass a [Float32Array with coordinates](https://deck.gl/docs/developer-guide/performance#supply-binary-blobs-to-the-data-prop) to be directly used in WebGL. With a custom wire format and worker+wasm processing, we are able achieve good frame rates with acceptable memory usage even for the larger sports events.
I was wondering, if there was a way to animate that many objects with Mapbox GL JS. I haven't found anything on that scale in the docs and I doubt this would be possible with updating GeoJSON sources in every frame.
Thanks!

### Links to related documentation

- https://docs.mapbox.com/help/troubleshooting/mapbox-gl-js-performance/
- https://docs.mapbox.com/help/troubleshooting/working-with-large-geojson-data/

**Comment by asheemmamoowala** [comment]
@normanrz Have you considered using a [Custom layer](https://docs.mapbox.com/mapbox-gl-js/api/properties/#customlayerinterface) directly? This is the method that deck.gl uses, but you could reduce the dependency if that is an issue for you.

Direct support for something of this scale is not currently supported by existing sources and layers, but is something that is on our roadmap for the coming year.

Im going to close this issue here since there is no further action needed here. 
cc @ansis

**Comment by normanrz** [comment]
Thanks  for the feedback. I wasn't aware of the custom layer. I'll give that a try!
