### ISSUE TITLE
How to do Caching with getBounds()?

### ISSUE THREAD

**Issue by bashasm** [mapbox/mapbox-gl-js#10520]
**mapbox-gl-js version**: 2.1.1

### Question
How to do Caching with getBounds()?

I am trying to show markers on the visible area and lazy load others when the user zooms/navigates

Do we need to always get the data from the server on the getBounds()? Do you think is there any way to avoid loading the same data using getBounds(). Something like caching etc...

Please advise

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/events/

https://docs.mapbox.com/mapbox-gl-js/api/map/#map#getbounds

**Comment by karimnaaji** [comment]
hey @bashasm , I'm not sure I understand the question fully, but I assume you're trying to reject things outside of a given map bounds. We don't provide functions that facilitate doing that in the library. With getBounds you will get geographical bounds that may not be aligned. 

>the visible region is not an axis-aligned rectangle, and the result is the smallest bounds that encompasses the visible region

You could align these by getting min and max of all these coordinates (to basically transform it to an aligned box) and use that to reject points that don't lie within.

Since this is not an issue or bug with the library I'll go ahead and close this, don't hesitate to contact support@mapbox.com for similar questions.
