### ISSUE TITLE
TypeError: map.on is not a function when trying to test Mapbox

### ISSUE THREAD

**Issue by brdv** [mapbox/mapbox-gl-js#10583]
**mapbox-gl-js version**: 2.2.0

We're using Mapbox in our project for a couple of months now. This project uses Create React App (CRA) with Typescript. As we started, we immediately ran into some problems with testing components > long story short; when we ran tests we got the error "[window.URL.createObjectURL is not a function](https://github.com/mapbox/mapbox-gl-js/issues/9889)". There was a proposed workaround to mock Mapbox in setupTests.ts which did not work for us.

The question here is: is it us, or something to do with Mapbox? + does anyone know how to get Mapbox tests working?

### Steps to Trigger Behavior

 1. Add Mapbox to a repository (Create-react-app & Typescript) (see [this repo](https://github.com/brdv/mapbox-test-example))
 2. Write a test for the component using mapboxgl
 3. Add mocking of mapbox to setupTests.ts 
 4. Run tests

### Link to Demonstration

https://github.com/brdv/mapbox-test-example

### Expected Behavior

Tests will run.

### Actual Behavior

`TypeError: map.on is not a function`

**Comment by rreusser** [comment]
Hi, @brdv. Thanks so much for the clear example! Mapbox requires web APIs to function so that it won't work in node by itself, though I think you're on exactly the right track with setting up a mock. Some people use [karma](https://karma-runner.github.io/latest/index.html) for end-to-end testing in the browser, though that's a completely different approach which may or may not align with your goals.

I took a look at `setupTests.ts` and was able to get the following working:

```
export const mockMapOn = jest.fn();
export const mockMapRemove = jest.fn();

jest.mock('mapbox-gl', () => ({
  Map: function () {
    this.on = mockMapOn;
    this.remove = mockMapRemove;
  }
}));
```

which at least allows you to spy on its methods, though I'm not sure why I couldn't get `jest.fn()` or `jest.fn().mockImplementation()` to work. If it's alright, I'll close this issue since your understanding and approach seem correct and since further details seem like a Jest-specific question.

If you need further help setting things up, [Mapbox Support](https://support.mapbox.com/hc/en-us) may be able to offer guidance and examples as well.

**Comment by brdv** [comment]
Hi, @rreusser. Thank you so much for your reply. As far as I've tested now, it seems to work. 
The only issue is that typescript starts complaining about `this.` not being recognized. This can be easily 'fixed' by adding `// @ts-ignore`, however, this is of course not the best solution. Did you have anything else set-up to make it work without the error?

Thanks again for your help!

**Comment by wangyangjun** [comment]
For anyone who might be interested, the following solution allows you to spy on both class `mapboxgl.Map` and its methods
```
jest.mock('mapbox-gl', () => ({
  Map: jest.fn()
}));
mapboxgl.Map.prototype = {
  remove: jest.fn(),
  on: jest.fn(),
  off: jest.fn(),
};
```
