### ISSUE TITLE
Cursor grab still there when dragPan is disabled

### ISSUE THREAD

**Issue by ygoe** [mapbox/mapbox-gl-js#10593]
**mapbox-gl-js version**: latest

**browser**: Firefox (should be irrelevant)

### Steps to Trigger Behavior

 1. Create a map with the option dragPan: false
 2. Place the mouse cursor over the map

### Expected Behavior

The mouse cursor should be default and not indicate any interaction that is not available.

### Actual Behavior

The mouse cursor is set to "drag" on the `mapboxgl-canvas-container mapboxgl-interactive` classed element. Drag panning is not possible though because it's disabled.

### Workaround

When disabling the dragPan option, call this:

```js
mapContainer.querySelector("div.mapboxgl-canvas-container.mapboxgl-interactive").style.cursor = "default";
```

When enabling the dragPan option, call this:

```js
mapContainer.querySelector("div.mapboxgl-canvas-container.mapboxgl-interactive").style.cursor = "";
```

**Comment by ryanhamley** [comment]
I think the cursor should still be `grab` in this case, at least in the library. Disabling dragPan doesn't disable zooming on double click, box zooming (shift + dragging a box) or drag tilt. If you were to disable all of these things, then the map would be non-interactive and the `pointer` cursor would make sense, but in that case, you can simply pass `interactive: false` as a map option which disables all interactivity and switches the cursor to `pointer`.

**Comment by ygoe** [comment]
Okay, how would I change that `interactive` mode later?

**Comment by ryanhamley** [comment]
You can't change the value of `interactive` since it's a constructor option and is never referenced again after the initial setup. If you just want `dragPan` to be disabled and the cursor to be a pointer until some later time when you enable `dragPan` and make the cursor a grabber again, the best bet is going to be implementing that yourself. [This example](https://docs.mapbox.com/mapbox-gl-js/example/toggle-interaction-handlers/) shows how to toggle interaction handlers on and off. You already outlined a way to change the cursor. Alternatively, you could delete the canvas container's `mapboxgl-interactive` class to display a pointer and then add the class back when you want a grabber. Note however that changing the classes by themselves will not have any effect on the actual interactivity of the map.

**Comment by tomaszs** [comment]
Is it fixed?
