### ISSUE TITLE
Mapbox GL Data Driven Styles Are not working as expected with this library

### ISSUE THREAD

**Issue by KatherineGraham2019** [mapbox/mapbox-gl-js#10609]
**mapbox-gl-js version**:

### Question

Hey,

I am currently trying to use properties to set feature colors using the following syntax but having issues making styles work with properties.

`styles={[{
      'type': 'fill',
       'paint': {
             'fill-color': ['get', "color"],
             'fill-outline-color': "#008BCE",
             'fill-opacity': 0.2
        }
}]}`

This is my syntax, I set a color property on each feature. Any help and guidance on why this isn't working would be great. I was unable to find documentation on how to use mapbox gl's data drive styles with this react version.

Thanks

**Comment by rreusser** [comment]
Hi, @KatherineGraham2019! If you're specifically trying to understand usage with React, Mapbox itself doesn't maintain React wrappers so you may need to look for the specific documentation of the wrapper you're using. If that's [react-map-gl](https://github.com/visgl/react-map-gl), you might try looking for the closest examples which include setting styles, e.g. [layers](https://github.com/visgl/react-map-gl/blob/272cb868bbaa30f861040428751088d5610bc607/examples/layers/src/app.js#L25). At a glance, I suspect it might be an issue with getting the styles in the expected format for the react component you're using.

To debug the styling itself and confirm it works before plugging into React, you might try starting with the closest Mapbox example, which is probably [data driven lines](https://docs.mapbox.com/mapbox-gl-js/example/data-driven-lines/).

If it's alright, I'll close this issue since, strictly speaking this issue tracker is for Mapbox GL-JS bugs and feature requests (though I'm glad to do what I can to point you in the right direction!). If working through some available examples doesn't get you where you need to go, I'd recommend contacting [Mapbox support](https://support.mapbox.com/hc/en-us) to see if they can help solve the issue.
