### ISSUE TITLE
getBounds() is returning Invalid LngLat object when terrain is enabled and map is at high zooms or large tilt.

### ISSUE THREAD

**Issue by KleggerKoder** [mapbox/mapbox-gl-js#10610]
I can only seem to replicate this on Mobile devices.
If I disable terrain mode getBounds() returns correctly.

https://github.com/mapbox/mapbox-gl-js/blob/798d073c5027e7b0d68a59bed733f4bfe0a2b43c/src/geo/transform.js#L1009

**Comment by jaybo** [comment]
I'm also experiencing this bug, but also on desktop Chrome.  Seems to only happen when all 3 of the following are true simultaneously:
1. 3D is enabled.
2. FlyTo()
3. Large tilt angles.

**Comment by SnailBones** [comment]
@jaybo Can you provide a minimum example that demonstrates the bug? [My attempt](https://codepen.io/snailbones/full/mdmKLgQ) hasn't been able to reproduce it for me.

**Comment by ted-piotrowski** [comment]
I believe I hit this today. It happens when:

Pitch is 45 degrees
mapbox-dem layer enabled
I call `map.fitBounds()`

It happens when I am zoomed in on a location, maybe level 16+, then I call `map.fitBounds()` to a far away location (also at high zoom, like a street address). Mapbox GL zooms way out and back in and throws the exception as it finishes zooming in on new location

```
Invalid bounds returned:  Error: Invalid LngLat object: (NaN, NaN)
    Ha mapbox-gl.js:31
    unproject mapbox-gl.js:31
    coordinateLocation mapbox-gl.js:35
    _getBounds mapbox-gl.js:35
    _getBounds3D mapbox-gl.js:35
    getBounds mapbox-gl.js:35
    getBounds mapbox-gl.js:35
```

It's not deterministic. Using the same starting point and calling `fitBounds()` to the same destination point does not throw an exception on subsequent attempts. 

Maybe something to do with caching or slow downloading DEM data as I notice the tiles don't load when this exception is thrown.

**Comment by SnailBones** [comment]
@ted-piotrowski Thank you for looking into this! Your potential suspect seems promising to me.

Are you able to create a reproduction of this bug? I'm still not seeing it though I've modified [my attempted reproduction](https://codepen.io/snailbones/pen/mdmKLgQ) to match your instructions.

Could you also please share what browser and OS you're seeing this on? Many thanks!

**Comment by SnailBones** [comment]
@ted-piotrowski Your intuition was spot-on! Just opened a PR to fix this, thanks for the help! :bow:

**Comment by ted-piotrowski** [comment]
@SnailBones thanks for this. I couldn't get a reproducible example going for you, but I will def verify this on my project once the new release is out.

**Comment by ted-piotrowski** [comment]
> I will def verify this on my project once the new release is out.

I just built and updated my mapbox-gl-js dependency to include this commit and no more invalid bounds errors. Fix looks good. Thanks @SnailBones .

**Comment by SnailBones** [comment]
Glad that this is working! Thanks for looking into this and confirming @ted-piotrowski.
