### ISSUE TITLE
Map pans at incorrect speed while pinching

### ISSUE THREAD

**Issue by rreusser** [mapbox/mapbox-gl-js#10657]
**mapbox-gl-js version**: v2.2.0

**browser**: iOS Safari on iOS 12.5.1

### Steps to Trigger Behavior

 1. Begin pinch gesture
 2. Zoom by pinching
 3. Pan
 4. If you zoomed in, the map pans too fast. If you zoomed out, it pans too slowly.

https://user-images.githubusercontent.com/572717/117512245-1b902300-af44-11eb-8529-0baf28588ddb.mp4

### Expected Behavior

Map pans at the same speed as centroid of pinch gesture

### Actual Behavior

Order of operations (pinch vs. zoom) is perhaps reversed and map panning does not take into account zoom which has occurred since the start of the gesture.

**Comment by rreusser** [comment]
See also:

https://github.com/mapbox/mapbox-gl-js/issues/8345 which notes that the pan does not pan at all (outdated but still open, perhaps?)
https://github.com/mapbox/mapbox-gl-js/pull/8100 which perhaps introduced this behavior?

**Comment by timsluis** [comment]
I dove a bit into the code behind this bug and found that it is caused by `handle_manager.js` on r499. It defines a 'dragOrigin' on the start of a drag event. This causes that the `panVec` (the amount the map should be panned based on user input) on r526 will be calculated based on the zoom level when the drag event started.

If you are at a low zoom level, zoom in, and then pan left without ending the drag event, the map will pan as if you're still at the low zoom level (which will be very fast as can be seen in the video of @rreusser).

If we change r499 from:
```javascript
if (eventStarted("drag") && around) {
```
to:
```javascript
if ((eventStarted("drag") || zoomDelta) && around) {
```
the problem is solved, effectively resetting the dragOrigin not only on drag start, but also when there is a delta in the zoom level.

I haven't looked into other (performance) side effects this code change can have. See this as a little help to fix the bug.

**Comment by AllenWilliamson** [comment]
Any progress on this issue?

**Comment by stepankuzmin** [comment]
Good catch, @timsluis! I've made a PR for that https://github.com/mapbox/mapbox-gl-js/pull/12543
