### ISSUE TITLE
korea font error

### ISSUE THREAD

**Issue by kimminhyug** [mapbox/mapbox-gl-js#10664]
hello 

i created "Gungsuh Regular" font from node-fontnik.
but that font Only consonant vowels are applied

how can i fix it?

![ERROR](https://user-images.githubusercontent.com/42853144/117611050-be8fa980-b19d-11eb-9076-1bd8e5780de4.PNG)

my code

	var baseLayer = [
		{	'id': 'baseTile_chk',
			'name': '초기타일',
			"type": "raster",
			'source': 'basebackGround_chk',
			'directory': '기본 배경지도'
		}];
	mapboxgl.accessToken = 'my key';
	var map = new mapboxgl.Map({
		container: 'map', // container id
		style:{
			'version': 8,
			"glyphs" : "http://wsglmap1.3/glyphs/{fontstack}/{range}.pbf" ,
			'sources': {
				'basebackGround_chk': { 
					'type': 'raster',
					'tiles': ["http://xdworld.vworld.kr:8080/2d/Base/service/{z}/{x}/{y}.png"],
					'tileSize': 256,
					'attribution':'<a href="https://www.mapbox.com/">Mapbox</a>,<a href="https://www.vworld.kr/">오픈플랫폼</a>,<a href="#" onclick="map.showLicence();">라이센스</a>'
				}
			},
			'layers': [
				baseLayer[0]
			]
		},	
		center: [126.76423,37.50252], // starting position [lng, lat]
		zoom: 9 // starting zoom
	});
	
	labelId="test";
	map._localIdeographFontFamily = "Gungsuh Regular"
	map.style.glyphManager.setURL("glyphs/{fontstack}/{range}.pbf");
	wfsData = turf.point([126.76423,37.50252]);
	map.addSource(labelId, {
		'type': 'geojson',
		'data': wfsData
	});
	
	//font Layout
	var fontLayout = {	
		'text-field': '가 ㄱ ㅏㅏ',
		'text-font': [
		'Gungsuh Regular'
		],
		'text-size': 30,
	}	                
		            
	//font Paint
	var fontPaint = 
	{'paint': {
               'text-color': '#202'
       }};
	
	map.addLayer({
		'id': labelId,
		'type': 'symbol',
		'source': labelId,
		'layout': fontLayout,
		'paint':  fontPaint.paint
	});

**Comment by kimminhyug** [comment]
@karimnaaji {localIdeographFontFamily:'serif'} option is  works.

but I think it's only a global setting.
I want to apply different fonts for each layer.

**Comment by ChrisLoer** [comment]
> but I think it's only a global setting.
I want to apply different fonts for each layer.

Yes, that's true, per-layer control only works with server-provided (e.g. node-fontnik) fonts.

I'm not sure if I'm understanding this correctly, but it looks like you are using `localIdeographFontFamily` _and_ a server-provided font. The local rendering is only applying to some Korean characters and not to others, and that may be why you see different results. Can you get more consistent results by setting `localIdeographFontFamily` to `null`?

It's probably a bug that only _some_ Korean characters are being rendered locally. We should broaden the character range to make sure it includes all Korean characters.

**Comment by kimminhyug** [comment]
@ChrisLoer Hey  localIdeographFontFamily : null this option was the right answer !!
My font is all applied thank you.
This problem has made me tired for days
Thank you so much. Next time I come to Korea, I will serve delicious food. :laughing:

**Comment by ChrisLoer** [comment]
@kimminhyug I'm vaccinated and I live only a one hour flight away from Korea, I definitely want to visit as soon as it's allowed!

Can you help us understand the use case for the text you were displaying? The characters unaffected by the `localIdeographFontFamily` setting are in the [Hangul Compatibility Jamo](https://en.wikipedia.org/wiki/Hangul_Compatibility_Jamo) unicode code block. We didn't include them because (1) they don't have fixed dimensions like the Hangul Syllables, and (2) we assumed they would be rarely used. Since you used them, maybe our assumption was wrong?

@karimnaaji If in fact it's common to have Korean writing outside of the `Hangul Syllables` block, we should consider changing the default behavior for Korean to use server-side fonts. Unlike Chinese and Japanese, there aren't that many Korean glyphs to download so server-side fonts should work just fine -- honestly Korean got pulled in just because it's the "K" in "CJK" 😅 .

**Comment by kimminhyug** [comment]
@ChrisLoer  The jamo in the code is meaningless if used individually. 
In most cases, consonants + vowels are combined to form words with meaning.
*case 
1. consonants + vowels ( 'ㄱ' + 'ㅐ' = '개' it's mean dog.)
2. consonants + vowels +consonants =  ('ㄱ' + 'ㅗ' + 'ㅇ' = '공'  <- it's mean ball.)

I don't know unicode well, but in case this might help, I brought it. [Hangul_Syllables](https://en.wikipedia.org/wiki/Hangul_Syllables)
