### ISSUE TITLE
Pitch on zoom possible?

### ISSUE THREAD

**Issue by djohalo2** [mapbox/mapbox-gl-js#10741]
**mapbox-gl-js version**: 2.3.0

### Question
Hi! I'm trying to pitch the mapbox camera on zoom. I know I can set a default/max pitch level and that the user is able to change the pitch of the camera by themselves, I'm however looking for a way to map a zoom level range to a pitch range. While scrolling/zooming I want the pitch to change according to this range.

I've tried the following:
```
function onMapboxZoom(e: MapboxEvent) {
  const zoom = e.target.getZoom();
  const pitch = mapRange(zoom, 6, 10, 0, 65);
  e.target.setPitch(pitch);
}
```

The problem I'm having with this approach is that I think the zoom interpolation that mapbox uses to create a smooth zooming effect is cancelled by my manual pitch change. Which makes sense I guess. I was just wondering if anyone has tackled this problem before and if it's possible in any way.

Thanks!

**Comment by rreusser** [comment]
@djohalo2 Do you mean that after manually pitching, then as soon as you zoom again, it instantly applies the computed pitch? You could deactivate the zoom+pitch linkage as soon as the user manually pitches the map with something like following:

```
map.on('rotate', function () {
    map.off('zoom', onMapboxZoom);
});
```

You'd then have to figure out what to do to reactivate it. [easeTo](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#easeto) and [isRotating](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#isrotating) might be a couple tools you could try toward building an acceptable interaction. Or instead of `easeTo`—which might be tricky to get just right—you could maybe pitch 5% toward the desired value on each frame, so that the jump wouldn't be so instantaneous.

I think my short answer is that although it's not a built-in behavior, I believe the tools you need to accomplish it are probably present, depending on the particular behavior you require. If it's alright, I'll close the issue unless there's a specific feature that's lacking and preventing you from achieving the desired result. You might also try reaching out to [Mapbox Support](https://support.mapbox.com/hc/en-us) to see if they have ideas or experience about how best to implement this.

**Comment by djohalo2** [comment]
@rreusser Thanks for your reply. It's not really what I meant. I'm actually trying to change the pitch automatically when you zoom in. Based on a certain zoom range it should linearly change the pitch between a certain range of values as well. I did manage to make it work a bit better by using `jumpTo` and leveraging the scroll handler `targetZoom` to both set the pitch and zoom value at once, like so:

```
function onMapboxZoom(e: MapboxEvent) {
  const zoom = e.target.scrollZoom._targetZoom;
  const pitch = getPitchByZoom(zoom);
  e.target.jumpTo({ pitch, zoom });
}
```

Besides having to use a private value that I'd rather not do, this also has the same problem I mentioned earlier about the zoom smoothness and interpolation the scroll handler instance gives me. Hopefully having clarified my question a bit, do you have any other suggestions?

**Comment by rreusser** [comment]
I see. Does something like this work? https://codepen.io/rsreusser/pen/ExWpmxY?editors=0010
