### ISSUE TITLE
CSP "script-src 'self'" denying worker - trying to use Mapbox with constraints (offline/local?)

### ISSUE THREAD

**Issue by realwakils** [mapbox/mapbox-gl-js#10789]
Hello, I'm currently in a situation where I am developing a Twitch extension that uses Mapbox GL in order to render in a map. The current issue however is that Twitch does not allow any external resources, like external css, js etc. The Twitch extension is rendered inside a constrained iframe. I've already downloaded down locally the css but I am now met with another error. I am really unsure how to avoid this error, when I am constrained to no external resources.

The error looks like this:
![image](https://user-images.githubusercontent.com/19620638/122683218-150cf080-d1fe-11eb-908d-281c95c4d826.png)

Also I am using Typescript and did `yarn add mapbox-gl`. So I am not importing mapbox gl in a script tag.

**Comment by ryanhamley** [comment]
This sounds like it's due to Twitch's CSP policies, but you may be able to work around it by using the [GL JS CSP worker script](https://docs.mapbox.com/mapbox-gl-js/api/#loading-and-transpiling-the-web-worker-separately). You can set `mapbox-gl-csp.js` as your main entry point and before instantiating your map, you can set `mapboxgl.workerUrl = "path/to/mapbox-gl-csp-worker.js";`. I'm not 100% certain this will fix the issue since I don't know the exact setup for Twitch, but it's worth a shot. If you continue to have issues, I'd recommend contacting [Mapbox Support](https://support.mapbox.com/).
