### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'thisCompilation' of undefined

### ISSUE THREAD

**Issue by BrennanPredmore** [mapbox/mapbox-gl-js#10794]
Hello, I have a bug to report. I recently update my node modules with NPM I and i am now getting this error which is not allowing the code to compile and the start my application.

Here is the error message in the terminal:

Failed to compile.

./node_modules/mapbox-gl/dist/mapbox-gl-csp-worker.js
Module build failed: TypeError: Cannot read property 'thisCompilation' of undefined

**Comment by rreusser** [comment]
Hi, @BrennanPredmore. Can you clarify from which version to which version you upgraded? And based on the error message, it sounds like this is a webpack error?

If this is an upgrade from 1.* to 2.*, some approaches to transpiling are explained in the [GL-JS docs](https://docs.mapbox.com/mapbox-gl-js/api/#transpiling-v2), and a bit more of the background and motivation is explained in https://github.com/mapbox/mapbox-gl-js/issues/10565.

We're glad to take a closer look if that doesn't help solve the issue, but it will require additional info about your setup in order to diagnose the issue.

**Comment by BrennanPredmore** [comment]
I have this version
        "mapbox-gl": "^2.1.0",

**Comment by rreusser** [comment]
Have you had any luck with the instructions, perhaps specifically [these instructions](https://docs.mapbox.com/mapbox-gl-js/api/#loading-and-transpiling-the-web-worker-separately) for loading the web worker code separately with webpack?

**Comment by asheemmamoowala** [comment]
@BrennanPredmore  Thank you for using Mapbox-GL-JS and for reaching out. As the team requested more information and we haven't heard back in a couple weeks, I'm going to close this issue. If you want to reopen the issue, please provide the information requested in https://github.com/mapbox/mapbox-gl-js/issues/10794#issuecomment-865435525.  

Thank you!
