### ISSUE TITLE
Correct way to do animation in Mapbox GL ?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1080]
I add following event on map :
```
map.on('refreshMarkers', function (){    
    markers.setData(
        updatedGeojson
    );
});
```
I try to fire the refreshMarkers event 24 times per second with setInterval. The maximum is about 10 refresh per second and if I try to go higher the markers disappear.

Edit : after updating to 0.7.0 it seems the markers are not flashing anymore, instead I see a smooth transition between positions. Does this mean that marker movement animation is now built-in?

**Comment by jfirebaugh** [comment]
There were some important optimizations for `setData` in 0.7.0 that probably account for the difference you're seeing. Marker movement isn't built-in _per se_, but your approach is on the right track. I'd suggest using `requestAnimationFrame` instead of `setInterval`. Also, you can have your timer function call `markers.setData(updatedGeojson)` directly -- it's not necessary to fire a map event.

**Comment by misterfresh** [comment]
#2417
