### ISSUE TITLE
map.setFilter() not working correctly when layer has no features.

### ISSUE THREAD

**Issue by henrikmaa** [mapbox/mapbox-gl-js#10803]
**mapbox-gl-js version**: 2.3.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Add two layers to the map with map.addLayer()
 2. Make sure **one** of the layers has features and the other layer **dont have features**
 3. use map.setFilter() on both layers

I used the mapbox [timeline slider example ](https://docs.mapbox.com/mapbox-gl-js/example/timeline-animation/)

But then I added a layer with a filter (to make sure it has no features)

```
map.addLayer({
            'id': 'field',
            'type': 'circle',
            'source': 'earthquakes',
            'paint': {
                'circle-radius': 8,
                'circle-color': '#65CDC9'
            },
            'filter': ['==', ['get', 'type'], 'field']
        });
```

And to the filter function of the timeline i did this:

```
function filterBy(month) {
        var filters = ['==', 'month', month];
        map.setFilter('field', filters); //add this to be filtered
        map.setFilter('earthquake-circles', filters);
        map.setFilter('earthquake-labels', filters);
        // Set the label to the month
        document.getElementById('month').textContent = months[month];
    }
```

Which is causing this behavior:

![Skjermbilde 2021-06-24 kl  09 40 33](https://user-images.githubusercontent.com/39732540/123222435-3b69af00-d4d0-11eb-8301-5f25b3805667.png)

Jsfiddle here: https://jsfiddle.net/ygrbvs6L/1/

### Expected Behavior

setFilter() should not show any additional features from the 'field' layer, since no features exist.

### Actual Behavior

Features that does not exist is being showed over other features.

**Comment by henrikmaa** [comment]
This is not a bug, I should of read the documentation more carefully.

Documentation states: map.setFilter() the function removes any existing filter from the layer.

And when i did addLayer i added a filter, which then got removed when setting new filter.

Now im trying to re add that filter on top of the new filter, which I cant manage to do

```
var filters = ['==', ['<=', ['number', ['get', 'start_year']], year],['>=', ['number', ['get', 'end_year']], year]] //i only want to do this if ['==', ['get', 'type'], 'field']

            map.setFilter('field', filters);`
```

**Comment by ryanhamley** [comment]
Hi @henrikmaa the `==` operator only accepts two arguments typically (see https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#== - there is a third argument but it's for comparing localized strings which isn't what's happening in this case) so what you have in the example won't work the way you expect it to.

Looking over your code, I'm not 100% sure I understand what you're trying to achieve. The `['==', ['get', 'type'], 'field']` expression appears to be intended to ensure that the filter applies only to the layer with `id: 'field'`? If so, that's unnecessary because the filter will always only apply to the layer it's applied to. In either case, `['get', 'type']` would actually return `'circle'` in that case, so the `==` will fail. I'm wondering if this [newer example](https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/) with earthquake data is more helpful for you. If you have more general "how to" questions, I'd recommend [contacting Mapbox Support](https://support.mapbox.com/hc/en-us). Best of luck.
