### ISSUE TITLE
Integrate sprite jsons into stylesheet

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1083]
Is there a compelling reason we keep `sprite.json` and `sprite@2x.json` as separate files from the stylesheet, rather than as JSON objects within? 

It adds more (unnecessary?) moving parts, and introduces the potential for missing links

**Comment by incanus** [comment]
Broader discussion happening over in https://github.com/mapbox/mapbox-gl-style-spec/issues/220. 

The reason we have sprites is similar to the web (less resources to handle) but also optimizing texture loads in GL since you can bind one image, then use the offsets to map textures. 

Since we also will eventually support runtime addition and subtraction of sprites, I'd say JSON's days are numbered.

**Comment by jfirebaugh** [comment]
Yeah let's keep the discussion over on the style-spec issue.
