### ISSUE TITLE
forward geocoding api mapbox.places endpoint doesn't return bbox property

### ISSUE THREAD

**Issue by hamzahaddougui** [mapbox/mapbox-gl-js#10897]
I'm using mapbox.places endpoint to retrieve some information about a location, but it doesn't return bbox property like in geocoding api in help demo section in this link: https://docs.mapbox.com/help/demos/geocoding/final.html

This image shows data that is collected.
![geocoding](https://user-images.githubusercontent.com/58179098/127364627-3bd6c994-2eb0-4e7f-83d7-1fb854d97e02.PNG)
Thanks.

**Comment by rreusser** [comment]
Hi, @hamzahaddougui! The GL JS team doesn't directly maintain or support this API, but I do see that the [geocoding response object documentation](https://docs.mapbox.com/api/search/geocoding/#geocoding-response-object) points out that

> Each feature object in the features array ***may*** have the properties described below:

(emphasis added) That section includes bbox. Things like points of interest, I would assume, don't have any finite extent so that they may omit the bbox. Apart from whether the field is present or not, I'm not sure if some other metadata (`place_type`?) might indicate whether bbox is expected to be present or not.

I'm glad to try to steer you in the right direction, but since our team may not be knowledgeable enough of the geocoding API to offer a more precise answer than that, if it's alright, I'll close the issue and direct you to [Mapbox Support](https://support.mapbox.com/) for more detailed inquiries about that API.
