### ISSUE TITLE
.off not working with the arrow functions

### ISSUE THREAD

**Issue by SourceCipher** [mapbox/mapbox-gl-js#10916]
### Steps to Trigger Behavior

If you use `map.off('mousemove', this.func)`

it will work fine

but if you use `map.off('mousemove', e => this.func(e))`

it will not

### Link to Demonstration

I just modified the demo from original docs to use arrow functions.

https://codepen.io/gmand/pen/dyWgeyb

### Expected Behavior

Once you release mouse button, the listener **should be destroyed** and the marker should not move when moving the mouse

### Actual Behavior

Once you release mouse button, the listener **is not being destroyed** and the marker still moves when moving the mouse

**Comment by mourner** [comment]
This is inherently a JavaScript property and works in the same manner across all JS frameworks with events. `map.off` expects the same function that you passed earlier to `on` to remove it, otherwise it has no way to know which one to remove. Once you do a closure with `=>`, it's a new function in JS.
