### ISSUE TITLE
Why can't I do data expressions on 'fill-extrusion-opacity'?

### ISSUE THREAD

**Issue by Philip2809** [mapbox/mapbox-gl-js#10955]
**mapbox-gl-js version**: 2.4.1

### Question
Hi! I have to say this is an awesome project and I love working with it, but I recently came across a problem. I have a 3d map and I have geojson features on it and I wanted to improve performance and to do this I want to combine the layers according to:
https://docs.mapbox.com/help/troubleshooting/mapbox-gl-js-performance/

So my geojson features need different opacity's, and when I try to do: `'fill-extrusion-opacity': ['get', 'opacity'],` I get the error saying: `layers.[layer_name].paint.fill-extrusion-opacity: data expressions not supported.` Why is this even a thing when I get use data expressions to get the color, base_height and height with no problems? And the weirdest thing of them all is that I can use camera expressions, aka zoom, but not data expressions? It would be really nice to have or at least a workaround because then I can add all my geojson to one source and one layer, which should reduce lag.

I don't think this should be hard to add, because it's already there for height, base and color.

Best Regards
Philip Magyar

**Comment by mourner** [comment]
It's not supported because it's surprisingly a very difficult technical problem to solve — you can read more in #9184.

**Comment by Dono7** [comment]
I ran into the same issue. I could handle this with a trick, my map style is based on a dark-style, and I applied a different RGB color for each feature (since Color property can use data expression). 

My main color is a red : `rgb(238, 83, 83)`
Every feature from my geojson has a value between 0 and 100 (wich I also use to calculate the height)

Then I get my color (and height) like this : 

```js
const features = features.map((f) => {
  const valueOver100 = ... // Get something between 0 and 100

  // Get height
  const heightFactor = 15
  f.properties.height = valueOver100 * heightFactor

  // Get color based on rgb(238, 83, 83) main color
  const r = (238 * valueOver100) / 100
  const g = (83 * valueOver100) / 100
  const b = (83 * valueOver100) / 100
  f.properties.color = `rgb(${r}, ${g}, ${b})`
  return f
})
```

My layer paint property is defined as:

```js
paint: {
  "fill-extrusion-color": ["get", "color"],
  "fill-extrusion-height": ["get", "height"],
  "fill-extrusion-base": 0,
  "fill-extrusion-opacity": 0.5,
  "fill-extrusion-vertical-gradient": true,
}
```

Here is a preview:

![image](https://user-images.githubusercontent.com/35794293/209822289-ace5a9cd-7834-4fd4-9ad4-ebeb83a6373f.png)

I'm not sure if this trick works with a light-style, but it did the job in my case ;)
