### ISSUE TITLE
Offer onAdd/onRemove callbacks for non-custom layers

### ISSUE THREAD

**Issue by thully** [mapbox/mapbox-gl-js#10974]
Currently, onAdd and onRemove callbacks for layers are only supported when using the CustomLayerInterface. When using any other type of layer, these are not used/ignored. It would be useful to support these callbacks for other types of layers besides CustomLayerInterface, as layers may want to use them to add/remove listeners and other components that they use..

**Comment by rreusser** [comment]
Thanks for the suggestion, @thully! This makes sense, but if I'm understanding it correctly, one issue with this is platform-dependence. Custom Layers represent the exception to the rule that layer definitions must be serializable and platform-independent. Since `onAdd` and `onRemove` are callbacks which cannot be serialized or executed on other platforms, it would violate this rule to include them in, for example, a style definition.

I agree it would be nice to be able to automate linking setup and teardown tasks to the layer definitions, but I think this is something which will have to be coordinated in user-land instead.

If it's alright, I'll close this issue since I think it's not something we'll be able to act on, but please do re-open the issue if I've not understood the proposal quite right or if you think I'm mistaken. Thanks!
