### ISSUE TITLE
Setting the minZoom does not update the enabled/disabled state of the nav controls

### ISSUE THREAD

**Issue by jonrimmer** [mapbox/mapbox-gl-js#11013]
**mapbox-gl-js version**: 2.4.1

**browser**: Chrome

### Steps to Trigger Behavior

 1. Create a map with a navigation control
 2. Call `setMinZoom()` with a zoom level higher than the current zoom.
 3. Observe that the map zooms to the new min zoom level, but the zoom out button remains enabled.

A similar bug occurs if the min zoom level if removed when the zoom out button is disabled. The button does not become enabled.

### Link to Demonstration

https://codesandbox.io/s/mapboxgl-basics-forked-ot2bu

Note that the map zooms in from the initial zoom level (3) to the min zoom level (6), but that the zoom out control remains apparently enabled. Only zooming in and out with the mouse wheel or clicking on the zoom out button will update its state. 

### Expected Behavior

The zoom out button remains enabled/disabled even when the min zoom changes to prevent/allow zooming.

### Actual Behavior

The zoom out button's enabled/disabled state should update immediately when the min zoom changes.

**Comment by rreusser** [comment]
Thanks for raising this! A way to sync the button is:

```
map.fire('zoom')
```

The only reason this is tricky to fix is that the control is as decoupled as possible from the map, so that the map can't simply dig into the control and update it when parameters have changed. The coupling is accomplished through events:

https://github.com/mapbox/mapbox-gl-js/blob/7c3a50d2f00af083a67082e995f507a12de24cd9/src/ui/control/navigation_control.js#L106-L124

Thus, I see two ways this could be fixed:

1. Have `setMin/MaxZoom()` fire a dummy `'zoom'` (and probably also `'zoomend'`) event for the sole purpose of triggering this update. This probably would be relatively low consequence as long as the right data is in place so that it's a no-op for people listening to zoom events.
2. Construct a new type of event for just this purpose. (`'newzoomlimits'`??) A new public event seems like maybe a bit much for this. There's an event or two that's strictly internal, so it wouldn't be without precedent if it weren't a publicly documented event, though undocumented events seem like kind of like tech debt it'd be nice not to accumulate more of.

**Comment by rreusser** [comment]
@jonrimmer I've merged a fix for this in #11018, which will be included in not in the currently-beta release of 2.5.0, but in the subsequent release, 2.6.0. Thanks for pointing this out!
