### ISSUE TITLE
Reduced labeling density compared with v7

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1106]
New labeling code shows fewer labels. Same style and zoom level:

v7

![screen shot 2015-03-18 at 11 02 46 am](https://cloud.githubusercontent.com/assets/4551508/6715959/46fc4816-cd5f-11e4-9da0-c5667e49b4f3.png)

new labeling code

![screen shot 2015-03-18 at 11 02 36 am](https://cloud.githubusercontent.com/assets/4551508/6715967/4f3e1108-cd5f-11e4-8b25-99aea1dcff21.png)

**Comment by ansis** [comment]
I'm seeing this with `http://mapbox.s3.amazonaws.com/mapbox-gl-js/master/mapbox-gl.js`:

![screen shot 2015-03-18 at 12 23 48 pm](https://cloud.githubusercontent.com/assets/1421652/6717448/b02b63a8-cd69-11e4-9abb-f91cb4695ada.png)

There are few labels because neighbourhood labels have a huge amount of padding (100px). The collision boxes can be enabled with `map.collisionDebug = true`.

![screen shot 2015-03-18 at 12 24 20 pm](https://cloud.githubusercontent.com/assets/1421652/6717464/dda3237a-cd69-11e4-9533-ce4753c91cca.png)

**Comment by ansis** [comment]
Closing because I think this is a style issue. If you hit any other problems open a new issue.

**Comment by peterqliu** [comment]
this was it :+1: thanks
