### ISSUE TITLE
how can i get the WMTS FeatureInfo on mapbox

### ISSUE THREAD

**Issue by Chanceshine** [mapbox/mapbox-gl-js#11060]
I know that the results can be obtained through the following link request，but how can I get the value of the parameter:`TileCol,TileRow,I,J`, when i click on the tiles.

`http://127.0.0.1:8080/geoserver/gwc/service/wmts?VERSION=1.0.0&LAYER=gis:taz&STYLE=&TILEMATRIX=EPSG:900913:10&TILEMATRIXSET=EPSG:900913&SERVICE=WMTS&FORMAT=image/png&SERVICE=WMTS&REQUEST=GetFeatureInfo&INFOFORMAT=application/json&TileCol=1674&TileRow=383&I=127&J=13`

Add the layer in the following way:
```
map.addLayer({
  'id': 'taz',
  'type': 'raster',
  'source': {
    'type': 'raster',
    'tiles': [
      'http://127.0.0.1:8080/geoserver/gwc/service/wmts?layer=gis:taz&style=&tilematrixset=EPSG:900913&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/png&TileMatrix=EPSG:900913:{z}&TileCol={x}&TileRow={y}',
    ],
    'tileSize': 256
  },
  'paint': {}
});
```

**Comment by ryanhamley** [comment]
GL JS doesn't expose an api for getting tile data like that. The closest I can think of is if you use `map.showTileBoundaries = true` you can see the tiles rendered with their outline and the z, x and y parameters for each tile. There may be other ways to achieve your goal, but since we can't offer direct support through Github, I'd suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us) if you need more assistance.
