### ISSUE TITLE
map.unproject(map.project(...)) with non-zero bearing/pitch gives incorrect result

### ISSUE THREAD

**Issue by doraeric** [mapbox/mapbox-gl-js#11076]
**mapbox-gl-js version**: v2.5.0

**browser**: firefox, chrome

### Steps to Trigger Behavior

 1. Rotate the map, so it has bearing or pitch
 2. Open dev console, input `map.unproject(map.project({lat: 0, lng: 0}))`

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/assets/simple-map-demo.html

### Expected Behavior

Get coordinate near (0, 0)

### Actual Behavior

Get coordinate far from (0, 0)

The result is correct if the bearing and pitch is zero.

**Comment by mourner** [comment]
`project` and `unproject` can only work properly when operating on coordinates within or near the screen, since the `Point` in both represents screen coordinates. You can see that once you zoom out so that the `0, 0` point is visible, the line above works much more accurately. We can't really fix this, but perhaps we should mention the behavior in the docs.

**Comment by doraeric** [comment]
How can I know the coordinates are near the screen?
I use project to calculate the corresponding screen coordinates, and divide them by screen width and height to see how far they are.
If I can't project first, I don't known is the point near the screen.
