### ISSUE TITLE
what is the expected behavior of animOptions.offset in the easing functions?

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1116]
@mourner what is the expected behavior of animOptions.offset in the easing functions?
I was going to try to finish up https://github.com/mapbox/mapbox-gl-js/pull/735 but I realized I didn't know what they were supposed to do.

- `panBy` ??
- `panTo` ??
- `zoomTo` center the zoom around `centerPoint.add(offset)` so that the location at that point is the same before and after the zoom
- `rotateTo` center the rotation around `centerPoint.add(offset)` so that the location at that point is the same before and after the rotation
- `easeTo` ???

Since offset affects the end position not just the animation, should it be a separate parameter instead of part of `animOptions`?

I'm also wondering if it would be clearer to provide the value as a point instead of as an offset from the center.

**Comment by mourner** [comment]
Basically `offset` changes the behavior of each method in a way as if map center was in a different point. This is especially useful if you have e.g. semitransparent sidebar on the right, which makes your map center shift to the left. Using `offset` in this case is more convenient since you don't have to calculate actual center and recalculate every time the map resizes. 

In case on `panBy`, offset is just the pixel offset  you pan by.
