### ISSUE TITLE
Polygons surrounding a pole don't correctly represent encompassed area

### ISSUE THREAD

**Issue by ramananda-kairi** [mapbox/mapbox-gl-js#11235]
**mapbox-gl-js version**: Latest

**browser**: All Browsers

### Steps to Trigger Behavior

 1. Open this codesandbox https://codesandbox.io/embed/flamboyant-smoke-0v546?codemirror=1&fontsize=14&hidenavigation=1&theme=dark
 2. Set the radius beyond 6000 km. e.g. 11,000 in my case.
 3. set the zoom label to 2.

### Link to Demonstration
Code Sandbox Link - [https://codesandbox.io/embed/flamboyant-smoke-0v546?codemirror=1&fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/flamboyant-smoke-0v546?codemirror=1&fontsize=14&hidenavigation=1&theme=dark)

Radius Screen Shot - 
![image](https://user-images.githubusercontent.com/64131361/140496250-c9344ee1-7fb6-49ae-ace1-df87ae991114.png)

### Expected Behavior
- A Perfect Radius

### Actual Behavior
- Not Working Properly.

**Comment by SnailBones** [comment]
I think what's happening here is that `turf.circle` returns a series of points that represent a circle on the globe, and then Mapbox GL draws a shape defined by those points on the projected map. When those points surround the north pole, drawing the line connecting the two most-northern points creates the flat-topped shape in your picture.

The technically correct solution would be to render all lines as curves (representing the shortest past on a sphere) but I suspect that would be a performance hit not worth taking.

Perhaps a more realistic solution would be to handle this special case by rendering a polygon that reaches all the way to the top of the map. But that would complicate the polygon logic. Since currently polygons have to be bounded on all sides on the map projection, the solution would be to add extra points along the top and sides of the map. I'm not sure what other side effects that might have.
