### ISSUE TITLE
Can't resolve 'react-map-gl'

### ISSUE THREAD

**Issue by younitee** [mapbox/mapbox-gl-js#11268]
**mapbox-gl-js version**: 5.1.1

### Question

I am attempting to build a `create react app` with typescript and mapbox-gl-js and get the following response:

"Module not found: Can't resolve 'react-map-gl' in ..."

Notable dependencies:
`"@types/react-map-gl": "^6.1.1",
"react": "^17.0.2",
"react-mapbox-gl": "^5.1.1",
"typescript": "^4.1.2",
`

Tried many things... am I missing something obvious?

### Links to related documentation
https://github.com/mapbox/mapbox-gl-js/issues/10565#

**Comment by ryanhamley** [comment]
Hi @younitee I believe what you want is

```
import ReactMapboxGl, { Layer, Feature } from 'react-mapbox-gl';
import 'mapbox-gl/dist/mapbox-gl.css';
```

Based on the error message you supplied, you're requesting `react-map-gl` instead of `react-mapbox-gl`. Hope that helps.

By the way, I noticed in trying to reproduce this that there's some peer dependency issues when installing react-mapbox-gl. We don't maintain that library so if you run into further issues, you should open issues on their Github repo.

**Comment by younitee** [comment]
oh shweet, I mix-and-matched my libraries... so embarrassed! thanks for catching that @ryanhamley

**Comment by Kiiitttttuuu** [comment]
ERROR in ./node_modules/react-map-gl/dist/esm/exports-mapbox.js 16:15-34
Module not found: Error: Can't resolve 'mapbox-gl' in 'C:\Users\Asus\New folder\ip-finder\node_modules\react-map-gl\dist\esm'

**Comment by Kiiitttttuuu** [comment]
ERROR in ./node_modules/react-map-gl/dist/esm/exports-mapbox.js 16:15-34
Module not found: Error: Can't resolve 'mapbox-gl' in 'C:\Users\Asus\New folder\ip-finder\node_modules\react-map-gl\dist\esm'

please anybody understand this error then please give me ans how can do correct the problems
