### ISSUE TITLE
Curvy lines rendering issue

### ISSUE THREAD

**Issue by davidxmartins** [mapbox/mapbox-gl-js#11275]
I'm trying to print a map and the curved streets such as roundabouts are rendered as polygons instead of actual circles which looks awful. 
Is there a way I can improve this?
Thank you.

![roundabout](https://user-images.githubusercontent.com/13626863/141451086-ebc8ae25-38bb-400a-a5a3-c6a4d7f90ba4.jpg)

**Comment by mourner** [comment]
Other than setting `"line-join": "round"` for the line layer, it's a data issue. Closing since there are no further details provided, so we have no way of exploring your issue more.

**Comment by davidxmartins** [comment]
I'm afraid that wasn't very helpful. I do have the "line joint" set to "round" by the way.
![Screenshot (69)](https://user-images.githubusercontent.com/13626863/141816340-2e4ae382-0403-479a-8bdc-d6fbf935cd3c.png)

**Comment by davidxmartins** [comment]
Can you show me an example of a downloaded map showing a roundabout with smooth lines? Because if that's possible I would love to know how. Thanks.

**Comment by mourner** [comment]
All roundabouts in our map data and OpenStreetMap are not perfect circles — they are approximated by discrete polylines. The only way to make them look better is to add more points to the polyline for better approximation. E.g. here's Strada Circolare in San Jose, which is not perfectly round, but still looks much nicer because of more detailed mapping:

![image](https://user-images.githubusercontent.com/25395/141820177-dcdd1033-4052-42fc-b68e-60b4bde46392.png)

If a particular roundabout looks awful, you can suggest improvements (see "Improve this map" at the bottom right of any Mapbox map), or edit the data yourself in OpenStreetMap.

**Comment by davidxmartins** [comment]
Got it. Thanks.
