### ISSUE TITLE
After use map.moveLayer method, the event related issues

### ISSUE THREAD

**Issue by jswit** [mapbox/mapbox-gl-js#11291]
When i after use `map.moveLayer()` method, I try trigger click event, The result returned by the event is still the layer before moving

npm package "mapbox-gl": "1.13.1",

**Comment by ryanhamley** [comment]
@jswit there's not enough information here for us to help. please fill out the template in full when opening an issue. at the very least, we need a minimal working example of the problem (using JSFiddle/CodePen/similar sites).

**Comment by jswit** [comment]
CodePen:  [After use map.moveLayer method, the event related issues](https://codepen.io/jswit/pen/xxLMRKz)
please run this demo and open the browser console to view the print results

**Comment by jswit** [comment]
Trigger the click event of layer overlay area. Before and after changing the overlay order of layers, the printed results are in the order of rendering

According to the normal idea, after changing the layer sorting, the sequence of triggered click events should be the sorted layer sequence

**Comment by ryanhamley** [comment]
Hi @jswit thanks for the update. The issue here is that GL JS layers are not DOM elements, but graphics drawn within a camera so there's no DOM tree to bubble events up through. If you were to switch the order of the click listeners, you'd see layer 2 log before layer 1 because without event bubbling, the listeners are responded to in order. https://github.com/mapbox/mapbox-gl-js/issues/5783 has some ideas on how to work with quasi-event bubbling in this case. It's not an exact match for what you're trying to do but it may help illustrate what's happening and allow you to figure out a solution for your app. If you need further help, [Mapbox Support](https://support.mapbox.com/hc/en-us) should be able to steer you in the right direction.
