### ISSUE TITLE
Add new DataDrivenProperty property to line paint 

### ISSUE THREAD

**Issue by EarlOld** [mapbox/mapbox-gl-js#11317]
### Question
I would like to add new  DataDrivenProperty property to the line layer and use it in draw_line function, but I can't understand how to  get value inside **draw_line**... Can someone help me with it? I try to use **evaluate** but in **draw_line** I don't have access to fetureState.

Related with https://github.com/mapbox/mapbox-gl-js/issues/8977

@mourner 

### Links to related documentation

Link to commit - https://github.com/EarlOld/mapbox-gl-js/commit/8f2709567d92356c36ac2506b0a11eccea42baf8

**Comment by mourner** [comment]
The data-driven logic is very complicated, and we don't really have any bandwidth to support others in adding custom data-driven properties. Most of that logic is in [program_configuration.js](https://github.com/mapbox/mapbox-gl-js/blob/main/src/data/program_configuration.js), not in `draw_line.js` because those values are set at feature processing stage (populating "paint array buffers"), not when drawing.

**Comment by EarlOld** [comment]
@mourner thanks
