### ISSUE TITLE
Street labels appear above raster layers if terrain enabled

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#11336]
**mapbox-gl-js version**: 2.6.1

### Steps to Trigger Behavior

 1. Start with Mapbox Streets, add a raster source and raster layer.
 2. Add terrain as per this example: https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/
 
### Expected Behavior

Raster layer continues to show above street labels.

### Actual Behavior

Street labels now appear above raster layer. This happens even if exaggeration is 0 and pitch is 0. That is, when calling `map.setTerrain({ source: 'terrain', exaggeration})`, the only thing that visually changes is the street labels suddenly appear over the raster layer.

I can't easily include a screencap from my current (NDA'ed) project, but I think this would be very straightforward to verify.

**Comment by avpeery** [comment]
Hi @stevage, there is an option on the map constructor to optimize for terrain: `optimizeForTerrain` which default value is `true`. Setting this option to `false` may help your case. 

From the [docs](https://docs.mapbox.com/mapbox-gl-js/api/map/) about `optimizeForTerrain`: 
_"With terrain on, if true , the map will render for performance priority, which may lead to layer reordering allowing to maximize performance (layers that are draped over terrain will be drawn first, including fill, line, background, hillshade and raster). Otherwise, if set to false , the map will always be drawn for layer order priority."_

**Comment by stevage** [comment]
Ah, thanks, that's great to know. That works.

Just a note that that information isn't very discoverable. Can't really think of any way I could have come across that other than by asking. Seems an odd choice to have the map prioritise performance over visual correctness in such a dramatic way, imho.

**Comment by avpeery** [comment]
Noted @stevage! Will bring this up with the team. Thanks for the report.
