### ISSUE TITLE
Unexpected zooming when panning up or down on globe

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11353]
I would expect the camera to remain at the perceived altitude as I pan up or down. Instead, it appears to move closer towards the map which doesn't feel right and curiously doesn't have an impact on the zoom value.

https://user-images.githubusercontent.com/61150/147150372-d661ec0c-9b2d-4180-950f-8c354606dd95.mov

---

**Mapbox GL JS version:** `2.7.0-alpha.1`

**Comment by karimnaaji** [comment]
Thanks @tristen that's a good point to bring up. We had some discussion about this with @mpulkki-mapbox here: https://github.com/mapbox/mapbox-gl-js/pull/10999#issuecomment-916764637. I initially switched it to constant sphere size, as I was also surprised by this behavior. But this would mean that we automatically adjust the zoom level in order to keep the altitude constant. The current approach is to keep zoom constant and compensate the camera altitude accordingly.

This could warrant an option as most globe renderer seem to adopt different behavior in that regards. Either they keep the zoom constant and compensate the camera altitude properly as it's currently being done or
update zoom level in order to keep the altitude constant (constant sphere size).

I can see two drawbacks to this approach:
 - Texture magnification artifacts are more prevalent
 - We may loose the perceived "true size" of the data as we get near the pole, as we're automatically showing them larger on screen: It is more difficult to perceptually reason about the size of things when they are automatically displayed larger to you

**Comment by mpulkki-mapbox** [comment]
Thanks for bringing this up! It's an important discussion to have.

The original reason behind this behavior was purely technical. Enabling of globe view has no effect on the camera logic meaning that the automatic "zooming" you're seeing while panning up and down is the result of distortion from mercator projection. While having a fixed zoom value leads to a constant perceived altitude in mercator projection it is not the case in globe view. This is because relation between pixel coordinates and meters (pixels-per-meter) is a function of latitude, i.e. one pixel covers larger physical area near poles.

It might make more sense to have constant altitude instead. As @karimnaaji mentioned there doesn't seem to be industry standard for the behavior. Some of the globe renderers are having a fixed zoom value while others like to keep the perceived altitude constant. 

@karimnaaji:
> * Texture magnification artifacts are more prevalent near the poles

This is an issue in the current tile streaming logic. Differences in physical sizes of tiles in different latitude ranges is not taken into account. This leads to either too many or too few tiles being loaded depending on the camera position. This could be solved or at least partly alleviated by using physical distance in the tile streaming logic rather than tile units. The adaptive projections feature is already using some nice logic for solving this same problem.


> * We may loose the perceived "true size" of the data as we get near the pole, as we're automatically showing it larger on screen: It is more difficult to perceptually reason about the size of things when they are automatically displayed larger to you

This is true. It is important to get some fresh ideas/feedback on these design related questions. :)

**Comment by ansis** [comment]
> It might make more sense to have constant altitude instead

I agree that maintaining a constant real altitude while panning would be good.

> But this would mean that we automatically adjust the zoom level in order to keep the altitude constant. 

There is another possible approach. You can make globe zoom levels not match mercator zoom levels at low zoom levels. This is what other projections do to solve the same problem. The way this could look is:
- at z > ~5 the scale of the center in globe view would match the scale of the *center* in mercator exactly
- at z < ~3 the scale of the center in glove view would match the scale of *a constant reference location* in mercator exactly
- between the two, the scale would be interpolated

This avoids zoom level changes while panning at low zoom levels. The downside is that for some range of zooms the scale of that map would match the equivalent scale in a mercator map less exactly.

**Comment by karimnaaji** [comment]
Some more feedback on that topic from current alpha builds: https://twitter.com/steveattewell/status/1482020338879942658

**Comment by ivovandongen** [comment]
To weigh in on this discussion. Weighing the alternatives, I think the current behaviour is the most consistent. Especially when taking into account zoom based expressions, changing the zoom instead of the altitude when panning north/south would lead to many more unexpected results. For example, a style using satellite on low zoom, but vector on higher zooms could suddenly change styles when panning. Or, more common, the level of detail would change (features, symbols).

**Comment by tristen** [comment]
> For example, a style using satellite on low zoom, but vector on higher zooms could suddenly change styles when panning

Is this not avoidable?

**Comment by ansis** [comment]
> changing the zoom instead of the altitude when panning north/south would lead to many more unexpected results. 

It should be possible to maintain both zoom and altitude

Altitude is currently a function of the mercator scale at the center of the map. This definition doesn't really make sense in situations where the mercator scale varies widely across the visible parts of the map. We can tweak it so that it isn't defined by a single point (at low zoom levels)

The tradeoff is that when looking at the poles at z1 or z2, the tiles near the poles would cover less than the regular 512px. I think this should be better than changing scale when panning though

**Comment by tjukanovt** [comment]
I think both options have their pros and cons, but as a user/designer I would prefer to have the altitude constant (i.e. minimise the unexpected zooming).  Now for example when zooming to the poles, it is impossible to first pan to close to the poles and then zoom out (without unexpected movement back towards the Equator) 👇 

![globe_zoom](https://user-images.githubusercontent.com/13899537/165230428-2ae94de1-cdeb-4a9b-8fcb-ee2490579110.gif)

Also the fact that you can't move way up to the poles could limit some use cases. After all having the globe would enable visualisations focusing on these areas which were unimaginable with Mercator. Map like below can't be done with the current behaviour.

![image](https://user-images.githubusercontent.com/13899537/165231235-3ed78fda-2be5-4d3b-9390-bdc49f4d36d8.png)

**Comment by mpulkki-mapbox** [comment]
The zooming behavior in globe view can be disabled with the following one-liner. The variable `this._projectionScaler` (yeah, very original name) defines pixels-per-meter ratio between globe view and mercator projection at a given latitude. Some additional fine tuning is required as well but it _should_ be quite achievable to implement the behavior @ansis described in an earlier post using this variable.

There are some cons in this approach of course. Having constant altitude will result in more exaggerated texture minification near poles that leads to more texture aliasing artefacts. Tile streaming logic is still done using the traditional zoom level which means that more tiles will be visible as camera is farther away from the map.

```
diff --git a/src/geo/transform.js b/src/geo/transform.js
index 82e4b6342..22b0e5a35 100644
--- a/src/geo/transform.js
+++ b/src/geo/transform.js
@@ -1667,7 +1667,7 @@ class Transform {
         // Z-axis uses pixel coordinates when globe mode is enabled
         const pixelsPerMeter = this.pixelsPerMeter;
 
-        this._projectionScaler = pixelsPerMeter / (mercatorZfromAltitude(1, this.center.lat) * this.worldSize);
+        this._projectionScaler = 1.0;
         this.cameraToCenterDistance = 0.5 / Math.tan(halfFov) * this.height * this._projectionScaler;
 
         this._updateCameraState();
```

https://user-images.githubusercontent.com/55925868/165380213-2a6549a5-89dc-49f6-92e6-32588557183c.mp4

**Comment by AgentSmith0** [comment]
Is it possible to add an option to the map constructor, to change the default behaviour?
