### ISSUE TITLE
Label latency panning globe view

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11351]
Seeing that if you pan quickly on a map with globe projection, the labels dislocate from their position and there's some latency with their disappearance:

![label-latency](https://user-images.githubusercontent.com/61150/146998292-6598d193-adb3-41ca-a89c-214ab8c7bb4a.gif)

Here's a snapshot of the gif above that captures the odd behaviour

<img width="334" alt="Screen Shot 2021-12-21 at 4 10 46 PM" src="https://user-images.githubusercontent.com/61150/146998436-01f7e995-81a4-4e9f-9e59-5c44d6806c42.png">

Countries in Central America are carried over as the map is panned sharply to the middle east 

---

**Mapbox GL JS version:** `2.7.0-alpha.1`

**Comment by karimnaaji** [comment]
Some thoughts on how we may be able to approach this:

Terrain depth rendering (useful for symbol occlusion) was disabled in https://github.com/mapbox/mapbox-gl-js/pull/11329/commits/d1bf917100d52887b0343090adb7d3b56b31421e for performance reasons: it is more performant and many less draw calls to skip terrain depth for symbol occlusion, since terrain occlusion contribution is very low at the zooms at which we display the globe. Instead, tiles are culled as part of the tile coverage, by adjusting the frustum far plane to be matching the end of the horizon (determining what part of the sphere is seen).  For these tiles, we could disable label fading, and this may be done by detecting which tiles are backfacing and doing a hard reset on the symbol opacity.
