### ISSUE TITLE
Getting CSS "CssSyntaxError" while using react-azure-maps

### ISSUE THREAD

**Issue by harshpatel1408** [mapbox/mapbox-gl-js#11378]
Hello

I used `react-azure-maps` to interact with azure maps and as a dependency package `mapbox-gl` is also added. So, while running the application using simple `npm "webpack serve` I'm getting strange error from the library mapbox-gl

Error:
```
in ./node_modules/mapbox-gl/src/css/mapbox-gl.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/css-loader/dist/cjs.js!./node_modules/mapbox-gl/src/css/mapbox-gl.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError
```

Webpack:
```
const { merge } = require("webpack-merge");
const singleSpaDefaults = require("webpack-config-single-spa-react-ts");
const Dotenv = require("dotenv-webpack");
const path = require("path");

module.exports = (webpackConfigEnv, argv) => {
  const defaultConfig = singleSpaDefaults({
    orgName: "ABC",
    projectName: "test",
    webpackConfigEnv,
    argv,
    orgPackagesAsExternal: false,
  });

  return merge(defaultConfig, {
    plugins: [
      new Dotenv({
        path: process.env.NODE_ENV ?  `./enviroment/.env.${process.env.NODE_ENV}`:'./enviroment/.env',
      }),
    ],
    module: {
      rules: [
        {
          test: /\.css$/,
          use: [
            'css-loader'
          ],
          include: path.resolve(__dirname, './node_modules')
        },
      ],
    }
  });
};

```

**Comment by ryanhamley** [comment]
I think this is an issue with the react-azure-maps library. They import `mapbox-gl.css` in [this line](https://github.com/Azure/react-azure-maps/blob/master/src/components/AzureMap/AzureMap.tsx#L7) which is presumably what's tripping up Webpack. The GL JS library doesn't import the CSS in this way. I'd recommend opening an issue in the react-azure-maps [Github repo](https://github.com/Azure/react-azure-maps). I'm going to close this since I think it's unlikely to be an issue with GL JS.
