### ISSUE TITLE
exponential interpolate expression does not interpolate for base !== 1

### ISSUE THREAD

**Issue by anneb** [mapbox/mapbox-gl-js#11373]
**mapbox-gl-js version**: 2.6.1 and below

**browser**: tested in Chrome

### Steps to Trigger Behavior
 1. add circle layer with exponential data driven circle radius, ["interpolate",["exponential",2],["get","property"]...]
 2. circle radii should scale proportional to the square of the data (circle surface is 2*pi*radius squared)
 3. instead, circle radii fall back to step values and are not interpolated. If first step output value is reduced from 5 to 0, the smaller circles completely disappear (radius=0). If the exponential base is replaced by  1 (= linear interpolation), then the radius scales linearly with the data as expected (but circle radii should not scale linearly with the data). 

### Link to Demonstration
https://jsfiddle.net/anneb/efdoL9zr/14/

### Expected Behavior
Circles for 'Rotterdam' and 'Utrecht' should exponentially scale with data, 

### Actual Behavior
'Rotterdam' and 'Utrecht' fall back to first step (input = 0, output = 5)

Replace the exponential base 2 by 1 to see linear interpolation that works as would be expected.

**Comment by ansis** [comment]
I think in this case `["interpolate",["exponential",2], ...]` is not the right approach.

This constructs an exponential function (`2^input`) and scales it so that it goes through the two end values that you provide. With scaling it looks something like this: `result = a * (2 ^ input) + b`. The way the scaling gets applied in this case makes it behave like a step function.

If the goal is to make it so that the area of the circles is proportional to the input number I would use something like this instead:

`"circle-radius": ["*", 3.5 ["sqrt", ["get", "awesomeness"]]]` 

The `3.5` is just an arbitrary scaling number that can be tweaked.

**Comment by anneb** [comment]
Thanks, for some reason I erroneously swapped the meaning of 'base' and 'exponent'.

I was looking for an interpolated stepping alternative for the "sqrt" solution because 
- it requires the scaling number
- does not directly express possible radius output in pixels
- cannot be used to derive expected output values (pixels) for use in a legend (as would be possible with step functions)
