### ISSUE TITLE
Geolocate only works once on desktop, not on subsequent clicks

### ISSUE THREAD

**Issue by janeschindler** [mapbox/mapbox-gl-js#11407]
**mapbox-gl-js version**:
0.53.1
**browser**:
chrome, safari, firefox
### Steps to Trigger Behavior

 1. include the geolocator in a new mapbox map instance
 2. click it and get located. this always works, and quite quickly.
 3. close the map and open another one, or click to deactivate the geolocator
 4. click the geolocator to locate again. it spins forever, never locates, and provides no error.
-> this is only true in desktop browsers. on mobile devices, it seems to work.
The context is a nuxt app. I'm not clear if geolocation after the first instance is just taking a very long time, or if the geolocator is failing silently. Every once in a while after maybe 10 minutes, the locator reappeared. It would be helpful to have some kind of console message telling me what is going on.

### Link to Demonstration
https://audiowalk-prod.netlify.app/

### Expected Behavior
every time you click the geolocator, it geolocates you.

### Actual Behavior
On clicks after the first page load, the geolocator spins forever but doesn't locate you.

**Comment by ryanhamley** [comment]
I can't replicate this in a [minimal reproduction](https://codepen.io/rsh412/pen/eYGwgvx). Since it hasn't been reported in any other situation, I'm inclined to think that the issue is with the particular setup of your application or your browser. If you can isolate the bug to a minimal example (not in a full application), please update this ticket and we can re-open it. If you need further assistance with implementing GL JS in your application, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).
