### ISSUE TITLE
Calling map.setTerrain() causes labels to appear above raster layers

### ISSUE THREAD

**Issue by ted-piotrowski** [mapbox/mapbox-gl-js#11421]
**mapbox-gl-js version**: Latest

**browser**: Safari 15.2. Also happens in Chrome and Firefox, but only when map pitch is > 0

### Steps to Trigger Behavior

 1. Create a map
 2. Add raster layer
 3. Add terrain layer

### Link to Demonstration

[https://jsfiddle.net/tppiotrowski/y5faxs60/1/](https://jsfiddle.net/tppiotrowski/y5faxs60/1/)

### Expected Behavior

Highway shields and city labels should remain underneath image overlay layer

<img width="524" alt="Without terrain layer" src="https://user-images.githubusercontent.com/2023571/150196178-080299e4-541a-4c07-b8a6-bb13cd37bb08.png">

### Actual Behavior

Highway shields and city label render above image overlay layer

<img width="519" alt="With terrain layer" src="https://user-images.githubusercontent.com/2023571/150196203-0e966a7c-124d-4ef7-ada9-bdd739ce909f.png">

**Comment by karimnaaji** [comment]
Hello! Terrain optimizes layer draping by default by batching subsequent drape-able layers into one large batch. We have an option that disable that optimization to honor layer draw order, `optimizeForTerrain` that you can set to `false` in the map constructor. 

_"With terrain on, if true , the map will render for performance priority, which may lead to layer reordering allowing to maximize performance (layers that are draped over terrain will be drawn first, including fill, line, background, hillshade and raster). Otherwise, if set to false , the map will always be drawn for layer order priority."_

https://docs.mapbox.com/mapbox-gl-js/api/map/#map-parameters

In that mode, layers may still be batched to improve performance, and visual correctness preserved. We decided not to make that the default to provide best terrain performance out of the box.
