### ISSUE TITLE
Overlaping icons with halo

### ISSUE THREAD

**Issue by stepanchvatik** [mapbox/mapbox-gl-js#11430]
Hello, I have custom layer viewer, where user can define SDF icon color (and outline). I solved outline by adding second layer with little bigger icons (blue hexagons under green hexagons). But when there are more overlapping, I need to see the outline. I mean The blue layer is bellow green layer, and I need to feature1 of blue to be bellow feature1 of green, which should be bellow feature2 of blue and so on.... I tried also icon-halo, but the result was same, maybe even worse. 

My idea is to add layer for each point ( layers: [bluelayer_feature_1,greenlayer_feature_1,bluelayer_feature_2,..] since number of points is few hundreds. 

Of course another solution is draw hundreds of icons, so user wouldn't pick color from colopicker, but from icons list.

Any idea?

current situation
![image](https://user-images.githubusercontent.com/34139286/150536871-d187ffd9-9edc-47cc-973d-2eccedab8919.png)

desired result
![image](https://user-images.githubusercontent.com/34139286/150537456-aeb99fdc-ce0f-4773-b46d-c97fb11a34df.png)

**Comment by ryanhamley** [comment]
The problem is that sorting and layering across multiple layers isn't something that's easily achieved. GL JS doesn't really know that the green and blue layers are linked in any way. If it works for you in terms of performance, you could add a new layer for each icon to get around this. Alternatively, you can create the icon with the outline and add it as a single layer; if you need more fine-grained control, something like [symbol-sort-key](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-symbol-sort-key) might be helpful. If you need more help, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).
