### ISSUE TITLE
Heatmaps and circles are visible through the earth during Globe-Mercator transitions

### ISSUE THREAD

**Issue by SnailBones** [mapbox/mapbox-gl-js#11476]
**browser**: all

### Steps to Trigger Behavior

- Open heatmap demo
- In console: `map.setProjection('globe')`
- Zoom in until globe begins to transition to Mercator

https://user-images.githubusercontent.com/14878684/152618422-99d64246-f24d-409a-b7f0-76ed66d08461.mov

### Expected Behavior

Distant heatmaps should not be visible until they are over the horizon

### Actual Behavior

Distance heatmaps can be seen through the earth

cc @akoylasar

**Comment by mpulkki-mapbox** [comment]
This is kind-of an expected behavior right now. Circles and "heatmap circles" are checked against the view frustum so that they're properly occluded by the globe. During transitions the far plane of the camera is interpolated between distances used with globe and mercator modes leading to this issue as circles are no longer clipped by the frustum. This is more visible with zoom based transition and less of a problem with animated transitions.

Perhaps we could try non-linear interpolation for the far plane distance? cc @akoylasar

**Comment by SnailBones** [comment]
A similar bug: In globe view circles can jump briefly while zooming out as the map switches from transition to full Globe.

https://user-images.githubusercontent.com/14878684/153337867-e9c42e79-5b80-426d-8863-4a0652189c81.mov

.
