### ISSUE TITLE
can we use setPaintProperty to update more than one value?

### ISSUE THREAD

**Issue by aryamandhawan** [mapbox/mapbox-gl-js#11495]
### Question
Is it possible to set multple paint properties at once for a given layer using setPaintProperty for a layer?

I want to change the paint properties for circle-color namely ```circle-color``` and ```circle-radius```
currently I have to write 2 different functions - 
``` 
map.setPaintProperty("image_point_layer", 
          "circle-color": "red"
      );
map.setPaintProperty("image_point_layer", 
          "circle-radius": "5"
      );
```

1. Why not/ why is updating multiple properties using ```setPaintProperty()```?
maybe somthing like this ->
```
map.setPaintProperty("image_point_layer", 
        {
          "circle-color": "red",
          "circle-radius": "5"
        }
);
```
![image](https://user-images.githubusercontent.com/21696511/153314535-fa157806-5d24-4fd0-92f4-abd693ac3b4e.png)

2. What is and how to use the options paramter?

**Comment by ryanhamley** [comment]
Hi @aryamandhawan `map.setPaintProperty` can only change one paint property at a time, because the second argument to the method is a string.

The options object is defined directly below the Parameters in the method description. For `setPaintProperty`, the only option is `validate`: "Whether to check if `value` conforms to the Mapbox GL Style Specification. Disabling validation is a performance optimization that should only be used if you have previously validated the values you will be passing to this function."
