### ISSUE TITLE
Marker on Southpole [180, -90] not displayed

### ISSUE THREAD

**Issue by slavanga** [mapbox/mapbox-gl-js#11536]
**mapbox-gl-js version**: 2.7.0

**browser**: all

### Steps to Trigger Behavior

 1. Open demo link
 2. Zoom all the way out

### Link to Demonstration

https://codepen.io/slavanga/pen/JjOLNpr

### Expected Behavior

A marker should be rendered at the coordinate [180, -90]

### Actual Behavior

No marker is rendered

**Comment by ryanhamley** [comment]
Hi @slavanga the marker does render, but it's offscreen, since the Mercator projection ends at approximately -85.56°. You can see this if you set the coordinates to `[180, -86]` and the marker will be halfway off the bottom of the screen. I don't think we necessarily want to change this behavior, because other projections have different boundaries. The Winkel Tripel projection, for example, shows a marker at `[180, -90]`.
