### ISSUE TITLE
City Name need to be changed

### ISSUE THREAD

**Issue by swarnkiran88** [mapbox/mapbox-gl-js#11593]
**mapbox-gl-js version**:
https://api.mapbox.com/geocoding/v5/mapbox.places/39.20359,21.778605.json?language%20=en&

**browser**:
Chrome 
### Steps to Trigger Behavior

 1. If I search the lat and long via API I am receiving the wrong city name, it should be Jeddah instead I am receiving Jiddah
 2. you can cross verify in map box search for the name refered below.
 3.

### Link to Demonstration

https://www.mapbox.com/contribute/#/details?utm_source=https%3A%2F%2Fwww.mapbox.com%2F&utm_medium=attribution_link&utm_campaign=referrer&l=11.0424%2F21.5364%2F39.2305&q=jeddah

### Expected Behavior

"place_name":"Jeddah

### Actual Behavior

"place_name":"Jiddah

**Comment by thismakessand** [comment]
@swarnkiran88  looks like you have an extra space in your query param.  Try `language=en` instead of `language%20=en`.  The English name of this place is Jeddah so it should work as expected when language=en.

![image](https://user-images.githubusercontent.com/2924736/158424918-b7bc8e58-41fd-4b5c-8018-c825c16ed75a.png)
