### ISSUE TITLE
Re-add mouse latlng example

### ISSUE THREAD

**Issue by abenrob** [mapbox/mapbox-gl-js#1171]
https://www.mapbox.com/mapbox-gl-js/example/mouse-latlng/

Throwing "Uncaught TypeError: Cannot read property 'lat' of undefined"

Example not using the referenced map.unproject method.

**Comment by jfirebaugh** [comment]
The issue is that `latLng` is a recent addition (1c086b1776a02c9bfcd9447883c46b7fd9aa108a) and is not in a released version yet. But this example duplicates the [mouse-position](https://github.com/mapbox/mapbox-gl-js/blob/master/docs/_posts/examples/3400-01-05-mouse-position.html) example, which is working. @tmcw -- Can we remove it?

**Comment by tmcw** [comment]
Yeah.. revert it for now, re-add it on release. Got pwned by working on a local copy.

**Comment by jfirebaugh** [comment]
How about just port the improvements (using `latLng`, better CSS) to the existing example: https://www.mapbox.com/mapbox-gl-js/example/mouse-position/

This can happen right now, on the master branch.

**Comment by jfirebaugh** [comment]
d5462e2d9d518534dadb29a155ae407d3833e801, #1222.
