### ISSUE TITLE
Clustering on some data sets causes points and clusters to disappear entirely

### ISSUE THREAD

**Issue by Jon-B94** [mapbox/mapbox-gl-js#11937]
When using clustering, some data sets will have their points disappear entirely even after clustering is applied. It is possible to also observe some points disappear and reappear inappropriately (as shown by the images). Removing clustering stops the issue from occurring. 

Clusters Shown:
![image](https://user-images.githubusercontent.com/106277321/170357075-7d4748b1-65e0-4389-ae38-20f4723426f5.png)

Clusters Gone (zooming out does not bring them back):
![image](https://user-images.githubusercontent.com/106277321/170357121-fd03d5d1-655e-4e9e-b635-d757d646a679.png)

Disappearing points: 
![image](https://user-images.githubusercontent.com/106277321/170356884-a8956821-72d8-4300-a8dc-36dbd969f7fc.png)

Reappearing points:
![image](https://user-images.githubusercontent.com/106277321/170356942-77544e98-51e2-4f05-b9dc-57c3edeccd34.png)

**mapbox-gl-js version**: 2.8.2 (I believe this happens in earlier versions as well)

**browser**: Any

### Steps to Trigger Behavior

 1. Load in source data with clustering enabled
 2. Zoom out of source data
 3. Observe that all clustered points disappear

### Link to Demonstration

https://jsfiddle.net/8qob4e7m/24/

### Expected Behavior

When you zoom out, you should see clusters of points. When you zoom in, all the points should be visible. 

### Actual Behavior

When you zoom out, the clustered points are disappearing entirely. When you zoom in, some points come into and out of focus depending on zoom level.

**Comment by karimnaaji** [comment]
@Jon-B94 supercluster requires the input GeoJSON to be of type Point, your data has a lot of GeoJSON data types represented as LineString, so you could reorganize the data to be split in point types if you need them to be processed correctly by supercluster.

Refer the documentation [here](https://github.com/mapbox/supercluster/tree/54ef093df73246ef3ebcd4c27084614613570780#loadpoints). Otherwise, this data result in a bunch of NaN value when they are being processed due to the wrong data type.
