### ISSUE TITLE
Getting a blank map while parsing from HTML script in React environment

### ISSUE THREAD

**Issue by lymine1996** [mapbox/mapbox-gl-js#12139]
**mapbox-gl-js version**: 2.7.0

**browser**: All major browsers (Chrome, Edge)

### Steps to Trigger Behavior

 1. I've been trying to render a report page with an embedded **map** from **Mapbox**. 
 2. The report was previously saved in the database as **HTML** in a **string** format. [This page](https://codesandbox.io/s/frosty-smoke-xbhzjk?file=/index.html) itself works perfectly under the primitive HTML/JS environment.
 3. When it comes to the **React** settings, I tried to simply import it using the `dangerouslysetinnerhtml` attribute like [this example](https://codesandbox.io/s/agitated-browser-zey1w4?file=/src/App.js), but suddenly the map stopped working and only showed nothing but whiteness. 
 4. I've also tried using the `parse` function from the `html-react-parser` package but it didn't work either.

### Link to Demonstration

[Original HTML Report](https://codesandbox.io/s/frosty-smoke-xbhzjk?file=/index.html)

[HTML Report Rendered in React](https://codesandbox.io/s/agitated-browser-zey1w4?file=/src/App.js)

### Expected Behavior

[Original HTML Report](https://codesandbox.io/s/frosty-smoke-xbhzjk?file=/index.html)

![image](https://user-images.githubusercontent.com/57604288/183223417-6458a81c-cda6-4f06-8fcb-b2d83d3361e2.png)

### Actual Behavior

[HTML Report Rendered in React](https://codesandbox.io/s/agitated-browser-zey1w4?file=/src/App.js)

![image](https://user-images.githubusercontent.com/57604288/183223431-56266460-da2a-4814-ab0a-b3782c7a938d.png)

**Comment by stepankuzmin** [comment]
Hi @lymine1996,

This is because of the [`innerHTML` security considerations](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#security_considerations). [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) is React’s replacement for using `innerHTML` in the browser DOM. HTML5 specifies that a [<script>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) tag inserted with innerHTML [should not execute](https://www.w3.org/TR/2008/WD-html5-20080610/dom.html#innerhtml0).
