### ISSUE TITLE
Does mapbox-gl-js collect telemetry? If so, how can I turn it off?

### ISSUE THREAD

**Issue by sfc-gh-tteixeira** [mapbox/mapbox-gl-js#12151]
**mapbox-gl-js version**: any

### Question

Hi there!

Does mapbox-gl-js collect telemetry? In particular, what kinds of user data do you collect (IP address, user agent string, etc)? And how can I turn this collection off?

I tried searching this in the docs but could not find an answer. Apologies if I missed it somehow!

### Links to related documentation

* https://docs.mapbox.com/help/troubleshooting/how-to-use-mapbox-securely/?size=n_10_n
* https://docs.mapbox.com/help/glossary/telemetry/

**Comment by sfc-gh-tteixeira** [comment]
I forgot to mention, I did find [this thread](https://github.com/mapbox/mapbox-gl-js/issues/9687#issuecomment-628419519) which says mapbox-gl-js in fact **does not** collect any telemetry. If so, can you confirm that this is accurate?

**Comment by mourner** [comment]
GL JS only collects technical telemetry — assigning a random ID to a user and collecting it for technical purposes (e.g. analytics for how many unique users are on a particular version). Here's the relevant GL JS code (you can browse the full file for details):

https://github.com/mapbox/mapbox-gl-js/blob/5b9609ff87019f6d096decc3c0a6284a604dda49/src/util/mapbox.js#L366-L373

You can't turn it off since it's part of Mapbox Terms of Service. Mapbox takes user privacy very seriously though — you can read more in detail here: https://www.mapbox.com/legal/privacy
