### ISSUE TITLE
How can I get the altitude of the MapBox Camera?

### ISSUE THREAD

**Issue by jrefusta** [mapbox/mapbox-gl-js#12180]
Hello everyone,

I need to know the position of the MapBox camera in 3D coordinates (x, y, z). For that, I thought that I can use the method MercatorCoordinate.fromLngLat([lat, lng], alt)
In that case, I only need the longitude and latitude (which I can get them using the .getCenter() method) and the altitude.
How can I get the altitude of the MapBox Camera in order to get its 3D coordinates?

Thank you in advance!
Joan.

**Comment by avpeery** [comment]
Hi @jrefusta - Thank you for using mapbox-gl-js! You can use the method `map.queryTerrainElevation(lnglat)` in order to get the altitude. Here are our [docs](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#queryterrainelevation) on `queryTerrainElevation`. This [example](https://docs.mapbox.com/mapbox-gl-js/example/query-terrain-elevation/) using `queryTerrainElevation` may also be helpful.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.
