### ISSUE TITLE
Why is the direction reversed?

### ISSUE THREAD

**Issue by kt7456** [mapbox/mapbox-gl-js#12221]
![image](https://user-images.githubusercontent.com/35618730/188782603-d53d93e1-5463-4922-b0b2-9e9921deca96.png)
![image](https://user-images.githubusercontent.com/35618730/188782620-0b704546-fc5a-4169-b90b-84755ca8a975.png)
the first picture is using webgl render
the second picture is using mapboxgl render
Why is the direction reversed，what causes this? thanks！
`const modelRotate = [Math.PI / 2, 0, 0]; `
this code is from the example
https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/
this is the address
Why need to rotate？

**Comment by mourner** [comment]
There's no way we could answer this question because you haven't provided any details as the bug report form suggests. What result do you expect, the one on the first image or the second? Where does the data come from? Do you have a live test page demonstrating this?

Judging from the pictures, it's not rotated by flipped vertically, which could be explained e.g. by the data being in longitude/latitude and latitude going in opposite direction to the usual y axis (smaller numbers are down, bigger are up), which is a common mistake in GIS. But can't say for sure without more details.

**Comment by kt7456** [comment]
thanks ,this is demo address
https://plnkr.co/edit/zdKhXxpkDkgIThfm?preview
![1662605696995](https://user-images.githubusercontent.com/35618730/189047656-ab812806-a484-430b-a3f8-75bafdf2d696.jpg)
<img width="371" alt="1662605680100" src="https://user-images.githubusercontent.com/35618730/189047955-f6ed3487-0766-45cb-9d7d-54c51b29f2c4.png">

first picture is incorrect direction
second picture is correct direction

**Comment by kt7456** [comment]
> There's no way we could answer this question because you haven't provided any details as the bug report form suggests. What result do you expect, the one on the first image or the second? Where does the data come from? Do you have a live test page demonstrating this?
> 
> Judging from the pictures, it's not rotated by flipped vertically, which could be explained e.g. by the data being in longitude/latitude and latitude going in opposite direction to the usual y axis (smaller numbers are down, bigger are up), which is a common mistake in GIS. But can't say for sure without more details.

hi
