### ISSUE TITLE
How to prevent animate Markers which are out of bounds?

### ISSUE THREAD

**Issue by tonviet712** [mapbox/mapbox-gl-js#12313]
I got thousands Custom Markers need to display on map I wanna ask how I can prevent Mapbox stop Markers's animate/modify css (transform animation) that out of bounds ? 

Like this video (https://imgur.com/a/7uST3lF). When I moved the map, all markers are animated (transforms - translate)
How to just animate Markers which are in bounds ?

If no way, how I can display 5k-10k Custom Markers without lagging ? 

I follow this to Add Custom Icon Markers: https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/

Thank you in advance

**Comment by mourner** [comment]
Markers aren't really meant to be used in such amounts because they're HTML elements, and animating such an amount is difficult for browsers to do, independent of GL JS. For a large amount of points, I'd suggest using GeoJSON with a symbol layer — you can assign custom icons to symbols as well, see the other examples here: https://docs.mapbox.com/mapbox-gl-js/example/?search=icon
