### ISSUE TITLE
Satellite tiles are very bad, full with cloud covered ground and blurry images

### ISSUE THREAD

**Issue by SourceCipher** [mapbox/mapbox-gl-js#12485]
**mapbox-gl-js version**:  2.10.0

### Question
We are trying to add the satellite style to the map but we noticing that the image quality in UK is horrible to the point where its really useless to even have it. 

For example this image you can see how different the tiles are on the same zoom level. Some even worse.
![image](https://user-images.githubusercontent.com/351018/208857084-45f034d7-ac0e-4c45-98e9-9093f645afab.png)

This for example is covering cities with the clouds and its impossible to view anything at all.
![image](https://user-images.githubusercontent.com/351018/208857823-8186f299-3d66-4ac0-8409-3062dbc5e1c7.png)

We are trying to shift our product to mapbox and we have been testing various solutions and so far its an amazing library, great performance etc, but this satellite mode is really bad.

Is there a way to make them better? Maybe replace with a 3rd party tile source?

**Comment by enersis-pst** [comment]
for shure, take a 3rd party service, pay for it and add it as raster source ;-).

**Comment by mourner** [comment]
@SourceCipher I'd suggest reaching out to [Mapbox support](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231), and please be sure to include as many details as possible, in particular specific coordinates of areas with low quality satellite coverage. Our satellite team constantly monitors and addresses feedback like this.

Closing the issue here since this repository is for reporting issues about the GL JS library itself, not the Mapbox data services.
