### ISSUE TITLE
Converting vt-geojson back to standardized geojson for use in turf

### ISSUE THREAD

**Issue by doebi** [mapbox/mapbox-gl-js#12495]
### Question

I am trying to transform the output of supercluster with turf, but since supercluster.getTile() returns a "vt-geojson" and turf expects a standardized geojson it won't compute. Which library is used to fill in this gap?

I tried [1] but it throws some internal errors. Is this up to date?

The library for geojson-vt[2] only provides methods for converting FROM geojson, but not TO geojson.

My previous flow was as follows:
features[] -> supercluster: vt-geojson -> vt-pbf:pbf and expose this as tiled vector layer to mapbox-gl-js

Now I want to use turf and apply some transformations after supercluster, before sending to the client via vt-pbf.

What is the recommended way of doing this?

Thanks.

### Links to related documentation
[1] https://github.com/mapbox/vector-tile-js
[2] https://github.com/mapbox/geojson-vt

**Comment by mourner** [comment]
I'd suggest using SuperCluster's [getClusters method](https://github.com/mapbox/supercluster#getclustersbbox-zoom) instead of `getTile` — the former returns GeoJSON features and the latter VT-compatible ones. If you have any further trouble, feel free to open an issue in the Supercluster repo (this one is for GL JS specifically).
