### ISSUE TITLE
Mapbox expects unavailable MVT pbf files

### ISSUE THREAD

**Issue by qwertguy** [mapbox/mapbox-gl-js#12529]
Hello, I want to convert a geojson to MVT and upload it to my s3 bucket. 
I tried multiple different geojson (lines and polygons) and used tippecanoe and ogr2ogr. 
After creating the MVT folder structure I upload it to my bucket and make use of it with Mapbox GL JS.

**mapbox-gl-js version**: ^2.11.1

**browser**: Firefox and Chrome and all other

### Steps to Trigger Behavior

 1. `tippecanoe --no-feature-limit --no-tile-size-limit --no-tile-compression --no-line-simplification --no-tiny-polygon-reduction --output-to-directory ../mbtiles/protectedareas ../mbtiles/protectedareas.geojson`
 2.  **OR** `ogr2ogr -f MVT ../mbtiles/protectedareas ../mbtiles/protectedareas.geojson -dsco MAXZOOM=10`
 3. Upload it to s3 bucket. The bucket is public. 
 4. Use it in Mapbox GL JS like:
 
`        map.addSource("protectedareas", {
            type: "vector",
            tiles: ["https://XYZ.s3.eu-central-1.amazonaws.com/protectedareas/{z}/{x}/{y}.pbf"],
        });`
`
        map.addLayer({
            id: "protectedareas-layer",
            type: "fill",
            source: "protectedareas",
            "source-layer": "protectedareas",
            layout: {},
            paint: {
                "fill-color": "#8cbd97",
                "fill-opacity": 0.50,
            },
        });`

### Link to Demonstration

Hard to demonstrate.

### Expected Behavior

Mapbox renders all tiles correctly. 

### Actual Behavior

It is working (most of the time) but Mapbox is asking for some Y tiles that are not available.
Browser error:
`{status: 403, url: 'https://XYZ.s3.eu-central-1.amazonaws.com/protectedareas/6/21/34.pbf', message: 'Forbidden'}`
When I look in the MVT folder I cannot find 6/21/34 but 33.

Sometimes it also misses the X coordinate.

There is one tutorial on the whole internet that reports the descending order problem after converting a geojson to mvt. https://geovation.github.io/tippecanoe-directory-support

What do I have to change? 

Thanks

**Comment by qwertguy** [comment]
I found this tutorial https://www.danieltrone.com/post/aws-vector-tiles-cloudfront/

He has a demo here https://www.danieltrone.com/map-tiles-s3/

When viewing the console he also gets these errors

<img width="913" alt="grafik" src="https://user-images.githubusercontent.com/38832691/213687088-4b41afe9-3844-4264-a8d9-f405f6161726.png">


How can I fix them?

**Comment by stepankuzmin** [comment]
Hi @qwertguy,

The problem is that you might miss some tiles after converting GeoJSON to Vector tiles because no data in GeoJSON cover this particular area. You can eliminate the 403 errors, but you'd need to change the response status from S3 to 404 for missing tiles.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
