### ISSUE TITLE
setConstant API?

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#1259]
Changing a color in the editor can be cascaded nicely, but changing a color via a constant (which happens a lot if you're tweaking preset style templates) doesn't cascade and looks jarring. Would it be worth adding a `setConstant` API that can cascade paint props? (potentially related to the [typed constants](https://github.com/mapbox/mapbox-gl-style-spec/issues/227) change…)

cc @jfirebaugh @tmcw @edenh @samanpwbb

**Comment by jfirebaugh** [comment]
Definitely. It should have `removeConstant` too.

**Comment by edenh** [comment]
:+1:

**Comment by jfirebaugh** [comment]
Here are some implementation notes. This is going to be a fairly complex addition, so feel free to ask questions.

* This should follow the pattern for the existing mutable style API methods: the public API is provided in `Map`, which delegates to `Style`, plus handles any other tasks necessary to keep everything in sync. The "other tasks" is mainly triggering `this.style._cascade`, and `this.update`, which are necessary whenever a change is made that affects paint properties. Since `setConstant` could be setting a constant value used in paint properties, it will need to do these two things as well.
* `Style` and `StyleLayer` is where all the interesting stuff will happen. The entry point to understanding how constants are currently handled is the [`_resolve` method of Style](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style.js#L97-97) and the other `resolve*` methods it calls.
* When a constant value is changed, you will need to figure out where that constant is being used, and re-resolve the properties that use it. For paint properties, the updated value can be rendered immediately. Layout properties will require that the tiles for the source be reloaded so that they are laid out again using the new value -- see what `setLayoutProperty` does.
* The existing way that constants are stored / resolved may not longer meet our needs. It may make sense to resolve constants "just in time", at the moment the property value is requested, rather than ahead of time, as they are now. It will require investigation to figure out what the best strategy is.
* This should be tied to implementation of typed constants in v8, and built off that code. @tmcw -- is the types implementation in the v8 branch complete?

**Comment by jfirebaugh** [comment]
Constants are being removed in v8.
