### ISSUE TITLE
Fill layers are partially rendered for high zoom values

### ISSUE THREAD

**Issue by vcardins** [mapbox/mapbox-gl-js#12603]
Once I display a fill layer on the map, with a zoom greater than exactly 8 (8.01) , the layer is only partially rendered. For zoom values less than 8 (7.99) it works correctly.

**mapbox-gl-js version**: 2.10.0

**browser**: Chrome Version 110.0.5481.177 (Official Build) (arm64)

### Steps to Trigger Behavior

 1. Add a `fill` layer with paint props: 
 {
	'fill-color': 'red',
	'fill-opacity': 0.3,
	'fill-antialias': true,
}
 2. Zoom in to a level greater than 8.5
 3. The fill layer will be partially rendered

### Link to Demonstration
At 8 zoom level
<img width="694" alt="image" src="https://user-images.githubusercontent.com/2383329/222302294-c1d32ee1-33b7-4617-9587-33f3d9445b46.png">

At 7.5 zoom level
<img width="876" alt="image" src="https://user-images.githubusercontent.com/2383329/222302544-b5a2fd2d-865c-4b33-924c-0750c4441d0d.png">

### Expected Behavior
The vectors layer should render correctly regardless of the zoom level

**Comment by vcardins** [comment]
Any thought on this?

**Comment by stepankuzmin** [comment]
Hi @vcardins,

Thank you for opening this ticket. Please provide a small reproducible demonstration for this. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.

**Comment by mmnoo** [comment]
I investigated this bug, and it stemmed from the fact that we were using geometry returned from `map.queryRenderedFeatures()`. That function seems to return a coordinates array with items in the wrong order when zoomed in (but functioned as expected when zoomed out). 

The fix was to track our feature geometry using application state and not query features from the map.
