### ISSUE TITLE
featuresAt returns an empty array

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#1265]
No clear errors shown and I'm also reproducing in [debug/site.js](https://github.com/mapbox/mapbox-gl-js/blob/master/debug/site.js) with like:

```js
map.on('mousemove', function(e) {
  map.featuresAt(e.point, {radius: 5}, function(err, d) {
    console.log(d); // Always `[]`
  });
});
```

**Comment by peterqliu** [comment]
@tristen are you using it on layers that are `interactive:true`?

**Comment by tristen** [comment]
>  are you using it on layers that are `interactive:true`?

Yep still empty.

**Comment by robbiet480** [comment]
Also having this issue when using a slightly modified [GeoJSON example](https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/) with the same code as @tristen except listening for the click instead of mousemove. If I do something like:

```
style.layers.forEach(function(layer) {
  layer.interactive = true;
});
```
from the [featuresAt example](https://www.mapbox.com/mapbox-gl-js/example/featuresat/) I can see buildings and roof tops when clicked, but not the Mapbox SF & DC markers.

**Comment by mourner** [comment]
Looking into it today.

**Comment by ansis** [comment]
@tristen It works for me with the latest master if I add `"interactive": true` to the layer's style. For example:
```
{
      "id": "building",
      "interactive": true,
      "type": "fill",
      "source": "mapbox",
      "source-layer": "building",
      "paint": {
        "fill-color": "@building_color_transition"
      }
    }
```

@robbiet480 It works for me with the latest master: https://gist.github.com/ansis/ee54fa7129fa14f3a658
I made three changes to the example:
1. used master instead of v0.7
2. added `"interactive": true` to the layer's style
3. added a click handler
`featuresAt` doesn't work that well with text and icons yet. It returns the features if their data point is within radius of the click, not if they actual rendered icon/text is within radius of the click.

**Comment by robbiet480** [comment]
@ansis Yup, works for me now! So i'm guessing it's 0.7 that has a bad featuresAt implementation?

**Comment by ansis** [comment]
@robbiet480 Great! yeah, I think so.
