### ISSUE TITLE
(Question) Is it possible to overlay raster images from a local file instead of a URL?

### ISSUE THREAD

**Issue by azrellie** [mapbox/mapbox-gl-js#12679]
What I wanna know is if it's possible to use a local file instead of a URL.
(currently using the latest version of mapbox)

```
// snippet of code from https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/
map.addSource('radar', {
    'type': 'image',
     // instead of using a URL, i would use a file path to the image on the system
    'url': 'C:\Users\username\Desktop\radar_image.png',
    'coordinates': [
        [-80.425, 46.437],
        [-71.516, 46.437],
        [-71.516, 37.936],
        [-80.425, 37.936]
    ]
});
```

Also, are image formats like **tif/tiff** supported?

**Comment by stepankuzmin** [comment]
Hi @azrellie,

Thank you for using mapbox-gl-js. You'd need to set up a web server for this since browsers have limited access to the local disk for security reasons. However, you can access local files using JavaScript and the File API, which allows users to select files from their local disk using an input element with the `type="file"` attribute. The File API can then be used to read and manipulate the content of those files within the browser, but only after the user has explicitly granted access by selecting the files.

Note that this issue tracker is for reporting bugs and feature requests. You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
