### ISSUE TITLE
transformRequest does not handle all requests

### ISSUE THREAD

**Issue by willdochnur** [mapbox/mapbox-gl-js#12735]
## Version
tested in 2.15.0 and 2.10.0

## Browsers
tested in Chromium and Firefox

## Description
Because of european GDPR i want to prevent http requests to any third party servers (Mapbox servers) from client device. Instead i wanted to proxy all the requests through my own servers. My expectaction was **transformRequest** would do the trick but it does not handle all the requests.

Following requests are not being handled through **transformRequest**:
* POST https://events.mapbox.com/events/v2?access_token=[TOKEN]
* POST https://events.mapbox.com/events/v2?access_token=[TOKEN]
* GET https://api.mapbox.com/map-sessions/v1?sku=[SKU]&access_token=[TOKEN]

**Comment by stepankuzmin** [comment]
Hi @willdochnur,

Thank you for using mapbox-gl-js! Mapbox Services are [fully compliant with GDPR](https://docs.mapbox.com/accounts/guides/settings/#privacy). We don't allow overriding these requests as it's part of our billing pipeline. For future questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/).

I'm closing this issue, but feel free to reopen it if you have any questions.

**Comment by willdochnur** [comment]
Your participation in Privacy shield framework is inactive since 2021.

**Comment by stepankuzmin** [comment]
Hi @willdochnur,

Yes, that's correct. Mapbox intentionally withdrew from Privacy Shield because it was invalidated by the European Court of Justice on July 16, 2020. As such, Mapbox and numerous other companies around the globe rely on Standard Contractual Clauses ("SCC") to safeguard data transfers from the EEA to other countries. Mapbox has implemented the latest version of SCCs released in 2021 by the European Commission. Mapbox is proud to say that it has implemented and operates in compliance with the current SCCs to safeguard transfers of personal data from the EEA to other countries.

**Comment by eduard-nomi** [comment]
Will it fixed in next version of mapbox?

**Comment by stepankuzmin** [comment]
@eduard-nomi the requests to `https://events.mapbox.com` and `https://api.mapbox.com` are used to count "map load" events for account billing. Allowing these requests to be overridden could enable malicious actors to alter or drop them, potentially using another service provider while rendering maps with Mapbox GL JS. This would result in Mapbox missing map loads and underbilling the account.

**Comment by eduard-nomi** [comment]
Thank you @stepankuzmin . Do you know if there are any plans to add separate "geocode" scope for tokens? Currently any public token can be used for geocode which is billable at some point.

**Comment by JuanIrache** [comment]
> [@eduard-nomi](https://github.com/eduard-nomi) the requests to `https://events.mapbox.com` and `https://api.mapbox.com` are used to count "map load" events for account billing. Allowing these requests to be overridden could enable malicious actors to alter or drop them, potentially using another service provider while rendering maps with Mapbox GL JS. This would result in Mapbox missing map loads and underbilling the account.

Currently, since proxies are not allowed and tokens can only be restricted by URL, a bad actor can easily work around the URL restriction (useless in the case of desktop software) and overbill our account. If allowing proxying is not planned, wouldn't it be reasonable to enable either:
- Blocking or rate limiting by IP
- Blocking countries: most bad actors come from certain countries and the MapBox backend already tracks map loads per country

I understand this is not a priority for MapBox, as the problem increases their revenue (in an immoral way).
