### ISSUE TITLE
Feature `ClosePath` command fails if only command in stream

### ISSUE THREAD

**Issue by nicomgd** [mapbox/mapbox-gl-js#1276]
I've been testing mapbox-gl-js with a custom dataset created using Mapbox Studio from a SHP file (world country boundaries, downloaded [here]( http://thematicmapping.org/downloads/TM_WORLD_BORDERS-0.3.zip) in SHP).

While viewing the data, some tiles go missing and a console error appears :
`Uncaught TypeError: Cannot read property 'push' of undefined`.

The error happens with the current *master* build and with v0.7.0.

I've traced down the problem to `VectorTileFeature.prototype.loadGeometry` :
```javascript
} else if (cmd === 7) {
    line.push(line[0].clone()); // closePolygon
}
```

This code expects line to be valid, but the data somehow has a feature which only contains a `7` command.

If I add a `if (line)` before `line.push` my data appears to be fine.

Is such data invalid ? or should mbgl-js be robust and handle this gracefully ?

**Comment by jfirebaugh** [comment]
Previously: #1019.

The data is invalid, due to [a bug in mapnik-vector-tile](https://github.com/mapbox/mapnik-vector-tile/issues/90) that has been fixed, but not made it into a Mapbox Studio release yet. I've published a workaround to the library that gl-js uses and will integrate it into gl-js shortly.
