### ISSUE TITLE
How can I get a heatmap whose radii change with zoom level?

### ISSUE THREAD

**Issue by jadekler** [mapbox/mapbox-gl-js#12916]
**mapbox-gl-js version**: HEAD

### Question

How can I get a heatmap whose radii change with zoom level?

I've read https://github.com/mapbox/mapbox-gl-js/issues/8165, https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/, and https://docs.mapbox.com/style-spec/reference/expressions/#interpolate and am still struggling to figure it out.

I am currently trying the following which on the face seems like it should work, but does not:

```
                'heatmap-radius': [
                    'interpolate',
                    ['exponential', 2],
                    ['zoom'],
                    10,
                    10,
                ],
```

I suspect my problem is the steps. I don't really understand them at all. Perhaps it's something else though. Thanks for any tips.

### Links to related documentation

Linked above.

**Comment by jadekler** [comment]
I used `import {Expression} from 'mapbox-expression';` to see what values this expression evaluates to and it's bafflingly always `10`. I guess I really don't understand steps after all. Any help would be appreciated.

**Comment by jadekler** [comment]
It appears as though `['zoom']` never changes, even though I certainly am zooming in and out:

```
    map.on('zoom', (e) => {
        // Always map.getZoom varies, but ['zoom'] is always 14 in my case.
        console.log('zoom:', map.getZoom(), 'expression zoom:', Expression.parse(['zoom']).evaluate(map));
    });
```

**Comment by rafraser** [comment]
Your issue is indeed with the stops - they're a little tricky to figure out. I'll admit most of my interpolate expressions are copy pasted from somewhere with the numbers changed!

The stops in interpolate are input and output pairs. As an example:

```
['interpolate', ['linear'], ['zoom'], 7, a, 14, b]
```

At zoom level 7 this expression will be ***a***, at zoom level 14 this will be ***b***, and at anything in between it'll interpolate between a and b.

The choice of ['linear'] vs ['exponential', 2] doesn't adjust the input/output stops you provide, but just describes the curve to interpolate between them.

---

Going back to your main point for the fixed-zoom heatmaps, you'll need to choose the stops in a way that the radius doubles for each change in zoom level. Something like this should work for you (with adjustments of the zoom levels and sizing according to your map):

```
'heatmap-radius': [
    'interpolate',
    ['exponential', 2],
    ['zoom'],
    10,
    1,
    15,
    32
],
```

At zoom level 10, we have a heatmap radius of 1. At zoom level 15, we've changed 5 zoom levels, so we need a 2^5 increase in radius giving us *32*.

**Comment by mourner** [comment]
@rafraser thank you for the thoughtful response, that's exactly right 👍
