### ISSUE TITLE
Fitting labels onto polygon boundaries

### ISSUE THREAD

**Issue by joaoprocopio** [mapbox/mapbox-gl-js#12959]
## Motivation

I'm infront a problem that i don't know how to solve, and maybe it can have another better way to get this done. So, if i'm overcomplicating, please let me know, and leave a suggestion.

Currently the application backend that i use serves two source-layers in `MVT` format:
- `polygons`: the polygons that are rendered and manipulated in the map;
- `centroids`: useful for positioning text using the `symbol` layer;

The problem is, that some geometries are to small compared to the polygon boundaries, and it overflows, like the following images shows.

![problem](https://github.com/mapbox/mapbox-gl-js/assets/88688324/c761d529-49ff-4fdd-bbb3-282b9ca9bc0e)

There's a unanswered [GIS StackExchange](https://gis.stackexchange.com/questions/424578/fit-label-text-size-within-the-polygon-mapbox-gl-js-symbol-layer) that is almost 2 years old illustrating the same problem.

## Design Alternatives

Maybe using expression like the [`distance`](https://docs.mapbox.com/style-spec/reference/expressions/#distance).

#### It will go from this

![before](https://github.com/mapbox/mapbox-gl-js/assets/88688324/337f349b-e052-41a1-8b3a-0d25d690d68e)

#### To something like this

![after](https://github.com/mapbox/mapbox-gl-js/assets/88688324/a66108c2-d5b3-4052-93c1-816a6e8e0551)

The idea is to scale the `text-size` based on the polygon boundaries and in current zoom level.

**Comment by brncsk** [comment]
Having come across this multiple times I always chose to add the area of the polygon at tile generation time as a property, then built a zoom-based expression based on that. Not perfect but it does the job.

**Comment by joaoprocopio** [comment]
Thank you @brncsk! This is actually a great solution, i'll consider doing it.

**Comment by DylanLyon** [comment]
Just wanted to chime in with my own experience with a scenario like this. I ended up just hard coding some values in a text-size interpolation corresponding with zoom levels after some manual trial and error which was simple enough to work for my case. But the otherwise biggest improvement I found was to align the label with the longest line of the polygon. I'd determine the longest line of the polygon using distance and comparing each set of points in the polygon then I would use that line to calculate a bearing angle that I can rotate the text by.

`'text-rotate': { type: 'identity', property: 'bearing' },`
`'text-rotation-alignment': 'map',`

Using the angle I calculated and keeping the rotation of the text fixed to the map gives the labels just a bit more room and helps reduce the overlapping of other polygon labels. You can end up with some really clean looking labels like so

![image](https://github.com/mapbox/mapbox-gl-js/assets/17810202/dd8ad86b-4a60-477b-ba6a-671d9bb49eea)
![image](https://github.com/mapbox/mapbox-gl-js/assets/17810202/3c65833f-f342-497e-87ed-9f99a2a35d27)

I have some additional logic that makes sure the labels don't get rotated beyond a certain angle (so as not to appear upside down by default etc) but that's the gist of it.

**Comment by brncsk** [comment]
Oh yeah, that looks even better!

(I had to look up what [`identity`](https://docs.mapbox.com/style-spec/reference/other/#function-type) does – for those who wonder, I think the new-style way of doing that is just `["get", "bearing"]`).
