### ISSUE TITLE
Add "fill-blur" style property

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1295]
maybe related to [inner glow](https://github.com/mapbox/mapbox-gl-js/issues/769). 

I'm looking for a way to blur polygons, now that composite layers are no longer supported. [Weather maps](https://www.mapbox.com/bites/00116/?style=peterqliu.dc09c54c&access_token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g#2.27/29.08/-90.12) will be a big use case.

![screen shot 2015-06-18 at 3 56 22 pm](https://cloud.githubusercontent.com/assets/4551508/8244166/a0b274aa-15d2-11e5-9a5f-25d7e8d032a8.png)

**Comment by lucaswoj** [comment]
:+1: 

... and hill shades!

**Comment by ansis** [comment]
We should also think about other ways to structure weather and hillshade data so that we don't need to blur. The regular polygon + real blur approach was great for mapnik but there may be better ways to do it:

two possibilities are:
- rasters and more complex tinting
- an actual mesh with shared vertices. Each triangle would have three vertices with different values, instead of the same value as in the current weather data. Neighbouring triangles would share vertices.

**Comment by kkaefer** [comment]
Agreed, we can render a [TIN](https://en.wikipedia.org/wiki/Triangulated_irregular_network) very easily and have nice looking gradients in the triangles.

**Comment by mourner** [comment]
Would we generate TIN on the server with Mapnik, or client-side based on existing terrain contours VT (very hard)?

**Comment by kkaefer** [comment]
Ideally we'd generate it on the server and only display on the client.

**Comment by lucaswoj** [comment]
cc @mapbox/gl

**Comment by mourner** [comment]
Closing the issue as stale, since there doesn't seem to be much interest in addressing it. Also, I don't think polygon blur is the right solution to the use cases mentioned above.
