### ISSUE TITLE
Mapbox GL JS V3 Raster Light Emission 

### ISSUE THREAD

**Issue by rivindubandara** [mapbox/mapbox-gl-js#12974]
mapbox-gl-js version: V3

browser: All

### **Why we need this fixed**

Hi Everyone,

I have recently migrated my web app to V3 of GL JS as the new maps are visually appealing and provide more detail. I have been using the different styles for the standard base map and have particularly liked the Dusk and Night settings. However, my web app uses custom raster layers which shows planning information. When I use these darker settings such as Dusk and Night, it affects the lighting of the raster layers as well making them appear darker and not visible. I have been toggling with the raster-contrast setting which fixes the issue slightly but affects the true colour of the raster layer and doesn't work for layers such as 'Satellite'. 

### **Feature proposed**

So the feature I would like to request is some sort of lighting option for raster layers so it only lights up or brightens the raster layer and keeps the darker base maps as is.

### **What it currently looks like** 

![Screenshot 2023-11-14 110954](https://github.com/mapbox/mapbox-gl-js/assets/54240628/1b287833-a758-442f-a2e3-0deebb2c6317)

### **What it should look like**
*Note this is from V2

![Screenshot 2023-11-14 110843](https://github.com/mapbox/mapbox-gl-js/assets/54240628/389d24eb-d3b8-4351-af61-48dbaf8120ec)

**Comment by astojilj** [comment]
@rivindubandara 

Thank you for reporting it and the example. I understand that the raster layer has areas that are transparent. For those areas with color, you'd like to display the layer under 3D content, fully lit - as they were rendered without 3D lighting. Would increasing the ambient light's "intensity" property help (all the layers would get affected by it)?

Assuming we'd add like If we'd add a property like "raster-emissive-strength" and value 1 used for it, shadows from buildings would still get rendered over the content. Would that be desired behaviour?

**Comment by rivindubandara** [comment]
Hi @astojilj,

Thanks for the reply. Increasing the ambient light intensity might be useful. Is that a feature already available?

Adding a property like 'raster-emissive-strength' would be a great option. Building shadows getting rendered over is fine, they don't seem to be affecting the raster layer that much. The goal is just to make the raster layer legible and visible.

Thanks

**Comment by astojilj** [comment]
@rivindubandara 

Brightening up up the full scene using Map.setLights() would not help, for Standard Style and your use case. Style would look too bright, and the desired effect of making footprints (the raster layer) more prominent cannot be achieved.

We will work on this problem and close the issue once the fix is available.

However, let me provide a hackish example (please don't use this as productization code as it might change given that it is using internal implementation details) to demonstrate how to use setLights API:

In Standard Style, lights (directional and ambient light) properties are expressions that depend on lightPreset configuration property.

When in this example we trigger light preset change, properties get reevaluated.

<img width="897" alt="Screenshot 2023-11-17 at 13 19 50" src="https://github.com/mapbox/mapbox-gl-js/assets/549216/cb234a21-7cfe-44ff-a705-cc495c9204fb">

You could use `map.getStyle()` to explore the values of all the properties:

<img width="1198" alt="Screenshot 2023-11-17 at 13 28 08" src="https://github.com/mapbox/mapbox-gl-js/assets/549216/31247f4c-0e5c-41f6-837e-cde8ac56cc20">

e.g. to get the value and override night preset:

```
            const lights = map.getLights();
            // there are two items in array now: directional and ambient, we'll modify ambient.
            const ambient = lights && lights.find((l) => l.id === "ambient");
            let lightPreset;
            try {
                // does the style use lightPresets?
                lightPreset = map.style.getFragmentStyle('basemap').options.get('lightPreset');
            } catch (error) {
            }
            if (ambient && lightPreset) {
/* original value is like this:
                ambient.properties.color = [
                    "match",
                    ['config', 'lightPreset'],
                    "dawn",
                    "hsl(28, 98%, 93%)",
                    "day",
                    "hsl(0, 0%, 100%)",
                    "dusk",
                    "hsl(228, 27%, 29%)",
                    "night",
                    "hsl(217, 100%, 11%)", 
                    "hsl(0, 0%, 100%)"
                ];*/
                // overriding with fixed value and removal of presets usage
                ambient.properties.color = "hsl(217, 100%, 15%);
                ambient.properties.intensity = 0.7;
                map.setLights(lights);
            }
```

As mentioned, this is only for illustration. In your style, you might decide to set different values for Map.setLights. The API is defined in [Map](https://github.com/mapbox/mapbox-gl-js/blob/37624d45b7185d5a213b8a5cd094ed95a9eb49d4/src/ui/map.js#L2675) and more documentation should follow shortly. There are plenty of examples in our render tests, e.g.:

https://github.com/mapbox/mapbox-gl-js/blob/37624d45b7185d5a213b8a5cd094ed95a9eb49d4/test/integration/render-tests/lighting-3d-mode/fill-extrusion/flood-light/edge-radius/style.json#L10

**Comment by mourner** [comment]
This will be a part of v3.1.0 — please check out the beta version! https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.1.0-beta.1
