### ISSUE TITLE
Dynamic styling of cluster depending on a feature in it

### ISSUE THREAD

**Issue by dmcbrn** [mapbox/mapbox-gl-js#12978]
**2.15.0**:

### Question

I'd like to change the coloring of a cluster when it contains a specific Property of a Feature.

I use the method below to change the style of a single marker. 

```
map.setLayoutProperty(
        'location-point',
        'icon-image',
        [
            'case',
            ['==', ['get', 'id'], mapLocationActive],
            'marker',
            'marker-alt'
        ]
    );
```
This works fine.

I would like to do the similar thing (distinguish active from other clusters) when my location is inside a cluster
```
map.addLayer({
            id: 'clusters',
            type: 'circle',
            source: 'locations',
            filter: ['has', 'point_count'],
            paint: {
                'circle-color': 'white',
                'circle-radius': 30,
            }
        });
```

something like this but I don't know how to do the condition part

```
map.setLayoutProperty(
        'clusters',
        'circle-color',
        [
            'case',
            ['in', ['getClusterLeaves', 'id'], mapLocationActive], //this is wrong
            'red',
            'white'
        ],
    );
```

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/example/cluster/
https://docs.mapbox.com/style-spec/reference/expressions/#in
https://docs.mapbox.com/mapbox-gl-js/api/sources/#geojsonsource#getclusterleaves

**Comment by mourner** [comment]
As far as I understand, there's no way to do this due to limitations of the clustering design. To style a cluster based on properties of features it includes, you would usually define custom [`clusterProperties`](https://docs.mapbox.com/style-spec/reference/sources/#geojson-clusterProperties) on the GeoJSON source (there's an example of it [here](https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/)). However, since clustering happens as a single preprocessing step on initial load, there's no way to update those based on a dynamic value. 

In theory, you could do something like `ids: ['concat', ['concat', ['get', 'id'], ',']]` in `clusterProperties`, which would generate a string of all comma-separated id values in one cluster property, and you would style based on that, but this is very inefficient and would only work for cases where there are not many features in each cluster.

**Comment by mourner** [comment]
100–1000 is a pretty small amount, so this should be fine. `clusterProperties` is defined on the source level (`addSource`), not on the layer — otherwise it won't work.

**Comment by dmcbrn** [comment]
Thanks again. 

Here is the final solution for anyone wondering.

This is the source definition:
```
map.addSource('locations', {
            type: 'geojson',
            data: geoJsonData,
            cluster: true,
            clusterMaxZoom: 14, // Max zoom to cluster points on
            clusterProperties: { //data for clustering
                ids: ['concat', ['concat', ['get', 'id'], ',']]
            }
        })
```

and the `setPainProperty()`
```
map.setPaintProperty(
        'clusters',
        'circle-color',
        [
            'case',
            ['in', ['literal', mapLocationActive + ','], ['get', 'ids']],
            'red',
            'white'
        ],
    );
```
