### ISSUE TITLE
Map rendered without any features since upgrade to v3

### ISSUE THREAD

**Issue by marcel-matchory** [mapbox/mapbox-gl-js#13017]
### General

The map loads, there are no errors on the console, but displayed incorrectly (s. screenshot map_default_style below). All buttons and zooming seem to work, but the ground isn't properly shown; if you zoom all the way out, the planet is rendered with a white surface. The screenshots make this clear.

**mapbox-gl-js version**: 3.0.1

**browser**: Google Chrome Version 120.0.6099.109 (Official Build) (x86_64) on MacOs Sonoma v14.2

### Steps to Trigger Behavior

 1. Render standard map without any customization on v2.x.x
 2. Upgrade to v3
 3. Verify map doesn't render properly (s. screenshot)

### Link to Demonstration

We didn't manage to reproduce this with a Fiddle yet, so I suspect this might be related to the combination of Vue/Vite/Mapbox. Unless somebody has suggestions on the error origin, we can try to create a stripped-down reproduction repository.

### Expected Behavior

Map is correctly rendered as before when upgrading to v3

### Actual Behavior

![map_default_style](https://github.com/mapbox/mapbox-gl-js/assets/111280137/d9e9bda5-260c-4708-92f2-ee39c42efe7b)
![map_custom_style](https://github.com/mapbox/mapbox-gl-js/assets/111280137/30d0782d-8148-46ef-a841-fe1e324f7ff3)

**Comment by stepankuzmin** [comment]
Hi @marcel-matchory,

Thank you for opening this ticket. Please try isolating the issue to help us address it. We recommend using https://jsbin.com/. Does it reproduce with the [simple map](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/) and your style?

**Comment by d-low** [comment]
@stepankuzmin @marcel-matchory I was able to reproduce this issue using the simple map example in a minimal Vue 2 application. The issue happens when using Mapbox 3 if the Mapbox map instance is saved as a reactive property on a Vue component. My guess is that something Vue is doing to make the map instance "reactive" is interfering with Mapbox functionality thus making the map render with nothing more than a yellow background as seen above. 

A straight forward work around is to save the map instance to a non-reactive variable, one not managed by Vue. This work around is demonstrated in second JS Bin. 

*Map instance saved to reactive data so map doesn't render properly:*

https://jsbin.com/qivoles/edit?html,output

*Map instance saved to non-reactive global variable so map renders properly:*

https://jsbin.com/xuhowak/edit?html,output

Note that in both JS Bin examples you will need to supply a valid Mapbox access token!

**Comment by d-low** [comment]
And here is a link to an earlier issue that documents what I am seeing above:

https://github.com/mapbox/mapbox-gl-js/issues/6872

**Comment by stepankuzmin** [comment]
Hi @d-low, thanks for the reproduction! It seems like an issue with how Vue wraps the map instance into reactive data. There is not much we can do with that on the GL JS side, so I will close the issue. Feel free to reopen if you have any questions.

**Comment by marcel-matchory** [comment]
thank you @d-low  and @stepankuzmin 👍 

sorry, this got lost in the everyday hustle and bustle.
