### ISSUE TITLE
Support relative urls in batched-model - tiles url

### ISSUE THREAD

**Issue by bertt** [mapbox/mapbox-gl-js#13107]
When using releative url in tiles property of batched-models the tiles are not retrieved (v3.2.0)

```
map.addSource('bag-3d', {
        "type": "batched-model",
        "maxzoom": 15,
        "minzoom": 15,
        "tiles": [
          "./content/{z}-{x}-{y}.glb"
        ]
      }
)});
```

Demo: https://bertt.github.io/mapbox_issues/relative_url/relative/

Workaround: Use absolute url

```
map.addSource('bag-3d', {
        "type": "batched-model",
        "maxzoom": 15,
        "minzoom": 15,
        "tiles": [
          "https://bertt.github.io/mapbox_issues/relative_url/absolute/content/{z}-{x}-{y}.glb"
        ]
      }
)});
```

Demo: https://bertt.github.io/mapbox_issues/relative_url/absolute/

Request: Support relative urls for easier deployment

**Comment by stepankuzmin** [comment]
Hi @bertt,

The source `tiles` property is a part of [TileJSON Spec](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0#32-tiles), requiring all URLs to be absolute. The main reasoning behind requiring the URLs to be absolute is because it's ambiguous what a relative URL should be relative to. For example, is it the TileJSON URL, the style URL, or the page URL? What if the TileJSON is inline in the style?

Thanks again for your input.
