### ISSUE TITLE
Mapbox Giving Extra Precision in Coordinate When Using queryRenderedFeatures

### ISSUE THREAD

**Issue by mani-mworks** [mapbox/mapbox-gl-js#13286]
I'm using Mapbox GL JS and when I call `queryRenderedFeatures`, I'm getting coordinates with extra precision. For example, I receive:

```
[0.7020950317382812, 51.18327064627687]
```

However, my actual coordinates are:

```
[0.70212426, 51.18327632]
```

Is there a way to adjust the precision or retrieve the original coordinates without the additional decimal places? 

**Tags:** mapbox-gl-js, coordinates, precision

**Code Snippet:**
```javascript
// Example code for querying features
map.on('click', (e) => {
    const features = map.queryRenderedFeatures(e.point);
    console.log(features);
});
```

Mapbox GL JS version 2.7.0

Thanks in advance

**Comment by mourner** [comment]
Because GeoJSON data you provide to GL JS goes through a lot of processing for rendering (converting to tile coordinates, clipping, simplification, etc.), the resulting coordinates of rendered features won't match the original data 1:1. You'd have to round the coordinates on your app side — e.g. with something like `Math.round(1e6 * num) / 1e6`.
