### ISSUE TITLE
Please register to bower

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#1342]
Since Mapbox GL JS is a library rendering maps in browser, why not  register it on Bower?

**Comment by jakeorr** [comment]
It appears someone else put it up on bower: https://github.com/olanod/mapbox-gl-js-bower

It would be great if the official mapbox version was available through bower though. Is there some reason it is not?

**Comment by mourner** [comment]
We're not going to support an official Bower package, because:

- Bower is effectively [not developed anymore](https://github.com/bower/bower/pull/1748#issuecomment-150104311)
- It is a pain to support for library maintainers (e.g. requires committing build artifacts to the repo, which is a very bad practice), and this time is better spent improving the library itself (see https://github.com/rackt/redux/issues/944 for a sample discussion why)
- It is effectively superceded by the NPM registry and tools like Browserify, Webpack and JSPM

**Comment by bennlich** [comment]
seems like bower continues to be developed? http://bower.io/blog/2015/bower-is-growing-join-us/

other points might still hold, but thought I'd point this out.

**Comment by mariusnita** [comment]
@mourner bullet points (1) and (3) are untrue but the second bullet point is valid enough. I think the least you can do, though, is provide a prebuilt downloadable zip archive somewhere. That would work well enough with bower and is useful independent of bower. Currently -- correct me if I'm wrong -- it seems users are limited to downloading individual files from the mapbox CDN.

**Comment by lgreenlee** [comment]
Bower is actively used for many UI packages and frameworks. This would be a help to me as well.

**Comment by baikon** [comment]
bump^ please

**Comment by lucaswoj** [comment]
jQuery uses a [shim repo](https://github.com/components/jquery) which is committed to once per release https://github.com/bower/bower/issues/859. This is something we could do alongside #2250. I will leave a note on that ticket.

**Comment by j-slvr** [comment]
I understand point (2).

However for many projects that started back in the "old" bower-days it is a pain to switch the whole frontend dependencies to npm. So basically you exclude every developer that did not start his project in the last few months with npm and webpack (or something similar).

**Comment by mourner** [comment]
There's nothing preventing you from including GL JS as an ordinary script in addition to your Bower setup. You don't have to have _all_ your dependencies in Bower. We're not excluding anyone.
