### ISSUE TITLE
Make data driven styles work with transitions 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1343]
[This hack will prevent data driven styling from working with transitions](https://github.com/mapbox/mapbox-gl-js/blob/v8/js/style/style_transition.js). ~~Should be an easy fix.~~

**Comment by lucaswoj** [comment]
@ansis,

Per a conversation I just had with @jfirebaugh, this is going to be harder than I thought. We have been calculating data-driven styles in the worker. This is similar to the way we have always calculated layout styles but different from the way we have calculated paint styles. Unfortunately, this breaks our convention that paint styles should be changeable without going back to the worker, a convention on which transitions rely.

Solutions to this problem:

 1. Don't support transitions for data driven styles (not desirable)
 2. Update the buffer in the `draw_*` methods, potentially every frame during a transition (maybe too slow)
3. Try to encode the function and feature properties in the buffer (limits the functionality of functions and increases the complexity of our shaders)
4. Encode feature properties in the buffer and dynamically write shader code for the function (maybe not so crazy?)

What are your thoughts on how we should proceed, @ansis?

**Comment by ansis** [comment]
ok, so

summary:
- make sure we actually need transitions for data-driven properties and that we have real use cases
- make sure we can't cover use cases with existing layer-wide opacity transitions
- 2) sounds better than 3) and 4).
- new idea 5) where vertex shader reads two attributes for each property and does a simple mix

---

1)

I think we should really consider not supporting transitions for data driven styles. We could still support instant switching between different data driven values using paint classes.

I'm not sure if transitioning entire layers is important. All our examples with paint classes are contrived. Until we see if there are real uses, and what they are, we can't know how necessary transitioning is.

I think transitioning is more important for applying classes, like a hover class, to individual features. I think we might want to try to implement this first and revisit transitions for entire style layers later.

---
2)

This approach would be great because it would be very flexible and relatively simple. It would make transitions more expensive than they are now. So far all transitions have been really cheap: we calculate a value once per layer and set a uniform.

Performance could be fine, it might not. It would depend on how complex the style is and how many data driven features it has. This approach could work great for a choropleth of 50 states, but it might not for something like this: http://interaktiv.morgenpost.de/europakarte/#5/48.429/11.294/de (although it might be better to use separate layers for this map since it has only 7 colours in the choropleth).

A good quick check would be to create a complex data driven layer and time how long it takes to calculate the data driven properties. It would take at least that long to update the buffers each frame.

We could also try a similar approach except where we use workers to calculate the new buffer values.

--- 
3)

This seems pretty complex and inflexible. 2) sounds mostly better to me.

---
4)

Dynamically writing shader code is interesting, but I'm worried:
- it would create a large number of different shaders and switching shaders is relatively expensive
- compiling many shaders frequently might be too slow if we want to do it too frequently. It takes us ~45ms to setup 15 shaders.

---

**Another way:**

5)

Have two attributes for each property and a uniform for mixing them:
`a_width = mix(a_width_from, a_width_to, u_width_mix)`
One attribute would be bound to the data value in the class it's transitioning from. The other would be bound to the class it's transitioning to.

---

data driven transitions could be faked with opacity transitions:

For example, there is a data driven choropleth with population data for years 2012, 2013, 2014. It has three style layers: population_2012, population_2013, population_2014. To fade between them it uses paint classes that change opacity for the entire layer.

---

cc @kkaefer

**Comment by lucaswoj** [comment]
Thanks for your thoughts @ansis! This conversation is definitely more in the realm of #1350 now. I'll respond to your comments here and write about next steps in #1350. 

-------

 > make sure we actually need transitions for data-driven properties and that we have real use cases

I don't see the cost/reward ratio being very high for this feature in the near term. I thought the cost was much smaller when I opened this ticket :wink: 

------

 > 2) sounds better than 3) and 4).

Yeah. 2 is a good short term fix. If the performance is ok, it might be a good long term fix too.

------

 > new idea 5) where vertex shader reads two attributes for each property and does a simple mix

 > it would create a large number of different shaders and switching shaders is relatively expensive

In the context of transitions, dynamically writing shader code would be hard and inefficient. But in the context of #1350 in general, I think it is a great solution because

 - it prevents adding an `O(number of features)` step to the `draw_*` methods (except maybe binding the buffer?)
 - it provides a really clear way to add new types of functions, even functions that depend on multiple inputs
 - it provides a really clear way to tackle hover transitions (I'm not sure how we would approach transitions using the `mix(a_width_from, a_width_to, u_width_mix)` approach)
 - it emphasizes putting immutable data in the buffers and mutable data in `uniform`s

**Comment by lucaswoj** [comment]
"new idea 5)" is interesting. In some ways, it feels like hand coding the kind of code we'd be generating automatically in 4). There are pros and cons to each approach

**Comment by lucaswoj** [comment]
This was a good discussion but there's nothing currently actionable in this ticket.

**Comment by alice-chen-sfdc** [comment]
What is the status on this issue? Is transition available on data driven properties, like fill-color now? Just checking since the original discussion was in 2015. @lucaswoj @ansis

**Comment by yuletide** [comment]
@alice-chen-sfdc The latest issue tracking this feature request is here: https://github.com/mapbox/mapbox-gl-js/issues/3170 Please add comments and discussion there!

**Comment by alice-chen-sfdc** [comment]
@yuletide 👍
