### ISSUE TITLE
Improvement the label style

### ISSUE THREAD

**Issue by apachemaven** [mapbox/mapbox-gl-js#1368]
Hi:

This library is  wonderful job, and I found that the label for the point is rather simple, the text can only be reside at the left(right,top,bottom) of the feature location which is monotonic more or less:
![image](https://cloud.githubusercontent.com/assets/4485890/8609905/f4e4982a-26dd-11e5-9b8f-876c2be6e031.png)

And the google label the points like this:
![image](https://cloud.githubusercontent.com/assets/4485890/8609973/bd56e808-26de-11e5-9ded-7a03c0a59bf8.png)

Which have a nice look and feel.

So I wonder if this can be possible technologically？

**Comment by ansis** [comment]
It would be great to support this but it's a bit tricky because of some past choices we've made. I think we will implement but I don't know how soon.

The long answer with lots of technical implementation details:

The map is divided up into tiles and labels are placed completely separately for each tile. We do this so that we can render raster tiles on the server for Leaflet that can be used when a browser doesn't support webgl. When rendering a raster tile on a server it doesn't have access to information about other tiles that are nearby.

Some labels still need to cross tile boundaries. To make this work, vector tiles contain information about potential labels that are outside the tile but near it's edges. With this extra information both tiles can usually make the same placement decisions and avoid overlapping labels.

If a label can be placed at multiple sides then it's position is less predictable. This means that it is harder for neighbouring tiles to predict the same placement for the label, making collisions more likely.

There are two ways I think we could implement this:
- we could decide that it's ok for fallback raster tiles to look different than maps in webgl. This would let us use knowledge about neighbouring tile placement to avoid collisions with relying on the prediction.
- we could make it possible to place labels on different sides but have only one possible side for each label

**Comment by apachemaven** [comment]
If I understand you fully, it seems that use the same labeling policy is to avoid overlapping labels between neighboring tiles. And the fact is that tiles are rendered one by one which is to support raster tiles as you said, this is necessary. 

While I wonder if we can render the vector tiles one by one for the geometry,icons and etc but excluding the text(label), and render the labels once for the whole viewport when necessary?

If this is possible, then we do not have to care about the label overlapping between the neighboring tiles. What's more, we can control the placement not only based on the feature itself but also on the features in the whole viewport. For example, when labeling a text for a point feature, and we find there is a road at the right of the point, then we can put the text label of the point at the left of the feature.

Only my own opinion, please let me know if I miss something.

**Comment by ansis** [comment]
Yes, this is probably what we will do.

But if we do it this way, then the raster tiles will look different than the webgl map since the raster tiles don't have a whole viewport. Differences between webgl and raster fallback might be ok, but it will make styling harder since you would need to check that it looks ok in both.

**Comment by apachemaven** [comment]
In fact I am not sure when you say "differences between webgl and raster fallback". What exactly are you meaning about the raster tiles? A common tiles like this:https://c.tile.openstreetmap.org/9/279/179.png

If yes, I am not sure why we have to make them looks like the same, since the look and feel (during rendering and operation like move and zoom) of the vector tiles and raster tiles can never be the same.

And I check google map a moment ago, and I found that it render the vector tiles one by one, and both the geometry and labels are drawn at the same time just like what mapbox done now, W..K.:(

**Comment by mourner** [comment]
@ansis yeah, I think we don't need to care much about having a 100% match between server-rendered and client-side. A bigger worry for me would be the complexity and performance of a solution involving cross-tile algorithms.

**Comment by ansis** [comment]
> A common tiles like this:https://c.tile.openstreetmap.org/9/279/179.png

Yes, that's what I mean

If the labels in gl and raster tiles look very different then the map designer needs to check what it looks like in both. The designer needs to find something that looks good for both versions. It is easier for the designer if the map always looks the same.

This decision was made a couple years ago when webgl support was less common in browsers.

Now that webgl support is more common, I think it is likely that we will switch to the approach you describe @apachemaven!

**Comment by apachemaven** [comment]
That would be nice, hope for you guys make some wonderful improvement one day. :+1:

**Comment by ansis** [comment]
I don't know how soon we'll be able to get around to this. I'm moving this to a separate issue with all the other label algorithm suggestions: https://github.com/mapbox/mapbox-gl/issues/14
