### ISSUE TITLE
Raster layer (video & raster) matte option

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1395]
Proposal:

We add a layout property like `matte-transparency` that defines a specific hex color that will be transparent when rendered in a raster layer.

Reasoning is that alpha support in video formats is lacking: only WebM, and only in a few browsers - and video overlays are very hard to pull off without it.

**Comment by scothis** [comment]
Worth trying, although it could be very messy with spatial and temporal video encoding artifacts.

**Comment by DevinClark** [comment]
This is also problematic for our weather tile server at WDT. (It also serves up a country tiles because reasons)
![2015-11-13 at 2 58 pm](https://cloud.githubusercontent.com/assets/353563/11157458/1bab07e0-8a17-11e5-9188-5c808132c360.png)
This is the country tiles with the mapbox dark streets under it (though you can't tell).

https://hivecache0.wdtinc.com/swarmweb/tile/countries/2010-03-25T00:00:00/{z}/{x}/{y}.png if you would like to plug that in yourself.

I did not use the radar tiles as my example because there is another issue with 0 alpha colors being rendered. I will create a separate issue for that once I get a reduced test case together.

**Comment by tmcw** [comment]
Semi-tranparency is better.
