### ISSUE TITLE
Right-clicking on map does not fire 'click' event

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1416]
also related to https://github.com/mapbox/mapbox-gl-js/issues/1405

**Comment by mourner** [comment]
Most mapping libraries including Leaflet don't fire click on right click — only on left click. Instead, right click fires a separate `contextmenu` event (already supported in GL JS). I believe we should follow the same convention here instead of https://github.com/mapbox/mapbox-gl-js/commit/c5fc74851aaaeb96a65e22ac5c16148a83edab14. @bhousel @jfirebaugh

**Comment by misterfresh** [comment]
I wanted to get a behavior where if I left-click on the map, it adds a
marker, and if I right-click on a marker, it removes it from the map.

**Comment by mourner** [comment]
@misterfresh that's a perfect use case for separate events (click for adding marker, contextmenu for removing it).

**Comment by bhousel** [comment]
I agree that we should generally just pass the DOM events as-is to the user.  

@misterfresh, I'll back out the change in c5fc748, but you can look at that for how to implement a right (or middle) click event by using `mousedown` and `mouseup` events and keeping track of the buttons that were pressed and their coordinates.

**Comment by misterfresh** [comment]
Interesting, thanks.

2015-10-07 14:14 GMT+02:00 Bryan Housel <notifications@github.com>:
