### ISSUE TITLE
Better error message on invalid LngLat

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#1443]
When trying to set center to `[37.8, -96]`, the error is `failed to invert the matrix`. We should have a saner error because lots of people will trip up on the latlon switch over.

**Comment by ezheidtmann** [comment]
For future users who hit this error when upgrading from mapbox-gl-js v0.9.x to v0.10.0, the problem is that you have point locations written as literal pairs of `[lat, lng]`. You need to change these to `[lng, lat]`.

I had these in my `new mapboxgl.Map({ center: [ ... ] })`, which prevented my entire map from loading but also threw this error hundreds of times as I panned around.
