### ISSUE TITLE
Add "transitionend" event

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1482]
If I run a `setPaintProperty` call or something, I want to know when the values given are represented on the map. To do this, we need a transitionend event.

**Comment by tmcw** [comment]
Closing: not seeing much interest in this feature.

**Comment by unitof** [comment]
I'm interested in this feature.

My specific use case is—because I [cannot transition between data-driven styles](#3170)—I'd like to fade out a layer, `setData` on it, then fade it back in. Of course I only want to setData as soon as it's completely faded out, and using `setTimeout`s feels imprecise and risky.

**Comment by webdeb** [comment]
we would like to prevent layer-re-rendering during transitions, because we see lagging of the map if we replace features & transition the map at the same time.

Instead we would like to render new features after the transition ended
