### ISSUE TITLE
Assert preconditions in dev builds

### ISSUE THREAD

**Issue by bhousel** [mapbox/mapbox-gl-js#1543]
from [#1528](https://github.com/mapbox/mapbox-gl-js/pull/1528#issuecomment-142712762)
>  assert preconditions in every internal method and then compile for production with [unassertify](https://www.npmjs.com/package/unassertify).

**Comment by mourner** [comment]
I'm perfectly fine with assertions in critical code paths like TileCoord/LatLng, but "every internal method" is just too much IMHO.

**Comment by tmcw** [comment]
See also [invariant](https://github.com/zertosh/invariant), that does automatic space-savings in production mode and is the way React-land does this.

**Comment by jfirebaugh** [comment]
> but "every internal method" is just too much IMHO.

Why? Providing they are removed in production builds, why wouldn't you want to assert wherever there is a clear precondition? It's an easy way to catch bugs and it is a form of self-documenting code.

**Comment by jfirebaugh** [comment]
Pushed a starting point in https://github.com/mapbox/mapbox-gl-js/compare/assert, however it's blocked by https://github.com/twada/unassertify/issues/1.

**Comment by mourner** [comment]
@jfirebaugh in my opinion, it will severely damage code clarity. It's much harder to navigate and read code where obvious type checks take more lines of code than the actual implementation. Readability had been already severely harmed by incredibly verbose and repetitive JSDoc comments (which I had to accept as a necessary evil), and a bunch of asserts in every single method will only make it much worse. 

If we really want to rigidly check every single function argument, why don't we use flow or TypeScript then? I agree that asserts are a good thing and can prevent lots of errors, but putting them in every possible place is an overkill.

**Comment by jfirebaugh** [comment]
I don't think we should use this primarily for type checking, but for [preconditions](https://en.wikipedia.org/wiki/Precondition) -- parts of API contracts that cannot be statically checked.

Also, I disagree that the JSDoc harms readability. On the contrary, I've come to find that they significantly aid my understanding of the code. They also have helped me make better decisions when adding new functions, because writing an English description and explicitly listing concrete types makes me think more clearly and critically.

**Comment by tmcw** [comment]
Yeah, gotta agree with @jfirebaugh on the value of JSDoc here, though, grain of salt that I promote it pretty heavily. In all of the projects I've used JSDoc on I've been really happy with how it's improved code comprehension as well as the way I write code. Arguments about 'readability' are always a little slippery since it is entirely, completely, enormously a point of opinion. For JSDoc, the word I'd use is 'explanatory' rather than 'readable' since it connotes that there is actually additional _information_ contained in code + docs rather than bare code, as well as the 'act of explaining' that you have to do to write JSDoc-annotated code.

**Comment by tmcw** [comment]
(and for 'why not flow/typescript')

* Flow & TypeScript are compile-time, and preconditions could be runtime. There are hacks to make flow & ts annotations into runtime annotations, but that's additional magic.
* Mapbox GL JS is pretty minimal in terms of transforms - envify, brfs, glify - such that all JS is vanilla. Going for an extended subset of JS means that everything down the line must be compatible - linting, static parsing, test suites, node-side test runners. It spreads.

**Comment by mourner** [comment]
@jfirebaugh yeah, I'm probably just being a little paranoid here. Let's proceed with precondition assertions and I'll bring this up again if it ever becomes a real problem. :+1: 

@jfirebaugh @tmcw Regarding JSDoc — that's just a little rant about it's verbose/repetitive syntax, complexity and code relations model applied to JS. I don't question the usefulness of documenting code in a structured way. With this in mind, I'm really looking forward to what eventually comes out of a rough but very promising https://github.com/IvanSanchez/Leafdoc. The main ideas behind it address all my gripes with JSDoc.

@tmcw to be clear, I'm really glad we don't use Flow or TypeScript in GL JS. :smile:

**Comment by tmcw** [comment]
Is Leafdoc a joke? Just to be clear, [we have control over the entire flow of parsing and generation in documentationjs](https://github.com/documentationjs/documentation).

**Comment by mourner** [comment]
@tmcw yeah, except strictly adhering to the JSDoc syntax and relying on code parsing. 

Leafdoc is a proof of concept without a proper implementation, but it's not a joke — see [the sample Leaflet output](http://ivansanchez.github.io/Leafdoc/Leaflet-docs.html), it's fantastic. The 🍂char is certainly a joke though. :)

**Comment by tmcw** [comment]
documentationjs doesn't need to strictly adhere to JSDoc, and doesn't rely on code parsing in --polyglot mode. I would rather try to make one good thing than nih'ing again.

**Comment by mourner** [comment]
@tmcw to be clear, I always expressed strongly against generated docs in Leaflet, never touched or encouraged creation of Leafdoc, and found out about it after most of it was written. But if someone puts so much time into building something of their own, it's not necessarily "a joke" or purely because of ego. Just _maybe_, the actual reason is that existing projects don't solve his problem (output that _exactly_ matches [current Leaflet docs](http://leafletjs.com/reference.html) or makes it better), or that they don't make it obvious that it is possible to do so in a simpler way than writing something from scratch.  ¯\_(ツ)_/¯

I've been bashed by OpenLayers devs in exactly the same way when I tried to create Leaflet 5 years ago, with people calling it a joke and making other sarcastic remarks about me for doing something different, so you can imagine that I have a strong emotional backlash when seeing someone treated similarly.

Currently documentationjs readme makes it pretty clear that it is designed around JSDoc — I'd love to see an example of using it to build a completely custom syntax with a completely custom output without any JSDoc involvement in the code path, or at least have good hints how that is possible.

**Comment by tmcw** [comment]
We created documentationjs after you, me and John all agreed that we could probably build a better documentation system. The joke is that we'd want to build a new documentation system before we've even finished building our new documentation system, or that you imagine some sort of 'guiding principle' behind documentationjs - a new and flexible project - that makes you really want to start from scratch rather than improve it or help.

**Comment by mourner** [comment]
> that makes you really want to start from scratch rather than improve it or help

I never said that. Again, I'm not involved with Leafdoc development, nor that I ever encouraged it, but I find it a useful proof of concept that shows that you can autogenerate beautiful docs like [Leaflet](http://leafletjs.com/reference.html) using simple custom doc syntax, and make them even better than manually managed docs (loving the expandable inherits blocks in particular). I'll look into hacking on documentationjs to fit a case like this whenever I get the chance to work on it.
