### ISSUE TITLE
Mapzen example not rendering properly

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox-gl-js#1576]
Can't tell what's happening in this example but it looks like the polygons aren't closing properly.

https://www.mapbox.com/mapbox-gl-js/example/third-party/

![mapzen](https://cloud.githubusercontent.com/assets/134753/10210429/cc21bd24-679b-11e5-85e7-f0338ba08524.png)

**Comment by mourner** [comment]
cc @rmarianski @zerebubuth @bcamper not sure what's going on here.

**Comment by bcamper** [comment]
@mourner taking a look!

**Comment by zerebubuth** [comment]
The problem seems to be everything in the layer is being filled as if it were a polygon, although we're now also including some water lines in the water layer. One way of working around this for a simple style is if the style only applies the fill to polygons, for example:

```js
var simple = {
    "version": 8,
    "sources": {
        "osm": {
            "type": "vector",
            "tiles": ["https://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt"]
        }
    },
    "layers": [{
        "id": "background",
        "type": "background",
        "paint": {
            "background-color": "#41afa5"
	}
    }, {
        "id": "water",
        "type": "fill",
        "source": "osm",
        "source-layer": "water",
        "filter": ["==", "$type", "Polygon"],
        "paint": {
            "fill-color": "#3887be",
        }
    }]
};
```

Note that the preferred tile format extension for Mapbox Vector Tiles is now `.mvt` instead of `.mapbox`. The latter is deprecated and will probably stop being supported at some point.

**Comment by zerebubuth** [comment]
@mourner - did filtering on the item type work for you? Please let me know.

**Comment by mourner** [comment]
@zerebubuth didn't try yet but sounds like it'll work just well, cc @bhousel up for a quick fix?

**Comment by bhousel** [comment]
@mourner @zerebubuth Sure, I will try to fix this today..

**Comment by zerebubuth** [comment]
Awesome, thanks!

**Comment by bhousel** [comment]
Fixed the example and applied to the `mb-pages` branch, so it's live now..
