### ISSUE TITLE
vector tiles urls aren't normalized

### ISSUE THREAD

**Issue by ycabon** [mapbox/mapbox-gl-js#1659]
tile urls created in the vector tile source aren't normalized where raster tiles' ones:

https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/raster_tile_source.js#L45
https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/vector_tile_source.js#L53

shouldn't they?

**Comment by jfirebaugh** [comment]
`normalizeURL` is a bit of a misnomer -- what this method [actually does](https://github.com/mapbox/mapbox-gl-js/blob/17247006c818626f779ffe616062e3a80dc25c7d/js/util/mapbox.js#L68-L71) is insert `@2x` in the URL if it's a Mapbox tile source and the pixel ratio is >= 2, in order to load retina raster tiles. There's no such thing as "retina vector tiles", so no need to "normalize" them.

**Comment by ycabon** [comment]
Ah! I feel stupid :) So what I was really look to do is to insert a token during the normalization, I didn't realize the `normalizeTileUrl` wasn't doing that.
