### ISSUE TITLE
featuresIn API doc syntax error

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mapbox-gl-js#1662]
https://www.mapbox.com/mapbox-gl-js/api/#map/featuresin

![image](https://cloud.githubusercontent.com/assets/2180540/10890070/d5e0e948-8163-11e5-9805-3756d8b5f191.png)

The code block has an unclosed bracket

**Comment by tmcw** [comment]
In the code: https://github.com/mapbox/mapbox-gl-js/blob/e6daa14c186ccf6d1c6d4ee6f9436595ea56cf93/js/ui/map.js#L339

**Comment by bhousel** [comment]
fixed in 728403e

This is not related to the example, but I don't know why documentation.js is now naming it `featuresInCallback`:

<img width="879" alt="screenshot 2015-11-11 16 12 25" src="https://cloud.githubusercontent.com/assets/38784/11103268/6597d6fa-888f-11e5-85d6-eb22c5853b81.png">

Related to:  https://github.com/documentationjs/documentation/issues/136 ?

**Comment by jfirebaugh** [comment]
@bhousel We need to split up the comment before `featuresAt` (and `featuresIn`) into two comments, one for the function and one for the callback type. Right now documentation is (correctly) parsing the whole thing as one big `@callback` comment. Please ticket or fix. Thanks!

**Comment by bhousel** [comment]
> need to split up the comment before featuresAt (and featuresIn) into two comments, one for the function and one for the callback type.

Thanks!  Docs look good now..
