### ISSUE TITLE
setCenter / setZoom don't work the first time if map initialized without a center/zoom

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1690]
I was building a little ui for switching between styles and ran into a problem. I wanted a function to apply every time the user paged to a new style, and I wanted the same code to work for the very first style and all subseqent style changes. Function looked sort of like this:

``` js
function setStyle() {
    mapboxgl.accessToken = next.token;
    map.setStyle(next.style);
    map.setCenter(next.center);
    map.setZoom(next.zoom - .5);
    map.flyTo({
        speed: .05,
        zoom: next.zoom
    });
};
```

And I was executing it like this, in an event handler:

``` js
if (!map) {
    map = new mapboxgl.Map({
        container: 'js-map'
    });
    map.addControl(new mapboxgl.Navigation({ position: 'top-left' }));
    setStyle();
} else {
    setStyle();
}
```

With this code, the map center would end up at: `{ lng: -117.84767918833975, lat: -1.1368683772161603e-13}` and zoom would be `12.134854352584124` when the code first ran. I ended up just adding a center and zoom property when initializing the map to get around the problem, but should that be necessary? Seems like a bug, docs don't say anywhere that zoom and center are required options.

I tried putting the setStyle() inside a map.on('load', ...) in the first part of the if statement, but that didn't have any effect.

**Comment by samanpwbb** [comment]
It appears that even if I set the center, the first setZoom and setCenter fail to work correctly. I needed to set the center to the map's actual center we initializing the map.

**Comment by jfirebaugh** [comment]
Can you provide a link to the full code?

**Comment by samanpwbb** [comment]
stale, plus I bet I was doing something wrong.

**Comment by apolishch** [comment]
For what its worth, I just ran into this. Still investigating as setting center to initial map center just seems like an awful awful hack

**Comment by mourner** [comment]
@apolishch a minimal JSFiddle test case would be very helpful.

**Comment by sheley1998** [comment]
Try putting setZoom before setCenter. There seems to be a bug?

**Comment by karantza** [comment]
I just encountered this bug too when attempting to initialize my viewport, and calling setCenter after setZoom rather than before fixed it. (I was actually using the `diffStyles` function to generate these commands, and it generated them in the bad order!)

I dug into it a little bit to see if I could find the bug. I'm fairly sure it has to do with the call to [_constrain](https://github.com/mapbox/mapbox-gl-js/blob/855b850e62196c46f0987ab73600fffddc3e22bc/src/geo/transform.js#L498) when setting `center` that limits its range. Since we haven't set a zoom properly yet, I think some of the scaling going on in there is incorrect, limiting the latitude down to something very small. Didn't have the time to figure out how exactly but hopefully this can point someone in the right direction!

**Comment by AliFlux** [comment]
Faced the same issue, @jfirebaugh provided an explanation at #2864 

```
When you call setCenter([0, 50]), the map is at zoom level 0, at which point the range of possible center latitudes is constrained by the height of the viewport. If you switch the order of calls such that the zoom is set to 5 first, it will work as you expect.
```

**Comment by nzayatz14** [comment]
> Faced the same issue, @jfirebaugh provided an explanation at #2864
> 
> > When you call setCenter([0, 50]), the map is at zoom level 0, at which point the range of possible center latitudes is constrained by the height of the viewport. If you switch the order of calls such that the zoom is set to 5 first, it will work as you expect.

Incredible
