### ISSUE TITLE
Unpin documentation.js

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1692]
We had to pin `documentation` at `3.0.0` (as opposed to `^3.0.0`) due to an upstream bug. As soon as the upstream fix https://github.com/documentationjs/documentation/pull/241 merges, we should unpin `documentation`.

**Comment by tmcw** [comment]
The fix is merged, shall we start switching to 4.x?

**Comment by jfirebaugh** [comment]
I started this a while back ([WIP here](https://github.com/mapbox/mapbox-gl-js/compare/documentationjs-4.0)). It needs an upstream change in documentation-theme-default: an addition of a `templateDirectory` option, so that you can use the code parts of documentation-theme-default but supply your own templates.
