### ISSUE TITLE
Use webp tiles instead of jpeg or png if browser support is detected

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1725]
Context:

* we used to serve png tiles by default because they support transparency, but they were too big, so
* we switched to jpeg tiles by default, but their lack of transparency support means the black matte is a problem for uploaded tiffs that aren't global
* webp is both efficient like jpeg and supports alpha like png
* webp has 66% browser support

Idea:

* we should expose available extensions in tilejson in order of preference
* mapbox-gl-js should detect webp support and use webp tiles if the browser supports then and the server advertises them

**Comment by jfirebaugh** [comment]
For static GL tiles, we're planning on solving this by HTTP content negotiation -- the tile template has no extension, and if a request `Accept` header indicates webp support, the response will be webp. If we can, it'd be better to rely on HTTP rather than extending TileJSON.

**Comment by dnomadb** [comment]
Right now, the TileJSON itself for any new (last year? more?) uploads is `webp`:
```
format: "webp"
```
In mapbox-maps, if no image format is specifically requested, it defaults to `jpg`: https://github.com/mapbox/mapbox-maps/blob/2831f9a6f760b5892203b9a17b446263b3c23532/lib/tilejson-util.js#L47

**Comment by sharkinsspatial** [comment]
Is there a technique to have my Mapbox tilesets' tilejson advertise .png extensions rather than .jpg in the tiles property?  I realize that I can force .png use with embeded tilejson properties directly as described [here](https://github.com/mapbox/mapbox-gl-js/issues/1616) but then I lose the retina checking and webp support provided by [normalizeTileUrl](https://github.com/mapbox/mapbox-gl-js/blob/e752a88be1ad24545472a2ad93283741724e3962/js/util/mapbox.js#L68).  Unfortunately I need to support alpha transparency on IE and Edge where there is no current webp [support](http://caniuse.com/#feat=webp).

**Comment by jfirebaugh** [comment]
cc @yhahn -- I was under the impression that Mapbox TileJSON always does advertise `.png` or `.jpg`, never `.webp`. That's why #1756 is implemented as "replace the extension with webp if the browser supports it".

**Comment by sharkinsspatial** [comment]
I may be misusing the term 'advertise' in this context (I'm unsure what the correct term would be).  I can make requests for `.png` tiles from an endpoint, but the the urls in the tiles property of the TileJSON for an uploaded `.tiff` always have a `.jpg` extension.  An [example](https://a.tiles.mapbox.com/v4/mulloverit.iu2tke29.json?access_token=pk.eyJ1IjoibXVsbG92ZXJpdCIsImEiOiIzVzZyY05JIn0.QxNcdiemvp44I0vi0ppBuw) from an uploaded `.tiff` from an older Mapbox blog post.

In this case [normalizeTileUrl](https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/mapbox.js#L68) will use `.jpg` when there is no `.webp` support.  It seems like the two approaches to circumvent this are 

1. Modify the upload so that the tiles property in the resulting TileJSON uses the `.png` extension.

2. Extend [RasterTileSource](https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/raster_tile_source.js) to include an alpha channel flag so that it can fall back gracefully to `.png` when there is no `.webp` support.

I am unsure if 1 is possible, and I'm not sure if 2 would be the right approach or not.
