### ISSUE TITLE
Change unit of camera pitch to be degrees

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#1732]
Same as https://github.com/mapbox/mapbox-gl-native/issues/3056:

![out](https://cloud.githubusercontent.com/assets/52399/11220415/3e8fa026-8d60-11e5-8a1d-fd195a472c63.gif)

**Comment by ansis** [comment]
> Pitch currently depends on the viewport height; we claim that it's an angle, but it's really not:

It is an angle. But the angle only matches the pitch angle along the middle of the viewport. The angle is the same in both screenshots at the middle of the viewport. The angle changes as you approach the top/bottom of the viewport in both screenshots but it changes more quickly in the shorter map.

The change shown is caused by the altitude of the camera being linked with the height of the map. The fov is a fixed angle vertically. If the viewport is taller we need to cover more area with that same fov so the camera moves further away. That means that the maximum stretching/squishing is the same in both maps but that max stretching/squishing occurs in different geographical places.

A fixed altitude and changing fov would have other problems. An altitude that produces a reasonable fov at [small](https://user-images.githubusercontent.com/1421652/101541451-7f9bc480-396f-11eb-9a8e-dcb7bf214f92.png) sizes would be extreme at [large](https://user-images.githubusercontent.com/1421652/101541437-7a3e7a00-396f-11eb-8fba-fe3763366e5a.png) sizes.

An orthographic projection would avoid this but isn't what we want.

I think a fixed fov is what we want here. Reopen if this is something we should revisit
