### ISSUE TITLE
Point geometry is unstable at high zoom levels

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#1733]
I have a point which begins to jitter as the zoom level get's higher. This point was processed from geojson via the Mapbox Uploads API. The instability starts around zoom 17 and get's gnarly around 20. Running on 0.10.4

![points at high zoom](https://cloud.githubusercontent.com/assets/302992/11230030/fa1f744e-8d4f-11e5-984b-090cec1d9b22.gif)

**Comment by incanus** [comment]
We've seen this before in native and usually is the result of using something of `float` precision instead of `double` precision. Not sure how that translates to JS, but an implicit cast might be going awry somewhere.

**Comment by scothis** [comment]
"cast" that's cute. All numbers in JS are floating point.

**Comment by incanus** [comment]
Sorry, I mean like treating a string value as a number or something like that. You know, the things JS devs do :smile:

**Comment by incanus** [comment]
A more concrete example: maybe mixing up `Buffer.AttributeType.UNSIGNED_BYTE`, `Buffer.AttributeType.SHORT`, or other types put into OpenGL buffers.

**Comment by incanus** [comment]
Similarly it could be related to `mediump` or `highp` precision in GLSL.

**Comment by indus** [comment]
I had a quite similar issue with another geo-visualisation lib (it happend when the map was rotated and zoomed below level 16-17).  I fixed it by changing the order in which matrix transforms get applied (translation <-> rotation)

**Comment by mourner** [comment]
> I fixed it by changing the order in which matrix transforms get applied (translation <-> rotation)

Could you submit a pull request for that?

**Comment by mourner** [comment]
@scothis also wondering if this goes away if you pass `maxzoom: 20` (or other high value) in the source options.

**Comment by indus** [comment]
@mourner I´m sorry, but as I said that worked for me in another map-library with seamless zooming (using Canvas2d). So I´m not sure if it would work and is feasable for mapbox-gl. I haven´t looked into the source of mapbox-gl a lot - so this was meant more as a hint.

You can have a look at the code I`m talking about here: https://github.com/indus/VAYU/blob/master/src/LAYR.TILE.ts#L46-L93. Its a loop to draw tiles in a pyramid shaped way (I know that we are talking about point features here; but I´m pretty shure it is the same). In a prior version I was having the same issue because I first rotated arround a global origin and translated afterwards. I think the problem is that the the global orgin is "too far away" from the position where you want to place something and because the resolution of a JS number is limited you can´t define every coordinate exacly as a directed ray from this global origin (or in other words: cosine and sine are small - the distance between origin and targtet is big - multiplying both gives a noticeable error because of cut off decimal places).
As you can see in the code provided I now translate first (to a coordinate that acts as a "local origin"; the place where i want to draw) and rotate afterwards.
I´m not sure if that is really the same for mapbox-gl and this issue- but the result looks identical (even the problemetic level of arround zoomlevel 17 and beyond is the same).

I´m not sure if I have the skills and the time to file a PR. I will give it a try but this may take some time.

**Comment by ansis** [comment]
@scothis can you still reproduce this?

**Comment by lucaswoj** [comment]
Potentially related to #2279

**Comment by scothis** [comment]
@ansis :+1:
