### ISSUE TITLE
Can't view points over raster base layer

### ISSUE THREAD

**Issue by rishabhjain30** [mapbox/mapbox-gl-js#1796]
I added a raster layer as custom style and want to visualize geojson points above that.

http://jsfiddle.net/rqt30301/

**Comment by jfirebaugh** [comment]
You need to add a ["glyphs"](https://www.mapbox.com/mapbox-gl-style-spec/#root-glyphs) and ["sprite"](https://www.mapbox.com/mapbox-gl-style-spec/#root-sprite) properties to the style, so that the marker text has a source for font and icon data.

http://jsfiddle.net/01qa6ebc/

#1632 tracks adding validation that will help diagnose these types of issues.
