### ISSUE TITLE
Rotated rasters don't align

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#1818]
When rotating map with raster layer, tiles don't always align. That leads to gap effects and torn rasters.
It looks like this:

![torn raster1]
(https://www.dropbox.com/s/es253kwee1truu9/IMG_0022.PNG?dl=1)

![torn raster2]
(https://www.dropbox.com/s/jv5m95dxokfsk0n/IMG_0021.PNG?dl=1)

![torn raster3]
(https://www.dropbox.com/s/q2dimjahiv0375s/IMG_0020.PNG?dl=1)

**Comment by jfirebaugh** [comment]
Looks like this is on an iPad, correct? Could be a the same underlying issue as #1285.

**Comment by nextstopsun** [comment]
@jfirebaugh ipad, yep

**Comment by lucaswoj** [comment]
This bug

 - affects vectors as well as rasters (it even affects the debug overlay) (it is more visible on rasters because the tiles are smaller)
 - affects iOS Safari but no desktop browsers (haven't tried Android yet)
 - can be consistently reproduced using this test page https://jsfiddle.net/srxhh6gr/6/
 - occurs between 80 and 90 degrees bearing (and -80 and -90 degrees)

**Comment by lucaswoj** [comment]
![image](https://cloud.githubusercontent.com/assets/281306/11885376/3953a396-a4d5-11e5-811c-b8a58050e1c9.png)

Here's a :fireworks: fun :tada: graph of the % difference between entires in the `posMatrix` on Desktop Safari vs iOS safari at various bearings at zoom level 10.5.

In particular, `posMatrix[13]` (and to a lesser extent `posMatrix[12]`) show, quantitatively, the difference we can observe qualitatively at https://jsfiddle.net/srxhh6gr/6.

**Comment by lucaswoj** [comment]
A similar graph for the `projMatrix` does not show the % error as a function of the bearing, like the graph of the `posMatrix` does; however it does show some big discrepancies (nearly 100% difference)

![image](https://cloud.githubusercontent.com/assets/281306/11885803/c8baa12c-a4d7-11e5-8adb-7c43d47c8bfc.png)

**Comment by lucaswoj** [comment]
Unfortunately, the nice fan pattern I measured above was due to experimental error. The actual graph for the `posMatrix` looks like this:

![image](https://cloud.githubusercontent.com/assets/281306/11886709/0226b6b2-a4e2-11e5-836d-682cca712561.png)

The +- 50% sections must be due to some screen size / pixel ratio settings that I haven't been able to control for. 

There is still a seemingly relevant fanning pattern in `posMatrix[0]` and `posMatrix[5]`

# Next Steps

 - [ ] try to control experiment better to eliminate +- 50% sections
 - [ ] hunt down the source of the fanning by stepping through matrix calculations on both platforms simultaneously :whale2:

**Comment by lucaswoj** [comment]
After better controlling for screen size and pixel ratio, the graph gets more interesting and more relevant

![image](https://cloud.githubusercontent.com/assets/281306/11887037/1466de8a-a4e5-11e5-894e-e4b27c01e063.png)
![image](https://cloud.githubusercontent.com/assets/281306/11887040/1700c26e-a4e5-11e5-89e1-47f338295aff.png)

The error _does_ seem to originate in the `projMatrix` and seems to be on a magnitude that makes me suspect floating point error is to blame.

**Comment by lucaswoj** [comment]
I've further refined my experimental technique to obtain the below graph of the `projMatrix` at 87 degrees (no distortion) and 88 degrees (significant distortion) on desktop vs mobile. I believe this graph shows a clear error in elements 0, 5, 12, and 13 in the `projMatrix` when the distortion is observed. 

![image](https://cloud.githubusercontent.com/assets/281306/11903538/cc4a368a-a56e-11e5-98c7-0a7cef59446a.png)

Next, I will step through the code on both platforms to trace the source of the discrepancy.

**Comment by lucaswoj** [comment]
I'm starting to think the projMatrix differences are a red herring and the solution has more to do with calibrating our use of `mediump` and `highp` precision in WebGL for different devices.

**Comment by lucaswoj** [comment]
ref https://github.com/mapbox/mapbox-gl-js/issues/750
