### ISSUE TITLE
Add text-wrap-width option

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#1827]
I miss text-wrap-width, text-wrap-before and text-wrap-character options from CartoCSS so much when trying to style long labels in Mapbox Studio. I guess that shouldn't be very hard to implement:)

**Comment by jfirebaugh** [comment]
Have you tried using the [`text-max-width`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-max-width) property?

**Comment by nextstopsun** [comment]
Yeah, setting it a bit below needed value did the trick. How low should I normally set it to have guaranteed wrapping?

**Comment by ansis** [comment]
The units are `text-max-width` are in em, so you if you have text with a 12pt font size and a 4em max-width then the maximum width of the text will be 48pt.

> How low should I normally set it to have guaranteed wrapping?

If you want every word to be on a new line set it to something really small like `0.1`. Otherwise just experiment and find the width you want.
