### ISSUE TITLE
Fix uncontrollable drift while panning the map

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-js#1889]
Not figured out how to reliably reproduce but seems to happen on random when trying to pan in areas  with sluggish FPS.

Releasing the mouse after panning the map causes the map to continue panning with high speed taking you on an unplanned map voyage. It can get annoying at times when the map just refuses to stay put where you want it to.

Happens to me in Safari, cannot reproduce on Chrome.

**Comment by kristfal** [comment]
I'm working on improving the touch handlers for issue #1844 (PR incoming) and suspect 2) in that issue also affects desktop in slow environments. I don't have a suitable test environment on desktop, but hopefully fixing #1844 will fix this as well.

**Comment by dpieri** [comment]
This is still happening for me intermittently. I can't give any steps to reproduce as it doesn't happen all the time.

Our map is fairly heavy, so maybe if you browse around at hivemapper.com on Safari long enough you will encounter this.

FWIW using Safari on a 4K monitor (bonus points if you use a scaled resolution instead of the monitor default) exposes a lot of rendering issues.

**Comment by lucaswoj** [comment]
I haven't seen this happen in a long time.
