### ISSUE TITLE
Avoiding selection of content in Chrome when shift-zooming

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#1907]
This may not be quite related to mapbox-gl-js, but I hope I'd get some pointers from all the clever people around here.

I have a page with a map with panels next to it, and when the focus of the page is on any of these panels while I perform a shift-bbox-zoom the content on these panels is selected. Obviously one ugly hack would be to start applying <code>user-select: none</code> to some of these areas, but there are actually some areas I do want to be selectable, just not as a result of shift-zoom.

This appears to be a problem in Chrome, but not Safari or Firefox (tested in OSX).

You can examine this behaviour on the codepen below. Click somewhere in the text on the panel and then perform a shift-zoom.

http://codepen.io/anon/pen/adWvOO

**Comment by bhousel** [comment]
We should probably prevent default handling of the events we capture in `interaction.js` and the other handlers.  I can't think of any good reason _not_ to.

But as a workaround until we do that, you can add this to your codepen:

```javascript
map.on('mousedown', function(e) {
  e.originalEvent.preventDefault(true);
});
```

**Comment by jfirebaugh** [comment]
The hard-won knowledge from d3 and Leaflet is that preventDefault shouldn't be used on mousedown because it prevents desired browser-native behaviors. For example, the default behavior of mousedown switches focus out of a focused input textarea. Likewise [preventDefault on mousedown disallows the capture of mouseup outside of an iframe](http://bl.ocks.org/mbostock/109620145f090cda1a7d).

Instead we'll need to [prevent text selection in other ways](https://github.com/Leaflet/Leaflet/blob/161172bbb92e60d2d7fc21173da7e58fc725dd2b/src/dom/DomUtil.js#L192-L217).

**Comment by jfirebaugh** [comment]
In fact [gl-js already has such code](https://github.com/mapbox/mapbox-gl-js/blob/75aab6d39fa4d221db3c2b2e82df39f816287c5e/js/util/browser/dom.js#L22-L34).

**Comment by averas** [comment]
@jfirebaugh Which only needs to be applied to shift-zooming as well?

**Comment by bhousel** [comment]
> Which only needs to be applied to shift-zooming as well?

We have a `DOM.disableDrag();` call in `box_zoom`, but it seems to happen on mousemove, which is too late.  The initial shift-mousedown is what extends the text selection in the sidebar.
