### ISSUE TITLE
Use font-provided metadata to determine glyph baseline position

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#191]
@kkaefer, is this something harfbuzz can produce?

Otherwise, the median bottom edge would probably be a good approximation.

**Comment by ansis** [comment]
re-opening because this is still hardcoded in -js: https://github.com/mapbox/mapbox-gl-js/blob/ec62ab898ace8b66f43b5fb586732e6328278604/js/symbol/shaping.js#L33

**Comment by ansis** [comment]
@mikemorris https://github.com/mapbox/node-fontnik/pull/50/files got merged into master but master doesn't have the ascender version?

**Comment by mikemorris** [comment]
@ansis Looks like we never updated the PBF spec in https://github.com/mapbox/node-fontnik/blob/master/proto/glyphs.proto, I started work on this in https://github.com/mapbox/node-fontnik/pull/97 but it never got merged.

**Comment by mikemorris** [comment]
I think there's more detail on our current implementation in https://github.com/mapbox/mapbox-gl-js/issues/154

**Comment by lbud** [comment]
Inadvertently closed due to some 🌳 history magic — reopening.

**Comment by lucaswoj** [comment]
Closing as stale. I haven't seen this become a practical concern yet.

**Comment by kkaefer** [comment]
Assuming that this will be subsumed by @ChrisLoer's push on fonts + harfbuzz.

**Comment by lucaswoj** [comment]
Ah! Good point. We can keep this open to track this aspect of our text shaping work.

**Comment by nickidlugash** [comment]
@ChrisLoer @ansis @kkaefer Is this something we can move on before switching to Harfbuzz? What would it require to accomplish this? It continues to be a visible issue:

- Text along lines are often not vertically centered (quite noticeable if the line geometry is also visible, like with road labels along roads).
- Labels using multiple fonts (due to font fallbacks for different unicode ranges) can have vertically misaligned glyphs.
- Vertically-oriented text along lines using multiple fonts can have awkward spacing or even overlap between glyphs.

Please let me know if there's anything I can do to help resolve this 🙏

**Comment by ChrisLoer** [comment]
@nickidlugash I think this is something we can work on without Harfbuzz. It does unfortunately require server-side changes -- i.e. we need to get node-fontnik to send the metadata down to the client. Hopefully we can add that to the glyph PBF is a backward compatible way, and just use the baseline if it's there, otherwise fall back to our hardwired value.

**Comment by tristen** [comment]
Unearthing this issue as deriving this from a fonts metadata instead of using a fixed value would greatly improve labels using mixed font families.

<img width="136" alt="Screen Shot 2019-07-10 at 9 44 44 AM" src="https://user-images.githubusercontent.com/61150/60974130-86945280-a2f7-11e9-822d-f91cf9b9fdf7.png">

> we need to get node-fontnik to send the metadata down to the client. 

@springmeyer wanted to put this on your radar. The only related issue I saw in that project was https://github.com/mapbox/node-fontnik/issues/51

**Comment by mikemorris** [comment]
@tristen There's an abandoned PR in which I started most of the work for this at https://github.com/mapbox/node-fontnik/pull/97

**Comment by springmeyer** [comment]
👋 @tristen - If someone from @mapbox/map-design-team wants to tackle this I'd be happy to help get them up to speed on node-fontnik development.  /cc @jseppi @agentpu1011 @ian29 @brsbl @philogb

**Comment by tristen** [comment]
Re-earthing @mikemorris's initial work in a new pr https://github.com/mapbox/node-fontnik/pull/160. That should address the downstream work to enable this.
