### ISSUE TITLE
Refactor to inline StyleDeclarationSet into StyleLayer

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1963]
`StyleDeclarationSet` creates a tangle of magic getters / setters without adding much value. Our code would be more clear and more performant if we handed over its responsibilities to `StyleLayer` directly.

**Comment by jfirebaugh** [comment]
I'm pretty happy with how these classes turned out in gl-native:

* https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/layout_property.hpp
* https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/paint_property.hpp

In particular, having calculations happen property-by-property, rather than as a set, made things much easier to understand.

See a layer implementation for how they are used:

* https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layer/line_layer.hpp
* https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layer/line_layer.cpp

Of course in JS you can avoid the repetitive boilerplate by metaprogramming against the style spec.
