### ISSUE TITLE
how can I generate static images from GL styles?

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#1984]
The way to go on printing high dpi maps seems to be to fall back to Mapbox Classic, but since gl styles and carto styles aren't easily interchangeable it causes problems when one wants to have highly dynamic map styles to print from.

I've evaluated some alternatives and would love some feedback.

### Rendering in the browser

I evaluated this track by creating a copy of my map in a hidden dom-element on my page. This element, although hidden, had high width/height settings to increase the resolution. Once the map is rendered in this hidden element I simply copy the canvas content and use that for further processing and downloading. This did in fact work quite well, but I ran into some caveats... 

1) Chrome (or mapbox gl js in Chrome) had problems when the resolution was higher than 2048x2048. My map wasn't centered, and I noticed when I unhid my element that the coordinate system was impacted in some way because zooming was skewed.

2) The canvas result from Chrome was of noticeable less quality than Firefox (this was when I really started to think this may be a bad method after all).

3) I'm not sure all computers and browsers and  will be able to pull up a 4961*3508 webgl canvas without any issues. This will perhaps work bad on mobile devices.

### Rendering in mapbox gl js - server side

Still wanting to reuse my styles I realised that the mapbox gl js test suite makes heavy use of headless rendering using gl in node. I got this working as well, to the extent that I could make a server call and get a high dpi map back to the client. There were some caveats here as well though. On lower resolutions this was quite fast, even when I ran it on a virtual machine without a GPU and with emulated gl. However when I did some testing with resolutions upp to 4096*2048 it would take over a minute to render the result on my laptop, with a GL compatible GPU. Another thing I noticed was that I started to see odd artefacts on my maps at these resolutions, but that may just have been me doing something wrong.

### Falling back to server side rendering using mapnik

This will be my last resort if none of the above methods is possible to get to a robust state. It will, however, as you understand, mean a lot of effort in generating mapnik styles from my gl styles... 

Any comments on this? Where is mapbox heading on this topic in general?

**Comment by jfirebaugh** [comment]
Can I reframe the question as "how can I generate static images from GL styles?" Printing is one possible use case but there are others.

We're going to be releasing a web API for this for Mapbox-hosted styles. It's implemented using the [node bindings for mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/node).

**Comment by averas** [comment]
@jfirebaugh Very interesting! I'll go ahead and try a fourth alternative then.. :-)

**Comment by ryanbaumann** [comment]
I am very interested in this functionality.  @jfirebaugh , what's the timeline on the Mapbox-Hosted style static image generation for Mapbox GL?

Currently, I've implemented "client-side" hidden-DOM static image generation from Mapbox GL layers.  I feel that the performance is acceptable for most browsers and those on decent hardware at a resolution of 350DPI @ 8''x10'' (2800x3500 pixels).  One thing I had to do to make this work well was to add a set_timeout() function after creating the hidden-DOM map.  My code repository is [HERE] (https://github.com/ryanbaumann/athletedataviz/blob/master/static/js/image_gl_canvas.js)

FYI - I based my implementation of client-side static images off print-maps, courtesy of [Matthew Petroff].  (https://mpetroff.net/2015/02/print-maps/)

However in order to provide the best user, experience, rendering the mapbox-gl-js static image on the server-side would be ideal.  I'll have to give this a go.

**Comment by primozs** [comment]
Hello @averas. How this works "Rendering in mapbox gl js - server side" where could I check this out?
Cheers

**Comment by averas** [comment]
@primozs Rather than using Mapbox GL JS server side I suggest you head down the path using Mapbox GL Native. If you want to have it written in JS you can use the node bindings provided by mapbox; this is the option I personally settled on, and it works well. I haven't open sourced my implementation but you can probably draw inspiration from other implementations such as https://github.com/klokantech/tileserver-gl

**Comment by primozs** [comment]
@averas Thank you for the info!
