### ISSUE TITLE
Optimize SymbolInstance memory usage

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2049]
It looks like around 2/3 of all the memory retained in workers is related to SymbolInstance.

Compare by adding `bucket.symbolInstances = null` here: https://github.com/mapbox/mapbox-gl-js/blob/e745190838edf673151bc5f75869a0b0bb9c6fe8/js/source/worker_tile.js#L174
- check if SymbolInstance is retaining anything it shouldn't
- maybe use a Buffer to store SymbolQuads. All we do with them is add them to buffers so we could store them in a buffer and copy later on.
- maybe create SymbolQuads lazily. This would involve retaining the geometry, shapedText, shapedIcon so it might actually be worse. This could speed up initial tile loads though.

**Comment by jfirebaugh** [comment]
@ansis @ChrisLoer Is this still relevant?

**Comment by ChrisLoer** [comment]
I'd have to check to see what's actually happening, but I think this might be both still relevant and easier to address. I think right now `SymbolBucket#serialize` is doing a copy of the SymbolInstances, since they're not in TypedArray format. And once layout is done, there's no longer any reason for us to hold onto the SymbolInstances at all in the background.

**Comment by ChrisLoer** [comment]
I looked closer, and I think @jfirebaugh fixed this in https://github.com/mapbox/mapbox-gl-js/commit/46b8566c0a7c216e9cef0d28d613571fae63a5a6#diff-2a5c03a2605a818d6f2d14697ce30e60 by making it so that `WorkerTile` no longer holds onto symbol buckets after `parse` returns.
