### ISSUE TITLE
Road clipping

### ISSUE THREAD

**Issue by hermansje** [mapbox/mapbox-gl-js#2061]
Using Mapzen vector tiles, roads are clipped at tile edges.
For example, here: https://mapzen.github.io/mapboxgl-vector-tiles/ I could see this:
![image](https://cloud.githubusercontent.com/assets/3393736/12829278/7b809b4a-cb89-11e5-8794-61ec6d719f5b.png)
Is this a render or a data problem, or something that can be solved by adjusting the style object?

**Comment by ansis** [comment]
We currently clip lines to tile edges at render time. To render seamless lines you need to have part of the line in both tiles. We're thinking about changing the way we do clipping, but for now you'll need tiles with data that goes a bit past the tile edges. When creating the vector tiles the data needs to be clipped a bit before/past tile edges instead of right on the edge. Unfortunately this can't be solved by adjusting the style object.

**Comment by hermansje** [comment]
I don't know much about WebGL, but would it be possible to (temporarily) solve this by changing the way line-endings are drawn at tile borders?

**Comment by ansis** [comment]
We're thinking about doing that but it will involve a bunch of bigger changes so I'm not sure how soon it will happen.

**Comment by hermansje** [comment]
OK, thank you for explaining, and for the great library!
