### ISSUE TITLE
Sometimes clipped featuresAt response?

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#2125]
I'm noticing some weird behaviour collecting a large number of points at once by setting a high radius on map.featuresAt:

![features-at-capture](https://cloud.githubusercontent.com/assets/61150/13051729/de1e8518-d3c8-11e5-9de0-083068e4af42.gif)

The collected features are sometimes clipped sometimes not.

- You can replicate this from https://www.mapbox.com/analysis-demos/philly-properties/#?center=-75.17410172731203,39.93499240883074&radius=116&zoom=15.21

- Code for capture is here: https://github.com/mapbox/analysis-demos/blob/2c8e4f1c7b25b7427419158e36d48d7b09446e01/philly-properties/index.js#L332-L350

**Comment by jfirebaugh** [comment]
This is expected behavior: the way `featuresAt` works is it determines which tile the point is in, then queries features within that tile. The `radius` option is a way of fudging the rendered representation of features before we have #316. It's not intended to make `featuresAt` a general purpose circular query. If you want to find features within a circle, you'll need to use `featuresIn` and post-filtering.
