### ISSUE TITLE
consider a larger parsed tile cache size

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2137]
The default parsed tile cache size is 20: https://github.com/mapbox/mapbox-gl-js/blob/6122e19a92f85c71579fc446271451cbe72a5dbb/js/source/source.js#L27

Can we increase this without using way too much memory?
Can we reduce the memory footprint of a parsed tile so that we can store more of them?

**Comment by averas** [comment]
I've been thinking about this too. Not so much on the implementation aspects you mention, but more based on the observations I've made when scrolling and zooming around on my own maps. It becomes more and more evident when one starts using multiple vector tile sources simultaneously that UX is impacted by the fact that tiles aren't loaded/parsed/rendered fast enough to avoid an "incremental" rendering experience.. Often, once the tiles are loaded, rendering is performant, which is why I get the impression that it is tile loading/parsing related. 

It's quite obvious that tiles still have to be loaded, parsed and rendered on demand - that's the whole idea with slippy maps, but as you open up for with this issue, there might be various kinds of configurable options that could increase the user experience depending on the situation, such as:

1) Increased tile cache (like you described)
2) Tile pre-loading (either zoom levels or viewport adjacent) - (http://openlayers.org/en/v3.13.1/examples/preload.html)
3) Be smart about sources so that the rendering engine can determine if it can start rendering even if not all tile sources are loaded yet (perhaps this is already being done?)

I would be nice if this discussion included the use case of using third party vector tiles on top of Mapbox services. I.e., are the answers different to your questions when using three vector tile sources instead of one? Is it just a function of how much data the tiles contain in total, not the amount of tile sources, etc.

**Comment by ansis** [comment]
@averas good points and questions. the fix for https://github.com/mapbox/mapbox-gl-js/issues/2139 should help a lot too
