### ISSUE TITLE
clusters and map.featuresAt

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/mapbox-gl-js#2143]
Currently hidden points inside a cluster bubble are still getting fired.
```
map.featuresAt(e.point, {layer: 'markers', radius: 30, includeGeometry: true}, function (err, features) {
   ...   
});
```
I believe it makes more sense to only fire them when points are not clustered.

![image](https://cloud.githubusercontent.com/assets/863731/13133662/a5995754-d5fd-11e5-8579-de59ebc64b11.png)

feature request to see if a point is in a cluster bubble so that you can return null

**Comment by ansis** [comment]
> Currently hidden points inside a cluster bubble are still getting fired.

Can you try to rephrase this or provide an example? I'm not sure that I understand.

Both clustered and non-clustered features are returned. If a point is part of a cluster it should not be returned separately. All points that are clusters have the `"cluster": true` property.

**Comment by gertcuykens** [comment]
example http://gps.nyimbo.nl/ 
please don't quote the link so i can remove it later

zoom out until you see

![image](https://cloud.githubusercontent.com/assets/863731/14006397/31c59f14-f16d-11e5-928a-cbedee44c380.png)

Now click on the bottom blue cluster bubble, something gets fired causing a error in the console. It should only be fired when unclustered and clicking on the icon like so.

![image](https://cloud.githubusercontent.com/assets/863731/14006431/6d721ee8-f16d-11e5-9425-c877aa5a0957.png)

**Comment by ansis** [comment]
I think the "markers" layer includes the clustered points. This can be fixed by adding a filter to the "markers" layer that only includes points that don't have the `"cluster": true` property. I think this should work: `"filter": ["!=", "cluster", true]`

The second problem that ties into this is that the clustered feature that is part of the "markers" layer is included in the featuresAt query even though it is not rendered. It collides with the feature drawn for the "cluster-count" layer. We're currently reworking the featuresAt api in https://github.com/mapbox/mapbox-gl-js/pull/2052 and https://github.com/mapbox/mapbox-gl-js/pull/2224. The new version will only include symbols that are currently visible.
