### ISSUE TITLE
Feature request - layer search

### ISSUE THREAD

**Issue by facultymatt** [mapbox/mapbox-gl-js#2157]
I find it hard to drill down into the layer I'm looking for. It would be handy to search for the layer by name. 

<img width="248" alt="search_layers_idea" src="https://cloud.githubusercontent.com/assets/1406258/13188203/ea047ec0-d71d-11e5-8991-c3f3f7cc2068.png">

**Comment by tmcw** [comment]
Hey @facultymatt this is mostly an issue tracker for gl-js, rather than Studio - we handle studio support over on help@mapbox.com

Re: this issue, you might be interested in the search interface: [hitting ⌘k while editing a style activates a fast search for layers, properties, and places.](https://www.mapbox.com/blog/mapbox-studio-search/)

**Comment by facultymatt** [comment]
Oh yes that is exactly what I needed!

And sorry about posting here - duh me I'm posting in the wrong place - long day !
