### ISSUE TITLE
Broken streets at high zoom 17-18-19-20

### ISSUE THREAD

**Issue by Rachine** [mapbox/mapbox-gl-js#2194]
Hi !

### Context
Version 12.3 for mapbox-gl. Self-hosting of vector tiles coming from OSM data. 

### Report

**Expected behavior**: We should have normal display for streets ,we plugged in our tiles with open layer, the streets look normal, no streets were broken.

**Actual behavior**:
The major roads and minor roads start breaking, if I zoom too much 
![broken_street](https://cloud.githubusercontent.com/assets/8396578/13362191/b6b7376a-dc77-11e5-8322-4b1df2115e6e.gif)
Here the zoom behaviour in San Francisco. I did not find any issue like this in the repo issues. 

**Steps to reproduce the behavior**:
It happens in city map with a lot of minor roads, such as san francisco, keep zooming in until zoom level 21, and you will see roads are broken.
The roads overlap over building and other roads. And I kind notice some pattern, and perpendicular "non-existing" roads.

**Comment by lucaswoj** [comment]
Thanks for the report @Rachine! I was not able to reproduce this bug using any of the Mapbox hosted vector tiles. The bug is most likely in your tile generation. Please investigate that first.

If you are certain that your generated tiles are correct but mapbox-gl-js is rendering them incorrectly, please re-open this issue with a functioning demo that uses your vector tiles. 

maybe related to #1575
