### ISSUE TITLE
Add .setMaxZoom/.setMinZoom method

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#2235]
Analogous to https://github.com/mapbox/mapbox-gl-js/issues/2175, except that it allows setting the zoom bounds after the map is already declared.

**Comment by peterqliu** [comment]
An alternate format could be `map.setZoomBounds({min:0, max:20})`

**Comment by lucaswoj** [comment]
This would be awesome! 

It think our preferred API would be
```js
map.setZoomBounds(0, 20)
```

**Comment by peterqliu** [comment]
@lucaswoj super naive stub [here](https://github.com/mapbox/mapbox-gl-js/commit/d8579e685f26256395500e89e419da7adac70e5c). Would appreciate some scope/context around this

**Comment by lucaswoj** [comment]
@peterqliu Looks like you're on the right track!

# Next steps

 - [ ] turn this stub into a pull request 
 - [ ] take `minZoom` and `maxZoom` as separate parameters rather than an array
 - [ ]  document the parameters in the docblock comment above the method.
 - [ ] add a way to unset the zoom bounds too
 - [ ] add some simple unit tests for this method

Let me know if I can help in any way.

**Comment by peterqliu** [comment]
:ship: https://github.com/mapbox/mapbox-gl-js/pull/2243
