### ISSUE TITLE
Double-drawing and flickering for translucent raster tiles

### ISSUE THREAD

**Issue by kriscarle** [mapbox/mapbox-gl-js#2236]
**mapbox-gl-js version**: 0.14.3 - 0.15+ (works fine in 0.14.2)

### Steps to Trigger Behavior

 1. Add raster tile layer as an overlay on top of vector layers
 2. Zoom in on the map
 3. Pan the map, raster tiles blur when you release the mouse

### Expected Behavior
v0.14.2 https://jsbin.com/rorijeciqi/1/edit?html,js,output
### Actual Behavior
v0.14.3 https://jsbin.com/busuxabife/edit?html,js,output

![raster_blur_issue](https://cloud.githubusercontent.com/assets/2431570/13650535/206a350c-e611-11e5-8d38-d2124fcd9a7b.gif)

**Comment by indus** [comment]
same here, but for me this bug came with v0.15.0 not 0.14.3

**Comment by lucaswoj** [comment]
My impression is that this problem is specific to translucent raster layers. I don't see this behaviour on our [satellite basemap](https://www.mapbox.com/mapbox-gl-js/example/satellite-map/), for example.

ref https://github.com/mapbox/mapbox-gl-js/pull/2211

**Comment by lucaswoj** [comment]
My diagnosis of the problem is that we haven't properly rearchitected `draw_raster` for our post-layer-by-layer world (i.e. with `gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA)`). 

If we draw tiles from smallest zoom to largest zoom, the depth buffer fails to prevent double-drawing.

If we draw tiles from largest zoom to smallest zoom, we get flickering per https://github.com/mapbox/mapbox-gl-js/issues/2208

Any idea how we can fix this @ansis? Do we need to do a big rewrite?

**Comment by timrobertson100** [comment]
Also seeing this on 14.3 and v15.
v14.2 not an option, as that fails with a different error on zooming (Uncaught TypeError: Cannot read property 'z' of undefined @ draw_rater.js).

**Comment by lucaswoj** [comment]
This bug is my top priority until it gets resolved. The symptoms lead me to believe this is a inter- rather than intra-tile issue.

cc @ansis 

## What’s Worked

* only rendering tiles of the same (max) zoom level

## What Hasn’t Worked

* setting child / parent opacities to 1 / 0 
* rendering tiles in reverse order (smallest zoom level to biggest)
* changing depth function
* enabling clipping mask + stencil test

**Comment by timrobertson100** [comment]
I can confirm that a build of the master branch today fixed the issue from what we see in v15.0.
Thank you very much for fixing this so quickly @ansis @lucaswoj

**Comment by kriscarle** [comment]
It fixed my issue as well. Thanks!!!
