### ISSUE TITLE
Add an example showing mapbox-gl-js in combination with d3

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2256]
There are many leaflet/d3 combos out there and d3 does provide some styling and animation capabilities that are either hard to accomplish or simply not (yet) possible with mapbox-gl-js. Would it be valuable with a mapbox-gl-js/d3 showcase in the examples section?

If so, I could provide a condensed example showcasing:
- Projecting d3 data with mapbox-gl-js
- Animations (when a Point is added etc.)
- Data driven styling (which is not yet possible with mapbox-gl-js)

Comments? Opinions?

**Comment by tmcw** [comment]
Sure! My viewpoint is that the more examples the merrier, as long as they're all high-quality.

**Comment by joedjc** [comment]
@averas I think it would be really useful - it's a very powerful combination. There is a D3 example which seems pretty good except it has to re-render all the D3 elements when panning/zooming (https://bl.ocks.org/shimizu/5f4cee0fddc7a64b55a9). I managed to do it a slightly different way but the maps don't stay in synch when panning/zooming (some browsers better than others). I could send you a video of the thing I have done if you're interested.

**Comment by urbanhop** [comment]
Curious about this combination. The example on bl.ocks is a good starting point (and has stylish comments). If anyone has something partly working I could maybe contribute finalizing it.

**Comment by ssweeney1988** [comment]
Hello I am very interested in this aswell- let me know if anyone want to work on something together.

Sam

**Comment by joedjc** [comment]
@ssweeney1988 I've yet to see an example which works well, but would love to get this working as it would open up a lot of opportunities. 

The challenge seems to be keeping the SVG overlay and mapbox in sync when panning/zooming (the demo above basically avoids this by only displaying the SVG when the user stops panning/zooming, which is ok but not ideal). Using a map move event to adjust the SVG causes some unpleasant looking lag/delay, though the results vary between browsers.

The second challenge would be to adjust the SVG to the map pitch which I could see being difficult as D3 doesn't have any methods i'm aware of for 3D transformations.

I was wondering whether the new canvas source could be used instead of a SVG overlay which would resolve both the problems above. D3 can be used quite happily with canvas (e.g. https://bl.ocks.org/mbostock/1276463).

The problem here is that the canvas source has to be given a geographic position on the map. This is fine if you know exactly where your D3 element needs to go, but not if you want the user to see/interact with D3 elements anywhere (which is what i'd like to do). It can also be a problem if the user zooms in because the canvas has a fixed resolution and therefore your D3 elements can become pixellated.

This made me think about creating canvas 'tiles' - which follow the same pattern as the underlying mapbox tiles, probably making use of d3-tile (https://github.com/d3/d3-tile). Not necessarily a great solution either as you'd need to add quite a few canvas sources (1 per tile), have a way of adding/removing them as the user pans/zooms around the map and no doubt all sorts of other issues.

Any thoughts on these, or other ideas would be interesting and i'm open to helping out with it.

Joe

**Comment by averas** [comment]
I have several working examples in local/private applications where I've combined mapbox-gl-js with d3, and it works fine. I will try to find the time to detach one of these and make a contained example. 

Some comments on the thoughts you put forward:

> The challenge seems to be keeping the SVG overlay and mapbox in sync when panning/zooming (the demo above basically avoids this by only displaying the SVG when the user stops panning/zooming, which is ok but not ideal). Using a map move event to adjust the SVG causes some unpleasant looking lag/delay, though the results vary between browsers.

I use the move events to trigger reprojection of the d3/SVG which, for a d3/SVG container with a reasonable amount of features, is snappy enough.

> The second challenge would be to adjust the SVG to the map pitch and bearing which I could see being difficult as D3 doesn't have any methods i'm aware of for 3D transformations.

Actually, there is no need to make the 3D projections on the d3/SVG side, since mapbox-gl-js already has support to make this for you. So long as your features use geographic coordinates (lng/lat) you use mapbox-gl-js to project geographic coordinates to screen pixels, which will account for any bearing and/or pitch.

> I was wondering whether the new canvas source could be used instead of a SVG overlay which would resolve both the problems above. D3 can be used quite happily with canvas (e.g. https://bl.ocks.org/mbostock/1276463).

I would say they solve different problems. I use d3 overlays whenever I want advanced animations and transitions not really achievable with mapbox-gl-js (yet?). In the past I also used it when I wanted features that were easy to interact with (drag/drop, mouse events etc.), but those things are becoming easier and easier to achieve with native mapbox-gl-js (for example by using mapbox-gl-js-draw).

**Comment by joedjc** [comment]
Thanks @averas - I hadn't thought about using the map.project() function to handle all the transformations (including 3D) - that works very well.

I still find the synchronisation can be poor but it is highly browser dependent - Chrome and Firefox are great but Safari and IE aren't. However, this also affects other overlay elements like HTML markers in exactly the same way so it's not really a D3/SVG issue.

I find D3 overlays useful for quite a few things including advanced animations, but also for drawing for now given how customisable and flexible it is.

**Comment by ssweeney1988** [comment]
@averas @joedjc what is the end result you are looking for?

Ideally I would want to add interactivity to an open street map- say ideally through something like map box. I know that kind of stuff exists where you can choose pins drop pins etc, but I think to do this through d3 would be really excited, especially to add a bit more sophistication to the process and data presented. thoughts?

**Comment by joedjc** [comment]
@ssweeney1988 something i'm working on is a 'presentation' layer, which allows users to add informal comments/annotations to a map. These aren't necessarily strictly geographic features - e.g. I might want an arrow pointing to something on the map with a floating text box connected to it. 

Becuase the users aren't used to mapping/GIS systems it needs to be very intuitive, so I want the experience to be more like drawing shapes in PowerPoint than editing something in OpenStreetMap. 

I also want more flexibility over styling when a user is drawing e.g. select a red arrow and you'll actually see a red arrow being drawn (rather than an orange line). I find this sort of thing very difficult with mapbox-draw (I know you can change the overall style but not for each feature?) and i'm also experiencing performance issues with it. D3 gives me far greater control over the user experience in this sort of situation.

**Comment by ssweeney1988** [comment]
@joedjc that sounds fantastic.
I assume you mean something like a
Standalone application where users can pick their map area and add on custom titles etc? That sounds very exciting- I don't think
That exists at the moment?

**Comment by stephanbogner** [comment]
Are there any news on this?
The best example I have found so far, is this:
http://bl.ocks.org/enjalot/0d87f32a1ccb9a720d29ba74142ba365

**Comment by ryanhamley** [comment]
I think a combination of feature state, data-driven styling and custom layers has made the examples in this thread unnecessary because they can be achieved with the GL JS library now. I can imagine there are cool animations that can be done with D3 but we can't cover every use case. Since there hasn't been activity in more than a year, I'm going to close this issue.
