### ISSUE TITLE
Markers animation performance

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#2257]
I'm trying to animate markers in a geojson feature collection.

I get between 15 and 20 fps with less than 10 markers, and the more markers I add the more the fps drops.

So I have questions regarding optimization : 
 
Would it be better to split the markers in several layers?

I thought about using web workers but the cost of transferring the json between threads 20 times per second will negate any performance gain I believe

Is there a throttling going on inside mapbox gl? Even with the simple animate point example from the documentation I can reach maximum 32 fps and usually between 25 and 30. 

What advice / best practice do you recommend for getting more fps in animation ?

**Comment by lucaswoj** [comment]
Hi @misterfresh! The GitHub issue tracker isn't the right place for us to answer this question. It is reserved for bug reports and feature requests only. I encourage you to ask this question on [StackOverflow](http://stackoverflow.com/questions/tagged/mapbox-gl-js) alongside a demo so that we can better understand your setup. 

We are tracking some performance improvements relevant to animation in #1504 and #2224.

**Comment by emperor1412** [comment]
@lucaswoj here you can find a demo, try to add like 20 cars and you will see
[Test Mapbox](https://jsfiddle.net/emperor1412/amo2cz1y/)

**Comment by misterfresh** [comment]
@emperor1412  if you want to animate for than a couple items, it is not very efficient to do it in JS. Better do it in the shaders to use the GPU. http://misterfresh.github.io/mapbox-animation/
