### ISSUE TITLE
Destroy gl buffers after calling Source#reload

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2266]
**mapbox-gl-js version**: 0.15.0

### Steps to Trigger Behavior

 1. `map.style.sources[vectorTileSourceName].reload()`

### Expected Behavior
The GL buffers from the old buckets are destroyed.

### Actual Behavior
The GL buffers from the old buckets are not destroyed.

When vector tiles are reloaded, only `loadVectorData` is called. The existing buckets and their gl buffers are never destroyed
https://github.com/mapbox/mapbox-gl-js/blob/2b809ddaf3be1547dd485a2d968f0cc9efbf4fd1/js/source/vector_tile_source.js#L74-L100

**Comment by ryd0rz** [comment]
Any progress on this? We are having issues with Mapbox-gl-js on iOS. Even after completely removing the script, and adding the script back in, we are seeing the error:
Terminated due to memory error.
After loading mapbox about 5 times.

We've tried everything from using the mapboxgl.remove(), to removing script and reloading dynamically for every map creation.

**Comment by wandergis** [comment]
@ansis  Have you solved this problem? I also have this problem when call geojson source `setData()`.

**Comment by wandergis** [comment]
@lucaswoj  How to destory the GL buffers from the old buckets?  Can you give me some advice？
Thanks very much.

**Comment by wandergis** [comment]
![memory](https://cloud.githubusercontent.com/assets/5799374/18057961/bf0bf432-6e44-11e6-8705-2baf25fe1353.gif)
![memory2](https://cloud.githubusercontent.com/assets/5799374/18057960/be99607a-6e44-11e6-8d67-4c617223ee6d.gif)
