### ISSUE TITLE
queryRenderedFeatures is inconsistent on bigger maps and different zoom levels

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-js#2320]
@ansis In my use of queryRenderedFeatures #2224 I've run into inconsistencies with what is returned based on zoom level and map size.

This is best seen in the fps benchmarks I'm currently working on. In `fps_small` all is well. In `fps_large` the same code (more or less) doesn't work. I've found that triggering a zoom before the tests start to run can fix this problem.

mapbox-gl@8b52b55251b4d63bc6713d76c8314c1f1007f04a

### Steps to Trigger Behavior

1. pull down `mapbox-gl-draw@fresh-start`
2. make sure `mapbox-gl@8b52b55251b4d63bc6713d76c8314c1f1007f04a` is the current version of gl. I've found installing mapbox-gl inside of draw doesn't always work so I'm working with a symlink locally.
3. npm start
4. open http://localhost:9966/bench/fps_small - this works
5. open http://localhost:9966/bench/fps_large - this fails

### Expected Behavior

I expect large to work just like small

### Actual Behavior

In large South America is never selected.

**Comment by ansis** [comment]
https://github.com/mapbox/mapbox-gl-draw/blob/fresh-start/src/lib/find_target_at.js#L36 passes an `{ x: ..., y: ... }` object as the first argument. `queryRenderedFeatures` currently accepts either a `Point` or an `[x, y]` array. Since it didn't see the first argument as a point it used a full screen box instead. This did not work for `fps_large` because boxes crossing the dateline are broken: https://github.com/mapbox/mapbox-gl-js/issues/2321

- mapbox-gl-draw should pass the point as an array [here](https://github.com/mapbox/mapbox-gl-draw/blob/fresh-start/src/lib/find_target_at.js#L36)



@lucaswoj @mourner:
- should we accept `{ x: ..., y: ... }` objects as valid points?
- or should we be more strict and only accept `[x, y]` arrays?
- are we sure that treating `queryRenderedFeatures(params)` as `queryRenderedFeatures(fullScreenBox, params)` is a good idea?

**Comment by lucaswoj** [comment]
> - should we accept `{ x: ..., y: ... }` objects as valid points?
> - or should we be more strict and only accept `[x, y]` arrays?

Given that Javascript is a weakly typed language, we should probably accept any object that adheres to the `Point` interface of `{x: number; y: number;}`

> - are we sure that treating `queryRenderedFeatures(params)` as `queryRenderedFeatures(fullScreenBox, params)` is a good idea?

Are you asking if we should overload the arguments on `queryRenderedFeatures`? I do not think this is desirable. One True Way :tm:

**Comment by mcwhittemore** [comment]
@ansis wow! I should have looked into this more. It was selected features most times so I just figured it was working... Thanks!

**Comment by mourner** [comment]
@lucaswoj @ansis yeah, we could easily add the `{x, y}` format API-wide by modifying the `Point.convert` function [here](https://github.com/mapbox/point-geometry/blob/master/index.js#L257).

Regarding overloading, I'd prefer to be explicit so that there are no unexpected results. Throw an error if there's no specific bbox or point.

**Comment by ansis** [comment]
> Are you asking if we should overload the arguments on queryRenderedFeatures? I do not think this is desirable. One True Way :tm:

The arguments are [currently overloaded](https://github.com/mapbox/mapbox-gl-js/blob/8b52b55251b4d63bc6713d76c8314c1f1007f04a/js/ui/map.js#L421-L424) which I think we decided on back when we had the conversation about combining featuresAt and featuresIn. I don't think that shifting argument positions is a good idea though. We should change this and either:
- treat an `undefined` `pointOrBox` as a full screen box: `queryRenderedFeatures(undefined, params)`.
- make the user provide a full screen box themselves if they want to query the full screen

cc @jfirebaugh 

> Given that Javascript is a weakly typed language, we should probably accept any object that adheres to the Point interface of {x: number; y: number;}

What about one true way? :P

I'm re-opening the issue until we decide whether we need to change anything.

**Comment by lucaswoj** [comment]
Can we turn `pointOrBox` into keys on `params`? 

```js
queryRenderedFeatures({
  point: {x: 5, y: 20}
});
```

**Comment by jfirebaugh** [comment]
Didn't we already have this discussion?

**Comment by lucaswoj** [comment]
> > Given that Javascript is a weakly typed language, we should probably accept any object that adheres to the Point interface of {x: number; y: number;}

> What about one true way? :P

> I'm re-opening the issue until we decide whether we need to change anything.

We get to pick the one true way and we ought to pick the simplest thing. Being consistent with the rest of our library is the simple. Using any object that adheres to the `Point` interface is simple. Asserting that objects are an instance of `Point` is less simple.

**Comment by lucaswoj** [comment]
> Didn't we already have this discussion?

I think we only discussed this in terms of [combining `findFeaturesAtPoint` and `findFeaturesInBox`](
https://github.com/mapbox/mapbox-gl-js/pull/2052#issuecomment-187383320). I don't recall a discussion about overloading.

**Comment by ansis** [comment]
We're going to keep the api but be more strict about accepting input: https://github.com/mapbox/point-geometry/issues/2
