### ISSUE TITLE
Allow background-pattern, fill-pattern & line-pattern to use tokens like icon-image does

### ISSUE THREAD

**Issue by dapowell** [mapbox/mapbox-gl-js#2340]
This is currently supported in icon-image.

To achieve the same results for any of the other three a new layer needs to be created for each variation in pattern.

**Comment by jfirebaugh** [comment]
We can't do this for `background-pattern` because there's no data to interpolate -- background layers don't have a data source. For `fill-pattern` and `line-pattern`, there are some implementation details that currently prevent us from supporting it. We're working through those for what we call "data-driven styles", which will enable this use case and many more. See #1932.
