### ISSUE TITLE
Add "circle-pitch-alignment" style property

### ISSUE THREAD

**Issue by dpieri** [mapbox/mapbox-gl-js#2420]
Circle layers do not have an orientation property, neither do polygons. Polygons seem to behave as if orientation was set to map, while circles behave as if it was viewport. This is frustrating for us because it means a map with circle layers looks bad when you tilt it.

Here's an example: https://jsbin.com/doyohewulo/edit?html,output

Is this the best place to raise this issue, or should I do that here: https://github.com/mapbox/mapbox-gl-style-spec? It also happens on the latest Android SDK.

**mapbox-gl-js version**: 0.16.0
### Expected Behavior

Circles go into perspective with the map and circles that do not overlap when pitch=0 also do not overlap when pitch=60
### Actual Behavior

Circles in the distance overlap.

**Comment by ashleyclough** [comment]
I've noticed the same issue. I can see that the current behaviour is fine if the circles are intended to be used as location markers - like icons, fixed to the viewport. However, if the circles are part of the geometry of the map - I use them to render roundabouts at road junctions from a point data source - then they need to be fixed to the map, rather than the viewport. Would it be possible to have an orientation 'map' or 'viewport' option similar to those already provided for markers and text?

**Comment by nickidlugash** [comment]
While a circle orientation property could be a good idea, I still think that the default orientation that makes the most sense for most data viz and basemap use cases is `map`.

**Comment by lucaswoj** [comment]
related to https://github.com/mapbox/mapbox-gl-style-spec/issues/459

**Comment by jfirebaugh** [comment]
Tracking this in #4120.
