### ISSUE TITLE
Show/Hide features using a filter with mapbox-gl-js

### ISSUE THREAD

**Issue by ThibaudM** [mapbox/mapbox-gl-js#2426]
Hello,

I'm working on an indoor project using mapbox and i'm looking for a way to show/hide features (floors) with a specific property `level=x`. In the first version of mapboxjs it was possible to use [this](https://www.mapbox.com/mapbox.js/example/v1.0.0/filtering-markers/). Now in the GL version I can easily [show/hide a layer using a filter](https://www.mapbox.com/mapbox-gl-js/example/filter-markers/) but this is not what i'm aiming because layers are already defined and are not dependant on floors.

I can query which features I would like to use:
```map.querySourceFeatures("indoorSource", {sourceLayer: "indoor", filter: ["==", "level", "2"]})```
 but I didn't find a way to show/hide returned features.

For information: indoorSource is a vector tile from a webserver:
```
"indoorSource": {
      "type": "vector",
      "tiles": [
        "http://xxx.xxx/tiles/{z}/{x}/{y}.pbf"
      ],
```

Thanks in advance,
Thibaud

**Comment by lucaswoj** [comment]
Hello Thibaud. I regret that I am unable to help you with this question on our GitHub issue tracker because this is neither a feature request nor a bug report. 

I encourage you to post this [question on StackOverflow if you need more help](http://stackoverflow.com/questions/tagged/mapbox-gl-js).

Hint: [Map#setFilter](https://www.mapbox.com/mapbox-gl-js/api/#Map.setFilter)
