### ISSUE TITLE
Support decimal values for "clusterMaxZoom"

### ISSUE THREAD

**Issue by lmellblom** [mapbox/mapbox-gl-js#2442]
**mapbox-gl-js version**: 0.17.0
### Steps to Trigger Behavior

``` js
map.addSource('cluster-src', {
    type: "geojson",
    data: 'path/to/geojson/source/data',
    cluster: true,
    clusterMaxZoom: 14.5, // A decimal seems to trigger a bug, see comment below. 
    clusterRadius: 60
});

map.addLayer({
    "id": "cluster-layer",
    "type": "circle",
    "source": "cluster-src",
    "paint": {
        "circle-color": "#ff2255",
        "circle-radius": 16
    },
    "interactive": true
});
```

When I use a zoom with a decimal, for example 14.5, the layer crashes and I can draw it. Error message: 

> TypeError: Cannot read property 'load' of undefined
### Expected Behavior

If I set a decimal value on the cluster I expect the cluster to change at that zoom level, similar to changing opacity at different zoom levels. To have a uniform behavior with the zoom levels. 
### Actual Behavior

The whole layer disappear and is not showing (the layer I gave that attribute). Hard to tell that it was the cluster that broke everything.

**Comment by mourner** [comment]
Can you set up a minimal JSFiddle or JSBin test case reproducing the bug?

**Comment by lmellblom** [comment]
@mourner Sure! 
https://jsfiddle.net/wgfywgxh/

If you test to change clusterMaxZoom to a number without a decimal the markers will show. Now they disappears due to the bug.

**Comment by mourner** [comment]
Unfortunately we can't implement this technically, since the clustering algorithm only works with integer zoom levels, unlike opacity that you can control fully at any zoom level during rendering. We could at least add `Math.floor` when accepting the argument, but I feel like we shouldn't — JS APIs generally aren't well suited to strictly validating inputs since the language isn't typed.
