### ISSUE TITLE
Unable to add a fill-pattern to a layer

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#2533]
**mapbox-gl-js version**: 0.18.0

### Steps to Trigger Behavior

Tested in Chrome 50.

 1. create a layer with a fill-color and no fill-pattern
 2. use `map.setPaintProperty()` to set a fill-pattern

### Expected Behavior

The layer should render with the pattern and continue to be responsive to user input and style mutations.

### Actual Behavior

The pattern is set for the layer. An error is logged to the console and the map is no longer interactive.

    Uncaught AssertionError: trying to bind a VAO to a different shader

<img width="512" alt="screen shot 2016-05-05 at 4 56 28 pm" src="https://cloud.githubusercontent.com/assets/302992/15056973/88bf6a5c-12e2-11e6-8238-5abdaa08b457.png">

cc @lucaswoj

**Comment by lucaswoj** [comment]
We will be unable to write a regression test for this bug because the bug is only triggered when using the VAO extension, which is unsupported in headless GL. 

@jfirebaugh @mourner @ansis @tmcw: Given this information, would we rather revert the VAO functionality (~17% perf regression) or apply a fix like the one proposed in #2550?

**Comment by mourner** [comment]
@lucaswoj I prefer performance of course :)
