### ISSUE TITLE
"Geometry exceeds allowed extent" warning from Mapbox tiles

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2568]
[This warning](https://github.com/mapbox/mapbox-gl-js/blob/8adff38f971a904d0cac7976ab8710e2300b35ee/js/data/load_geometry.js#L30) is being triggered on data in Mapbox tiles.

To reproduce, `npm start` and load http://localhost:9966/#7.92/-0.176/0.063.

The layer is `"marine-label-sm-ln"`, tile is https://a.tiles.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7/7/63/63.vector.pbf

**Comment by jfirebaugh** [comment]
The offending x coordinate is 16384, one more than the EXTENT_MAX of 16383. I know there was some discussion of off-by-one errors in the [original PR](https://github.com/mapbox/mapbox-gl-js/pull/2383); looks like there's still some of these lurking in either this code or our VT generation code.

cc @yhahn @ansis

**Comment by lucaswoj** [comment]
After a bit of digging, here is my understanding of the problem:

 - Mapnik supports buffer sizes up to and including the extent size 
 - our marine label layer has a buffer size equal to its extent size
 - GL JS supports buffer sizes up to _but not including_ the extent size (due to how we pack coordinates into our `StructArray`s)

The fix is to 

 - [ ] adjust how we pack coordinates into our `StructArrays` by adding a fudge factor [here](http://github.com/mapbox/mapbox-gl-js/blob/28a03739d204e53b9d6bf4e6092dea93a5c18336/js/data/load_geometry.js#L15-L16) 
 - [ ] centralize our extent conversion math
 - [ ] clearly document our extent conversion math 

Thanks to @flippmoke and @ajashton for the help!

**Comment by gertcuykens** [comment]
When I zoom out fast enough at load time, I got allot of those errors?

example http://gps.nyimbo.nl

PS Always performance above graphics please :P same as in video games :)

**Comment by geoangelotti** [comment]
For some reason i got this error when I had `width="100%" height="100%"` inside my **MapGL** component.

After removing it and assigning the height and width on the viewport the warning disappeared.

**Comment by andreevanatasha** [comment]
I'm getting this error in the same situation as @geoangelotti, however, I don't want to fall back to setting height in vh because it will mess up my layout. :( Does anyone have ideas on how to fix it?
