### ISSUE TITLE
How to draw routes returned from directions plugin?

### ISSUE THREAD

**Issue by johnnyluu** [mapbox/mapbox-gl-js#2646]
Hey guys,

I'm trying to implement directions plugin without using the default interface and the clicking on map to set origin and destination because we need a more restricted user experience. I'm able to do the api call and get the data back, but I don't have any clue on how to draw that polyline. The geometry data that's returned is like ""v~gis@goo}bHg@rIoFr{@cGv~@rfCbVvy@jHrv@vGzc@rDvQnAzw@jHnAwQ", and I've no ide what it means. Is it supposed to draw the lines automatically but I didn't set things up properly? If not, how do I draw the route on the map the way the plugin draws when the directions controls is added to the map?

Thank you!

**Comment by andrewharvey** [comment]
@johnnyluu You have two options:

1. In your request to the Directions API you can set the `geometries` parameter to `geojson`  as per https://www.mapbox.com/api-documentation/#retrieve-directions so that the response is GeoJSON rather than an [encoded polyline](https://developers.google.com/maps/documentation/utilities/polylinealgorithm). You can then draw the route like in this example https://www.mapbox.com/mapbox-gl-js/example/geojson-line/

2. Use https://github.com/mapbox/polyline to decode the polyline into GeoJSON then proceed to add it to your map as per the above example.

**Comment by johnnyluu** [comment]
Thanks for the answer Andrew, The documentation says "This API is not available through the JavaScript SDK" and when I tried to access API directly, it gave me "unauthorised" error, which is why I'm using the plugin instead, but it doesn't have the geometry option.

I did try to decode the polyline by copying out the decode function you have in your polyline.js, because I don't need the rest of the plugin. But the result it produced was 10 times the actual coordinates, and in 'lat, lng' format. What I did in the end was just adding '/10' in where the decode function produces the result and swapped lat and lng. I'm sure it's not the best way to do it, but it worked.

Would be nice if there was a documented official way of doing this. 

Also, this is probably a separate issue, but it would be nice to manually trigger routing and pass in callback handler instead of it triggering automatically whenever destination changes and me capturing the route event outside of the function.

**Comment by andrewharvey** [comment]
@johnnyluu 

> it gave me "unauthorised" error

Did you include an [access_token](https://www.mapbox.com/api-documentation/#access-tokens)?

>I did try to decode the polyline by copying out the decode function you have in your polyline.js, because I don't need the rest of the plugin. But the result it produced was 10 times the actual coordinates, and in 'lat, lng' format. What I did in the end was just adding '/10' in where the decode function produces the result and swapped lat and lng. I'm sure it's not the best way to do it, but it worked.

I ran into the exact same problem the other day, but thought it was a problem on my end. I believe the directions api is returning an incorrect polyline encoding, which I've reported at https://github.com/Project-OSRM/osrm-backend/issues/2498

I would wait for a fix for that, because it's only triggered under some conditions so your /10 code will cause valid results to be wrong.

http://gis.stackexchange.com/ is probably a better place for "how do I" questions, as this doesn't seem to be a mapbox-gl-js issue.

**Comment by johnnyluu** [comment]
> I would wait for a fix for that, because it's only triggered under some conditions so your /10 code will cause valid results to be wrong.
That is definitely the thing I'm most worried about. Will give the API another try. I didn't put in access key due there's nothing about that in the documention. Was wondering if that was the issue, then I saw the  "not available through js sdk' comment in the doc...

Thanks for your help!!

**Comment by lbud** [comment]
Closing as unrelated to mapbox-gl-js; addressed in https://github.com/Project-OSRM/osrm-backend/issues/2498#issuecomment-223297456. 

(The npm polyline module that @andrewharvey linked to above defaults to precision 5 — to decode polylines with precision 6 (the responses that seem to need to be divided by 10) you can optionally specify the precision as documented [here](https://github.com/mapbox/polyline/blob/master/API.md#polylinedecodestring-precision).)
