### ISSUE TITLE
Ability to set up Layer's "z-index" level - discussion

### ISSUE THREAD

**Issue by emakarov** [mapbox/mapbox-gl-js#2672]
At the moment, accordingly to documentation, layers can be added only "before" or "above" some other existing layer. But, there're some use cases when such ability is not enough.
For example, we have an array of asynchronously-loaded objects which we're placing on the map as individual Layers (for example, Circles), and, in addition, some Cluster Layer of those objects, or some other GeoJSON layer that's loaded independently but should be above or under all of these Circles.
So, it seems good to have some form of "z-index" for Layers so we can precisely control which level is under or above some another Layer.

**Comment by jfirebaugh** [comment]
We're not likely to add a second mechanism for controlling z-order. You'll need to work out some way of using the `before` parameter, for instance by placing placeholder layers, and then setting their data when the asynchronous operation completes.

**Comment by emakarov** [comment]
yes, at the moment we're using such approach, but it makes independent layers, like Circle a bit "discriminated" against GeoJSON layers, because they cannot be in a group

**Comment by GadyTal** [comment]
@emakarov Can I force the Circle to be under GeoJSON layer?

**Comment by emakarov** [comment]
@GadyTal I think yes, why not

**Comment by det-jscott116** [comment]
> We're not likely to add a second mechanism for controlling z-order. You'll need to work out some way of using the `before` parameter, for instance by placing placeholder layers, and then setting their data when the asynchronous operation completes.

Hi @jfirebaugh,

Has your or teams opinion on this changed? We are building a highly dynamic application with many different layers, where it is quite difficult to predefine all the layer orders relative to each other which makes using the `before` parameter quite difficult to take advantage of. Especially considering that all "custom layers" and "basemap" layers are lumped together. It would be great to use z-index style order values (similar to how you do in CSS) to better ensure layers are in the correct order.

Its great that the `moveLayer` function is available, and this is what we will have to use to achieve what we are after. However after thinking about the way I am going to tackle this issue, I essentially am going to have to create a wrapper for the `addLayer` function and pass in a z-index value along with . I will then keep track of all existing layers and their specified z-index values, and then re-order them each time a new layer is added using the `moveLayer` function. But it seems like this process could be built into Mapbox directly. It would be more efficient to just insert a layer based purely on its z-index value rather than having to keep track of all the layer IDs that exist within our application.
