### ISSUE TITLE
Text translate is throwing an error

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-js#2762]
**mapbox-gl-js version**: 0.20.0

### Steps to Trigger Behavior

 1. updating text-translate value throws an error

### Expected Behavior

The text should move

### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/1551510/16160864/6f0ef348-3498-11e6-8be5-f76c64aaeec7.png)

**Comment by samanpwbb** [comment]
This is breaking Mapbox Studio in production right now.

**Comment by jfirebaugh** [comment]
I'm unable to reproduce the issue. I added [this test case](https://github.com/mapbox/mapbox-gl-test-suite/commit/ba1a2327e23555829d5e787c56d20491438c1e63) to the test suite and it passes as expected.

Can you provide more detail about how to reproduce this?

**Comment by jfirebaugh** [comment]
Never mind, I can reproduce it if I set an explicit starting value for `text-translate`.

**Comment by jfirebaugh** [comment]
This seems to be related to #2561, the fix for #2534.

**Comment by jfirebaugh** [comment]
This is a latent bug in transition calculation that existed prior to #2561. Prior to #2561, a transition between `"text-translate": [a, b]` and `"text-translate": [c, d]`:

1. Started with [a, b]
2. Jumped to a value of [0, 0] when the transition began
3. Stayed at [0, 0] for the duration of the transition
4. Jumped to [c, d] at the conclusion of the transition

After #2561, it causes a runtime exception instead. Both behaviors are incorrect; the intended behavior is a smooth transition between the old and new translate values.

The bug arises due to an incorrect condition on when to apply the transition calculations intended for "cross-fading" properties. `{background,fill,line}-pattern` and `line-dasharray` are the only properties that are intended to have this type of transition calculation. [This condition](https://github.com/mapbox/mapbox-gl-js/blob/667157b3aba10cb26a4b3d7e81aee540115eeb1a/js/style/style_declaration.js#L23-L23) correctly selects only those properties, but [this one](https://github.com/mapbox/mapbox-gl-js/blob/667157b3aba10cb26a4b3d7e81aee540115eeb1a/js/style/style_transition.js#L17-L17) incorrectly includes any array-typed property.

(Strict typing would have caught this bug.)

**Comment by mcwhittemore** [comment]
@jfirebaugh sorry for missing your comment above.
