### ISSUE TITLE
Fix transitions from property default values

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2769]
Noticed while working on #2762.

`map.setPaintProperty("circle", "circle-color", "red")` when called on this layer will interpolate black to red correctly:

```
                {
                    "id": "circle",
                    "type": "circle",
                    "source": "geojson",
                    "paint": {
                        "circle-color": "black"
                    }
                }
```

However, with this layer it'll just jump from black to red without a transition:

```
                {
                    "id": "circle",
                    "type": "circle",
                    "source": "geojson",
                    "paint": {}
                }
```

The expected behavior is for both to have an interpolated transition.

**Comment by stepankuzmin** [comment]
Hi! I've done a little research and found, that `StyleLayer#_paintDeclarations` is empty for layers with default paint properties, while layers with specified paint properties have `_paintDeclarations`.

I've tried to set paint declaration to default after https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style_layer.js#L111 like this:

```js
this._paintDeclarations[klass || ''][name] = new StyleDeclaration(this._paintSpecifications[name]);
```

but it does not affect transition. So am I missing something? Should we explicitly define default paint properties in StyleLayer constructor? (something like this)

```js
for (paintName in this._paintSpecifications) {
    this.setPaintProperty(paintName, this._paintSpecifications[paintName].default);
}
```

**Comment by mourner** [comment]
@stepankuzmin I would suggest exploring `style_transition.js` for why it doesn't transition from a default property. There's an early bailout there somewhere probably.

**Comment by stepankuzmin** [comment]
It seems that there is no transition from defaults because there is no `oldTransition` to transition from. `oldTransition` for `StyleLayer` is set in `_applyPaintDeclaration`, which is called from `updatePaintTransitions` if `StyleLayer._paintDeclarations` is not empty. For layer with default paint properties, there is no `_paintDeclarations`, so there is no `oldTransition` also.

Defining default paint properties in `StyleLayer` constructor solves the problem, but I am not sure about this.
