### ISSUE TITLE
Make double-tapping on make zoom in by a factor of 2 on iOS

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#2784]
In WebKit on iOS, double-tapping the map zooms in by a very small amount, probably a factor of 1.1. Double-tapping should zoom in by a factor of 2, for consistency with double-clicks in desktop browsers and double-taps in the Mapbox iOS SDK.

Reproduced in v0.19.1 in Safari on iOS 9.3.

/cc @lucaswoj

**Comment by kristfal** [comment]
I think this may be a bug. It was working as intended (zooming by a factor of 2) before – but now, you'll need to double-tap and hold on the last tap for the map movement to continue zooming by a factor of 2.

**Comment by mgd722** [comment]
Any workaround for this?  Still a thing in Chrome on iOS using v0.36.0

**Comment by aparajita** [comment]
Looking at the behavior, it's clear that the problem isn't that the zoom factor is no longer 2, it's that the zoom stops as soon as touchend is received. So maybe the touchend needs to be ignored until the zoom is finished.

**Comment by aparajita** [comment]
I take it back. I put some logging in all of the event handlers, and this is what happens on iOS Safari when I double-tap:

double click handler
map touchend
drag pan touchend
drag pan up
map mousemove
drag rotate down
drag pan down
**map mousedown** (this calls map.stop(), killing the zoom)
map mouseup
drag pan mouseup
drag pan up
map click
zoomend

When I commented out the `map.stop()` call in the map mousedown handler, the zoom worked correctly.

Some policy decisions have to be made by the maintainers. Currently, any zoom or pan can be canceled by a click. The simplest solution would be to set a flag in the double click handler that the map mousedown handler checks, and if the flag is set, the map mousedown handler doesn't call `map.stop()`. It may be preferable to ignore the mousedown completely during a zoom, so that user map event listeners don't get the mousedown.

Thoughts?

**Comment by maaljam** [comment]
We are experiencing the same behavior in Android 7.0 (Cordova 7.0.1, crosswalk 23.0). Double tapping would zoom by factor of ~0.5 and as you zoom, it gets less (~0.3), unless you hold on to the second tap, it would zoom properly.
