### ISSUE TITLE
Add "Map#isMoving" method

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2792]
It is useful to know whether the map is currently moving (i.e. because of a `flyTo` call). This method would sit alongside `Map#loaded` (to be renamed to `Map#isTilesLoaded`?) as a guard against expensive operations during times of rapid map change

``` js
map.on('render', function() {
    if (!map.isMoving() && map.isTilesLoaded()) {
        map.queryRenderedFeatures(...)
    }
});
```

cc @peterqliu

**Comment by lucaswoj** [comment]
I think this is a solid alternate solution for #2471

**Comment by peterqliu** [comment]
👍  I think this would be useful for expensive operations that need to happen regularly ("keep doing this, *unless* the map is moving").

However, it shouldn't replace #2471 altogether. For occasional operations, it's easier to reason about what's going on via event callbacks (moveend, dataend, renderstable, etc), rather than constantly checking the map state before executing something.

**Comment by averas** [comment]
There is currently issues with Mapbox GL JS Draw in regards to adding/removing draw in a controlled fashion (https://github.com/mapbox/mapbox-gl-draw/issues/572). This is in part related to that adding Draw currently depends on <code>Map#loaded</code> returning true, which during long transitions can take a while. If draw is removed before it has been successfully enabled (i.e. loaded returns true) Draw enters a degenerate state which is hard to recover from.

Even though this is more a concern for the Draw project rather than Mapbox GL JS I wonder if <code>Map#isMoving</code> and <code>Map#isTilesLoaded</code> covers the potential state queries a client or plugin would want to make. I imagine that adding draw would be possible before these states are fulfilled, but after the map's style is initialised.

I guess my question boils down to - What is the earliest state the map can reach when it is reasonable to add/remove controls/sources/layers and is it possible to query for _this_ state?

**Comment by lucaswoj** [comment]
> What is the earliest state the map can reach when it is reasonable to add/remove controls/sources/layers and is it possible to query for this state?

This state is when `Map#loaded` returns `true`, also marked by the `Map#load` event. If that doesn't work, I'd consider it a bug.

**Comment by averas** [comment]
@lucaswoj Currently <code>Map#loaded</code> returns false during any kind of transition, meaning that a 10s flyTo transition will block a plugin/client (such as Draw) from enabling itself if it is specifically waiting for <code>Map#loaded</code> to return true (which it is).

If I understand this ticket correctly <code>Map#isMoving</code> will take <code>Map#loaded</code>'s place semantically while <code>Map#loaded</code> will instead return true once all tiles are loaded (and then possibly be renamed to <code>Map#isTilesLoaded</code>)

1.  Isn't it viable to mutate sources/layers/controls _before_ all tiles loaded but _after_ the style is loaded?
2. Wouldn't a transition like a 10s flyTo mean that new tile requests would continuously get queued effectively meaning that <code>Map#isTilesLoaded</code> would also return false until the flyTo is completed?

**Comment by lucaswoj** [comment]
> Currently <code>Map#loaded</code> returns false during any kind of transition, meaning that a 10s flyTo transition will block a plugin/client (such as Draw) from enabling itself if it is specifically waiting for <code>Map#loaded</code> to return true (which Draw is).

Good point. This is a real hole in our API.

> If I understand this ticket correctly <code>Map#isMoving</code> will take <code>Map#loaded</code>'s place semantically while <code>Map#loaded</code> will instead return true once all tiles are loaded (and then possibly be renamed to <code>Map#isTilesLoaded</code>)

Not exactly. `Map#loaded` returns true because as the map moves, new tiles have to be loaded; renaming the method to `Map#isTilesLoaded` would not change this behavior. Adding a `Map#isStyleLoaded` may be more useful.

> 1.  Isn't it viable to mutate sources/layers/controls _before_ all tiles loaded but _after_ the style is loaded?

Yes. If this isn't already allowed, we should allow it.  

> 2. Wouldn't a transition like a 10s flyTo mean that new tile requests would continuously get queued effectively meaning that <code>Map#isTilesLoaded</code> would also return false until the flyTo is completed?

Yes.

**Comment by mourner** [comment]
This was done in #3941
