### ISSUE TITLE
Weather-arrow grid visualization

### ISSUE THREAD

**Issue by swratten** [mapbox/mapbox-gl-js#2829]
Hi Mapbox GL Team,

I am trying to implement a weather arrow grid system in Mapbox. I have done this previously in multiple systems for example: 

http://www.volvooceanrace.com/en/dashboard.html (view this on desktop)
Once the two buttons on the left have gone from grey to black click the top one which shows a label "wind" when hovered over.

I have had a good chat with my colleagues and have convinced them that we should use Mapbox over Gmaps as previously, I just have to make a good prototype.

Now using `map.getBounds()` I can get the screen bounds and divide the co-ords into a "grid".
To draw the Arrows I have tried creating a "symbol" layer using a dynamically generated geojson data source and using the new `icon-rotate` data driven property. 

That works pretty well to that point. I'm stuck with that solution though as I need to scale and color the icons as well through the dynamic data.

So what I'm asking here is: Is this going to be easily possible for me to achieve using any form of current mapbox functionality? All suggestions welcome. 

I am however expected to have this work well on iOS, Android, OSX, Windows. IE11 is my min for Windows for any indicator.

**Comment by mollymerp** [comment]
Hi @swratten -- unfortunately we do not have the bandwidth to provide direct user support over github. 
I recommend you direct your questions to [stackoverflow](https://stackoverflow.com/questions/tagged/mapbox-gl-js). 

[`icon-size`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-size) is not yet supported with data driven styling, but is likely to be added to the supported properties soon. 

Closing here because this is not a feature request or bug report.
