### ISSUE TITLE
Fix fill-color property-function interpolation of alpha value

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#2846]
**mapbox-gl-js version**: v0.20.1

### Steps to Trigger Behavior

Check out https://jsfiddle.net/p6tjyehh/. DDS fill-color based on the property `someNumber`.

### Expected Behavior

I expect the polygon to be nearly transparent here, since the styling rule is `[[0, 'rgba(30,60,90,0)'], [1,'rgba(30,60,90,1)']]`, and the value I provided is near 0.

### Actual Behavior

The polygon is opaque. **There's some quirk with the alpha value `1`, though;** when I change it to 0.99 (making the styling rule `[[0, 'rgba(30,60,90,0)'], [1,'rgba(30,60,90,0.99)']]`, it works properly

**Comment by jfirebaugh** [comment]
This, #2827 and #2828 are probably all related.

**Comment by mollymerp** [comment]
Just tested the example and this is not an issue with `circle-color` interpolation, so for now it seems isolated to the `fill-color` property functions

https://jsfiddle.net/LLgL3byL/

**Comment by lucaswoj** [comment]
This bug is caused by `draw_fill`'s [inability to understand property functions when deciding whether to render in the opaque or translucent pass.](https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/draw_fill.js#L11).

For this reason, we should consider `StyleLayer#paint` and `StyleLayer#layout` deprecated and work towards #2739. 

Like #2065, this use case would benefit from some methods to determine the range of a style function.
