### ISSUE TITLE
Fix exception thrown when removing 1px stroke programmatically

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#2886]
**mapbox-gl-js version**: 0.21.0

Error is also visible at 0.20.0: https://jsfiddle.net/tmcw/yzmz8wL4/

### Steps to Trigger Behavior

 1. When a map's style loads, add a 1px stroke by calling `map.setPaintProperty('building', 'fill-outline-color', '#f00');`
 2. Then immediately remove the stroke by calling `map.setPaintProperty('building', 'fill-outline-color', undefined);`

### Expected Behavior

The stroke is set and removed.

### Actual Behavior

Color parsing throws an uncaught error: `map.js:474Error: Invalid color undefined(…)`

---

Testcase: https://jsfiddle.net/tmcw/nhLd924o/1/

**Comment by anandthakker** [comment]
Unit test added here: https://github.com/mapbox/mapbox-gl-js/pull/2962

I believe this issue originates [here](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style_layer.js#L297), because `fill-outline-color` does not have a `spec.default` value in the spec (probably because its default is supposed to be "the same as fill-color").  Ways to fix include:
 - Extend the style spec json schema to allow for default values that reference other properties in the same layer. This seems pretty complicated -- does this happen for many properties?
 - Hardcode a special case in `style_layer.js` to handle this case (and ones like it) by fetching the `fill-color` value instead of `spec.default`.  This might also be complicated because of all the transition stuff, which I'm totally unfamiliar with.
