### ISSUE TITLE
Add contour lines layer

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-js#2892]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by stackTom** [comment]
How can we add contour layers with elevation labels to our map? I found this: https://www.mapbox.com/blog/satellite-map-with-contours/ , but it doesn't show how. I also found this: https://www.mapbox.com/mapbox-gl-js/example/toggle-layers/ , but the contour lines have no altitude information.

**Comment by lucaswoj** [comment]
Thank you for using GL JS. This is neither a bug report nor a feature request. Due to the large volume of issues we get and the relatively small size of our team, we are unable to help you here on GitHub. I recommend asking this question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox-gl-js).

**Comment by stackTom** [comment]
Will do, thanks
