### ISSUE TITLE
Add an API to create markers that repeat across the dateline. 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2894]
Markers do not repeat across the dateline. Sometimes this is the intended behaviour, sometimes it is not. We could add an API to create markers that repeat across the dateline. 

cc @mourner @adcooley

**Comment by mourner** [comment]
Note that implementing this will increase the complexity of the marker code significantly in addition to a possible performance hit (since each marker will have to dynamically manage several DOM elements rather than a single one).

 Leaflet has a long history on this issue and we ended up not implementing it. Instead, we added an option (off by default) to move markers to another copy of the world when you pan the map (and to be fair, I regret adding this option too).

**Comment by adcooley** [comment]
@mourner understandable. In my case (following a trip journal) it's essential that they are repeated. I've gone ahead and implemented the copies as you pan, which turned out not to be too bad. It would be great if the Marker docs simply stated something to this effect (I simply thought it was broken until I started investigating)
