### ISSUE TITLE
3d/Oblique view

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-js#292]
How feasible is this? It would be truly amazing to have a 3d view.

![screen shot 2014-02-17 at 9 30 21 am](https://f.cloud.github.com/assets/1058624/2187666/4ac11004-97f9-11e3-9f00-0803cdbce97a.png)

cc @kkaefer @ansis @mourner

**Comment by ansis** [comment]
merged in https://github.com/mapbox/mapbox-gl-js/pull/1049
For remaining problems or wishes, open more specific issues

**Comment by atlefren** [comment]
Sorry if i'm jumping in here, but this is really cool! One question though: Have you given any thought to controls for this (keyboard-based or something like the GUI-control for rotate)?

**Comment by ansis** [comment]
@atlefren we haven't implemented anything yet, but there's an open issue https://github.com/mapbox/mapbox-gl-js/issues/1063

**Comment by atlefren** [comment]
@ansis Oh, cool. I was thinking along the lines of a button, experimenting a bit with that now.

**Comment by benstadin** [comment]
I think with the transition from 2D to 3D, it's also time to move from tiles to cubes and scene graphs. I think some things will not work desirably or scale in the long run (LOD, styling,...), and the question is just when to start investing in new 3D-enabling technologies - especially on the server (or preprocessing tools) side. 
Our company has an own 3D map renderer for native devices since quite some time (I'm the product owner and partly still developer), though it works with offline data only at the moment (and we don't have yet plans to change this). In comparison to the open source based web maps that we also deploy, we had to rethink about many things from scratch. Things like styling and other stuff just doesn't fit anymore if you go 3D (e.g. forget about traditional tiles with zoom levels, instead you need sooner or later distance-based and parent-child based style rules for object visibility and LODs).

**Comment by ansis** [comment]
@benstadin yeah, we've started to run into some of those problems. For now we're focusing mostly on 2d so that we can get that right, but I'd be really interested in reading anything more you have to say about how things could be done and how you've handled them in your own 3d renderer!
