### ISSUE TITLE
Create a memory usage benchmark

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2947]
https://docs.webplatform.org/wiki/apis/timing/properties/memory

cc @anandthakker

**Comment by anandthakker** [comment]
In my quick attempts to use this API, I was seeing `performance.memory.usedJSHeapSize` staying the same even after I allocated and retained references to very large objects.  Looks like this is intentional:

> In particular, this patch adds an option to expose quantized and rate-limited memory information to > web pages.  Web pages can only learn new data every minutes, which helps mitigate attacks...

(source: https://bugs.webkit.org/attachment.cgi?id=154876&action=prettypatch -- this is from 2012, so who knows what's changed, but stands to reason that this security safeguard would still be in place.)

**Comment by lucaswoj** [comment]
Subsumed by #4216
