### ISSUE TITLE
Share parsed tiles across maps

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2951]
When one page contains many maps which use the similar styles to show the same geographic region we can improve performance by sharing parsed tiles between maps. 
#1. Create Globally Unique Tile Identifier

Tiles can be uniquely identified by a hash of their
- coordinate
- source's URL or data
- style layer's `id` (to accommodate the `paintVertexArray`s)
- style layer's `type`
- style layer's `layout` properties
- style layer's `paint` properties which are property-functions 

I'm not sure how exactly to handle ref families. The easiest solution is to have an entry in the tile cache per layer, not per ref family. Every entry within the same ref family would still point to the same `Tile` object. 

This could replace the existing `Tile#id` property 
#2. Create Shared Tile Cache

The simplest way to implement this is to replace the `SourceCache#_cache` instance property with a static `SourceCache.cache` property, keyed by the globally unique tile identifier ☝️. We will need to tweak the cache's retention policy to suit. 

We may need to implement this cache as a locking cache to prevent simultaneous requests for the same time from spawning multiple requests. 

cc @anandthakker

**Comment by lucaswoj** [comment]
Related to #899

**Comment by anandthakker** [comment]
👍 

@lucaswoj thinking about this in the context of custom sources, it probably makes sense to implement 1 in a way that allows the `Style` and the `Source` to share responsibility for generating a tile's unique id.

**Comment by anandthakker** [comment]
Hmm -- @lucaswoj right now, for a given coord, the source cache holds one `Tile` per _source_--not per style layer.  It seems to me like the "tiles" you're describing above are really closer to `Bucket`s.

It _almost_ seems like instead of caching `Tile`s, we could cache individual `Bucket`s--keyed off of a hash like you described above--and then use them to construct `Tile`s on the fly... except that `Tile`s also have stuff like:

 - collisionBoxArray
 - collisionTile
 - symbolInstancesArray
 - symbolQuadsArray
 - featureIndex

I don't yet know enough about how these work to guess whether they would make such a strategy infeasible.  What do you think?

**Comment by lucaswoj** [comment]
@anandthakker Ah. Good thinking. We'll need to think a little bigger in terms of the architectural changes needed to support this feature (#2432 would do the trick)

**Comment by andrewharvey** [comment]
see also https://stackoverflow.com/questions/47891132/create-several-mapbox-gl-maps-that-show-different-markers-using-single-map-insta/

**Comment by mourner** [comment]
Closing as stale — not enough interest to pursue this.
