### ISSUE TITLE
support language Korean

### ISSUE THREAD

**Issue by kruny1001** [mapbox/mapbox-gl-js#2984]
Does mapbox support Korean?

**Comment by mollymerp** [comment]
Hi @kruny1001,
Thank you for using GL JS. Due to the volume of issues and limited engineering resources, we are unable to provide support here on GitHub. I encourage you to check out our guides and resources at https://www.mapbox.com/help/ or ask your question on a forum like [Stack Overflow](stackoverflow.com/questions/tagged/mapbox-gl-js).

**Comment by lucaswoj** [comment]
@kruny1001 What aspect of Mapbox are you asking about? The languages built into the [Mapbox Streets tileset are English, Spanish, French, German, Russian, Chinese](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/) (no Korean). You may create your own tileset in Korean for use with Mapbox GL JS.
