### ISSUE TITLE
raster tile request support cors

### ISSUE THREAD

**Issue by wangtun** [mapbox/mapbox-gl-js#3009]
**mapbox-gl-js version**: 0.20.0

### Steps to Trigger Behavior
 1. mapboxgl loading tile pngs without Access-Control-Allow-Origin will Encounter cors errors

### Expected Behavior
will mapboxgl support to load tiles without Access-Control-Allow-Origin setting?
### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/14052340/17686429/ff52cb8e-639e-11e6-975f-e8045e67cad8.png)

**Comment by wangtun** [comment]
@tmcw thanks very much!

**Comment by andrewserff** [comment]
@tmcw Is there no other way for you Mapbox to handle this? This is a big problem for those of us who have no control over the map tile servers we are getting base maps from.  Could you not instead use GET Requests to get the image and then feed the raw image data into your processing? Right now, I basically can't use Mapbox because I can't hook up to my clients Map Server because they don't set the CORS headers...

**Comment by jfirebaugh** [comment]
@andrewserff No, sorry, CORS support is a hard requirement. The browser security model does not permit reading cross-origin image data from non-CORS endpoints, and we need to do so in order to render those tiles.

**Comment by Justin114** [comment]
@wangtun 你好，我也在做同样的事情，请问你是如何解决的？

**Comment by dfy167** [comment]
can add a setting such as :crossOrigin: ‘anonymous’ for some map
