### ISSUE TITLE
Add new 'fill-outline-width' functionality

### ISSUE THREAD

**Issue by anna-geo** [mapbox/mapbox-gl-js#3018]
Hi!
Is it possible to add **fill-outline-width** functionality? Now it is only possible to set color (**fill-outline-color**) but no possibility to set width of outline.

**Comment by mourner** [comment]
No, unfortunately it's a technical limitation of WebGL — it can't render outlines with width wider than 1, so you'll have to create another style layer with type=line. 

We considered removing the `fill-outline` property altogether to avoid this confusion, but decided against it because 1px fill outlines are faster to render.

**Comment by shawnmgoulet** [comment]
@mourner so, the recommendation from mapbox for those that would like to increase the thickness of a polygon geojson outline would be to create a line geo from the poly geo and then manipulate the `line-width` of the line geo overlaid atop the poly geo?  yeah?

**Comment by mollymerp** [comment]
yep that's what I'd suggest @shawnmgoulet

**Comment by mollymerp** [comment]
just to clarify -- you can use the same geojson polygon `Feature` / `source` and then use it in two separate layers (one of `type: "line"`, one of `type: "fill"`)

**Comment by shawnmgoulet** [comment]
A late thanks for the clarification on this @mollymerp.

**Comment by peitalin** [comment]
Could this perhaps be important enough to include in the documentation somewhere?
say the geojson-polygon page?:
https://www.mapbox.com/mapbox-gl-js/example/geojson-polygon/

**Comment by nittyjee** [comment]
@mollymerp @mourner I'm trying to add a layer that's a tileset, not a data source (the tileset was generated from a geojson source with Tippecanoe, and uploaded... my geojson file was enormous); How do I change the line thickness with a source that's a tileset?

**Comment by benrudolph** [comment]
Since this issue shows up first on a lot of related google queries, I'll put my solution, since the ones above didn't work for me. Particularly when trying to style a collection of `Polygon` features with a `Layer` type of `line`, nothing would show up. To get outlines of polygons, I created a new geojson source with `LineString`s generated from the geojson polygons. Turfjs's [`polygonToLine`](http://turfjs.org/docs#polygonToLine)  function was useful for this.

**Comment by emamd** [comment]
@nittyjee Realize you've probably found a way around this but thought I'd leave it for the record. I ran into a similar solution and realized you can use RGBA values for the outline-color. 

ie.:

`'fill-outline-color': 'rgba(255,255,255,0.0)'` 

worked for me.

**Comment by OisinSlevin** [comment]
I'm new to mapbox gl and I have run into this issue I can't believe this is still an issue from 2016, It seems redundant to ask but why hasn't this been addressed, If its possible to have a fill outline, somewhere in the code the outline thickness is being set  so why cant it be made configurable?

Short term fix will be to figure out how to hide the outline layer and attach the visibility control to the fill layer.

**Comment by orthotypos** [comment]
> I'm new to mapbox gl and I have run into this issue I can't believe this is still an issue from 2016, It seems redundant to ask but why hasn't this been addressed, If its possible to have a fill outline, somewhere in the code the outline thickness is being set so why cant it be made configurable?
> 
It was addressed - it's a limitation of WebGL:
https://github.com/mapbox/mapbox-gl-js/issues/3018#issuecomment-240381965

**Comment by Puzzl3Mak3r** [comment]
> just to clarify -- you can use the same geojson polygon `Feature` / `source` and then use it in two separate layers (one of `type: "line"`, one of `type: "fill"`)

So i have both as togglable, to turn them off and on, one for the fill and one for line,
is there a way to have them synced ( When fill is turned on, so is line and vice versa )
