### ISSUE TITLE
particular area wise hotel search in gl mapbox

### ISSUE THREAD

**Issue by achalnexus** [mapbox/mapbox-gl-js#3049]
Particular park or area wise search hotel, mall  using geocoder gl mapbox.??

**Comment by jfirebaugh** [comment]
Hello @achalnexus. I regret that I am unable to help you with this question on our GitHub issue tracker because this is neither a feature request nor a bug report. 

I encourage you to post this [question on StackOverflow if you need more help](http://stackoverflow.com/questions/tagged/mapbox-gl-js).
