### ISSUE TITLE
Improve readability of text-pitch-alignment: "viewport" text

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#3057]
**mapbox-gl-js version**:Master
### Steps to Trigger Behavior
1. Tilt map using Shift + up-arrow key
2. Watch text along line.
3. Its extremely illegible. (See attached screenshot).

![illegible_text_screenshot](https://cloud.githubusercontent.com/assets/8890269/17917837/b723c2ce-6974-11e6-8ff4-f9c21994ffb6.png)

**Comment by 1ec5** [comment]
Setting `text-pitch-alignment` to `viewport` (#2668) untilts the labels, going a long way towards making the labels toward the back legible. The labels are still scaled by viewing distance, which would be addressed by a to-be-implemented `text-pitch-scale` property: https://github.com/mapbox/mapbox-gl-style-spec/issues/459#issuecomment-224957055.

The default Streets style doesn’t set `text-pitch-alignment` to `viewport`, in part because this functionality hadn’t been implemented by the time the current Streets style was published. However, you can use this property in your own custom styles.

**Comment by mb12** [comment]
I am still seeing very high illegibility in text esp when placed on lines going vertically(screenshot below). 

![pitch_alignment_viewport](https://cloud.githubusercontent.com/assets/8890269/17935604/ce3860f8-69d0-11e6-9467-05d71c95c4ab.png)

**Comment by 1ec5** [comment]
That's related to the observations in https://github.com/mapbox/mapbox-gl-js/pull/2668#issuecomment-224113564 and the caveats in https://github.com/mapbox/mapbox-gl-js/pull/2668#issuecomment-224664159. Definitely agree there's room for improvement.

/cc @lucaswoj @yhahn

**Comment by lucaswoj** [comment]
I agree. The readability of `text-pitch-alignment: "viewport"` is poor. We should look into improving it. 

Overall, our plans to address pitched text readability are captured by the `text-pitch-alignment` and `text-scale-alignment` style properties and this ticket.

**Comment by jfirebaugh** [comment]
@ansis Was this fixed by #3790?

**Comment by ansis** [comment]
@jfirebaugh I don't think so

**Comment by ajashton** [comment]
Noting that one specific aspect of this is that perspective is not accounted for in text orientation. If you look at [this JSFiddle](https://jsfiddle.net/ajashton/25peL7y2/1/) First, 2nd, & 3rd Streets should be rotated 180° to be closer to "upright", but if you change the pitch to 0 the same orientation is correct.

**Comment by nickidlugash** [comment]
Update: after syncing up over the last couple of weeks seperately with @yhahn, @lucaswoj, and @pveugen, I've started to revisit this issue. Per chat, if @chrisloer has bandwidth, he and I are going to push on some incremental improvements for pitched label rendering, starting with this issue. 

To summarize and expand on the above conversations:

- Labels rendered with `text-pitch-alignment: "map"` are not very legible (as shown in the [opening comment](https://github.com/mapbox/mapbox-gl-js/issues/3057#issue-172859679)), but they look accurate to what you would expect using this style property assignment. Since road labels and other use cases that require high legibility would most likely not use this assignment, for now we are not focusing on improving this behavior.  

- As the adjustment in this ticket's title suggests, we'll continue to focus this ticket specifically on improving readability of labels along lines for `text-pitch-alignment: "viewport"`.

- The issue of [pitch not being accounted for in text orientation](https://github.com/mapbox/mapbox-gl-js/issues/3057#issuecomment-278766953) is general to pitched labels along lines and not specific to `text-pitch-alignment: "viewport"`, so I've moved it [to its own ticket](https://github.com/mapbox/mapbox-gl-js/issues/4376).

**Comment by jfirebaugh** [comment]
There seem to two main causes of illegibility:

* Text that is "further away" due to pitch is scaled down. The proposed `"text-pitch-scale": "viewport"` property (part of #4120) would provide a way to disable this effect.
* Text running vertically is foreshortened by pitch, squishing glyphs together. Ideally glyphs would be able to spread out in order to preserve the effective letter spacing as the map tilts, while still remaining attached to the line if the geometry curves.

**Comment by nickidlugash** [comment]
@jfirebaugh I agree with ^

> Text that is "further away" due to pitch is scaled down. The proposed "text-pitch-scale": "viewport" property (part of #4120) would provide a way to disable this effect.

My comments about this [are here](https://github.com/mapbox/mapbox-gl-js/issues/4120#issuecomment-286126434).

> Text running vertically is foreshortened by pitch, squishing glyphs together. Ideally glyphs would be able to spread out in order to preserve the effective visual spacing as the map tilts, while still remaining attached to the line if the geometry curves.

From what I understand from @yhahn, the [foreshortening factor](https://github.com/mapbox/mapbox-gl-js/blob/master/src/shaders/symbol_sdf.vertex.glsl#L61-L64) was put in place to avoid other legibility issues around label placement/collision boxes not taking into account the unskewing of pitched labels (which is particularly problematic for curved labels, as @jfirebaugh mentioned). I agree that it would be best to remove the foreshortening and address the other issues. 

As @yhahn [mentioned in the original PR](https://github.com/mapbox/mapbox-gl-js/pull/2668#issuecomment-224901818), in order to transform label placements and collision box size/positioning to accurately reflect the rendering of labels with viewport pitch alignment, we probably need to adjust both the rotation and x/y movement.

Currently we are adjusting for viewport pitch alignment in the render, shader and collision tile, but in order to do ^, it seems like we may need to make adjustments further upstream. I think shaping.js is where the first relevant calculations take place (e.g. label length and glyph positioning), but I don't know whether it make sense for Shaping to take into account pitch/pitch-alignment (conceptually it doesn't seem like the right place).

/cc @ChrisLoer

**Comment by ChrisLoer** [comment]
#4547 addressed the first part of this problem (text in the distance was scaled down too much).

@ansis's work in #4781 will fix the second part of the problem (vertical foreshortening of text makes it illegible).

**Comment by ChrisLoer** [comment]
#4781 has landed: while I'm sure there are further improvements we'll want to make, I think that basically addresses this issue.
