### ISSUE TITLE
Fix bug preventing the use of property functions in style classes 

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#3091]
**mapbox-gl-js version**: Master and 23.0
### Steps to Trigger Behavior

Map style is set with paint properties:

```
'paint': {
    'fill-color': {
        'property': 'drval1',
        'stops': [[0, 'red'], [10, 'red']]
    },
    'fill-antialias': false
  },
  'paint.contrast': {
     'fill-color': {
        'property': 'drval1',
        'stops': [[0, 'blue'], [10, 'green']]
    }
  },
  'paint.night': {
     'fill-color': {
        'property': 'drval1',
        'stops': [[0, 'yellow'], [10, 'orange']]
    }
  }
```

Call `setClasses(['night'])` or `setClasses(['contrast'])`. The DDS layer does not update it's style.
### Expected Behavior

Paint classes containing DDSs should update and render the selected class.
### Actual Behavior

Paint classes containg DDSs are not updated.

Minimum fiddle: https://jsfiddle.net/3y6pv6q3/1/

**Comment by lucaswoj** [comment]
This is likely a subset of https://github.com/mapbox/mapbox-gl-js/issues/3098

**Comment by kristfal** [comment]
Any progress or timeline on this? It's been 6 months and it would be really cool to have this working properly.

**Comment by anandthakker** [comment]
@kristfal I'm not aware of any recent work on this, but note that we are planning to [deprecate style classes](https://github.com/mapbox/mapbox-gl-js/pull/3643) in the near future.

As an alternative to using classes, please consider using `map.setStyle(...)`, which, as of v0.29.0, should smoothly transition from one style to another, performing only the necessary changes rather than reloading the whole style.  (We'll be adding examples of this to the docs soon.)

**Comment by kristfal** [comment]
@anandthakker Alright thanks for the info. I'll migrate to a classless approach instead. Feel free to close this issue then.

**Comment by anandthakker** [comment]
@kristfal 👍
