### ISSUE TITLE
queryRenderedFeatures returns duplicate results

### ISSUE THREAD

**Issue by sleepycat** [mapbox/mapbox-gl-js#3099]
Please see the [JSbin](https://jsbin.com/gawetazihe/edit?js,console,output) that reproduces this issue.

**mapbox-gl-js version**: 0.23.0

### Steps to Trigger Behavior

 1. Pan and zoom the map to focus on Mapbox DC.
 2. Look at the console to see the number of features reported by queryRenderedFeatures
 
### Expected Behavior
With a single feature rendered, the expected behaviour is that queryRenderedFeatures returns a single copy of that feature. 

### Actual Behavior
QueryRenderedFeatures returns between 0 and 4 copies of the same feature.

This issue may be related to mapbox/mapbox-gl-js#2647. That issue is reporting that sometimes no data is returned. At issue here is that when data *is* returned, it's multiple copies of the same data. 

If you feel this is a duplicate (oh the irony) feel free to close or fold it into #2647 .

**Comment by davidtheclark** [comment]
@sleepycat There's a caveat mentioned [in the docs](https://www.mapbox.com/mapbox-gl-js/api/#Map#queryRenderedFeatures) that may be the reason you're seeing this:

> Because features come from tiled vector data or GeoJSON data that is converted to tiles internally, feature geometries are clipped at tile boundaries and, as a result, features may appear multiple times in query results when they span multiple tiles. For example, suppose there is a highway running through the bounding rectangle of a query. The results of the query will be those parts of the highway that lie within the map tiles covering the bounding rectangle, even if the highway extends into other tiles, and the portion of the highway within each map tile will be returned as a separate feature.

**Comment by sleepycat** [comment]
@davidtheclark: Thanks for pointing that out. I had read that at some point and it had slipped my mind.

These are just single points, so I wouldn't expect them to span tiles. If I [turn on](https://jsbin.com/hobabepule/edit?js,console,output) `showTileBoundaries` it doesn't look like the bounds ever really get close to these particular markers. So at least at first glance it looks like something else is going on.

**Comment by lucaswoj** [comment]
@sleepycat  The intent of `queryRenderedFeatures` is to query the geometry of the rendered shapes on the map (including labels) rather than the underlying source geometry. Labels are 2 dimensional shapes that do span tile boundaries.

**Comment by sleepycat** [comment]
With 65 points in bounds in my "markers" layer and 5 rendered I get:
```javascript
map.querySourceFeatures("markers", {filter: ["has", "address"]}).length
Array[258]
map.queryRenderedFeatures({layers: ["markers"]}).length
14
```

I'm expecting `querySourceFeatures` to return 65 and `queryRenderedFeatures` to return 5.

The fact that the features are sometimes split across tiles and therefore shows up multiple times seems to be a detail/side-effect of the underlying implementation.

I guess what's being questioned  here is the value of exposing those implementation details to the callers of `queryRenderedFeatures` and `querySourceFeatures`.

Does having  the same point [show up 2-4 times](https://jsbin.com/yaloviz/edit?js,console,output) in the results array impart some information that they can act on?

My particular usecase (you can decide how representative of the average that is), is that I want to generate a summary chart of the various types of markers within the current bounds. 

If the current behaviour of `queryRenderedFeatures` and `querySourceFeatures`  makes sense in some other context, perhaps there could be an option or another method which would return a non-duplicated array?

Thoughts?

**Comment by jfirebaugh** [comment]
The reasons that `query*Features` doesn't do deduplication automatically:

* It would have to require that every source feature have a unique identifier, in order to have a key on which to base deduplication. Not all sources do.
* For lines and polygons, it would be expected to union the feature geometries, an expensive and algorithmically-difficult operation. There are no good JS implementations of geometry union; this is something we are working on with [turf](https://github.com/Turfjs/turf-union/pull/9) but it's a difficult problem.
* It still wouldn't solve the issue that if a feature is partially offscreen, those tiles aren't loaded, and therefore the geometry will necessarily be incomplete. Therefore even if deduplicating and merging were done automatically, it would still have the caveat that it's a lossy operation.

Mapbox GL JS is primarily a rendering library. The implementation of `query*Features` is provided as a convenience accessor to the tile data backing the rendering, and is not intended to be a general purpose GIS query tool.
