### ISSUE TITLE
Invalid LngLat object with valid data.

### ISSUE THREAD

**Issue by eatpurely** [mapbox/mapbox-gl-js#3132]
When creating some LngLat objects, i will get this issue where this.lat is null, but as you can see in the screen shot, they should not be null, as the data is being passed in correctly.

This is ultimately giving me a:

`transform.js:469 Uncaught Error: failed to invert matrix`

when trying to fitBounds() on the map.

![screen shot 2016-09-01 at 3 51 30 pm](https://cloud.githubusercontent.com/assets/13232996/18183894/0f0bb81e-705c-11e6-997c-46ec103ec064.png)

Thanks,

Dan

**Comment by jfirebaugh** [comment]
Can you please provide a self-contained JSFiddle that demonstrates the issue?

**Comment by eatpurely** [comment]
I am trying t fitBounds and cant seem to get past this error anywhere:

transform.js:469Uncaught Error: failed to invert matrix

https://gist.github.com/eatpurely/d7e8cd8e76695472d87d828fc60645a4

**Comment by eatpurely** [comment]
Here you go:

https://jsfiddle.net/tkkjqvm4/16/

**Comment by jfirebaugh** [comment]
As mentioned in the [CHANGELOG](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md), as of 0.23.0, the `LatLngBounds` constructor obeys its documented argument order (southwest, northeast), in order to allow bounds across the dateline #2414. You need to ensure that the coordinates you pass to it are actually a southwest and northeast corner, or use [`LatLngBounds#extend`](https://www.mapbox.com/mapbox-gl-js/api/#LngLatBounds#extend) to build a containing hull.

**Comment by eatpurely** [comment]
@jfirebaugh can you please give an example of how to solve this problem with extend().

Thanks in advance.
