### ISSUE TITLE
Use lovell/sharp instead of png-js for faster render tests

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#3180]
By my (unsystematic) observations in a different project, https://github.com/lovell/sharp seems to be perhaps 10-20% faster than `png-js` at writing a `Buffer` => PNG image.   If it installs smoothly on CircleCI, it may be worth using it in `suite_implementation.js` to get faster render tests.

**Comment by mikemorris** [comment]
Looks like the install process has gotten better since the last time I looked, but would be good to confirm this compiles cleanly on macOS (for local dev) and Linux and possibly get https://github.com/lovell/sharp/issues/186 addressed - this was the primary reason I stuck with `png-js` for tests on another project.

**Comment by anandthakker** [comment]
@mikemorris Ah yeah -- pre-built would be nice.  It's been installing pretty quickly and cleanly for me on OS X, and also worked fine on my CircleCI build (which is an ubuntu container, I think).  

Looking again at suite_implementation here in this repo, I realized that the image i/o is actually happening over in mapbox-gl-test-suite.  Gonna close this and open an issue there instead.

**Comment by jingsam** [comment]
Sharp may conflict with node-canvas, as described in https://github.com/lovell/sharp/issues/371. So if you want to use packages depending on node-canvas in the future, be careful.
