### ISSUE TITLE
GeoJSON defined property string is not validating to style specification

### ISSUE THREAD

**Issue by damon-rand** [mapbox/mapbox-gl-js#3269]
GeoJSON defined property string is not validating to `color` style specification: https://www.mapbox.com/mapbox-gl-style-spec/#types-color

**mapbox-gl-js version**: 0.24
### Steps to Trigger Behaviour

 1. https://jsbin.com/palijohera/edit?html,js,output

### Expected Behaviour
The marker icon color should change to color value defined in the GeoJSON objects. 

### Actual Behaviour
[object Error] {
  column: 198,
  line: 128,
  sourceURL: "https://api.tiles.mapbox.com/mapbox-gl-js/v0.24.0/mapbox-gl.js"
}

Commenting out the following lines:
        ```"paint": {
           "icon-color": "{color}"
        }``` will prevent the error from occuring, allowing the markers to display. Also tested on circle layers with `circle-color`.  GeoJSON seems valid according to http://geojsonlint.com

**Comment by mollymerp** [comment]
Hi @damon-rand, 
String interpolation is only supported for the [`icon-image`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-image) and [`text-field`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-field) properties at this time. The [`icon-color`](https://www.mapbox.com/mapbox-gl-style-spec/#paint-icon-color) paint property only works on `sdf` icons and the icons included in our default styles are `png` sprites. In order to change the color of your icons, you will have to create a custom sprite sheet with the icons in the colors you need for your map style.  

You can find more information at #1817 and a guide on uploading custom markers [here](https://www.mapbox.com/help/custom-markers/)

**Comment by louisdecharson** [comment]
Is this possible to do something like this using Mapbox-gl (this is done with mapbox.js):
<img width="1280" alt="screen shot 2016-10-08 at 17 54 38" src="https://cloud.githubusercontent.com/assets/3234544/19214352/563e5b6e-8d81-11e6-997e-0c2eb617fff7.png">
The best-attempt I did was something like (but pretty ugly though):
<img width="1280" alt="screen shot 2016-10-08 at 17 10 27" src="https://cloud.githubusercontent.com/assets/3234544/19214354/69e46c4e-8d81-11e6-9fd5-74480788c918.png">
