### ISSUE TITLE
Dissociation of markers and map moving, when animating camera

### ISSUE THREAD

**Issue by julesanchez** [mapbox/mapbox-gl-js#3273]
Hello,

When I moving the camera, using methods like `panTo`, `easeTo`, or `flyTo`, I have sort of jitter/drift between the move of the map and the markers.
The issue is similar to this one https://github.com/mapbox/mapbox-gl-native/issues/6139 , on mapbox-gl native.

Here a illustration of the behavior. Markers looks to moving not in the same time as map canvas : https://infinit.io/_/5Yb2vxm

The effet is particulary visible on low-performances devices.

**Comment by jfirebaugh** [comment]
I'm not sure it's possible to guarantee that WebGL rendering is perfectly synchronized with DOM elements such as markers, because GL is inherently an asynchronous rendering pipeline.

If you require frame-perfect synchronization, you probably need to use a symbol layer rather than markers, so that everything is rendered with WebGL.

**Comment by lucaswoj** [comment]
Agreed with @jfirebaugh. This is a technical limitation of `Marker`s. If you require perfect synchronization, you must use the built-in layer types.
