### ISSUE TITLE
Attribution control does not render in a basic map

### ISSUE THREAD

**Issue by ajithranka** [mapbox/mapbox-gl-js#3277]
In the latest version of GL, the attribution control does not render until at least one source is added to the map. Setting `attributionControl` to `true` in the map options has no effect.

**demo**: http://jsbin.com/cikobewuma/edit?js,output
**mapbox-gl-js version**: 0.25.0

**Comment by mourner** [comment]
In fact, all controls are not displayed. Investigating.

**Comment by mourner** [comment]
The bug happens because `data` listener in the attribution control fires before `source.load` listener in `SourceCache` (which copies the attribution string from underlying `Source`). It means that `map.sources.<source>.attribution` is empty at the time while `map.sources.<source>._source.attribution` isn't.

@lucaswoj we can either do `getSource` in `Attribution.createAttributionString`, or fiddle with the order of events. What approach do you prefer?

**Comment by lucaswoj** [comment]
Closed in #3278
