### ISSUE TITLE
Scoping events to the source created

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#3279]
I was expecting this:

```js
var foo = map.addSource('foo', {
  type: 'vector',
  url: 'mapbox://tristen.6lhnhxai'
});

foo.on('data', function(ev) {
  console.log(ev); // Reports all map events not just `foo`.
});
```

To just respond to the event activity of the source but it reports all map data events.

cc @lucaswoj

**Comment by lucaswoj** [comment]
This is happening because [`Map#addSource` returns the `Map`](https://www.mapbox.com/mapbox-gl-js/api/#Map#addSource) rather than the newly created `Source. The intent behind this convention is to allow method chaining. 

The following should work as you expect: 

```js
var foo = map.addSource('foo', {
  type: 'vector',
  url: 'mapbox://tristen.6lhnhxai'
}).getSource('foo');

foo.on('data', function(ev) {
  console.log(ev); // Reports all map events not just `foo`.
});
```

Does that make sense? Can you think of any way to make this more clear? Do you think we should change our convention?

We may need to revisit some of these questions as we make the `Source` interface more of a public API.

**Comment by tristen** [comment]
> This is happening because Map#addSource returns the Map rather than the newly created `Source. The intent behind this convention is to allow method chaining.

Oh dur of course. This makes sense and some future code documentation will make this more clear.
