### ISSUE TITLE
Add ability to modify layer z-index via API

### ISSUE THREAD

**Issue by bbodien** [mapbox/mapbox-gl-js#3303]
**mapbox-gl-js version**: 0.25.1

I'm adding LineString layers based on GeoJSON data, each representing the route a particular trip takes on a specific day of a holiday. As the user scrolls down the page, I'm highlighting the layers for each day in turn by changing the `line-color` value. 

Here's an [example illustration of one such map](http://b.ntrn.cc/0j3q1w0b2C08).

The problem I have is that the lines/routes for some days overlap, using the same routes as other days, and where this happens, my highlighted line is at risk of being obscured by layers that were added later, as you can see in the image above.

It'd be great if I could update the z-index of a specific layer, to allow the highlighted layer to be fully visible.

**Comment by lucaswoj** [comment]
Hi @bbodien! I love that you're building a trip visualizer in GL JS.

The preferred way to set a layer's z-index is to [`removeLayer`](https://www.mapbox.com/mapbox-gl-js/api/#Map#removeLayer) and then [`addLayer`](https://www.mapbox.com/mapbox-gl-js/api/#Map#addLayer) the layer, using `addLayer`'s `before` parameter to control its `z-order`. 

You may find [`Map#getStyle`](https://www.mapbox.com/mapbox-gl-js/api/#Map#getStyle) helpful if you don't keep track of the layer's definition within your own code. 

I understand this isn't the most ergonomic API. We're caught in between an imperative paradigm and a [declarative paradigm](https://github.com/mapbox/mapbox-gl-js/issues/1989#issuecomment-243608479) right now and trying to move towards the latter. Because we are moving towards a declarative paradigm, we are going to put our energy into making a more powerful `setStyle` primitive rather than create `setLayerBefore` mutator. 

I hope this workaround works for you! Happy mapping.

**Comment by bbodien** [comment]
Thanks @lucaswoj! While not ideal, I'll try removing the layer and re-inserting it at the "front" at the point at which I need to highlight it.

**Comment by lucaswoj** [comment]
Good luck @bbodien!

Another approach that might work for you: have a permanent `highlighted-route` layer and mutate that layer's `source` and `filter` so that it shows the right data.

**Comment by bbodien** [comment]
@lucaswoj is there a method for setting a new `source` on an existing layer? I can't see anything with a look through the GL JS API docs, and the response to [this issue](https://github.com/mapbox/mapbox-gl-js/issues/1722) suggests that the recommended approach is to remove and re-add the layer.

**Comment by lucaswoj** [comment]
@bbodien You are correct -- the only ways to change a layer's source is to remove and re-add it. Related operations include using `GeoJSONSource#setData` to change the source's data and using `Map#setFilter` to change the source's filtering.

**Comment by LarryFix** [comment]
It looks like `moveLayer` is an another way to change the z-index of a layer. Is there any advantage over removing and adding the layer?

**Comment by jfirebaugh** [comment]
Yes, `moveLayer` is a recent addition, and it's more efficient than removing and re-adding the layer.

**Comment by LarryFix** [comment]
Thanks @jfirebaugh!
