### ISSUE TITLE
Inconsistent style-rendering

### ISSUE THREAD

**Issue by vhaze** [mapbox/mapbox-gl-js#3354]
**mapbox-gl-js version**:  v2.4.0

### Steps to Trigger Behavior

 1. Open Mapbox Studio preview/sharing url:
https://api.mapbox.com/styles/v1/ngeens/circ2dl5u002hh1kp950caxzq.html?title=true&access_token=pk.eyJ1IjoibmdlZW5zIiwiYSI6ImNpcmMyYXVjMDAwN21pYWx3b2lvcHpvNDAifQ.7QcQaZtD1ttfCq4qgBdzLw#3.577873543226374/48.009524894513106/7.8074666275565505/0
 2. Open Codepen with style embedded:

 3. Compare rendering. See how the white country-borders are visible in the preview url, but don't show in the codepen url.
http://codepen.io/nikogeens/pen/VKdvXX
### Expected Behavior
Rendering should be consistent.

### Actual Behavior
White country-borders dissapear.  

This used to render correctly in the past, I think... Is this a bug?
Or I might be missing something...

**Comment by mollymerp** [comment]
Hi @vhaze -- thank you for the bug report! 

In your codepen you're using [Mapbox.js](https://github.com/mapbox/mapbox.js/), which uses raster tiles, not mapbox-gl-js which uses vector tiles. I have forwarded on your bug report to the team that works with our API for GL raster tiles to see if they can identify the problem. 

If the problem still occurs when using mapbox-gl-js, please reopen. Closing because this is not actionable for gl-js.
