### ISSUE TITLE
redoPlacement is broken for GeoJSON sources

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3365]
The ['redo placement' message](https://github.com/mapbox/mapbox-gl-js/blob/31523a851362e3d3feb8b33d78dc8f92d99d8977/js/source/tile.js#L131-L137) does not include a `type` key, so when the worker [receives](https://github.com/mapbox/mapbox-gl-js/blob/691f3fee4df842275dbae3c1704c2b9ca272e147/js/source/worker.js#L126-L129) the message, it defaults to `'vector'` and calls `redoPlacement` on the wrong `WorkerSource` object.

@lucaswoj @anandthakker Advice on fixing this? `Tile#redoPlacement` is passed a `SourceCache` (the parameter name is misleading) and I don't immediately see a way to get the source type from that.

**Comment by anandthakker** [comment]
@jfirebaugh oof.  At one point I'd thought to require each Source to expose a `type` property, but nixed it because I thought it was an unnecessary complication.  Perhaps I should have kept it.

Given that the custom source API will undergo [heavy development/revision](https://github.com/mapbox/mapbox-gl-js/projects/2) (especially w/r/t workers), I'd propose tabling the general question for now.  For the immediate-term fix, note that GeoJSONSources [do expose `type`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/geojson_source.js#L101), so `Tile#redoPlacement` could get it by digging into the SourceCache's inner Source.

**Comment by jfirebaugh** [comment]
Actually it looks like `Tile#redoPlacement` is normally called with a `Source` as the argument, not a `SourceCache`. [This](https://github.com/mapbox/mapbox-gl-js/blob/d60575a2ffe145c294d2e2da044939e3033979db/js/source/source_cache.js#L516-L516) is the exception; I'll try changing it to pass `this._source`.
