### ISSUE TITLE
Use (some) ES6 features

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3368]
Let's try allowing the following ES6 features:

* `let`/`const`
* arrow functions
* template strings
* `for...of`
* object literal extensions

This is a subset of ES6 that's implemented in node 4.x+ and available without runtime flags, meaning we can run the code in node without any transpiling, avoiding https://github.com/mapbox/mapbox-gl-js/issues/855#issuecomment-70935993.

For the browser build, we'd transpile with babel, under a configuration that allows only these features. (ES6 browser support is still lacking in browsers supported by GL JS, in particular IE 11 and iOS 9's Mobile Safari.)

**Comment by mourner** [comment]
Node v6 [enters LTS phase in 4 days](https://github.com/nodejs/LTS), and we already use it in Circle CI, so we could already target ES6 features in v6 instead of v4.

For the browser build, I'd love to explore [Buble](https://buble.surge.sh/guide/) instead of Babel, which in my opinion aligns much better with our goal of transpiling a productive, safe subset of ES6 (without heavy stuff like generators and iterators), and producing clean lightweight code without huge slowdowns in compilation times.

@lucaswoj mentioned this as a good opportunity to also add Flow annotations, which I'd love to do to. But to keep the source runnable under Node for tests, we'd have to experiment with something like [flow-node](https://flowtype.org/docs/running.html) and I'm not sure how well it plays with our testing pipeline (e.g. whether `nyc` still runs properly with it, etc.).

**Comment by mourner** [comment]
Useful ES6 features that are available in Node v6 but not v4:

- default function parameters
- rest parameters
- spread operator (`...`)
- destructuring assignment

I'd also love to use native `class` syntax (available in v4+).

**Comment by jfirebaugh** [comment]
@mourner I'm confused by https://buble.surge.sh/guide/#unsupported-features and https://buble.surge.sh/guide/#dangerous-transforms. Does this mean buble does or does not support `for...of`?

**Comment by mourner** [comment]
> Bublé offers 'dangerous transforms', which generate highly efficient ES5 code but with important caveats.

@jfirebaugh it supports `for...of`, but with a caveat that it can't be used with ES6 iterables (`Map`, `Set`, `[Symbol.iterator]` etc.) and generators, because it transpiles it to a simple `for` loop without complicated wrappers. It's fine to use in our case.

**Comment by tmcw** [comment]
Given that we have a WebGL requirement, we're mostly supporting newer browsers - except for IE11 which still is pretty iffy. But point being, could we rely on native support for these features? At least for let, const, and for of, it's all green for all modern browsers on https://kangax.github.io/compat-table/es6/

**Comment by jfirebaugh** [comment]
Among other things, iOS 9 (Mobile Safari) doesn't support `let`/`const` or arrow functions, and IE 11 doesn't support `for...of`. So I think the answer is that we have to transpile for the time being.

**Comment by jfirebaugh** [comment]
Started experimenting in #3388. For certain features, we can do an automated conversion using `eslint --fix`.
