### ISSUE TITLE
Array.prototype breaks version 0.26.0

### ISSUE THREAD

**Issue by mkeshields** [mapbox/mapbox-gl-js#3373]
If any prototype is created on the Array object, the map breaks with the following errors:

Uncaught TypeError: Cannot read property 'type' of undefined(…) in style_declaration.js:16

Demo: https://jsbin.com/raretoc/edit?html,output

**mapbox-gl-js version**: 0.26.0

**Comment by tmcw** [comment]
We have a few options for handling extended prototypes:

* Add `hasOwnProperty` everywhere
* Recommend folks don't extend native objects. This is the current practice, and I think it works pretty well: we don't clutter code with `hasOwnProperty` checks, and native extension has been rare since the prototype.js days ended.

In the given example, you can also still extend the prototype but not bork other libraries by defining it as non-enumerable:

```js
Object.defineProperty(Array.prototype, 'getLast', {
  enumerable: false,
   value: function(){
return this[this.length - 1];
   }
});
```

**Comment by mkeshields** [comment]
Thank you, very much I have never seen it done that way.

Mike
