### ISSUE TITLE
_typeof is not defined

### ISSUE THREAD

**Issue by bensleveritt** [mapbox/mapbox-gl-js#3422]
Getting a `_typeof is not defined` error when using `babel-preset-es2015` in Webpack. Not using the preset removes the error.

v0.26.0:

### Steps to Trigger Behavior

 1. Set up Webpack, Babel, Mapbox-gl as per [my repo](https://github.com/bensleveritt/mapbox-gl-_typeof-bug).
 2. `npm start` to start webpack-dev-server.
 3. Observe console log errors:

```
Uncaught ReferenceError: _typeof is not defined
exports.clone @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
StyleDeclaration @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
setPaintProperty @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
set @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
StyleLayer @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
FillStyleLayer @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
StyleLayer.create @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
t @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
setLayers @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
Actor.receive @ blob:http://localhost:3000/c231e9bd-0ca6-4a10-8b58-eecdc79fe25d:1
```

### Expected Behavior

Basic map is displayed over beige background.

### Actual Behavior

Beige background is displayed.

**Comment by jfirebaugh** [comment]
Looks like a bug in babel (https://github.com/babel/babel/issues/4125, not sure why this is closed).  The dist mapbox-gl.js file does not use ES2015, please exclude it from transpilation.

**Comment by bensleveritt** [comment]
I've excluded it, thanks for the help.

**Comment by rotoglup** [comment]
> Add exclude: `/(node_modules)/` to the babel loader definition in `webpack.config`.

FWIW, I've got bitten by this whole exclusion, better exclude only mapbox-gl with `exclude: /mapbox-gl/`

**Comment by caesarsol** [comment]
Hitting the same error here, it was hard to find because one minified becomes `s is not a function`...

Waiting for the babel issue, in the meantime `exclude: /mapbox-gl/` is the way.

**Comment by digitalkaoz** [comment]
anyone has an idea how to solve it without excluding it from babeling?

**Comment by cyrilchapon** [comment]
This is still an issue using

- mapbox-gl `0.53.1`
- react-map-gl `4.1.1`
- parcel-bundler `1.12.3`

Getting
> Uncaught ReferenceError: _typeof is not defined
From webworker

**Comment by fabiobarboza7** [comment]
It's sometimes happen when you are trying to read some javascript before load the js file.

**Comment by CharlieMartell** [comment]
Seeing this aswell on Chrome 76 mapbox-gl@1.2.0

**Comment by KevinColemanInc** [comment]
For rails devs scratching their heads at this, I found this fixed the problem:
in `environment.js`
```
environment.loaders.delete('nodeModules')
```

related content:
https://github.com/rails/webpacker/blob/54c3ca9245e9ee330f8ca63b447c202290f7b624/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader

**Comment by jordymeow** [comment]
Was anybody able to do it using Parcel, and Babel 7? @cyrilchapon, did you find a way? It would be awesome to find a solution to this.

**Comment by cyrilchapon** [comment]
@jordymeow nah I just gave up on parcel.
Found out that this 0-config stuff is just basically not suitable for complex projects involving complex libs like mapbox

**Comment by jordymeow** [comment]
@cyrilchapon Went back to WebPack, but I am still running into exactly the same issue. Excluding mapbox from being transpiled through `exclude: /mapbox-gl/` has no effect. That said, normally I don't even need this since it should go only through my own code: I am using `include: [ path.resolve(__dirname, 'src') ]` for `babel-loader`. I am going nuts over this :( Can you share your webpack config? I must be missing something...

**Comment by willallendev** [comment]
I created my project with create-react-app, so I've got no direct access to the webpack.config file.

I did the following:

1. Add **react-app-rewired** to my project in order to override webpack.config in node_modules/react-scripts/config. This will be true if you create your project the same way as I did (https://github.com/timarney/react-app-rewired) make sure to follow all the instructions and modify the scripts in your package.json
2. Add **customize-cra** to my project (https://github.com/arackaf/customize-cra#with-webpack) and follow the instructions
3. In your newly created config-overrides.js file use the "babelExclude" helper function from customize-cra package in order to exclude mapbox-gl from babel loader (make sure to write the path correctly, you may want to use "path" package).
4. This might do the trick for you

however depending on the structure use in your webpack.config files in node_modules/react-scripts/config the helper function "babelExclude" might not be able to reference your babel loader definition and you will get an error like “cannot set property exclude of undefined” if that happens you will have to do what I did to make it work, which is checking your webpack.config files and figuring out where in the structure you will be able to write/override the exclude sentence (see my config-overrides.js below).

My version of "react-scripts": "2.0.0" (this is the one package that defines the webpack.config file for you)

`const path = require('path');

const babelExclude = (exclude, config) => {
  config.module.rules[2].oneOf[2].use[1].options.exclude = exclude;
  return config;
};

module.exports = function override(config) {
  config = babelExclude(path.resolve('node_modules/plotly.js'), config);
  return config;
};`

Not pretty but that did the trick for me without having to eject. You may want to remove de **^** sign in front of the version of react-scripts in your package.json. If the webpack,config changes you project might break again, of at least be aware that you will have to update config-overrides.js accordingly.

Hope it helps someone!

**Comment by zzzev** [comment]
We're using parcel & babel 7, and fixed this by narrowing the scope of browsers we include in the browserslist property of our package.json. Some of the browsers we were including were causing the [transform-typeof-symbol](https://babeljs.io/docs/en/babel-plugin-transform-typeof-symbol) plugin to be applied, which is what causes this (something about this plugin doesn't work properly when typeof is used inside the web worker used by mapbox).

**Comment by andrew-j-roberts** [comment]
Hey @zzzev , do you mind posting your package.json file?

I'd love to see if this solves my issue too.

**Comment by zzzev** [comment]
The browserslist part:
```
  "browserslist": {
    "production": [
      "last 3 chrome versions",
      "last 3 firefox versions",
      "last 3 safari versions"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
```

We're using parcel 1.12.4, with no explicit babel dep and no babelrc file.

**Comment by sachinpatil55** [comment]
> The browserslist part:
> ```
>   "browserslist": {
>     "production": [
>       "last 3 chrome versions",
>       "last 3 firefox versions",
>       "last 3 safari versions"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
> ```
> 
> We're using parcel 1.12.4, with no explicit babel dep and no babelrc file.

This solution worked for me thanks @zzzev

**Comment by daveycakes** [comment]
> 
> 
> For rails devs scratching their heads at this, I found this fixed the problem:
> in `environment.js`
> 
> ```
> environment.loaders.delete('nodeModules')
> ```
> 
> related content:
> https://github.com/rails/webpacker/blob/54c3ca9245e9ee330f8ca63b447c202290f7b624/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader

You are a wonderful human being

**Comment by Fradomati** [comment]
> > The browserslist part:
> > ```
> >   "browserslist": {
> >     "production": [
> >       "last 3 chrome versions",
> >       "last 3 firefox versions",
> >       "last 3 safari versions"
> >     ],
> >     "development": [
> >       "last 1 chrome version",
> >       "last 1 firefox version",
> >       "last 1 safari version"
> >     ]
> >   },
> > ```
> > 
> > 
> > We're using parcel 1.12.4, with no explicit babel dep and no babelrc file.
> 
> This solution worked for me thanks @zzzev

Yeah, me too but, might this be a problem in the future?

**Comment by gooin** [comment]
> The browserslist part:
> 
> ```
>   "browserslist": {
>     "production": [
>       "last 3 chrome versions",
>       "last 3 firefox versions",
>       "last 3 safari versions"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
> ```
> 
> We're using parcel 1.12.4, with no explicit babel dep and no babelrc file.

It's work for me too.  webpack version  `^5.8.0` , babel verison `^7.12.8`

**Comment by jswelsh** [comment]
> The browserslist part:
> 
> ```
>   "browserslist": {
>     "production": [
>       "last 3 chrome versions",
>       "last 3 firefox versions",
>       "last 3 safari versions"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
> ```
> 
> We're using parcel 1.12.4, with no explicit babel dep and no babelrc file.

This worked for me

**Comment by cacheflow** [comment]
> For rails devs scratching their heads at this, I found this fixed the problem:
> in `environment.js`
> 
> ```
> environment.loaders.delete('nodeModules')
> ```
> 
> related content:
> https://github.com/rails/webpacker/blob/54c3ca9245e9ee330f8ca63b447c202290f7b624/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader

I ran into this same issue with another module I'm using. This fixed it!

**Comment by Sioomak** [comment]
Excluding quagga from babel-loader in webpack.mix.js fixed the `issue` for me:


![Screenshot (11)](https://user-images.githubusercontent.com/66186918/111806522-742e3280-88a8-11eb-8c9c-32f8cc5da0f4.png)
