### ISSUE TITLE
Dashes are not scale properly on a non-integer zoom level

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#3427]
line-width = 20px, line-dasharray = [0, 2]

Zoom = 17:
![image](https://cloud.githubusercontent.com/assets/1522494/19592039/9f0f5b60-97ac-11e6-8bac-e6b3feb26ecb.png)

Zoom = 17.5:
![image](https://cloud.githubusercontent.com/assets/1522494/19592052/aa7521ce-97ac-11e6-833f-e2d0922e143d.png)

Zoom = 17.9:
![image](https://cloud.githubusercontent.com/assets/1522494/19592091/cc1e88ce-97ac-11e6-9e0e-045c99de02ad.png)

Zoom = 18:
![image](https://cloud.githubusercontent.com/assets/1522494/19592112/dd5bdf42-97ac-11e6-956a-936a6d56637d.png)

**Comment by mourner** [comment]
I didn't notice this effect before. Can you try it on other GL JS releases and see if it was like that before or broke with a specific release?

**Comment by jingsam** [comment]
I tested this in Mapbox Studio, and I think this problem may relate to #2351

**Comment by mourner** [comment]
Oh, I think that's a special case when the dash is very short and wide. It renders like this due to the way we handle dash scaling, and is probably not something we can easily fix.

**Comment by jfirebaugh** [comment]
This is the intended behavior of the current implementation. To avoid it we either need an implementation that:

- increases the sizes of spaces but not dashes at fractional zoom levels
- resets dash size to an unscaled version when zooming finishes

Because we've previously spent quite a bit of time iterating behaviors before settling on the current behavior, I don't think revisiting this is a priority for the foreseeable future.
