### ISSUE TITLE
Add a example of using style-optimized vector tiles

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#3430]

**Comment by lucaswoj** [comment]
@mapsam Do you think it makes sense to add an example for this?

**Comment by mapsam** [comment]
Good question @lucaswoj - thanks for posting @jingsam! My first inclination is "no" since it's going to be almost exactly the same as the ["display a map"](https://www.mapbox.com/mapbox-gl-js/examples/) basic example and the map itself won't look any different, since you're only getting rid of features that _aren't_ styled. I _do_ think there should be an example for offline caches in the GL SDKs, though.

Follow-up question: is there a better way to document this in the API docs?

**Comment by jfirebaugh** [comment]
Is there any reason why GL JS shouldn't use style-optimized VTs (for Mapbox sources) by default?

**Comment by mapsam** [comment]
> Is there any reason why GL JS shouldn't use style-optimized VTs (for Mapbox sources) by default?

Yes, I think it would be confusing for users dynamically updating their styles for layers/features that were cut out during the initial request - they don't exist so nothing happens against expectations. If style-optimization is turned on by default, every user will need to see this documentation before they start editing their styles after loading tiles, and turn it off.

**Comment by lucaswoj** [comment]
👍 Sounds like there are no next actions in this issue.

@jingsam if your original question was "how much faster are style-optimized vector tiles?" the answer depends on the style you're using and your network speed.
