### ISSUE TITLE
symbol-features-in pitched-screen query test is failing

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3447]
https://github.com/mapbox/mapbox-gl-test-suite/tree/master/query-tests/symbol-features-in/pitched-screen

cc @brunoabinader

**Comment by brunoabinader** [comment]
It turns out the generated expectations from -native are wrong. I've updated the [test suite](https://github.com/mapbox/mapbox-gl-test-suite/commit/2817eedfe76f38b63bb77cb58c3b691e47169a92) (https://github.com/mapbox/mapbox-gl-js/commit/baa2b8dc092d5c5fb35d954fbe83f4970ef72ac7) to reflect this.

Related -native issue: https://github.com/mapbox/mapbox-gl-native/issues/6817
