### ISSUE TITLE
Extruding with very large heights causes "height wrapping"

### ISSUE THREAD

**Issue by steinbachr** [mapbox/mapbox-gl-js#3464]
When using extrusions with very large heights, a sort of wrapping can occur as demonstrated in the below snapshots:

![heights_1](https://cloud.githubusercontent.com/assets/1424445/19708173/aadf364a-9aea-11e6-991c-fa24c6febc14.png)

for section `G`, the heights of the row polygons - in ascending order - are as follows:

```
[13225.54,
 25253.665,
 37281.79,
 49309.915,
 61338.04,
 73366.17,
 85394.295,
 97422.42,
 109450.545,
 121478.675,
 133506.8,
 145534.925,
 157563.05,
 169591.18,
 181619.305,
 193647.43,
 205675.555,
 217703.68,
 229731.81,
 241759.935]
```

when decreasing the heights by a constant factor of 2, the result looks as follows:

![heights_2](https://cloud.githubusercontent.com/assets/1424445/19708332/c1b2a22a-9aeb-11e6-8a8b-e9e8130f04d1.png)

with the following heights for the polygons of section G:

```
[7225.54,
 13253.665,
 19281.79,
 25309.915,
 31338.04,
 37366.17,
 43394.295,
 49422.42,
 55450.545,
 61478.675,
 67506.8,
 73534.925,
 79563.05,
 85591.18,
 91619.305,
 97647.43,
 103675.555,
 109703.68,
 115731.81,
 121759.935]
```

and finally, when reducing heights by a factor of 12, we see "height wrapping" cease (but we lose nearly all sense of height hierarchy:

![heights_3](https://cloud.githubusercontent.com/assets/1424445/19708506/041a3410-9aed-11e6-8c98-d3f80a2d55c4.png)

with heights for section G polygons of:

```
[2225.54,
 3253.665,
 4281.79,
 5309.915,
 6338.04,
 7366.17,
 8394.295,
 9422.42,
 10450.545,
 11478.675,
 12506.8,
 13534.925,
 14563.05,
 15591.18,
 16619.305,
 17647.43,
 18675.555,
 19703.68,
 20731.81,
 21759.935]
```

**mapbox-gl-js version**: v0.26.0

**Comment by lbud** [comment]
Thanks for your report @steinbachr. Can you provide a minimal JSFiddle or JSBin test case to reproduce this?

**Comment by steinbachr** [comment]
sure, see JSFiddle here:

https://jsfiddle.net/0at9zcnm/3/

**Comment by lbud** [comment]
@steinbachr this is a limitation of the current vertex attribute size: extrusion types' height and max-height attributes both use `Uint16` types, so they'll overflow after 65535. Increasing these attribute sizes would have performance costs that would not be worthwhile as most extrusion use cases we've seen so far don't require heights that large, especially after the recent switch to using meters as units (issue https://github.com/mapbox/mapbox-gl-js/issues/3385, PR https://github.com/mapbox/mapbox-gl-js/pull/3509) 
(65535-meter extrusion in Manhattan = 
![image](https://cloud.githubusercontent.com/assets/3170312/19942718/ec9e019e-a0f1-11e6-8800-afecdb5e97d6.png) 😳)

Your use case is very cool! ✨ but in order to make use of extrusions like this you'd need to try to scale down your maps…

Glad you brought this to our attention though, we'll be adding validation to catch number overflows like these.

**Comment by steinbachr** [comment]
thanks for looking into it @lbud!
