### ISSUE TITLE
npm-shrinkwrap not in sync

### ISSUE THREAD

**Issue by x9xjdzz9** [mapbox/mapbox-gl-js#3481]
When I use npm and webpack to deploy mapbox-gl v0.26.0, it is not deploying the correct version of the project. The function that I notice is different is _remove() in style.js. It looks like it may be related to  npm-shrinkwrap.json. Oddly, the version of style.js that is being deployed by webpack is not the same as the one that is checked in to 0.25.1 or any other committed version.

**Comment by jfirebaugh** [comment]
Can you please try to pinpoint this to a more concrete issue? "not deploying the correct version of the project" isn't really specific enough for us to be able to help.

Note that since 0.26.0 we've removed npm-shrinkwrap.json. You might want to try the current master branch, or 0.27.0, which will be released soon, probably today or early next week.

**Comment by x9xjdzz9** [comment]
When using the v0.26.0 with npm/webpack, Map.remove() throws an exception. In the incorrect version of the code that is deployed, the dispatcher is removed before the cache is cleaned up. But the cache tries to use the dispatcher.

**Comment by x9xjdzz9** [comment]
I'll retry with 0.27.0 as soon as it's released.

**Comment by mourner** [comment]
Closing as not actionable.
