### ISSUE TITLE
window.URL.createObjectURL Error

### ISSUE THREAD

**Issue by jeromecn** [mapbox/mapbox-gl-js#3530]
https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/browser/web_worker.js

`'use strict';

const WebWorkify = require('webworkify');
const window = require('../window');
const workerURL = **window.URL.createObjectURL(new WebWorkify(require('../../source/worker'), {bare: true}));**

module.exports = function () {
    return new window.Worker(workerURL);
};`

# fix:
const workerURL = **new WebWorkify(require('../../source/worker'), {bare: true});** ?

**Comment by jfirebaugh** [comment]
That wouldn't be an appropriate change as it would break other code.

If you'd like to report an issue, please use the template provided, filling in the requested details like mapbox-gl-js version, steps to trigger the behavior, and the error message you received. I'm closing this issue because it doesn't provide the necessary information.
