### ISSUE TITLE
Add map.moveLayer method for changing layer z-order

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3576]
This is a small piece of #1989 which will address one of the most common use cases. 

If a layer is removed and an identical layer is added immediately we should re-use the layer resources to avoid unnecessary computation and loading time.

**Comment by mourner** [comment]
Per discussion in chat, instead of making remove/addLayer a noop (which needs to cover many edge cases and will still have to do some unnecessary work), we'll add a `map.moveLayer(id, before)` method that will update the layer's order (with an instant change if it's a non-symbol layer, and redoing placement if symbol).

**Comment by anandthakker** [comment]
Is this done as of #3584 ?

**Comment by jfirebaugh** [comment]
Yep.
