### ISSUE TITLE
Label collisions

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3599]
Seen on the debug page. Note the tile boundary:

![image](https://cloud.githubusercontent.com/assets/98601/20231779/0c39eba2-a819-11e6-86b4-4e69d4bf2901.png)

I checked back as far as v0.25.0 and the collision was present in that version.

**Comment by ansis** [comment]
I haven't checked, but here's what I'm guessing is happening.

- the rendered museum points are in the top tile (and also the bottom tile)
- the line label is only in the bottom tile
- the point labels are below the line label in the style so they don't collide it out in the bottom tile
- the top tile is not able to predict the location of the line label in the bottom tile, so he museum labels aren't collided out
- symbol-avoid-edges is false (the default) for the museum layer so it can place labels across the edge

This is the expected behavior of the implementation. **The fastest way to fix this is by making the style use `symbol-avoid-edges: true` for the museum layer.**

### improving our implementation so this doesn't happen

Some history (from https://github.com/mapbox/mapbox-gl-native/issues/6670#issuecomment-256816692):

> symbol-avoid-edges prevents the symbols from crossing any tile boundary. The reasons behind it are complicated. It exists because of some limitations of our tiled collision detection.
>
> These same limitations existed in Mapnik before it. CartoCSS had -avoid-edges properties which worked the same way. We calculate placement separately for each tile. In order to support cross-tile labels we need both tiles to be able to make the same choice without any communication between them. A tile needs to know where the neighbouring tile would place labels close to the tile edge. We include features in a tile that are outside it's strict boundaries so that it can make a good guess what it's neighbours are doing. There are some cases where these guesses aren't good enough.
>
> We can't predict line labels because they could be anywhere along the line. Any point labels placed after line labels are contaminated by the chaos in the line labels so we can't predict their position either. symbol-avoid-edges should be used to prevent these point labels from crossing tile edges.
>
> OK, why don't we just automatically set this for any point labels below a line label layer? My understanding (I might be wrong) is that there are cases where we want to risk the chaos in exchange for having cross-tile point labels that are placed after line labels. We might have a rare line label layer somewhere early on and we don't want that to affect all subsequent point layers.
>
> Another case where it might be used is if the style makes the text bigger than the buffer safely supports.

The most immediately actionable fix is to implement the "all layers below any line symbol layer have `symbol-avoid-edges: true`. We should double check and think hard about whether we can make this non-optional. If there are cases where this is too aggressive, we should think about adding an `auto` property that is the default but lets users opt out of it.

We should also think about ways we could make the cross-tile placement prediction work for lines.

Or if we don't care about the quality in api-gl fallback tiles then we could do some global label placement.

**Comment by ChrisLoer** [comment]
Fixed in #5150.
