### ISSUE TITLE
"null" value fill-extrusion-color 

### ISSUE THREAD

**Issue by mapsam** [mapbox/mapbox-gl-js#3601]
An exception is thrown when the [value for `fill-extrusion-color` is null](https://github.com/mapbox/mapbox-gl-js/blob/f5734e1ab4607bc8b544f4c4d75cf1b71c154609/js/style/style_layer/fill_extrusion_style_layer.js#L10). Let's investigate if we are improperly returning a default, or if there is no default set in the style spec.

This can be reproduced on the [indoor floor plan example page](https://www.mapbox.com/mapbox-gl-js/example/3d-extrusion-floorplan/).

Hotfix in place at 868adb7 

cc @lucaswoj @lbud

**Comment by lbud** [comment]
@mapsam can you produce a minimal example that reproduces this or provide more guidance as to how to do so? Took a quick stab at it (used the streets style, used `addLayer` to add a fill-extrusion type layer) and providing no fill-extrusion-color resulted in black extrusions (the [default value](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v8.json#L1748)); providing a deliberate `null` value threw the correct validation error: 
> `layers.building.paint.fill-extrusion-color: color expected, null found`

(This after I commented out the hotfix you mentioned.)

**Comment by jfirebaugh** [comment]
Ping @mapsam.

**Comment by lucaswoj** [comment]
I can reproduce this bug by

 1) checking out 087ae1e9e921ccb99f7f856f66522273d961fdee
 2) running `npm install`
 3) running `npm run start-docs`
 4) navigating to http://127.0.0.1:4000/mapbox-gl-js/example/3d-extrusion-floorplan/
 5) observing an error in the console 

```
Uncaught TypeError: Cannot set property '3' of undefined (fill_extrusion_style_layer.js:11)
    at e.getPaintValue (http://127.0.0.1:4000/mapbox-gl-js/dist/mapbox-gl.js:128:423)
    at e.i.recalculate (http://127.0.0.1:4000/mapbox-gl-js/dist/mapbox-gl.js:124:4411)
    at t._recalculate (http://127.0.0.1:4000/mapbox-gl-js/dist/mapbox-gl.js:120:4304)
    at e._render (http://127.0.0.1:4000/mapbox-gl-js/dist/mapbox-gl.js:204:10997)
```

**Comment by lbud** [comment]
Investigated this today. In fact, I think the hotfix @mapsam added at https://github.com/mapbox/mapbox-gl-js/commit/868adb72163757a89756d7b1d05debfebe421610 is good and right: 

the intention of setting `fill-extrusion-color[3] = 1` is to ignore alpha values set by `rgba` values (since fill-extrusion-opacity is per layer, we render all buildings offscreen at full opacity, then render the full offscreen texture back to the screen using the layer's opacity value; we set non-1 alpha channels to 1 here rather than simply ignoring alpha in the shader so that we don't produce unexpected colors due to premultiplication). So if we have an undefined fill-extrusion-color, nobody's trying to mess with the alpha channel anyway 😅

**Comment by mapsam** [comment]
Cool - thanks @lbud!
