### ISSUE TITLE
Add a "pin GL JS version" property to "plugins.json"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3642]
We made some breaking changes to the `Control` interface with https://github.com/mapbox/mapbox-gl-js/pull/3497. It's natural and healthy to make breaking changes to APIs in a pre-v1.0 product. Unfortunately these changes caused all of our plugin example pages to break. 

I propose that we add some sort of "pin GL JS version" property to plugins in "plugins.json". This would allow us to 1) document when there is a version requirement and 2) keep our example pages running while we fix version-specific bugs.

When would the "pin GL JS version" property be updated? I envision us manually testing a few high profile plugins during the release process and pinning them as needed. Low profile plugins can be pinned as soon as we are made aware of a problem. https://github.com/mapbox/mapbox-gl-js/issues/2240 will mitigate the problem somewhat. 3rd party plugin authors are empowered to create PRs to update their pinned version if need be. 

cc @tmcw @mapsam @mollymerp @anandthakker @mcwhittemore

**Comment by tmcw** [comment]
The 0.27.0 breakage is pretty recent. I don't think we necessarily need to fix for exactly what happened ([obligatory svn article](https://m.signalvnoise.com/dont-scar-on-the-first-cut-e9afd256afdf#.rnaqmrxbb)).

Right now the lay of the land is:

* There are 3 plugins we have examples for, and we maintain all of them
* The 0.27 release reduced the API surface that plugins rely on
* That was the first release since the introduction of addControl that changed it
* It's likely that the addControl API will change once or twice before release, but probably not more than that

To put it another way: we can make sure that plugins are kept up-to-date, and it's now part of the releasing doc. We didn't in the very recent past, and part of that is my bad. But I don't want to turn that organizational failure into a point of friction, and I don't want to remove the imperative that we keep plugins up to date: which is a convenient property of the current system.

I'm open to the system changing, and can see a situation where change will be unavoidable - when we start showing examples for third party plugins.

But at this point in time, I think adding the ability for plugins to 'pin' versions will remove an incentive to keep them up to date, complicate the build process further, and add a new kink to the simplicity of using examples: since, as we've found from years of writing them and reading support issues, people _will_ copy and paste arbitrary sections from one example to another. Having examples relying on different mapbox-gl-js versions will require either a big banner, which will be inevitably ignored, or it will increase support load and confusion.

**Comment by lucaswoj** [comment]
With the addition of manual testing during releases (😬) we can ice this for the time being and revisit if it continues to be a problem. I hope the smalified API surface reduces future bugs. 

Thank you for sharing your experience & thoughts @tmcw.
