### ISSUE TITLE
Property function not working when reference field has string values

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#3717]
Here's a JSBin (do you call that a "bin"?) illustrating: http://jsbin.com/bikeqatomo/edit?html,output

When the country name layer is given this property function value for `text-color` ...

```js
  {
    property: 'name_en',
    base: 1,
    stops: [
      ['Mexico', 'red'],
      ['Brazil', 'pink'],
      ['xxx', 'blue']
    ]
  }
```

... *all* of the country names are `'blue'`, even though the function specifically names Mexico and Brazil and `'xxx'` is not a real country name.

It seems that the last property output value in the list of stops is always used.

cc @jfirebaugh

**Comment by jfirebaugh** [comment]
Confirmed. It works if you explicitly specify `"type": "categorical"`, but that's supposed to be the default when the stop domain is a string.

@lucaswoj It looks like #3384 doesn't actually do what it's supposed to. [Here](https://github.com/mapbox/mapbox-gl-function/blob/41c6724e2bbd7bd1eb5991451bbf118b7d02b525/index.js#L22), `defaultType` is always present, because mapbox-gl-js uses [these functions, which pass `'exponential'` / `'interval'`](https://github.com/mapbox/mapbox-gl-function/blob/41c6724e2bbd7bd1eb5991451bbf118b7d02b525/index.js#L201-L207)

**Comment by davidtheclark** [comment]
> It works if you explicitly specify "type": "categorical"

@jfirebaugh I'm not seeing that — but I do see a change. In the JSBin if I add `"type": "categorical"` to the value, all country names render as *red* (the first stop's output value) rather than blue.

**Comment by jfirebaugh** [comment]
Good point -- that's due to the fact that `text-color` doesn't actually support data-driven properties yet (#2730). (Related: https://github.com/mapbox/mapbox-gl-style-spec/issues/592.)

**Comment by davidtheclark** [comment]
Thanks @jfirebaugh. Here's a new JSBin that uses `fill-color`, and shows the behavior: http://jsbin.com/xovojupufa/edit?html,output

**Comment by jfirebaugh** [comment]
That shows the expected behavior, right?

**Comment by davidtheclark** [comment]
@jfirebaugh Yes, sorry for lack of clarity: That bin shows what you confirmed ^^, that `"type": "categorical"` is necessary for the property function to work correctly. The buggy behavior when it's missing is different here than in the first (bad) example (bad because `text-color` wasn't supported anyway), but still buggy.

**Comment by jfirebaugh** [comment]
Great. I think we're on the same page about what the issue is.

However, I'd like to propose we consider simply reverting #3384 / https://github.com/mapbox/mapbox-gl-function/issues/19 instead of getting it working. I don't think the the complexity implicit "categorical" functions add to the implementation and mental model is justified. I think users are just as likely to be surprised that a stop such as `["string", 0]` triggers different function behavior than `[0, 0]` as they are to find that this feature "just works". Explicit is better than implicit. And in any case, most users will be exposed to a Studio UI where the function type will likely need to be an explicit UI control in any case.

If we revert #3384 / https://github.com/mapbox/mapbox-gl-function/issues/19, then in the case where a user forgets `"type": "categorical"`, the default type of "exponential" or "interval" applies, and a string stop domain value will produce a validation error.

**Comment by davidtheclark** [comment]
I'm a little confused here, because the Studio UI does not currently allow users to manually select function `type` for zoom functions, so I had assumed that type was just determined by the property. Could someone in @mapbox/appbox chime in about the history here, and if you have opinions about exposing function selection to users for DDS?

**Comment by jfirebaugh** [comment]
> type was just determined by the property

Yes, for most of the history of the style specification, this was the case: "interpolated" properties used "exponential" functions, and "piecewise-constant" functions used "interval" functions. We didn't use the names "exponential" and "interval" back then, but the behavior was the same as today's functions of those types.

With the advent of data-driven properties, we had many discussions about the best way to extend function types. Over time, we added the following extensions:

* The ability for "interpolated" properties to opt-in to "interval" function behavior, by explicitly specifying `"type": "interval"`.
* The "categorical" function type.
* The "identity" function type.

These extensions are usually lumped into the "data-driven styling" category (although strictly speaking the first bullet is independent of DDS). And because we haven't yet implemented support for DDS in Native or Studio, by association we haven't implemented support for these new function types either.

There are a few reasons why I say that Studio will likely want to offer function type selection up front:

* To allow users to opt in to "interval" function behavior for properties that would otherwise use "exponential".
* For a function with numeric stop domain values, it can't really be deduced whether those values represent sample points in a continuous domain, or a set of enumerated constant values -- the user needs to explicitly indicate whether a "categorical", "exponential", or "interval" type is desired.
* A UI that first asks for the desired type, then presents subsequent UI that's tailored for that particular type, is likely to be more effective and easier to use than a generic UI that's not type-constrained in any way. For example, the former can provide better guidance in selecting appropriate properties, stricter validation of the stop types, and a streamlined UI that omits stops entirely in the case where the "identity" type is selected.
