### ISSUE TITLE
mapbox-gl.js missing from dist/ folder

### ISSUE THREAD

**Issue by benjaminhon** [mapbox/mapbox-gl-js#3747]
i noticed that mapbox-gl.js is missing from the dist/ folder when i tried to include it in my script tags

**Comment by jfirebaugh** [comment]
Hi @benjaminhon -- could you please use the provided issue template when submitting issues? It includes spaces for key information like the version of mapbox-gl-js that you're using, and exact steps to reproduce the issue. These are missing from your report, and we need them in order to diagnose the issue.

**Comment by mollymerp** [comment]
Please see: https://github.com/mapbox/mapbox-gl-js/blob/master/CONTRIBUTING.md#creating-a-standalone-build.

If that doesn't fix your issue please reopen this ticket.

**Comment by benjaminhon** [comment]
hi, 
I'm looking at (#3473)

```
/dist
 mapbox-gl-draw.css
 /svg
```

but there is no mapbox-gl-draw.js included in the dist folder. Was this intentional, and we have to build it ourselves?

**Comment by lucaswoj** [comment]
`mapbox-gl-draw` is a separate project. You can navigate to the repo for that project here: https://github.com/mapbox/mapbox-gl-draw/

**Comment by benjaminhon** [comment]
sorry i mean 
```
/dist
 mapbox-gl.css
 /svg
```

as you can see there is no /dist/mapbox-gl-draw.js

it has to be built
