### ISSUE TITLE
Unable to base a layer off a layer that's present in the style

### ISSUE THREAD

**Issue by nicoabie** [mapbox/mapbox-gl-js#3749]
**mapbox-gl-js version**: 0.27.0

### Steps to Trigger Behavior

 1. have a layer defined in the style
 2. Create a new source for the layer
 3. Get the layer
 4. Add a layer based off the layer defined in the style

### Expected Behavior
The layer works

### Actual Behavior
The layer does not works from version 0.27.0

@jfirebaugh #3698 
[jsbin example](https://jsbin.com/zugotug/11/edit?js,console,output)

**Comment by mollymerp** [comment]
You have to delete the [`source-layer`](https://www.mapbox.com/mapbox-gl-style-spec/#layer-source-layer) attribute off the old layer for it to work because Vector Tile sources require the `source-layer` field because they support multiple layers, but `GeoJSONSource`s do not. 

https://jsbin.com/tubetofali/edit?js,console,output

**Comment by nicoabie** [comment]
@mollymerp you are a genius! many thanks :)
