### ISSUE TITLE
document world wrap behavior for DOM elements

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#3770]
While the map wraps around infinitely when panning in either direction, popups only show up on the "main" world. Unfortunately, it's hard to know which world is the main one. I would like to add [this code](https://github.com/mapbox/mapbox-gl-js/issues/2071#issuecomment-245990952) to the doc for `Marker` and `Popup` as well as in the examples that show interactions with markers and popups.

cc @jfirebaugh @lbud @lucaswoj @mollymerp

**Comment by jfirebaugh** [comment]
I'd like to fix #2071 instead, which would make the library behave as most people expect it to behave, and likely remove the need for documentation altogether.

**Comment by lyzidiamond** [comment]
@jfirebaugh what's the timeline on this? We should have something in place at least temporarily for the users who run into this issue -- this could easily be a saved reply, though.

**Comment by jfirebaugh** [comment]
There's not a set timeline. We'd need someone to jump in and do the work. My guess is it's an hour to a day of work.

**Comment by lucaswoj** [comment]
@lyzidiamond How commonly do you think users and developers will expect to be able to interact with multiple wrapped worlds at once at z0? With #2071, Asia on the left of the screenshot below, will not have any popups or markers. 

<img width="1680" alt="screen shot 2016-12-09 at 10 27 02 am" src="https://cloud.githubusercontent.com/assets/281306/21060354/c40b1eb6-bdfb-11e6-875f-3f06127b6faa.png">

**Comment by jjb867** [comment]
The snippet on #2071 works but is less than desirable imho since the map needs to instantly re-render and therefore a flash is created.

Would be nice to have an option to limit the map to 1 world instance or to show a given popup on all instances of the world.

**Comment by andrewharvey** [comment]
I feel it's okay for `Markers` to only appear once (so if you're zoomed out it doesn't duplicate DOM elements).

But even with #2071 implemented, I feel `Marker` will still need to dynamically move between world 0 and -1/1. If your map center is still in world 0, but parts of world -1 are visible, I think the `Marker` should render on world -1 so it's visible on the map.

**Comment by andrewharvey** [comment]
In https://github.com/andrewharvey/mapbox-gl-js/tree/draw-markers-in-other-worlds I've changed the behaviour for Markers and Popups to render in world -1 and world 1 when best.

Together with #2071 I think it address this issue (short of creating duplicate markers and popups which might lead to too many headaches for little gain).

This can be fixed without #2071 but https://github.com/andrewharvey/mapbox-gl-js/tree/draw-markers-in-other-worlds would need to be extended to move the Markers and Popups to worlds > 1 and < -1, which requires more code. Due to all the problems with non world 0 coordinates (eg Mapbox Geocoding API doesn't accept them) I feel #2071 should be done and we only move popup and markers between world -1, 0 and 1.

**Comment by jfirebaugh** [comment]
#4451 and #4452 have been merged, and marker and popup wrapping should now "just work". As always, let us know if you run into any issues.

Thanks to @andrewharvey for implementing this functionality!
