### ISSUE TITLE
Circle no longer runs on external contributor PRs

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#3802]
I noticed that since a few days ago, Circle is no longer running on external PR commits. Examples: #3783 #3781. This makes reviewing PRs much harder, so we should investigate what happened.

cc @lucaswoj @jfirebaugh

**Comment by lennerd** [comment]
I assume this is blocking for my PR right? Are there any schedules for the next release?

**Comment by mourner** [comment]
@lennerd don't worry about it, it's just an inconvenience on the maintainer side since we have to run the tests manually to verify that they pass. It's not blocking your PR.

**Comment by lucaswoj** [comment]
I was poking around in CircleCI recently in an attempt to resolve #3603 more elegantly. It's possible I triggered this regression. I will take a look today.

**Comment by mollymerp** [comment]
I was wondering about that... thanks @lucaswoj! 

@lennerd no finite schedule for the next release but we should have one out before the holidays 🎄. thanks again for your awesome contribution!

**Comment by lennerd** [comment]
Thank you for your awesome peace of software and services! We enjoy using it! :)

**Comment by lucaswoj** [comment]
This regression is due to a breaking change made by CircleCI in which forked PRs do not trigger builds by default. See https://discuss.circleci.com/t/pull-request-from-forked-repos-are-not-being-tested/8588/3

I have resolved the issue by enabling the "build forked pull requests" setting.

<img width="862" alt="screen shot 2016-12-15 at 2 43 17 pm" src="https://cloud.githubusercontent.com/assets/281306/21245019/280450a8-c2d5-11e6-920c-cc29f5083ecf.png">
