### ISSUE TITLE
contextmenu event not fired at first click in windows browsers

### ISSUE THREAD

**Issue by VladimirJarabica** [mapbox/mapbox-gl-js#3803]
**mapbox-gl-js version**: v0.21.0

I'm unable to catch "contextmenu" or rightclick event in windows browsers (tested chrome, edge, IE, FF). It is needed to click twice, and even after second click, lng lat coordinations are from the old event.
I have tried it in this simple example:
https://jsfiddle.net/6ctfssy9/1/

### Expected Behavior
Fire event at first right click

### Actual Behavior
Fires at second (that second click can be also left click)

**Comment by mollymerp** [comment]
Hi @VladimirJarabica,
Thank you for reporting this issue. Could you please upgrade to the most recent version (v0.28.0) and see if the issue persists?

**Comment by VladimirJarabica** [comment]
Hi @mollymerp,
I updated to v0.28.0 https://jsfiddle.net/6ctfssy9/4/
And sadly, problem is still there.

**Comment by lbud** [comment]
I was able to reproduce this in multiple browsers on Windows as well:

On Mac, the `contextmenu` event is fired on `mousedown`, so we're able to set [`contextMenuEvent` as expected](https://github.com/mapbox/mapbox-gl-js/blob/41cdecdb461149df54e0c81f97ec9d9fa0c3b6b7/js/ui/bind_handlers.js#L18) and we fire the event on mouseup.

On Windows, the `contextmenu` event is fired _after_ the `mouseup` event, so as implemented here, on the first right click `contextMenuEvent` is still null, and then `contextMenuEvent` is set _after_ the click and not unset before the next right click, so the second right click event uses event data from the previous one. (In practice this means also that, since the `contextMenuEvent` is set to null at the end of the `onMouseUp` handler, right clicks will _only_ be successful after another right click — not after a regular click event, even if it was previously successful on the same map instance.)

Working on a fix.
