### ISSUE TITLE
queryRenderedFeatures returns invisible features when opacity is 0

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#3835]
**mapbox-gl-js version**: 0.28.0

### demo
http://jsbin.com/vohokivudu/edit?html,output
1. Move the cursor over the US and it changes to a pointer, meaning queryRenderedFeatures returned the features even though they aren't visible since fill-opacity is set to 0.

### Steps to Trigger Behavior

 1. Add a layer with an opacity paint property set to 0 so it is invisible on the map.
 2. queryRenderedFeatures over that feature

### Expected Behavior

As per the documentation "Only visible features are returned."

### Actual Behavior

The indivisible features are returned.

**Comment by jfirebaugh** [comment]
This is the expected behavior; I've made the documentation more precise in cc097fb06dd132a274f7fe7397c8891bf5c251e6.

**Comment by andrewharvey** [comment]
> This is the expected behavior; I've made the documentation more precise in 708c628.

Thanks for the clarification. The documentation is much clearer now!

**Comment by strech345** [comment]
It would be nice to only query visible features (remove features with opacity=0 or alpha = 0). Maybe by a filter property?
I need this because i hide layers at on zoom in and need to select the first (top) layer. I now select layers which are hidden by fill-opacity=0 (dependends on zoom).

**Comment by fvanwijk** [comment]
I think the current behaviour is ok and the docs help to understand why features with opacity 0 are still being returned.
However, I still don't have a solution in the case that a feature has opacity 0 and `queryRenderedFeatures` still results the feature (eg. in case of click on map).

Setting `visibity` is not always an option because it isn't a data-driven property and it can't be interpolated/transitioned.

I want to filter out the feature, eg. by having a `computedProperties` object on the returned feature so that I can read the **computed** layout/paint properties, based on the map state, layer settings and the data/state that represents the feature.
Suppose that the opacity interpolates linearly from 0 to 1 between zoom level 18 and 19, the `opacity` value is 0.5 on zoom 18.5. Then I can determine wheter of not to filter out the feature. 

The current workaround is to *replicate* the paint expression in JS code using `feature.properties`, `feature.state` and `map.getZoom()`, which easily could lead to bugs.
