### ISSUE TITLE
Outline for lines (styling)

### ISSUE THREAD

**Issue by dannybloe** [mapbox/mapbox-gl-js#3847]
It would be nice to have a style property for lines like:
```
line-outline-color
line-outline-opacity
```
This removes the need for having to create a separate layer in order to give my geojson geometries a white outline. Guess that improves performance as you only have one geometry instead of two.

**Comment by mollymerp** [comment]
Hi @dannybloe thanks for submitting this feature request! 

Have you tried using the [`line-gap-width`](https://www.mapbox.com/mapbox-gl-style-spec/#paint-line-gap-width) property to accomplish this? Its not exactly what you're suggesting because you still need an extra layer for the line casings, but it does prevent you from having to generate additional geometries.

**Comment by dannybloe** [comment]
Of course but indeed you need an extra layer. Of course you share the same data source but still. An extra style would be a lot easier/faster.

**Comment by jfirebaugh** [comment]
We may introduce this for fill layers (https://github.com/mapbox/mapbox-gl-style-spec/issues/223), but don't have plans to do so for line layers. Using two layers is a reasonable balance between efficiency and keeping the style specification simple.

**Comment by bergkvist** [comment]
### I want to be able to click on a line and visually "select" it using a border

#### Approach 1: Use id to set the feature-state, and create a new layer where the selected line is filtered
The idea here is to use line-gap-width and a different color with some opacity to represent the outline/border.
```js
// separate layer for drawing the borders (using the same source)
{ ..., filter: ['boolean', ['feature-state', 'selected'], false] }

// => Error: layers[1].filter: "feature-state" data expressions are not supported with filters.
```

#### Approach 2: Create a new source, and make sure it contains only the selected feature, but with different styling
```js
map.addSource('selected', { type: 'geojson', data: feature })

// => Uncaught Error: There is already a source with this ID
```

Okay, so what if I clone the feature but omit the id then?
```js
import { omit } from 'ramda'
// ...
const clonedFeature = omit(['id'], feature)
map.addSource('selected', { type: 'geojson', data: clonedFeature })

// => Error: The feature id parameter must be provided and non-negative.
```


@jfirebaugh Line borders are available in OpenLayers. Should it not be simple for people to migrate from OpenLayers to Mapbox GL? Mapbox GL right now tries to be "simple" while also being "inflexible".

This is not a combination that works well if you want to capture market shares from competitors. Since replicating behaviour from competitors is either extremely cumbersome/ugly in code.

Also, in my use case, it seems that I'm either not understanding how to do this, or it is not possible (in a clean way) to use a separate layer like you suggest.

**Comment by shaunakv1** [comment]
In my usecase where am rendering hurricane segments, loading a while new vector layer to highlight selected storm is pretty expensive.  Essentially when if we had `line-outline-color` and 
`line-outline-opacity` I can get away with just rendering all segments, and then showing a highlight around the entire track. Without that, I now have to maintain and load a whole new tracks layer.

**Comment by dazzatron** [comment]
This is how I solved this issue, it seems to do the job most of the time:

 https://codepen.io/joedazza/pen/QWwKRKP

**Comment by Mina-Amir** [comment]
> This is how I solved this issue, it seems to do the job most of the time:
> 
> https://codepen.io/joedazza/pen/QWwKRKP

This is a good solution but if you have overlapping lines then it wouldn't work since the layer that is used for showing borders would disappear behind the lines layer in the overlapping sections

and `line-outline-color` is good to have for this particular case to show contrast between different lines intersecting with each other

**Comment by mack-guardian** [comment]
seconding @Mina-Amir 

> This is how I solved this issue, it seems to do the job most of the time:
> https://codepen.io/joedazza/pen/QWwKRKP

This case explicitly also does not work with a line-dasharry, which is needed to highlight contrast of black lines against satellite imagery

**Comment by alexwohlbruck** [comment]
How does adding one, very common and useful property make the style specification "not simple"? This should be added, helps create contrast against the rest of the map features for things such as transit maps:
https://www.transit.land/map#12.54/40.73911/-73.98507
![Screenshot 2023-11-21 at 1 50 05 PM](https://github.com/mapbox/mapbox-gl-js/assets/10440826/2ba800b1-af14-447c-8cf6-e3451ce63e84)

**Comment by bhambrah-asbuilt** [comment]
> How does adding one, very common and useful property make the style specification "not simple"? This should be added, helps create contrast against the rest of the map features for things such as transit maps: https://www.transit.land/map#12.54/40.73911/-73.98507 ![Screenshot 2023-11-21 at 1 50 05 PM](https://github.com/mapbox/mapbox-gl-js/assets/10440826/2ba800b1-af14-447c-8cf6-e3451ce63e84)

exactly. are there any plans for this to be added in the future?

**Comment by cmdalbem** [comment]
This is clearly something that people still want, and the workarounds don't work for some cases. Can we reopen the issue and reconsider?
