### ISSUE TITLE
Non EPSG:3857 raster tiles

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#3884]
I have come across a few instances where raster imagery is being served using ArcGIS server in a non EPSG:3857 spatial reference (usually it is a local SRS for a particular country or region, and they are insistent on using it). 

I can't see a way to display these in mapbox-gl without re-projecting the whole image tile set in EPSG:3857 which would mean duplicating the entire tileset. This means mapbox-gl isn't really an option.

I think Leaflet may have a plugin to deal with this issue (https://esri.github.io/esri-leaflet/api-reference/layers/image-map-layer.html). I also saw this fork which aims to incorporate this functionality: https://github.com/maphubs/mapbox-gl-js. However, I think there is still an issue as these tile formats can have completely different zoom levels which I don't think this solution accounts for.

For smaller datasets it is practical to re-project into EPSG:3857 but for large datasets such as raster imagery it can create a lot of problems, so I wondered if this functionality could be incorporated?

**Comment by tmcw** [comment]
Hi,

Thanks for the suggestion! We're already tracking this request in an existing ticket: #3184 - let's keep the discussion there.

To summarize the linked ticket: there's some interest in non-mercator projection support, but it isn't highly prioritized on the Mapbox team's schedule because it isn't part of our main usecases. That said, we'd certainly be open to a pull request implementing or starting the functionality.

- Tom
