### ISSUE TITLE
[IE11] compact attribution not visible in IE11

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#3945]
Same issue as https://github.com/mapbox/mapbox.js/issues/1086 and is caused by an [IE bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3346391/) where descendants an invisible element are also made to be invisible 😞

**Comment by mapcarta** [comment]
This is a legal matter because attribution isn't being displayed at all to any Internet Explorer users, whenever using the compact attribution control. Currently (in September 2018) 9% of our Mapbox GL JS users use Internet Explorer.

There is a simple fix in using a normal element for the icon instead of the ::after pseudo element. Due to a bug, child pseudo elements of a parent with hidden visibility will always be invisible in Internet Explorer even if their visibility is set to visible.

I've found a CSS solution that overrides the default Mapbox style sheet. It seems to work on all browsers and devices.

.mapboxgl-map .mapboxgl-ctrl-attrib.mapboxgl-compact {padding:0; visibility:visible;}
.mapboxgl-map .mapboxgl-ctrl-attrib.mapboxgl-compact:hover {padding:2px 24px 2px 0;}
.mapboxgl-compact > a {display:none;}
.mapboxgl-compact:hover > a {display:inline;}

**Comment by mapcarta** [comment]
This is a legal matter because attribution isn't being displayed at all to any Internet Explorer users, whenever using the compact attribution control. Currently (September 2018) fully 9% of our Mapbox GL JS maps loads use Internet Explorer.

There is a simple fix in using a normal element for the icon instead of the ::after pseudo element. Due to a bug, child pseudo elements of a parent with hidden visibility will always be invisible in Internet Explorer even if their visibility is set to visible.

I've found a CSS solution that overrides the default Mapbox style sheet. It seems to work on all browsers and devices.

.mapboxgl-map .mapboxgl-ctrl-attrib.mapboxgl-compact {padding:0; visibility:visible;}
.mapboxgl-map .mapboxgl-ctrl-attrib.mapboxgl-compact:hover {padding:2px 24px 2px 0;}
.mapboxgl-compact > a {display:none;}
.mapboxgl-compact:hover > a {display:inline;}
