### ISSUE TITLE
Smart Position Labels to show More

### ISSUE THREAD

**Issue by natew** [mapbox/mapbox-gl-js#3956]
## Motivation

![image](https://cloud.githubusercontent.com/assets/12100/21869977/0294cb1e-d80f-11e6-8213-aa54da4b1542.png)

In this image, we have labels for every point. Notice the point without the label (theres another one near Shane Battier).

Ideally this would show as far zoomed out as this:

![image](https://cloud.githubusercontent.com/assets/12100/21869998/1de5d7dc-d80f-11e6-854a-615d34668161.png)

Because there is definitely "room" for it. But instead we have to zoom in until you don't see any other points.

I do understand this is an interesting use case. Perhaps there are other label libraries that already exist have have this ability?

## Design Alternatives

New property for label layer styles:

- `offset-padding`: `x: number`

This would tell mapbox that you are "ok" with this label being offset `x` amount in order to display it. So if we put in `20`, that would allow the other point's label to "shift" 20 pixels to try and display.

## Design

This isn't perfect, because really you'd want *both* labels to move a bit, one showing above more and one below more. I could imagine a physics based system for this where things "push" around within bounds to try and fit, which may be better.

### Mock-Up

Pretty easy to imagine: shows more labels at any given zoom level, by shifting around within constraints.

### Implementation

Will research into some layer positioning stuff.

**Comment by mourner** [comment]
Thanks for the suggestion! Note that one of the constraints of the label collision/positioning algorithm is making sure labels don't pop in/out or jump randomly as you zoom smoothly (except between round zoom levels when new data is loaded). But designing the label shifting features so that labels transition between different offsets as you zoom can get very complicated, and there's problem of inconsistency between label offsets which can make reading the map confusing. But it's certainly exciting if we could find a suitable solution given these constraints.

**Comment by mourner** [comment]
Not pursuing this at the moment.
