### ISSUE TITLE
setFilter() changing the the icon of another layer

### ISSUE THREAD

**Issue by parry-drew** [mapbox/mapbox-gl-js#4019]
**mapbox-gl-js version**:v0.31.0

### Steps to Trigger Behavior

 1. load two layers with different data sources in Mapbox Studio.
 2. use mapbox-gl.js to set()Filter for the two layers in the same function.
 3. after the function runs the icon for one of the layers is changed to the icon of the second layer.

[Example Here](http://codepen.io/parry-drew/pen/GrWpaB?editors=0010)

### Expected Behavior
each layer will be filtered at the same time and retain their icons.

### Actual Behavior
the first layer's icon will change to the icon used by the second feature

**Comment by jfirebaugh** [comment]
Thanks for the test case. In your style, neither the `mta-subway-stations` nor `sir` layers have the `icon-allow-overlap` or `icon-ignore-placement` properties set, so no icons will be displayed that would collide with other icons. The default filter for the `sir` layer appears not to match any features, so when the map is initially loaded, you only see icons from the `mta-subway-stations` layer. Then when you change the filter, it allows features from the `sir` layer to become visible, and those icons take priority over the `mta-subway-stations` icons because the `sir` layer comes later in the layers. That's makes it appear that the icons are changing, but in fact features from one layer are disappearing and features from another layer are appearing.

If you want to be able to show icons from both layers at the same time, you'll need to adjust the locations so that they don't collide, or adjust the `icon-allow-overlap` or `icon-ignore-placement` properties.
