### ISSUE TITLE
Duplicate property value in paint stops fails silently

### ISSUE THREAD

**Issue by nicotejera** [mapbox/mapbox-gl-js#4042]
**mapbox-gl-js 0.31.0**:

### Steps to Trigger Behavior

 1. Create a property-based style with paint.stops = [[1, 'red'], [2, 'orange'], [2, 'yellow']]
 2. Render the map
 3.

### Expected Behavior
Throw an exception saying that two stops with the same value are not allowed (similar to not providing stops in ascending order)

### Actual Behavior
No exception thrown and the features simply don't render at all.

**Comment by jfirebaugh** [comment]
We tried to add this validation for zoom functions, but had to roll it back due to existing styles with duplicate stops: https://github.com/mapbox/mapbox-gl-style-spec/issues/414

That was for zoom functions specifically. It's possible we could increase the strictness for property functions without causing as much disruption.

**Comment by jfirebaugh** [comment]
See #4107.
