### ISSUE TITLE
Does mapbox supports Labelling of 3D features and filtering through text?

### ISSUE THREAD

**Issue by shahidnawazkhan** [mapbox/mapbox-gl-js#4059]
1. I actually want to make an application having 3D buildings labelled and can be searched by text but i don't know whether mapbox 3D supports searching labelling or not?

### Expected Answer
How they works, if there are?

**Comment by lbud** [comment]
Hi @shahidnawazkhan, 

Mapbox GL has no functionality by which to search rendered features by strings. In order to interact with the rendered map in any meaningful way, you'll need to know the coordinate of a feature — whether by a direct query method such as [`map.queryRenderedFeatures`](https://www.mapbox.com/mapbox-gl-js/api/#Map#queryRenderedFeatures), by a mapping of features to geographical coordinates in your application (you'll need to provide the mechanism to search through your data separately) or a [geocoding service](https://www.mapbox.com/geocoding/#for-developers). If you're looking to search through features on a smaller (geojson) scale, you may be interested in [this example](https://www.mapbox.com/mapbox-gl-js/example/query-similar-features/).

As to labelling 3D buildings, Mapbox GL JS currently supports rendering 3D polygons but not 3D/z-offset labels at the moment, so the labels would all be at 0 height.
