### ISSUE TITLE
Filtering features with in same layer and Labelling 3D Buildings

### ISSUE THREAD

**Issue by shahidnawazkhan** [mapbox/mapbox-gl-js#4065]
I recently asked a question but didn't get a proper reply or maybe my question was misunderstood. 
### What I want to do is?

 1. I want to search within the same sayer and want to filter features within that layer based on some attributes values. 
 2. I want to label 3D buildings such as their names appears along with them. 

### Important Note:
I look the mapbox filter by text example but doing exactly the same with 3D buildings is not working in my code

### What I want from you?

How these things will work in mapbox? Does these things avaialable in mapbox or not? if yes, how they works

**Comment by lucaswoj** [comment]
Thank you for using GL JS. Due to the large volume of issues we get and the relatively small size of our team, we are unable to provide support here on GitHub. I recommend asking this question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox-gl-js).

You may find this example helpful re 1: https://www.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/
