### ISSUE TITLE
Write an explanation and include a picture of each layer type in the style spec docs

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4123]
_From @tmcw on August 16, 2016 14:42_

Right now we don't explain layer types in narrative text. They have names and properties and one can infer from those, but we should be more explicit:

![2016-08-16 at 10 42 am](https://cloud.githubusercontent.com/assets/32314/17703013/2c3aa082-639e-11e6-9dbd-b6f4166261c3.png)

_Copied from original issue: mapbox/mapbox-gl-style-spec#479_

**Comment by lucaswoj** [comment]
_From @1ec5 on August 16, 2016 19:58_

This would be helpful for the Mapbox iOS SDK, since by design, symbols without documentation comments are completely excluded from documentation, as if they don’t exist.

**Comment by 1ec5** [comment]
The iOS and macOS SDKs are providing their own explanations for the time being:

https://github.com/mapbox/mapbox-gl-native/blob/01b557aeb34d51b2a63ee54ef38192f705d068e9/platform/darwin/scripts/style-spec-overrides-v8.json#L5-L22

These descriptions could be adapted for use with the style specification, although there’s quite a bit of iOS/macOS-specific terminology.

**Comment by domlet** [comment]
Gathered some images; couldn't resist.

 <img width=200 src="https://user-images.githubusercontent.com/6026447/96493619-0ea32080-11fa-11eb-8a00-c8a2c9ccad2f.jpg"> <img width=200 src="https://user-images.githubusercontent.com/6026447/96493623-0fd44d80-11fa-11eb-98a9-e83495886375.jpg"> <img width=200 src="https://user-images.githubusercontent.com/6026447/96493631-119e1100-11fa-11eb-9db3-b438d850a5eb.png">
 <img width=200 src="https://user-images.githubusercontent.com/6026447/96493633-119e1100-11fa-11eb-8368-37da7b3c6e6a.png"> <img width=200 src="https://user-images.githubusercontent.com/6026447/96493636-1236a780-11fa-11eb-8779-e4336bc45ada.png"> <img width=200 src="https://user-images.githubusercontent.com/6026447/96493638-12cf3e00-11fa-11eb-8a99-fc932e302275.png">
 <img width=200 src="https://user-images.githubusercontent.com/6026447/96493644-1367d480-11fa-11eb-8e35-1500966fe40b.png"> <img width=200 src="https://user-images.githubusercontent.com/6026447/96493648-14990180-11fa-11eb-9128-2c755016a108.png"> <img width=200 src="https://user-images.githubusercontent.com/6026447/96493649-14990180-11fa-11eb-8eee-13cfa190b466.png">

Possible places to add images:

1. https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/ (3x3 grid above the fold?)
2. https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#type (inline beside each explanation?)

**Comment by asheemmamoowala** [comment]
@domlet Yes!! Can we do it inline for each type in the docs.

For the background layer - a sample image with a pattern might. and non-background showing through could provide more clarity.

**Comment by domlet** [comment]
Thanks for the guidance @asheemmamoowala – I've tried shoehorning an image into this content [here](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#fill) (in the gl-js-docs repo to preview the change), but I'm unable to get hard-coded html to render:

<img src="https://user-images.githubusercontent.com/6026447/96654902-23aeab00-12f1-11eb-8cc6-756afddd34b0.jpg" width=400>

Perhaps @katydecorah can help with shoehorning hard-coded image elements into the style spec, but I think it might be better to add an additional optional property (like `doc-img`) to enable inline images as part of `style-spec` documentation, like so:

<img src="https://user-images.githubusercontent.com/6026447/96654055-450e9780-12ef-11eb-8b43-eb3e4517767f.png" width=400>

I think that the ability to add an image into the `style-spec` would be beneficial, since images make content (especially re: styling) easier to understand.

I don't think the `GL JS` docs need a parallel `doc-img` property for items like [`dragpanhandler`](https://docs.mapbox.com/mapbox-gl-js/api/handlers/#dragpanhandler) but it's worth considering since users traverse a lot between these docs sets, and consistent structure/formatting reduces UX friction.

Would love to know your thoughts, and  🍰 hbd!

**Comment by katydecorah** [comment]
@domlet Do you have a plan for where the images will be hosted? (For example, I would caution against using an image not hosted by Mapbox as the owner could delete it or, in the worst case scenario, replace it with something obscene.)

**Comment by domlet** [comment]
I'd love to host the images somewhere in `mapbox-gl-js` or `mapbox-gl-js-docs` – 
@katydecorah I thought I might reach out to you for advice on the architecture.

**Comment by asheemmamoowala** [comment]
@domlet The content could live in `https://github.com/mapbox/mapbox-gl-js-docs/blob/publisher-production/docs/pages/style-spec/layers.md` and images be a part of docs so that it's all in one place and easy to maintain?
