### ISSUE TITLE
Include Static API rendering in sdk-support properties

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4140]
_From @scothis on November 15, 2016 19:32_

In addition to our client side SDKs we also have a server side renderer with the [Mapbox Static API](https://www.mapbox.com/api-documentation/#static). Unlike our SDKs, the static support is not versioned, the property/feature is either supported or not.

```
"sdk-support": {
  "basic functionality": {
    "js": "0.10.0",
    "ios": "2.0.0",
    "android": "2.0.1",
    "static": true
  }
}
```

_Copied from original issue: mapbox/mapbox-gl-style-spec#569_

**Comment by 1ec5** [comment]
The Static API depends on node-mapbox-gl-native, which is versioned – we should include both in the compatibility tables.

**Comment by colleenmcginnis** [comment]
@chloekraw @riastrad is this something we want to do?

**Comment by riastrad** [comment]
@colleenmcginnis I’m torn because _technically_ our static api doesn’t have versions and we’re hopefully going to be doing a lot more work to make sure we’ve got a more frequent release cadence for node-gl-native. However, from a user perspective I can appreciate that it would be nice to have a `true`/`false` indication of whether or not api-gl supports something (in the event our release cadence doesn’t live up to our expectations). 

@mapbox/api-gl does anyone have strong opinions on this subject?

**Comment by chloekraw** [comment]
@colleenmcginnis thanks for the tag! I maintain the opinion I expressed previously:
- For the Static Tiles API (api-gl), the supported/unsupported question is a "yes/no" question rather than a "which version" question. I think adding api-gl into the table for every property on the style spec docs would be overkill, and actually make the info that customers need harder to find. What customers need is a list of properties that are currently a "no."
- Instead, I think the ideal solution is a separate section on the [Static API documentation page](https://docs.mapbox.com/api/maps/#static-tiles) that lists the style-spec properties which are currently not supported. This hopefully short list will allow customers to efficiently identify properties that won't work, and to know that everything else does.
- If there's no good way to automate the ideal solution, then I think a note in the Static API documentation that says: "The Static Tiles API currently supports all properties listed in the [Mapbox Style Specification documentation](https://docs.mapbox.com/mapbox-gl-js/style-spec/) as available in version `X.Y` of the Maps SDK for Android. All properties added after this version are not yet supported in the API." would suffice to provide a guideline for customers when perusing the style-spec docs. The version number can be auto-updated with every mbgl upgrade.
- On a lesser note:
  - The Static Tiles API is not an SDK, so technically speaking, its inclusion would require renaming the "SDK Support" section to a broader name.
  - I think adding a 5th column to the sdk support section of the style-spec docs would lead to overcrowding on that table.

**Comment by riastrad** [comment]
@colleenmcginnis after some reflection after a good nights sleep, I’m inclined to agree with @chloekraw on several of the above points:

* tracking and keeping this information up to date would create too much maintenance overhead
* there isn’t an obvious way to automate this and reduce overhead 

(@chloekraw I hope you don’t mind my paraphrasing your comments)

I think these two points outweigh other considerations. And I’m happy to close this issue out and discuss how to communicate style spec support over in the appropriate docs repo.

**Comment by colleenmcginnis** [comment]
Thanks @chloekraw and @riastrad! I'm going to close here, but we can reopen if anyone feels strongly that we should explore this further.
