### ISSUE TITLE
CameraOptions bearing is clockwise, not counter-clockwise?

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4179]
According to [the documentation](https://www.mapbox.com/mapbox-gl-js/api/#CameraOptions):

>bearing (number) : The destination's bearing (rotation), measured in degrees counter-clockwise from north.

I'm calling `flyTo` with `{ bearing: 90 }` and the camera ends up pointing east. Something isn't right. Maybe it's trying to say that the camera is west (90 degrees counter-clockwise) of the destination? If so, this could be made clearer.

**Comment by stevage** [comment]
Hmm, thinking about this more, this is one of the awkward and confusing things about the 2D/3D transition.

When the pitch is zero, increasing the "bearing" by 20 degrees rotates the map to the left (counter-clockwise). You don't perceive any "camera", there is just a flat image of a map rotating.

When the pitch is 45 degrees, however, everything really changes. Increasing the bearing is perceived as the camera rotating clockwise around the focus point. Even thinking about it from the point of view of the focus point doesn't help: it's still clockwise. 

¯\_(ツ)_/¯

**Comment by jfirebaugh** [comment]
The documentation is misleading, both in conflating bearing and rotation and using the word "destination". I would suggest simply:

> **bearing** (`number`) : The desired bearing of the map, in degrees clockwise from true north.

"Bearing" here means what is "up" on the map, and is measured in degrees clockwise from true north -- a 90° bearing is "east-up". This necessarily implies that increasing the bearing produces a rotation of the map counter-clockwise.

The documentation should also avoid using the term "destination" in connection with "bearing", since the word "bearing" has other meanings when used in relation to a desired destination point.

> Increasing the bearing is perceived as the camera rotating clockwise around the focus point.

That's not how I perceive it. At both pitch 0° and pitch 45°, I perceive the map to rotate counter-clockwise when increasing the bearing.

**Comment by stevage** [comment]
Personally, and despite having done a lot of outdoor sports (including mountain bike orienteering) and making maps for the last few years....I'm not very confident in understanding the word "bearing". So I'd suggest being more explicit. IMHO "orientation" is clearer:

`bearing (number): The desired orientation of the map in degrees, where 90 means east is up.`



Aside:

> At both pitch 0° and pitch 45°, I perceive the map to rotate counter-clockwise when increasing the bearing.

If the centre of rotation is exactly in the centre of the screen, I agree - but have a look at this:

https://bl.ocks.org/stevage/b863ddd9364c7bf076413119215022fd

I find it very hard to perceive that as anything other than a camera moving around a fixed map. (Or maybe it's the 3D buildings that contribute to the effect that the city is fixed, and therefore the camera must be flying...)
