### ISSUE TITLE
Support fill-extrusion stroke style

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4231]
It would be useful to be able to style the edges of fill-extrusions. (And possible, independently style the vertical edges versus the flat edges at the top and bottom).

Why? It's currently not possible to visually distinguish between two adjacent fill-extrusions. The main workaround is to give each of them a slightly different color (which means you can't really use color as an independent variable visualisation).

![3d-vis-adjacent](https://cloud.githubusercontent.com/assets/678344/22722529/c40cf8b8-ee0b-11e6-9cc5-001514aa4d4e.PNG)

A contrasting stroke colour could also be aesthetically preferable in some cases, and to help better perceive the 3D shape. For instance:

![image](https://cloud.githubusercontent.com/assets/678344/22722563/153d52fa-ee0c-11e6-9064-01f7789f56ae.png)

I'm not fussed whether the occluded edges are rendered or not.

**Comment by lbud** [comment]
@stevage this property was initially implemented but removed due to concerns about antialiasing, as well as the lesson we'd already learned regretting `fill-outline-color`: https://github.com/mapbox/mapbox-gl-style-spec/issues/456#issuecomment-241578737, https://github.com/mapbox/mapbox-gl-js/pull/3223#issuecomment-252130021. We do not intend to revive it. To distinguish between extrusions I'd suggest experimenting with adding more contrast between your basemap and fill-extrusions and/or playing with the `light` property.

**Comment by stevage** [comment]
Ah, thanks. Dang. Seems like the kind of feature where for some use cases it would be worth someone forking the codebase to reinstate. That screenshot looks so sweet :/

**Comment by rowanwins** [comment]
Just dropping a note here that this is available in the ArcGIS JS API, eg [this demo](https://developers.arcgis.com/javascript/latest/sample-code/visualization-buildings-3d/index.html).

In my case I'd love to be able to render outlines to show the floors of a building and then apply symbology to each floor, for example looking at a building I can distinguish which floors have vacancy - this would have lots of potential in the real estate world for example.
