### ISSUE TITLE
zoom maxBounds should be depend on window size

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#4371]
if i set the maxBounds the zoom would be also fixed. But it would be nice if it depends on the window size, so that its possible to see full bounds on max zoom out.

here i see full frame on max zoom out
![correct](https://cloud.githubusercontent.com/assets/7572377/23604919/f1d5e620-025a-11e7-97ff-a623fa3cb6ef.png)

here i dont see full frame on max zoom out 
![correct-not](https://cloud.githubusercontent.com/assets/7572377/23604936/07abeec2-025b-11e7-9015-7c263aa50be6.png)

There is olso a problem with flyto by using maxBounds. It flicker - i think because of flying out and in of boundary.

**Comment by mollymerp** [comment]
Hi @strech345 , 
Thank you for submitting your issue. Could you please use the provided issue template for this issue? It includes spaces for key information like the version of mapbox-gl-js that you're using and exact steps to reproduce the issue. Because these are missing from your report, we cannot diagnose and fix the issue. 

`maxBounds` is meant to constrain the viewable area of the map by preventing the user from  zooming / panning outside those bounds. if its behaving unexpectedly we'd like to help but need the information requested in the template 👍

**Comment by mourner** [comment]
I think the original report was about changing the `maxBounds` behavior so that you can zoom out further than maxBounds dictates so that you can see the maxBounds area fully. No plans to implement this currently. And the flyTo flickering issue is likely #2521.
