### ISSUE TITLE
moveend setCenter stack overflow

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-js#4398]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. set the map center on moveend with map.setCenter(map.getCenter().wrap());
 2.
 3.

### Expected Behavior
map sets the new center and doesn't crash

### Actual Behavior
exception indicating stack overflow is thrown

I am trying to follow this suggestion: https://github.com/mapbox/mapbox-gl-js/issues/2071#issuecomment-245990952 
By using this code:
`map.on('moveend', function() {
  map.setCenter(map.getCenter().wrap());
});`

But, when doing that, an exception is thrown once I pan the map:
`Uncaught RangeError: Maximum call stack size exceeded
    at e.Evented.fire (evented.js:81)
    at e.i.jumpTo (camera.js:445)
    at e.i.setCenter (camera.js:80)
    at e.<anonymous> (mainMap.js:858)
    at e.Evented.fire (evented.js:87)
    at e.i.jumpTo (camera.js:461)
    at e.i.setCenter (camera.js:80)
    at e.<anonymous> (mainMap.js:858)
    at e.Evented.fire (evented.js:87)
    at e.i.jumpTo (camera.js:461)
    at e.i.setCenter (camera.js:80)
    at e.<anonymous> (mainMap.js:858)`

**Comment by stevage** [comment]
I think you have two problems here:

1. You're using `map.on` instead of `map.once`, so the handler keeps getting called for every subsequent move.
2. You're creating a move event from within a move handler, causing a never-ending loop.

Combine those two things, and you have a never-ending snowball, which quickly explodes.

You can kill the loop by passing a property as event data:

```
map.once('moveend', function(e) { 
  if (e.source == 'recenter')
    return;
  map.setCenter(map.getCenter().wrap(), { source: 'recenter' }); 
});
```

**Comment by maximelafarie** [comment]
Doesn't work anymore in latest mapbox gl version
