### ISSUE TITLE
Allow null as a filter value

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#4410]
mapbox-gl-js: 0.33.1
When I tried to filter out null values like this:
```
filter: [
  "!=",
  "name",
  null
]
```
But  it warns:
```
string, number, or boolean expected, null found
```

**Comment by mourner** [comment]
You can do this currently with `['has', 'name']` filter. However we might want to support `null` as a valid value too. Did we consider this @jfirebaugh?

**Comment by jfirebaugh** [comment]
Yes, see https://github.com/mapbox/mapbox-gl-style-spec/pull/421. Main reason we haven't implemented it is in most cases you want `['has', 'name']`, not `["!=", "name", null]`, because vector tiles don't support `null` (https://github.com/mapbox/vector-tile-spec/issues/62).

**Comment by jingsam** [comment]
But geojson does suuport null

**Comment by stevage** [comment]
What would the semantics of `has` be for a null value then? Does a feature `has` a value, if that value is `null`? And is it really useful to be able to distinguish `""`, `null` and not-present?

**Comment by lucaswoj** [comment]
@stevage I spent some time thinking about this while implementing https://github.com/mapbox/mapbox-gl-style-spec/pull/451. My conclusion was that we should be as true to the Javascript semantics as possible. This would suggest that we should support `null` in `Map#setFilter`. (`undefined` is a sticker case because it isn't supported in JSON.)

**Comment by stevage** [comment]
Ah, thanks for pointing me to that.

**Comment by zuo1188** [comment]
![image](https://cloud.githubusercontent.com/assets/4045937/26818487/66344114-4acd-11e7-9da1-fc4bf3c6ee0e.png)

![image](https://cloud.githubusercontent.com/assets/4045937/26818531/9801745a-4acd-11e7-8237-03aa63a9989b.png)

so it's awkward

**Comment by zuo1188** [comment]
or please do not render it when property==null

**Comment by benstadin** [comment]
@zuo1188 I can top this! ;)

<img width="606" alt="null" src="https://cloud.githubusercontent.com/assets/1433419/26818807/7192d3da-4a9c-11e7-92a0-6b865cdeb6fb.png">

To me this is an important feature for data-driven styling. Because you get GeoJSON data often from external data sources, and null is a valid value. 

I think an isNUll comparator would be handy.

**Comment by anandthakker** [comment]
Closing this, as it will be covered by the upcoming 'arbitrary expressions' feature https://github.com/mapbox/mapbox-gl-js/pull/4777

**Comment by qrohlf** [comment]
Correct me if I'm wrong, but after reading this, #421, and #4777, it appears that the _intent_ in these discussions was to support a filter like `["==", "temp", null]` for asserting that a feature has the property `temp` and it is equal to `null`, but the actual functionality doesn't appear to have made it into the product. As far as I can tell, `map.setFilter("mylayer", ["==", "temp", null])` is currently a no-op and does not result in any filtering being applied to my data.
