### ISSUE TITLE
Map keeps rotating on mouse move after mouseup outside map control

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#4411]
Mapbox GL version 0.33.1

### Steps to Trigger Behavior

 1. Go to the Mapbox GL example 'Display a map'
 2. Rotate the map using the ctrl-key
 3. While keeping de mouse button and the ctrl-key down, move the mouse out of the map control element 
 4. Release the mouse button and the ctrl-key

### Expected Behavior

The map does not rotate anymore when the mouse is moved over the map

### Actual Behavior

The map is still rotating when the mouse is moved over the map

**Comment by anandthakker** [comment]
Thanks for reporting this issue @jaapster!  

I believe that the reason it's happening on that page is that the example is actually embedded via an `iframe` element, so that the `mouseup` event does not make it to the HTML document containing the map.

Closing this issue for now, but if I'm mistaken and you're seeing this in a non-iframe context, please reopen the issue!

**Comment by andrewharvey** [comment]
@jaapster Would you be able to test https://github.com/mapbox/mapbox-gl-js/pull/4390 to confirm that fixes your scenario?
