### ISSUE TITLE
Document maximum fill-extrusion-height

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#4454]
`fill-extrusion-height` maximum is 65535 (https://github.com/mapbox/mapbox-gl-js/issues/3464#issuecomment-257962795) but this is [not documented in the spec](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/reference/v8.json#L2000-L2018).

**Comment by moklick** [comment]
Thanks for the info :) Do you have a hint what do we need to change in order to be able to show higher extrusions? For now I tried to change `fill-extrusion-height` to `Uint32`

https://github.com/mapbox/mapbox-gl-js/blob/13363a2b7eb6154272827dda066f588b050412bb/src/data/bucket/fill_extrusion_bucket.js#L22 
```javascript
{property: 'fill-extrusion-height', type: 'float'},
```

and added a new `float` type

https://github.com/mapbox/mapbox-gl-js/blob/13363a2b7eb6154272827dda066f588b050412bb/src/data/buffer.js
```javascript
const AttributeType = {
    Int8:   'BYTE',
    Uint8:  'UNSIGNED_BYTE',
    Int16:  'SHORT',
    Uint16: 'UNSIGNED_SHORT',
    float: 'FLOAT'
};
```

without success (no extrusions anymore)
