### ISSUE TITLE
LayersControl

### ISSUE THREAD

**Issue by lrlinde** [mapbox/mapbox-gl-js#4468]
Hi, there!

After searching a bit, I couldn't find any issue/googleresults related to this (probably I'm not using the correct terms in my search!)
So I'm looking for a LayersControl, similar to the one we have in Leaflet. Is there something already implemented for this in Mapbox GL JS, or any plans for doing so?

Thanks and regards!

**Comment by jfirebaugh** [comment]
Hi @lrlinde -- nope, you didn't miss anything! There's not a layers control provided out of the box. This is primarily because Mapbox GL uses a vector based rendering model -- instead of a few static tile layers, a typical map has many vector layers. Outside of a few specific contexts such as [a Mapbox style editor](https://www.mapbox.com/studio/), displaying all of these layers to the user is rarely desired. Instead, a more application specific UI is desired, so we leave the implementation up to the user -- [here's an example that demonstrates one possible approach](https://www.mapbox.com/mapbox-gl-js/example/toggle-layers/).
