### ISSUE TITLE
Get original request contents on tile error

### ISSUE THREAD

**Issue by alecf** [mapbox/mapbox-gl-js#4483]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Add an error handler (`map.on('error', handler)`)
 2. Add a tile source to a site that returns an error (like a 500/400 or whatever)
 3. Try to inspect the error object to figure out what went wrong.

### Expected Behavior

That there would be a way to get at the error response

### Actual Behavior

All you get is the request's stats string (in my case "INTERNAL SERVER ERROR")

What I'd like is that you could get a handle to the original request. We'd like to return some JSON that our error handler can parse, and deal with it appropriately. The error object has a few useful fields like `tile` but no actual contents of the response.

**Comment by jfirebaugh** [comment]
Thanks for the suggestion @alecf! Unfortunately the GL JS implementation of tile requests has some constraints that make it infeasible to implement this, most notably, the fact that the requests are made on a Web Worker, rather than the main thread. It's not possible to transfer the request object across the Web Worker boundary, so I don't think it's possible to implement this feature.

**Comment by alecf** [comment]
That's too bad - I'm not sure why transferring a response across the webworker boundary is infeasible though? All the web APIs should support it...
