### ISSUE TITLE
Order/Priority of symbol labels when colliding in a custom data source

### ISSUE THREAD

**Issue by dagjomar** [mapbox/mapbox-gl-js#4671]
**v0.37**:

### Steps to Trigger Behavior

 1. I have a custom data source with GeoJSON Point features which I render as text labels
 2. I notice that when these text labels collide, the priority of visibility is the one that is top-most in the viewport y axis - and not the order of the elements in the GeoJson features array.

### Expected Behavior
I would expect to be able to determine the priority/order of the individual elements in the geojson source, so that the visibility of the labels when colliding is more pre-determined and does not change when rotating the map.

### Actual Behavior
When text labels collide, one is hidden, and when rotating the map it is clear that the label that is "above" the other in viewport y-axis gets drawn first.

**Comment by mollymerp** [comment]
Hi @dagjomar – you are correct, and this is expected behavior for the current implementation of our collision detection algorithm. Due to the complexity of collision detection and the fact that the algorithm may change in the future, we don't make any guarantees about feature dominance for collisions within a layer. If you want to control collision precedence differently, you will have to separate your features into multiple layers using `filter`s on your GeoJSON source. In a style's array of layers (i.e. `["country", "city", "road"]`,  later layers (i.e. `"road"`) symbols take precedence over earlier layers.
