### ISSUE TITLE
points in vector tiles were loaded incorrectly

### ISSUE THREAD

**Issue by wzrg** [mapbox/mapbox-gl-js#4683]
when i tried to load vector tiles using wmts protocol with geoserver，points in vector tiles were loaded incorrectly as the followed pictures show. For example, when i zoom in the map at a level, points in vector tiles of the level are loaded while points in vector tiles of previous level will be also loaded. In fact, they are the some points but at different level. What does cause the problem and how can i solve the problem. thanks!
![error](https://cloud.githubusercontent.com/assets/28420659/25731286/8bb47478-3177-11e7-9502-88a4e2a1aa05.png)

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. Unfortunately, you haven't provided enough information for us to be able to help you. When opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer. In particular, for issues such as this we will almost always need you to provide a minimal working example that demonstrates the issue. If you can provide those things, please feel free to open a new issue.
