### ISSUE TITLE
Runtime styling sometimes doesn't take effect

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#4738]
When using a GeoJSON source, and setting runtime styling properties, then updating the GeoJSON source data, the changes to the style don't always take effect.

https://jsfiddle.net/ygxuk5zy/ contains a reduced test case (replace your access token). This is how it *should* look:

![screen shot 2017-05-22 at 23 05 13](https://cloud.githubusercontent.com/assets/52399/26328437/4eb84a2a-3f43-11e7-8eec-01631bbabaaa.png)

This is how it actually looks:

![screen shot 2017-05-22 at 23 05 20](https://cloud.githubusercontent.com/assets/52399/26328440/53c3876e-3f43-11e7-84c4-cf958a670bba.png)

**Comment by anandthakker** [comment]
Ah - the problem here is that `map.getLayer().setPaintProperty()` is not intended to be a user-facing method.  In fact, that's true of _all_ the methods of the `StyleLayer` class; I think `map.getLayer()` should really be returning a serialized copy of the layer -- I will ticket this separately.

Replacing `map.getLayer('route').setPaintProperty('line-width', 5)` with `map.setPaintProperty('route', 'line-width', 5)` fixes the fiddle.

**Comment by jfirebaugh** [comment]
There's an actual bug here too, however. Consider the following execution sequence:

| Main | Worker |
| ---- | ---- |
| `geoJSONSource.setData(new);` | |
| sends `geojson.loadData` message | |
| `layer.setPaintProperty(new);` (using DDS) | |
| | receives `geojson.loadData` message |
| | performs indexing |
| | sends response |
| receives response | |
| sends `reloadTile` message | |

And then the following (in independent relative ordering):

| Main | Worker |
| ---- | ---- |
| 🎉 animation frame 🎉 | receives `reloadTile` message |
| `style.update(...)` | parses the tile using _new_ data but _old_ property definition 💣 |
| broadcast `updateLayers` | |
| send `reloadTile` (due to the DDS property change) | |

If the old property definition depended on attributes that aren't present in the new data -- for example, if the property value is a categorical source function where the source domain values are unique feature IDs -- then the result will fall back to default values (e.g. black color).

**Comment by jfirebaugh** [comment]
@anandthakker Can you take a look at this? I am finding it difficult to see any easy fix without large scale refactoring (#2291, #4875), so that #3692 is feasible.

**Comment by anandthakker** [comment]
@jfirebaugh until we can take on the necessary refactoring to solve the problem more systematically, a temporary measure to patch this would be to expose something like `SourceCache#{pause,resume}()`.  The `Style` could use this to prevent tiles from being (re)loaded between the call to a runtime-styling method and the subsequent animation frame => `updateLayers` broadcast.
