### ISSUE TITLE
`glUniform1iv: wrong uniform function for type` on Chrome 45 (is this still supported?)

### ISSUE THREAD

**Issue by mbullington** [mapbox/mapbox-gl-js#4765]
Hello! With the latest version of mapbox-gl-js (v0.37.0 and master), the map is broken when using older (but still somewhat recent) Chrome versions like Chrome 45. Is this version still supported? Thank you!

### Steps to Trigger Behavior

Go to https://www.mapbox.com/mapbox-gl-js/examples/ on older Chrome versions, in my example Chrome 45 works for sure.

### Expected Behavior

Map appears normally, like with most recent Chrome.

### Actual Behavior

Text is enlarged to ~90px and covers the entire map, error line in the console.

```
(256) [.WebGLRenderingContext-0x7fa180f6b520]GL ERROR :GL_INVALID_OPERATION : glUniform1iv:
wrong uniform function for type
WebGL: too many errors, no more errors will be reported to the console for this context.
```

**Comment by jfirebaugh** [comment]
No, sorry, we don't support old Chrome versions.

**Comment by andrewharvey** [comment]
@mbullington do you know if there as a way to test support for this in mapbox-gl-supported at https://github.com/mapbox/mapbox-gl-supported/blob/gh-pages/index.js?

**Comment by afenix** [comment]
Adding a comment here in the hopes that 1. drive attention back to this issue on this thread and 2. determine if a workaround for users can/should be initiated in the mapboxgl.supported() side. While doing cross browser testing for a site that I've built using both mapbox-gl-js and mapbox.js, I've hit this exact issue for both <=48 Chrome browsers and Opera browsers <=35 but only on Mac OS, not Windows OS.  Since we are relying on mapboxgl.supported() to switch from using either mapbox-gl or mapbox.js what are workarounds that we can put in place to remedy this situation for our users?

**Comment by afenix** [comment]
To add to my previous note, I'm finding the same issue I described above with Opera <= v35, and again only on Mac OS (Sierra, El Capitan, etc).
