### ISSUE TITLE
on hover, filled extrusions showing only clipped portions of the extruded volume

### ISSUE THREAD

**Issue by jasonlally** [mapbox/mapbox-gl-js#4776]
**mapbox-gl-js version**: v0.37.0

### Steps to Trigger Behavior

 1. [Open this map](https://datasf.org/sf-building-explorer) in Chrome (I'm using 58.0.3029.110 (64-bit))
 2. Search for 1 S Van Ness, San Francisco in the geocoder
 3. Zoom in pretty close (screenshot below)
 4. Mouse over buildings

Source code here: https://github.com/datasf/sf-building-explorer

### Expected Behavior
On mouse over, the full volume of the hovered building should turn yellow

### Actual Behavior
Intermittently only portions of the volume are highlighted

### Screenshots

The yellow portion should include the bottom left sliver of the building.
![screen shot 2017-06-02 at 9 37 21 am](https://cloud.githubusercontent.com/assets/534176/26735558/42926e74-4777-11e7-94bc-e5c7c829ae92.png)

**Comment by lbud** [comment]
Because data is tiled, it inevitably splits up features at tile boundaries. In this case, once you've zoomed in past z18, that building is split along a tile boundary. In order to reliably select a full feature like a building you'd need to have unique building IDs in your dataset and add all features from the building layer with the matching ID to your hover layer (you might do this by using a filter on the hover layer to match a given ID, or, since it looks like you're using a `source#setData` approach, querying for all features within a certain radius of the selected point and adding all features matching the ID of the hovered building to your hover layer data).

**Comment by jasonlally** [comment]
Ah, thank you!

**Comment by lp6191** [comment]
Hi, I know this issue is closed, but I won't open another issue just for one question.. so, this is my code and my goal is to change color of doubleclicked building:
 `map.on('dblclick', function (e) {
    var feature = map.queryRenderedFeatures(e.point, { layers: ['3d-buildings'], filter: ['==', 'extrude', 'true'] });
    console.log(feature);
    var feat = [];
    for (var i = 0; i < feature[0].geometry.coordinates.length; i++) {
        feat[i] = {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": feature[0].geometry.coordinates[i]
            }
        }
        //console.log(feat[i]);
    }
    var building = {
        "type": "geojson",
        "data": {
            "type": "FeatureCollection",
            "features": feat
        }
    }
    var height = feature[0].properties.height;
    var minHeight = feature[0].properties.min_height;

    map.addSource("building", building);

    map.addLayer({
        'id': 'buildings',
        'source': 'building',
        'source-layer': 'building',
        'filter': ['==', 'extrude', 'true'],
        'type': 'fill-extrusion',
        'minzoom': 15,
        'paint': {
            'fill-extrusion-color': '#FFFF00',
            'fill-extrusion-height': {
                'type': 'identity',
                'property': 'height'
            },
            'fill-extrusion-base': {
                'type': 'identity',
                'property': 'minHeight'
            },
            'fill-extrusion-opacity': .75
        }
    });
});`

When the code runs I get no error, but also nothing changes. Any help would be highly appreciated.
