### ISSUE TITLE
client-side terrain: scale slope calculations by latitude

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-gl-js#4807]
@mollymerp @kkaefer I brought this up recently in chat but figured I should capture details in a ticket.

Slope calculations for terrain visualization from mercator-projected tiles should ideally to take into account the varying scale along latitude. The ground distance covered by 1 pixel in mercator shrinks as you move away from the equator, so hills at extreme latitudes will appear more flat than they really are if this is not accounted for.

[This StackExchange answer](https://gis.stackexchange.com/questions/14750/using-srtm-global-dem-for-slope-calculation/40464#40464) explains the situation well and includes some math that can be used to adjust the terrain visualization to be more accurate.

> …assuming scale is correct at the Equator, its distortion equals the secant of the latitude. That is, distances on the map appear to be multiplied by the secant.

| Horizontal scale factor | approx. latitude |
| --- | --- |
| 1.25× | ±37° |
| 1.5× | ±48° |
| 2× | ±60° | 
| 3× | ±70° |
| 4× | ±75° | 
| 5× | ±78.5° |

Options:

- Compensate for latitude on a per-pixel basis. Most accurate but probably difficult or expensive.
- Compensate for latitude on a per-tile basis (eg adjust all pixels in a tile based on the lat of the tile center). This would require Some gradual falloff at the most zoomed out levels to avoid obvious seams between tiles. A mostly-acceptable tradeoff, but unfortunate for places like Svalbard.
    - This is the option we went with for vector terrain
- Do nothing. A hillshade style designed with 20-40° of latitude in mind would slightly over-exaggerate slopes in equatorial regions and under-exaggerate them at more extreme latitudes, but the error would not be very noticeable at most populated latitudes. Northern North America & northern Europe would lose out on accuracy in the most noticeable way, with perhaps also southern South America and New Zealand.

**Comment by mollymerp** [comment]
Thanks @ajashton for capturing in a ticket. Very interesting stack exchange article! I think per-pixel basis might be more trouble than its worth but I don't think per-tile scaling would be too difficult. 

@kkaefer let me know if you have thoughts on this or if you have explored any of these options previously.

**Comment by kkaefer** [comment]
I haven't explored any of this. It might be preferable to do per-pixel, since we could use varying interpolation, and enable this effect for z0 tiles as well by having 4 triangles, 2 for the northern hemisphere and two for the southern hemisphere that'd allow us to compute the latitude for every pixel. If we do it per tile, we might end up with seams at the tile boundaries, in particular for low zoom level tiles.

**Comment by mourner** [comment]
An option in the middle would be to calculate adjustment at the top and the bottom of a tile and then interpolate (e.g. linearly) in each pixel. This should be cheaper than per-pixel `cos` calculation. Although the per-pixel shouldn't necessarily be expensive, since `cos` should be calculated with simple lookup tables on many GPUs — we should try it out first.

**Comment by mollymerp** [comment]
I implemented a per-pixel scaling in https://github.com/mapbox/mapbox-gl-js/pull/5286/commits/f7eb44be9dfe1f370aa93b7f84438f01c8a561f7. not sure how best to profile this, but let's move the discussion over to the PR now.
