### ISSUE TITLE
icon-image base64 support

### ISSUE THREAD

**Issue by Wykks** [mapbox/mapbox-gl-js#4816]
## Motivation

Having custom icon image per feature. Icons may be different depending their data.
A the moment, we need call `addImage` in order to add custom icon-image, but it's not appropriate if each feature have differents image (and if these images are generated based on feature data).

## Design

data-driven _generation_ of icon-image would be ideal, but we can't have js callback inside styling as far I know.
The source server could calculate the base64 image for each feature into a `icon` property, and then we just have to set something like: 
```
 "layout": {
              "icon-image (or another property name)": "{icon}",
              "icon-size": 0.25
}
```

I know that html markers can do this, but they're not as smooth as symbol layers.

**Comment by brianhyper** [comment]
I really need this feature, the html markers is not supported with clustering and I have a shit load of icons to load and the "addImage" is limited by the "AtlasSprite" size.

**Comment by rahuldhawani** [comment]
I know this has been brought up again and again, but I couldn't find a proper solution to support the way we want our markers to be shown and ability to form cluster, drag, drop, filter etc. (`Marker` is a way, but not sure how you do clustering and drag, drop with them). 

Design wise, our markers consists of two layers, background: where users select color and foreground where the user selects the icon. Colors and Icons are dynamically selected. 
With `Mapbox.js`, doing this was easy, `L.mapbox.featureLayer
().addLayer(L.Marker(…))`, this would support clustering as well. 
But with GL-JS, `Marker` doesn't return a layer(?), where supporting clustering is a tricky (looping GeoJSON back and forth).

Markers we want to support:
![screen shot 2017-08-03 at 12 25 02 pm](https://user-images.githubusercontent.com/7352827/28909610-cff41268-7846-11e7-9cc5-5424cebf87c5.png)

Is it possible to create markers like above with `Symbol`?

**Comment by rikup88** [comment]
Does this trick help you? I find this approach a bit more flexible than using external URLs because external requests are not needed. Not as elegant as using base64 from icon-image directly:

`this.map.loadImage(' data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAF8CAMAAADW5x0HAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAB3RJTUUH4QgIEAoEBayOSgAAAv1QTFRFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////5iEdCQAAAP10Uk5TAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3Bxc3R1dnd4eXp7fH1+f4CBgoOEhYaHiImKi4yNjo+QkZKTlJWWl5iZmpucnZ6foKGio6Wmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/jnwBzgAAAABYktHRP7SAMJTAAANIElEQVQYGe3BC7iNdb4H8O/aa1/Y221j0G5CKLrIcZsjjhraTMaIyMxEoelwDuVSTc7UKLkljTBTzFYkkTTNKSWJGWpwRIPI9SDlunPd7Yt9W+v7PGeeZqYTe73vXutd77v/7/+/fp8PhBBCCCGEEEIIIYQQQgghhBB6S7vj8UXzZ/2iEYQf1Hn2LL9RtrA+hHIDv+K3DjWDUCv4HL9rdwaESml/4KWmQiiU9j4vk58JoUzKW6xgJIQqgVdY0UoIVaYxgovpEM7dNPnlGXfVgSOjGNEtEI49EeLflCzritjdWc6IHoRwagj/6c9dEaMeFxlZDoRD1XL5/9Z0Riy6FtLChxAODeIl1tyEqLU9TyuHIBx6nZcqn5+F6LQ9R0sXAxDOnODlCqfWRRS6X6CN+hCO1GUEeZPqojJDSminDYQjHRlR3qS6sFN9Pu39GMKRbFrI+00zWOqyk5UYDuFIb1oKreibikiuWhRmZZ6CcKQ/7ZyZe3t1XKbDklJWbiGEI3ezEkWrnuxzJf4uqWnv5z9nVNZCODKY0Sj+cvOadZ/susioHYBwpBe9URyAcOIH9EhDCCda0CMdIJzIpEf6QziRVEJvjINwZA+9MRvCkbfojVUQjjxDbxyGcOR+eiNUDcKJf6NHWkM4UaOc3rgLwpFd9MbjEI68RG8shnBkBL3xCYQjbeiN4mQIJ4Ln6Y3rIRz5A71xN4QjI+iN6RCONKE33odwZh89cRLCmZn0RkMIR26mN3pBOBL4gp6YAOHMLHriLQhnutATxyCcCXxJT1wB4cwceqIPhDNd6YmnIJxJOkYvvAvh0Cx64SCEQ53ohbIUCGcCR+iFxhAOzaAXmkA41J5e+D6EUwfovuIUCKem0H3bIBxrQ/c9A+HcIbquNYRzM+m2tyHi0JUuK24FEYfgabrrYYi4vEZX/TEJIi7D6KaP0yHi0yhM9xxsABGvz+ia3OYQccuhWwo7QcRvGF1S3hfCBdfSJf8B4YZAHl3xKoQ7ttANX9SAcMdiuuFOCJc8Rhd8COGWX9AFvSDcMoDx2xeAcEs24zcZwjVdGL8OEK75MeNWkAThmsGM2yYI94xm3HIg3DOPcXsSwj3bGbeHIFxzZZhxux/CNY8zfvdCuCXjBOM3EsIt0+iCX0K45LZyuuApCHd0zKMbZkK4on8BXbEEwgWNFtMlWyHidt3sQrrl6wBEPNK7TNxCN2VBOFOz/aDJyz8rp8t+BBGrK3uOfmHtUXpjCkT0arUfMmfNKXppPUQ0gq3vmb7yC3qvKA2iEll9Jr5zjlXlhxA2rh+57CSr1HQICy0eWJ7LKrcdIoLU7Of2U4lwI4jL1Bn2x3wqMwjiu6r3WVxIlV6E+FZq39cKqNhhiH+4etop+kBjiL9Jyl5eTl/oD4F6TxyjX0xBwms48QL94z0kuKZziugnuUho1y8pp89kInHVm1NG37kJiSp17AX6UG8kpsDAw/Sl/0RC6riVPjUVCaj6jHL61SIkns576V9vINGkTw/Rx95Fgsn+nL72JySU5Ikh+tsmJJImG+l325FA+uXR9/YjYSRNDtP/DiJR1FlJHXyGBHH1HmphKxLDzbnUw0dICHddpCbeRCIYUkZdzEECGBumNsbDfNOokZ/CeFOok2thuinUSVEQhptGrfwFhhtPvUyE2YaEqZeuMNqd5dTL6RSYrEMhNTMXJmuaS910gcFq7aRudgZgruBqamcoDPY0tXMkDebqG6Z2hsBcLfOonU+DMFb6Z9ROqDPMlUP9zIO5BlA/+2vCWFedpXYutoGxkj6kfobCXA9RPwtgrpZF1M7mdBgruIna2VMX5nqI2jnRFOZqnE/dfN0WBnubuinqBoMNoG5Ke8Ng1Y9QM+U/h8kmUzPh4TBZ40Jq5mEY7Q1q5tcwWscw9TILZltLvSwIwGi3UC8rgjDbJmplSzrM1pdaOdwQZkvaQZ2cbQnDDaJOym6B4ZL/lzoZD9MNok5WJcF0H1MjpxrBdN2pkdBtMN671MhEGK9ViPrYmQLjLaA+QjfDeI2KqY85MN8U6uNMJoyXfIL6eADm60997E+G+d6nPu6B+RqXUxsHkmG+ydTHvTBf8jFq40QqzHcH9fFrJIC3qY3iBjBfZgm1sRQJYDj18SMkgD9TG8eDMN8V5dTGDCSAcdRHRySAzdTG8QDM1yxMbcxDAvgl9dELCWATtVGSDvM1CFEbHyEB/Dv1MQkJ4B3qozvMl1FEbZSlw3x3Uh87kQBepj5egfkCJ6iPsTBfW2qkK8z3X9RIJsy3jvr4CuarWUJ9bID5+lIjC2G+udTIr2C+A9TIz2G8q6iTrjDeUOqkOYy3iDpJh/GOUCPnYbzm1MkeGG84dbIBxltKnayE6QInqZOlMN0N1MrvYboHqZVnYLo3qZXHYbik09TKwzBcW+plLAz3CPUyEoZbRb0Mh9lSC6iXYTDbLdTMYJjtKWpmEMy2kZoZCqPVLKVmhsNoP6FuRsFos+gHB54edv+IEeNnL9tSzMqMg9F2Ur3D9wTxT6nZOQW0NQEmaximcq/VxiXq/q6cNmbBZIOpWmg0Kuh+htYWwWSvU7HSwYjgxvO0tAIGS8ujWmX9EFGPMK1sgsF6Ua3w/bDwe1o5CoPNo1qPwkr9QloIpcBYScep1EuwNodWroaxelCp/0mDtTa00h3GWkKVTmTBzkFaGANT1S6iQqHusPU8LeTAVCOo0mTYG0oLG2GowDYqtCEZ9m6ghfxkmKkPFSpogUpUC9NCO5hpIxUaiUp9RQujYaQeVGhtAJXaRgvLYKLgX6lOQRNUbh0tnAnCQOOo0HhE4T1auRnmubGI6uxOQRTepJXJME7mXqoTvhXReJVW9sI0KWuo0GJEZR4ttYNhFlCh8w0RlSm0NBNmeYwqjUJ07qOl09Vgkp+FqdBfg4hOJ1obAoP0LKFK2YhStWJa2gJzdC6gSqsRtY201gOmaH2WKoXbIWoTaG0jDHHNKSq1FNFrQxu3wwgtj1Gp0uaIwS5a25MMA9xwkmr9DrF4kDYehP5u+opq5TdALOoU0lp+M+iu4xkq9hvEZgFtrE+C3nrlU7HiKxGbDrQzBlobWkrV5iNWb9NGYSto7LEwVSu/BrFqHaKNfXWgq7SFVG8ZYreEdj4IQk9Zm+kD7RC7q0to51loqdMJ+sAHcOI52hoJDY0ooR8MhBPph2gnfB90U+t1+sKZNDhyO22VD4BeOn1Of5gJh5bS1sWe0Ejq1DL6xPVwqMEZ2irqAW20+ZR+8UkqnLojTFtF2dBD2sQS+kro3Llzxw9tX/ffOROGdq2DqD1He4XdoYNu++lrR14ZVBtRSf2Y9gq7wfeyXgnT9/LnZiEaTc/RXmFH+FvNyYXUwoV7EY2flNPeicbwsZRRudRFeDSiMYaV+LQafCt7FzVS1gnRmMNKTIRP9dhAvWxCNIIraK/4GvhQ0oCt1E57RCPjY9p7Cb6TMmwvNTQRUamzlbYuBOEvNcd8QS2tR3Qyt9HWjfCTlr/No6ZyEaV6O2inB3wjqc/qMJ0Jfb5+zXtrD5ZSoVqIUv0ttPFD+MT3Hj1MR/YsuO+GVHwjNXt2LlVpgWhlrKC1FvCFW5cW04GilSOvwiWqP/Al1eiEqAXn0srpANSrM3YPHShfNTgDFdWYXU4VuiEGj4YY2ctQrs38QjrwybhGsND5KBXoiVj0OMWIukOtYJ81dODonH+BjfqrWfV6IyYNVjOCHQGoVOORE4xd4ctdA7AXfIFVrh9iE3yilBX0g0I1x55k7PaOr4cojA2xig1ErK5dzcusgzq1Jp1nzAoXdkKUWravYnURu7uP87vyr4MqweG5jNmOB2rDMDUeOclvFfeDKq02MVYFC/4VJkr96cqL/MbWTlBl9EXGaPuo2jBWerfRTz89pi1UyVjK2BS89AMIz9TZyJjsHl8Xwjv1P2UM8l/sCOGlahsYvd3j60J46zVGK39+BwivDWGUdo2sCeG5rAuMRunyWyGqwnxG4etnsyCqRKsyVur0hEyIKjKXlTn/qwyIqlIjj/ZKchpAVJ0htPdOU4iq9DrtHO0PUaWSz9PGG5kQVasDreUPhahqw2npeDuIKvcCrezIgqh6f6KF3d+DUGAfI/vyCggVChhRWRcIFWoyskkQSjRiRMczIJRowogehVCjJSMJZUGocR0j2Q2hyPcZyTIIRVJKGcGLEKrsZgSLIVTJYQQfQajSjxEUpkEoknaWEdwOocokRvAmhCq1z7GiUBsIVZ5kBKsCEIpk7GMEIyBUaV/KigqugVDlCUawJR1CkaTljOCdIIQi1dYzglkQqtTexggmQahS4wNGMANClbRljOBZCFWSJodY0XQIZXrmsqJnIJTJeo8VTYVQ5+5TrOAJCHUyny/hZcIDIRRq9mqIl8pvBqHSdTmFvMRvIdSqN34Xv2MxhHKtp2wu49/taw7hBzWyR87IyZlyWyqEEEIIIYQQQgghhBBCCCGEEFr5P245j2uerrJdAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE3LTA4LTA4VDE2OjEwOjA0KzAwOjAwbTkmPQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxNy0wOC0wOFQxNjoxMDowNCswMDowMBxknoEAAAAASUVORK5CYII=', (error, image) => {
        console.log(error);
        if (error) {
          throw error;
        }
        this.map.addImage('cat', image);
        this.map.addLayer({
          'id': 'points',
          'type': 'symbol',
          'source': {
            'type': 'geojson',
            'data': {
              'type': 'FeatureCollection',
              'features': [{
                'type': 'Feature',
                'geometry': {
                  'type': 'Point',
                  'coordinates': [27, 61.7]
                }
              }]
            }
          },
          'layout': {
            'icon-image': 'cat',
            'icon-size': 0.25
          }
        });
      });`

**Comment by Wykks** [comment]
In your example your base64 image is not generated based on feature properties.
It could be, but it means one layer per symbol (not sure if it's better than html markers at this point), and it's still probably limited by the `AtlasSprite` size issue.

**Comment by vanceric** [comment]
This is also an issue for a project I am working.

We consume a GeoJSON that is a feature collection of aircraft locations, heading, etc. Each feature includes a base64 encoded icon for that type of aircraft. Ideally we should be able to to reference the properties that contain the icons and heading and have it render.

Using the loadImage method is very clunky and not appropriate for our use-case.

**Comment by Wykks** [comment]
I'm not using mapbox-gl currently, but this seems to solve this issue: https://github.com/mapbox/mapbox-gl-js/pull/7987 🎉
