### ISSUE TITLE
use higher precision angles for glyphs

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#4829]
https://github.com/mapbox/mapbox-gl-js/pull/4781#issuecomment-306886334

> > > Do we have a choice? On this PR a_data is using 40 bits and a_size is using 32 bits, and I believe the only extra space is 16 bits in a_projected_pos. If we keep a_size and try to get rid of a_data, we'd have 40 - 16 -> 24 bits to pack in somewhere else. We can drop a few bits of precision from the offset in a_pos_offset (dropping from 1/64 precision to 1/8 saves 6 bits and doesn't look too noticeably different although the render tests do change), and a few bits from the anchor position. You could also go back to dropping 8 bits of precision from segment_angle (but that'd be a bummer, because the low precision angles meant that labels sometimes didn't quite line up with their lines).

> > I'm not sure, I guess the impulse was to just pack everything as tightly as possible instead of using an extra 4 bytes. Should I switch to using a fourth item?

> I’d like label angles to be higher precision, but once we start using that space if we want to take it back and use it for something else we’d be creating a regression. So I’m totally fine with keeping label angles low precision for now and maybe making an issue to track increasing the precision.

**Comment by ChrisLoer** [comment]
Using low precision angles isn't super noticeable for a single glyph (it's at most off by 360/256 =1.4 degrees), but it adds up over longer distances. Since line-following labels are now placed in the CPU, they're not cumulatively affected by the lower precision across the length of the line. However, you can still see the difference in icons that follow lines (as in `icon-text-fit/placement-line`. Look at the diff at:

https://github.com/mapbox/mapbox-gl-js/pull/4781/commits/42c7375ba61ecd7856a6a318a4d567e75e9d9fc5#diff-23918628c939d13d4c6b4d65af685ed2

And you can see the icon not quite agreeing with the label.

**Comment by mourner** [comment]
I think this is good enough at the moment, so closing as stale — let's reopen if this resurfaces as a real problem.
