### ISSUE TITLE
showTileBoundaries debug option should read from a source whose min/maxzoom include current zoom if available

### ISSUE THREAD

**Issue by DanielCeregatti** [mapbox/mapbox-gl-js#4830]
**mapbox-gl-js version**: 0.38.0

### Steps to Trigger Behavior

 1. Visit [the openmaptiles style page](https://openmaptiles.org/styles/), open the javascript console.
 2. Paste `maps['osm-liberty'].showTileBoundaries = true;` in the console.
 3. Note the red tile boundaries appear in osm-liberty map on that page. If you zoom that map beyond zoom 6 the tile boundaries disappear.

### Expected Behavior

The boundary tiles should not disappear.

### Actual Behavior

The boundary tiles disappear.

While the instructions above reference a page that's using mapbox-gl 0.31.0, I have a private test case that's using 0.38.0 that's exhibiting the same behavior. Unfortunately I can't link to it because it's behind firewalls.

I've opened a ticket on the style maker's github here: lukasmartinelli/osm-liberty#13. Here's a relevant excerpt from that ticket:

I found this out because I've copied this style to a map I'm working on as a proof-of-concept for the use of mapbox-gl for my company. I've noticed this problem is tied to the natural_earth layer in style.json. If I completely remove this layer definition and reload the page, setting `showTileBoundaries = true` does absolutely nothing. If I remove the source declaration for `natural_earth_shaded_relief` after removing the `natural_earth` layer, everything works as expected.

**Comment by lbud** [comment]
Thanks for the report @DanielCeregatti. This is happening because the [code for rendering tile boundaries](https://github.com/mapbox/mapbox-gl-js/blob/ce09894e56a5722e58a27153a41517633450a56e/src/render/painter.js#L225-L228) does so based on the first present source, which in the case of OSM Liberty is [`natural_earth_shaded_relief`](https://github.com/lukasmartinelli/osm-liberty/blob/gh-pages/style.json#L9-L10), with a maxzoom of 6. We should consider hardening this logic on the gl-js side, but on the OSM Liberty side, you could move the most complete source (in this case, `openmaptiles`) to be the first source listed in `sources` as a workaround for now.

**Comment by DanielCeregatti** [comment]
This solution worked. Considering this could technically still be considered a bug, I'm opting to leave this open, unless you object, in which case I'd be happy to close it.
