### ISSUE TITLE
Layers get Css body background-color when adding fill-extrusion layer.

### ISSUE THREAD

**Issue by NieneB** [mapbox/mapbox-gl-js#4963]
**mapbox-gl-js version**: v0.38.0

I have a map with a background layer and several other layers, based on my own vector-tiles. Styling it goes fine until adding a fill-extrusion. I have a body { background-color: yellow } with CSS but when  adding 1 layer with a fill-extrusion the body background-color is shown instead of the background layer or some other layers.

To reproduce: 

https://jsbin.com/hawodekobi/edit?html,css,js,output

### Steps to Trigger Behavior

 1. Setting CSS body { background-color: "yellow"; } 
 2. Adding 1 layer with fill-extrusion ( un comment the water layer ) 

### Expected Behavior
Background layer color will always show behind the layers added. The body color is not to be seen in the map. 

### Actual Behavior
Body background-color is seen instead of background layer or seen as the color of some other layers.

**Comment by jfirebaugh** [comment]
Can you please reduce the example to the minimum code and style JSON needed to replicate the issue? Right now it's a little much for us to debug. Thanks!

**Comment by NieneB** [comment]
Sorry. Removed all the extra layers. I have the same problem with another map too. Using different tiles and different layers. 

There you go: https://jsbin.com/vogubupife/edit?html,css,js,output

**Comment by lbud** [comment]
Thanks for the report @NieneB! Interesting — this was actually fixed on master in https://github.com/mapbox/mapbox-gl-js/commit/3cdc10bef9fe64114b58d7e12113c6e095483135 (not sure if this particular bug was fixed intentionally or not). Previously, when opaque fill layers were rendered on top of fill-extrusion layers, for some reason during the opaque pass when we'd unnecessarily render an empty texture to the map per fill-extrusion layer, it would clear any opaque fill layers already rendered ("above" this layer on the map, since the opaque pass renders top-to-bottom). (Their depth values were not overwritten, so the background layer wasn't rendered in the place of the fill layer, hence the CSS background showing through.)

The fix (https://github.com/mapbox/mapbox-gl-js/commit/3cdc10bef9fe64114b58d7e12113c6e095483135) will be included in the next release.
