### ISSUE TITLE
Fix bug wherein queryRenderedFeatures uses paint properties evaluated at tile's zoom rather than map zoom

### ISSUE THREAD

**Issue by juliangums** [mapbox/mapbox-gl-js#5016]
newest mapbox gl version

seems to work fine on symbol layers. the area seems to get scaled with the icon-size
![selection_004](https://user-images.githubusercontent.com/22907521/28469670-e7484f8c-6e2e-11e7-923d-3f41ddea0985.png)

but on a circle layer i need to go right into the center to click it
![selection_003](https://user-images.githubusercontent.com/22907521/28469697-023fe16a-6e2f-11e7-8302-80bc7f4eac1b.png)

otherwise it doesn't recognise i'm clicking the circle layer
![selection_002](https://user-images.githubusercontent.com/22907521/28469730-1dd02264-6e2f-11e7-83ab-fac95db6d95b.png)

**Comment by mollymerp** [comment]
Hi @juliangums, 
Thank you for submitting your issue. Could you please use the provided issue template for this issue? It includes spaces for key information like the version of mapbox-gl-js that you're using and exact steps to reproduce the issue. Because these are missing from your report, we cannot diagnose and fix the issue. A jsfiddle/jsbin demonstrating the problem would also be helpful!

Thanks!

**Comment by juliangums** [comment]
using the newest version
here a fiddle
https://jsfiddle.net/mw5cm2u2/

instructions:
1.) hover over the green dot and you'll see your cursor turns into a pointer on the entire area.
2.) zoom a little into the red dot, hover over it and you'll see only the very center of it triggers the mouseenter event

**Comment by anandthakker** [comment]
Thanks for the helpful test case @juliangums -- looks like this may be a regression of https://github.com/mapbox/mapbox-gl-js/issues/3604

**Comment by anandthakker** [comment]
Ah -- it's not a regression, but rather a limitation that's been there all along: `queryRenderedFeatures` evaluates paint properties at the _vector tile_'s zoom level to calculate the geometry to be tested against the query.  So, when the map's rendered zoom level is different than that of the tile, the queried feature's geometry may differ from what's rendered.

In this example, because GeoJSONSource has a default `maxzoom` of 18, what's happening is that when you're at z20, it's still a z18 tile being rendered -- and thus the geometry being queried is based on the `circle-radius` value evaluated at z18.  

Raising the maxzoom (see below) makes the problem less pronounced, but it does still occur at non-integer zoom levels.

```js
map.addSource('circle2', {
      'type': 'geojson',
     
       // Set maxzoom to 22 (geojson source's default of 18)
      'maxzoom': 22,

      'data': {
        "type": "Feature",
        "geometry": {
          "type": "Point",
          "coordinates": [-122.4019807, 37.788339]
        },
        "properties": {}
      }
    });
```

**Comment by juliangums** [comment]
seems to be a good enough solution until the bug is fixed. legend! thanks!

**Comment by PBrockmann** [comment]
I would be curious to see what is the "good enough solution" applied to my real case.
See https://jsfiddle.net/PBrockmann/xwp7ns7h/

**Comment by ttsirkia** [comment]
To get a bigger mouse interaction area, I just tried the following which seems to work:

```
"stops": [
            [14, 15],
            [14.01, 2],
            [16, 4],
            [22, 20]
          ]
```

With lower zoom levels the interaction area is too large but that is not a problem if the density of elements is sparse.

**Comment by asheemmamoowala** [comment]
No longer reproducible in  v0.51.0

**Comment by juliangums** [comment]
> No longer reproducible in v0.51.0

I can confirm this seems to be fixed now. Thanks!
