### ISSUE TITLE
E street not coming correctly in maps

### ISSUE THREAD

**Issue by niteshgrg** [mapbox/mapbox-gl-js#5056]
**mapbox-gl-js version**: v0.39.1

### Steps to Trigger Behavior

 1. Open mapbox gl map
 2. Go to washington D.C. E street between 3rd and 4th street
 3. Compare with any other maps like osm or js version of mapbox

### Expected Behavior
<img width="1023" alt="screen shot 2017-07-28 at 12 42 24 am" src="https://user-images.githubusercontent.com/6282293/28688061-3b35ef74-732e-11e7-9fbc-558639a5e307.png">

### Actual Behavior
<img width="740" alt="screen shot 2017-07-28 at 12 43 23 am" src="https://user-images.githubusercontent.com/6282293/28688065-3f6ebe54-732e-11e7-8a3e-4592ef76151a.png">

**Comment by jfirebaugh** [comment]
[E Street is currently closed for construction](https://ddot.dc.gov/release/e-street-between-4th-and-5th-close-construction-project-june-27). So in this case, the Mapbox map is actually more correct and up to date than Google, due to [using OpenStreetMap](https://www.mapbox.com/about/maps/#data-sources).
