### ISSUE TITLE
Complex layer (All US Zipcodes) disappears on zoom out - mbtiles added

### ISSUE THREAD

**Issue by gofishwbeeler** [mapbox/mapbox-gl-js#5065]
@jfirebaugh  I think this issue was closed a bit soon.. I did the suggestions that you asked, and I updated the other issue here: 

https://github.com/mapbox/mapbox-gl-js/issues/5063

Thanks

Will

**Comment by jfirebaugh** [comment]
Hey @gofishwbeeler -- we try to reserve the issue tracker for clear bugs and feature requests for Mapbox GL, and as noted in the first issue, I don't think this issue is related to Mapbox GL, but rather the tileset or other Mapbox services. Please use our [support contact](https://www.mapbox.com/contact/) and they can help you out.
