### ISSUE TITLE
Error when adding controls dynamically

### ISSUE THREAD

**Issue by jedgar1mx** [mapbox/mapbox-gl-js#5089]
**mapbox-gl-js version**:
v0.39.1
==========Link==============
https://cityofdetroit.github.io/health-department-map/
### Steps to Trigger Behavior

 1. Click on any of the hearts.
 2. Click on "Get Directions" button
 3. Close Panel
 4. Click on another heart
 5. Click on "Get Directions" button

### Expected Behavior
Add a new directions controller.
### Actual Behavior
Uncaught Error: There is already a source with this ID

=============== Notes =================
I used "removeControl" but apparently leaves a source ID.
I  also tried "removeSource" but does not work.

**Comment by anandthakker** [comment]
Thanks for the report, @jedgar1mx .  This appears to be a bug in the `mapbox-gl-directions` plugin I filed an upstream issue here: https://github.com/mapbox/mapbox-gl-directions/issues/141.

Meanwhile, two possible workarounds would be:
1. Hide the directions control with CSS, rather than actually removing it, when the panel is closed.
2. Manually remove the source that the directions control adds to the map.  According to https://github.com/mapbox/mapbox-gl-directions/blob/master/src/directions_style.js, this source should have id `directions`, so: `map.removeSource('directions')`.

**Comment by anandthakker** [comment]
Closing this in favor of the upstream ticket.

**Comment by lilessam** [comment]
Here's the code for the second manually solution that @anandthakker mentioned if anyone interested.
```Javascript
map.removeControl(directions_control)
map.removeLayer('directions-route-line');
map.removeLayer('directions-route-line-alt');
map.removeLayer('directions-hover-point-casing');
map.removeLayer('directions-hover-point');
map.removeLayer('directions-waypoint-point-casing');
map.removeLayer('directions-waypoint-point');
map.removeLayer('directions-origin-point');
map.removeLayer('directions-origin-label');
map.removeLayer('directions-destination-point');
map.removeLayer('directions-destination-label');
if (map.getSource('directions')) map.removeSource('directions');
```
