### ISSUE TITLE
Incorrect coords for zoom level

### ISSUE THREAD

**Issue by marcusmilne** [mapbox/mapbox-gl-js#5146]
When I'm intercepting the tiles being loaded I seem to get inconsistent results.  I'm intercepting calls to "_addTile" and the coordinates being sent look like this:

TileCoord {z: 18, x: 236617, y: 160849, w: 0, id: 1349306779954, …}
TileCoord {z: 18, x: 236619, y: 160848, w: 0, id: 1349298391410, …}
TileCoord {z: 18, x: 236620, y: 160848, w: 0, id: 1349298391442, …}
TileCoord {z: 18, x: 236618, y: 160848, w: 0, id: 1349298391378, …}
TileCoord {z: 18, x: 236621, y: 160848, w: 0, id: 1349298391474, …}
TileCoord {z: 18, x: 236617, y: 160848, w: 0, id: 1349298391346, …}
TileCoord {z: 18, x: 236622, y: 160848, w: 0, id: 1349298391506, …}
TileCoord {z: 18, x: 59154, y: 40213, w: 0, id: 337332986450, …}
TileCoord {z: 18, x: 59155, y: 40213, w: 0, id: 337332986482, …}

The last 2 seem to be referring to a grid that's a quarter of the size.  If I multiply them by 4 I would get
z: 18 x: 236616 y: 160852
z: 18 x: 236620 y: 160852

Yes, I know I could just multiply those kind of results by 4, but the thing is, they are valid coordinates.  I only know they're wrong 'cos I can see how the map is relating to the tiles.

Does anyone know how to deal with those results?

**Comment by mollymerp** [comment]
Hi @marcusmilne, 
Thank you for submitting your issue. Could you please use the provided issue template for this issue? It includes spaces for key information like the version of mapbox-gl-js that you're using and exact steps to reproduce the issue. Because these are missing from your report, we cannot diagnose and fix the issue.

**Comment by marcusmilne** [comment]
Mapbox-gl version - 0.39.1 (July 24, 2017)

### Steps to Trigger Behavior

 1. Open source_cache.js
 2. Go to function update(transform: Transform)
 3. After 
for (i = 0; i < visibleCoords.length; i++) {
            coord = visibleCoords[i];
add "console.log(coord)"
4. Go back to map running in MapBox, zoom into levels 17 and higher
 
### Expected Behavior
Consistent grid system for zoom level
so for level 18 I expect to see:
TileCoord {z: 18, x: 236617, y: 160848, w: 0, id: 1349298391346, …}
TileCoord {z: 18, x: 236622, y: 160848, w: 0, id: 1349298391506, …}

### Actual Behavior
Getting some of this:
TileCoord {z: 18, x: 59154, y: 40213, w: 0, id: 337332986450, …}
TileCoord {z: 18, x: 59155, y: 40213, w: 0, id: 337332986482, …}
which looks like the expected result divided by 4

**Comment by anandthakker** [comment]
Possible duplicate: #2868

**Comment by jfirebaugh** [comment]
You're observing an _overzoomed_ tile. When you zoom the map beyond the maximum zoom of a tile source, `SourceCache` constructs tile coordinates with x and y coordinates corresponding to the maximum zoom of the tile source, but z coordinate reflecting the overzoomed zoom level. This is expected behavior. (Note that as these are all internal, private APIs, we don't document or guarantee particular behavior.)
