### ISSUE TITLE
Line disappears when zooming closer than 18th zoom level

### ISSUE THREAD

**Issue by NameFILIP** [mapbox/mapbox-gl-js#5171]
**mapbox-gl-js version**: 0.39.1

### Steps to Trigger Behavior

1. Open [JSBin Example](https://jsbin.com/zucupub/edit?html,css,js,output) 
2. Set `accessToken` variable to your token
3. Zoom in and see the grey line disappear

### Expected Behavior
Line should be visible

### Actual Behavior
Line disappears

P.S. Looks like duplicated points with a different floating point precision is the root of the issue

**Comment by mourner** [comment]
Yeah, that looks like some kind of bug. Meanwhile, as a workaround, you can set `maxzoom: 24` in the source config — this seems to fix the issue.

**Comment by CombesA** [comment]
Hey there !

I wanted to add some informations about this bug.

When drawing a LineString, no matter how many points there are, if the last two are duplicated, the line before those point will disappear when reaching the 18th zoom level.
For example, if we draw a LineString between A, B and B, the line between A and B will disappear, and I think it shouldn't.

Though I noticed some things :

- That behavior happens when there's at least 3 digits after the decimal point on the coordinates numbers.
When there's less than 3 digits after the decimal point, only a part of the line disappears, near the second duplicated point.

- That behavior does not occur if the duplicated points are not the last two.

- Even though the previous line disappears, there is apparently a bit of a line drawn. I guess it's the one between the two last points.

I made a JSFiddle as an example, there is two lines, one with three points, where the last two are duplicated, and another line with three point, where the first two are duplicated.
here it is : 
https://jsfiddle.net//9f5t5jcp/2/

Thank you in advance for your answer, keep up the good work !

**Comment by sumbulalvi** [comment]
Is there any update on this issue? Running into this as well. Can confirm @CombesA 's bug is occurring for me as well. (Last two points are duplicated = only a piece of the line gets drawn after zoom level 18)

**Comment by benheb** [comment]
I am setting `minzoom` on the source config and this still doesn't seem to work. If vector tiles are generated through zoom 11, they always disappear when I hit 12. This did not use to be the case...

**Comment by sinkingstones** [comment]
![image](https://user-images.githubusercontent.com/13111410/35800932-74d23efe-0aa5-11e8-8cd7-2c4082cee604.png)

**Comment by bart-1990** [comment]
I'm experiencing the same issue and I could fix it by setting maxzoom for the source to 24, also removing duplicate points didn't help.

**Comment by qeternity** [comment]
We're seeing this as well. Linestrings become very distorted at high zoom levels.

**Comment by mnutsch** [comment]
Hi, Is there any update on this issue? I would like to be able to zoom in further and still see all polygon lines. Thanks.

**Comment by mourner** [comment]
Fix for the issue coming in #9218. Apologies for addressing this so late! And thanks a lot to @CombesA for such a clear test case.
