### ISSUE TITLE
Rename "&&" and "||" expressions to "all" and "any"

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5227]
Capturing from slack:

@jfirebaugh proposed using `"all"` and `"any"` rather than `"&&"` and `"||"` (and addihng `"none"` as a convenience).

Pros:
> friendlier to people who don't (already) have a programming background

> consistent with existing filters, so there's one less new thing to learn / change when you're switching to expressions

The latter may be a con, too:
> if we keep them the same, would users easily think that you could nest an old-style filter within an expression?  Will it be clear to them which thing they're writing?
> "It's the same, but different" can be confusing

Validation would catch this issue, but:
> to a user with the wrong mental model, errors might be really confusing

**Comment by jfirebaugh** [comment]
One other pro: `"all"` and `"any"` read better in the lispy prefix-style expression syntax that we have (this is why I chose them for filters). "All" of the following are true: .... "Any" of the following are true: ....

**Comment by 1ec5** [comment]
I’ve always found `all`, `any`, and `none` to be very confusing, even when reading in prefix order. When using the runtime styling API’s filters, I’m usually thinking about a condition to be evaluated on each feature, rather than a description of the resulting set. `and`, `or`, and `not` fit better with the first mental model.

By comparison, in Objective-C and Swift, NSPredicate has an infix syntax that supports both `&&` and `and`, as well as (essentially) a prefix syntax that [uses the “and” terminology](https://developer.apple.com/documentation/foundation/nscompoundpredicate/1407855-init) as part of a factory method name.

**Comment by jfirebaugh** [comment]
@1ec5 I'm surprised you don't think in terms of `NSPredicateEditor`! 😉 

![image](https://user-images.githubusercontent.com/98601/30226854-6629519c-948c-11e7-9149-85d4930202aa.png)

**Comment by 1ec5** [comment]
Haha, you’ve got a good point there! Honestly, my mental model differs based on whether I’m coding (`and`) or using a UI like NSPredicateEditor that has additional wording like “of the following are true”. Maybe this speaks to a need for Studio UI that slightly differs from the underlying syntax, as with NSPredicate and NSPredicateEditor.

**Comment by anandthakker** [comment]
👍 for `any`/ `all`
