### ISSUE TITLE
Inconsistent transparency for multiple fill-extrusions

### ISSUE THREAD

**Issue by kekscom** [mapbox/mapbox-gl-js#5288]
**Refers to mapbox-gl-js 0.40.0**
Likely rendering fill extrusions in common 3d space is involved:
https://github.com/mapbox/mapbox-gl-js/pull/5101

Adding more than 2 fill-extrusion layers causes different transparency behaviour than for first 2.

### Steps to Trigger Behavior

- fill-extrusion layers 1+2 blend and transparency is applied to result
- subsequent fill-extrusion layers do not blend with others but at least 3d space is correct

### Expected Behavior

A: Either all fill-extrusion layers get transparency applied separately or
B: All fill-extrusion layers are blended and then transparency is applied. Guess this is intended and preferred.

<img width="1119" alt="screenshot 2017-09-14 10 11 42" src="https://user-images.githubusercontent.com/1887727/30419391-73798c28-9936-11e7-9247-a562548a832a.png">

**Comment by lbud** [comment]
Right — what you're seeing is based on layer order:
* Layer 1 is rendered to an offscreen texture.
* Layer 2 is rendered to an offscreen texture with knowledge of the depth values of Layer 1, and some fragments, which would be visible with only this layer rendered, are dropped due to failing depth testing in relation to already-rendered values in layer 1. However, fragments that overlap with layer 1 fragments and _pass_ the depth test are rendered.

Then in the main (translucent) rendering pass,
* Layer 1's offscreen texture is rendered back to the map at desired opacity. No further depth testing is done to discard fragments in relation to layer 2, so some fragments that are "behind" layer 2 are rendered anyway and will be visible if layer 2 is translucent.
* Layer 2's offscreen texture is rendered back to the map at desired opacity.

It's possible we could fix this down the road with clever use of stencil testing, but this may necessitate introducing more rendering passes and it's hard to say if/when this will be prioritized.

**Comment by lbud** [comment]
(In the meantime, this can be mitigated by potentially being strategic about layer order, or otherwise reducing the number of layers by using data-driven styling, which is always preferable for performance reasons.)

**Comment by kekscom** [comment]
I did not notice even my layer 2 (green roof) is transparent for buildings because of effective height of 0. With that in mind behaviour is consistent through all extrusion layers.
I think this is acceptable.
Thank you!
