### ISSUE TITLE
WebGL CanvasSource performance drop in 0.40.0

### ISSUE THREAD

**Issue by gpbmike** [mapbox/mapbox-gl-js#5301]
**mapbox-gl-js version**: 0.40.0

### Steps to Trigger Behavior

Add a webgl canvas source/layer.

### Expected Behavior

Should be a buttery 60fps like 0.39.1.

### Actual Behavior

Severe drop in framerate. In the example codepens below I'm using [plotty](https://github.com/santilland/plotty/blob/master/src/plotty.js) to generate a colorful webgl canvas. The only difference between the codepens is the `mapbox-gl-js` version.

The performance is heavily dependent on the size of the canvas being used. In this case it's 2000x2000, which is not uncommon for me.

It's probably the overhead of creating a large image on every render. 😢 
https://github.com/mapbox/mapbox-gl-js/pull/5155

#### 0.39.1
https://codepen.io/gpbmike/pen/oGXmRJ

#### 0.40.0
https://codepen.io/gpbmike/pen/jGPvpo

**Comment by gpbmike** [comment]
I can't seem to create a reduced test case for this so I'm going to close it and do more digging.

**Comment by gpbmike** [comment]
I have updated the description with a reduced test case.

**Comment by lbud** [comment]
🙁 right, likely a side effect of having to copy all pixels into an intermediary buffer #5155 — we can mitigate this for non-animated canvases actually (added in #5303), but unfortunately since #5155 is a workaround for a hardware bug I don't have ideas for making animated, WebGL-based canvas sources much faster easily. (Eventually down the road when Mapbox GL adds support for ["custom layers"](https://github.com/mapbox/mapbox-gl-js/issues/281) — that is, layers that define their own layout and shaders, using our existing pipeline — that'll be the way forward for fast custom WebGL overlays.)

**Comment by gpbmike** [comment]
I've been doing some additional tinkering in `mapbox-gl-js` with my broadwell processor machine (https://github.com/mapbox/mapbox-gl-js/issues/4262#issuecomment-320343557).

- I **reconfirmed the problem with `0.39.1`** when adding a webgl canvas source. 
- I **confirmed that the problem is fixed in `0.40.1`** when adding a webgl canvas source.
- I pointed to a local copy of `0.40.1` where [`readCanvas`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/source/canvas_source.js#L118-L140) simply sets `this.canvasData = this.canvas` and it still works. 🤔 

Now I suspect https://github.com/mapbox/mapbox-gl-js/issues/4262 was fixed and maybe there's no need for the intermediary `imageData` step?

**Comment by jfirebaugh** [comment]
Fixed in #5448/#5449; thanks @gpbmike!
