### ISSUE TITLE
Pitch view: POIs incorrectly perceived closer to viewer

### ISSUE THREAD

**Issue by knigal** [mapbox/mapbox-gl-js#5315]
![mapboxgl-poi-infront-low-fps](https://user-images.githubusercontent.com/1245766/30525502-6428b74e-9c10-11e7-9c89-41bdb7e9ae9c.gif)
When having a few POIs (points of interest such as markers/circles/images etc) crowded in one place on the map, it'd be "visually correct" if the POIs that are "closest" would be fully visible, while those more distant would be partially obscured - as if they were really behind them. With current mapboxgl version (v0.40.0) It is possible to see in my app that some POIs are unconditionally visible in front of others. As a result, the scene looks less realistic/credible. I would like to get the scene to looks more realistic by having the closer POIs always in front of the more distant ones.  

Is there a way to achieve that? Perhaps a setting/flag I can set?

Attached: screenshot of problem. While the view rotates, the orange POIs always obscure others - even when more distant from viewer

**Comment by ChrisLoer** [comment]
Hi @knigal, I'm just guessing based on the screenshot, but it looks like you added these POIs using the [Marker API](https://www.mapbox.com/mapbox-gl-js/api/#marker)? In that case, each of these POIs would be a DOM element, and the rendering order would be controlled by normal HTML conventions (i.e. based on order added, but can be overridden with the `z-index` CSS property). I'm not aware of any first class support for this, but you could listen either for `move` events fired by the map, or for mutations of the `transform` attribute of each marker element. Then you could set the z-index based on the y position of the transform (higher y -> closer to viewer -> higher z -> rendered in front). I'm kind of speculating here: you'd need to experiment to see if this actually worked well.

There is an alternative approach where Mapbox would do the sorting for you -- if you added all the markers as icons within the same layer (see https://www.mapbox.com/mapbox-gl-js/example/add-image/, you would have to use data-driven styling so that one layer could have multiple images), Mapbox would sort the icons based on their y-order (although the built-in sort order is the opposite of your request: higher/more-distant items would always sort on top).

**Comment by knigal** [comment]
@ChrisLoer Some of the POIs are set via the `Marker` api. These are the marker shaped icons. I guess I could have logic which modifies the z-index based on the rotation and the lat,lng coords. I may look into it and see if I can figure something out.

That being said, we are now in the midst of switching to data-driven style markers (based on https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors which is quite similar to the link you provided). This use case is being demonstrated by the circles. They are all set using the `source` features array and circle style APIs. The purple circles is one layer and the orange one is another layer. As you can see, the orange layer icon is always over the purple one. Even when it's more distant. Based on this behavior, I'd guess that if there's viewport-sensitive "z-indexing effect" of icons, it's not happening between markers of two different layers.   

Furthermore, it seems that when having POIs in the same layer, some always display over the others, even when further away from the viewer. If you observe closely the purple circles - you'll see that there are a couple of circles which always shows over the others, even when more distant.

Not sure if this info is enough to point out the issue. wdyt?

**Comment by ChrisLoer** [comment]
> I guess I could have logic which modifies the z-index based on the rotation and the lat,lng coords.

That could work, but it would probably be easiest to get it straight from the y-coordinate of the transform for the element (which mapbox will automatically update based on rotation/position/etc).

> Based on this behavior, I'd guess that if there's viewport-sensitive "z-indexing effect" of icons, it's not happening between markers of two different layers.

That's right, items in different layers are strictly ordered based on the layer. You'd have to move both items into the same layer _and_ it would have to be a symbol layer (i.e. "icon") to get relative sorting based on position (circles and other types don't do the position-based sorting).  Also as a minor technical point, the "z-indexing" I talked about would only apply to DOM elements (that is, things added with the Marker API).

**Comment by knigal** [comment]
> That could work, but it would probably be easiest to get it straight from the y-coordinate of the transform for the element (which mapbox will automatically update based on rotation/position/etc).

To clarify: 
Lets say I set the markers z-index to match the (negative value of the) y-coordinate. Then, in the northern hemisphere, northern markers have lower z-index so will be covered by the southern markers. This is the desired outcome. Now, when rotating the view (lets assume north now points downward), mapbox will rearrange the markers z-index (internally?) to have the more distant (southern) markers behind the closer (northern) icons? That detail seems to go against my understanding. Can you elaborate on this? Does this logic take into account the distance from the equator? Or does it actually resort the markers based on the distance from the viewer?

**Comment by ChrisLoer** [comment]
@knigal Sorry for the confusion -- here's what I meant when I wrote "y-coordinate" (look at the transform/translate on the marker element):

<img width="1104" alt="screenshot 2017-09-21 11 10 13" src="https://user-images.githubusercontent.com/375121/30711465-a5ed3588-9ebd-11e7-8448-c61c0c484f72.png">

Since the units are pixel coordinates on the screen, you don't have to worry about rotation/hemisphere etc.

**Comment by ChrisLoer** [comment]
Yes, that all sounds right. You could listen to `rotateend` to update the z-index, or you could just register a listener on the marker itself that updates the z-index whenever the transform attribute changes (with something like https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).

**Comment by knigal** [comment]
ok, great. I think I have all the info I need for now. Thanks!
