### ISSUE TITLE
Implement LAB/HSL color interpolation for expressions

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#5326]
The expressions PR is already merged into master, but it [removed support](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/function/convert.js#L30-L32) for LAB/HSL `colorSpace` property.

We should either add it back before a release (since it's a breaking removal), or remove its support fully (along with `color_spaces.js` and related code) if we don't plan on also implementing it on the Native side. 

cc @anandthakker @kkaefer

**Comment by mourner** [comment]
Another option would be to roll back expressions-based stop functions conversion until we reach feature and performance parity.

**Comment by anandthakker** [comment]
Oops, I intended to ticket this follow-up, but forgot to -- thanks @mourner .

@jfirebaugh had an idea about removing the `colorSpace` property from stop functions, and instead making it part of the `*-transition` properties.

**Comment by mourner** [comment]
Hmm, how would that look? `trasition` properties are for timed fades, while `colorSpace` controls the way colors are interpolated between stops in a function.

**Comment by anandthakker** [comment]
> trasition properties are for timed fades

Yeah, I think in order to use that approach we'd probably have to broaden the idea of what the transition properties are for.  The advantage, though, is that there would be a consistent way to control color interpolation both for DDS and for the case of transitioning between constant paint property values (e.g. via `setPaintProperty()` / `setStyle()`)

**Comment by jfirebaugh** [comment]
Retitled/de-labeled, given #5379.
