### ISSUE TITLE
Assess & improve performance of creating expressions

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5347]
We've made some good improvements on expression _evaluation_ performance, but we should also look into the cost of creating them (parsing, typechecking, compiling), and also of first converting stop functions into expressions.  It's surely slower than creating pre-expression functions, and so we should expect the performance of parsing a style layer to have been degraded.

**Comment by ryanbaumann** [comment]
One test to run that's a common use case is with the `data-join` technique.  Since there are a lot of unique elements in the stops array, the conversion from stops to expressions may be a bottleneck under the hood.  Below is a quick example with 413k unique stops that illustrates the difference.

GL JS Master 170926 - https://bl.ocks.org/ryanbaumann/63ca44169e657d66c1878f1083017e85/953c8fe671adb9910e08e73845a565eb6d99263e

GL JS 0.40.1 - https://bl.ocks.org/ryanbaumann/db8a61f5d156274ecd56ea02d6388322

**Comment by anandthakker** [comment]
Good call @ryanbaumann & thanks for the test case
