### ISSUE TITLE
Functions converted to expressions should not produce warnings

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5352]
It seems that in various situations, evaluating an expression-converted function can produce a console warning. Among other things, this pollutes test output (#3900) with warnings like "No default property value available" and "Expected value to be of type Number, but found Null instead."

While expressions may have safer semantics, functions should continue to behave how they have always behaved. Unless I'm missing something about the purpose of these warnings, I don't think it's necessary, at this point, to call out the existing quirks of function evaluation behavior with warnings.

cc @anandthakker

**Comment by anandthakker** [comment]
@jfirebaugh yeah -- in general, we're logging errors any time they occur in expression evaluation.  The way functions are being converted right now, that means they happen for mistyped or missing input (and the case where the spec doesn't provide a default value, though that's more of an edge case specific to function conversion).

We could either adjust how conversion happens, including whatever preflight checks are needed to ensure no such error occurs (this might be slower), or just modify the logic in the wrapping `catch {}` for the converted-function case to not log any errors.

**Comment by mourner** [comment]
The third option I've been advocating is reverting the old-style stop functions to the pre-expressions code, accepting some possible duplication in exchange for having them behave exactly the same as before.

**Comment by anandthakker** [comment]
> The third option I've been advocating is reverting the old-style stop functions to the pre-expressions code, accepting some possible duplication in exchange for having them behave exactly the same as before

I think we should try as hard as we can to avoid that.  Having the old-style functions go through expressions will be simpler to maintain and will help us find bugs and performance issues with expressions much sooner.  Also, other than the error logs mentioned in this ticket, I think they _do_ behave exactly the same as before.

**Comment by mourner** [comment]
I just personally don't like the idea of making the performance worse in a stable release for existing users (both creating and running functions), combined with a high risk of breaking edge cases, in the hope that maybe we'll recover it somehow in future releases thanks to increased exposure. The regression may not be that noticeable in average use cases, and it improved a lot since the initial merge, but it's still definitely there, and regressions like this tend to pile up. It feels safer to have expressions as purely added functionality for the initial release rather than replacing a critical part of the existing code path. I don't think the old functions code would be hard to maintain because it's very short and simple, especially compared to expressions. But I see the advantage of going full-on with expressions too, so won't insist — just sharing my thoughts. :)
