### ISSUE TITLE
Roads :: Not rendering properly in MapBox GL at random zoom levels

### ISSUE THREAD

**Issue by mrunalkap** [mapbox/mapbox-gl-js#5355]
The road elements (Line feature) appear jagged or broken at random zoom levels. Please guide to an existing issue (if any) or provide appropriate solution.

Tested in browsers : Safari, Chrome, Firefox, Edge

![screen shot 2017-09-26 at 11 27 50 am](https://user-images.githubusercontent.com/32289152/30844856-85485ed0-a2ae-11e7-9bd1-a4177ac55e47.png)

![30844877-9766b5f8-a2ae-11e7-81ee-158e08cc2dff](https://user-images.githubusercontent.com/32289152/30846562-c8bfcc64-a2b5-11e7-8b9b-904890c30be5.jpg)

![30844893-a755411e-a2ae-11e7-8ffe-007d78ea44b6 copy](https://user-images.githubusercontent.com/32289152/30846566-ccaa9854-a2b5-11e7-8795-686b77741daa.jpg)

**Comment by jfirebaugh** [comment]
Hi @mrunalkap, thanks for using Mapbox. When filing an issue, please use the provided issue template so that we have enough information to diagnose your issue. In particular, we need to know what version of Mapbox GL JS you are using, and in this case, we need you to provide a minimal, self-contained demonstration of the issue.
