### ISSUE TITLE
Display some kind of warning if mapbox-gl CSS is is missing

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5359]
We should somehow issue a warning if the mapbox-gl CSS is missing.  As suggested by @nfarina in https://github.com/mapbox/mapbox-gl-js/issues/4048#issuecomment-332560458, a div added to the map's target element and hidden by our default CSS should do the trick.

**Comment by eltonjuan** [comment]
A random callout but if you're delivering your CSS in JS (e.g. local development with Webpack) the injection of this div causes Mapbox's calculation for determining the canvas size to be thrown off by the amount of the div. 

Not really an issue since you should be generating a CSS bundle in production, but was driving me a little mad (thinking my CSS rules were messed up). Figured I'd call it out in case anyone else goes searching...

**Comment by tywoodpav** [comment]
@eltonjuan How did you get around this? V annoying

**Comment by Srounsroun** [comment]
@tywoodpav Make sure to reference css link in index.html headers 

```<link href='https://api.mapbox.com/mapbox-gl-js/v0.42.0/mapbox-gl.css' rel='stylesheet' />```

and load the correct **style** in mapbox:

```
var map = new mapboxgl.Map({
container: 'YOUR_CONTAINER_ELEMENT_ID',
style: 'mapbox://styles/mapbox/streets-v10'
});
```

as describe in https://www.mapbox.com/install/js/bundler-install/
