### ISSUE TITLE
Allow webpack/rollup treeshaking

### ISSUE THREAD

**Issue by alex3165** [mapbox/mapbox-gl-js#5408]
I love mapbox-gl and use it a lot but one thing that I would love to see improved is the bundle size (currently 565kb). It would be nice to allow treeshaking for users chasing small bundle size, which I think would imply a few changes:

- Change modules from CommonJS to ES2015 (import / export)
- Compile ES2015 modules to ES5 with Babel
- Expose two versions of the bundle, an ES5 version and an ES2015 one using the entry `jsnext:main` of package.json

This way users can treeshake mapbox-gl and get a smaller bundle size.

**mapbox-gl-js version**:

0.40.1

### Expected Behavior

smaller bundle size

### Actual Behavior

bundle of size 565kb

**Comment by jfirebaugh** [comment]
Hey @alex3165, thanks for the suggestion! We'll change to ES modules once there's tooling support for bundled Web Worker source code (https://github.com/rollup/rollup/issues/1029).

My guess is that mapbox-gl-js will not gain much from treeshaking however; I don't think there's much that can be statically determined as "unused". For example, it can't be determined at build time if certain source and layer types are not used -- that's determined only when a particular style is loaded.

Closing here since this is not currently actionable.
