### ISSUE TITLE
Add unit test checking that each expression type is documented

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5438]
Check that each expression has an entry in the style spec JSON and in `docs/style_spec/_generate/expression-metadata.js`, and vice versa

**Comment by jay-manday** [comment]
hi Anand, been doing some experimenting with mapbox gl and really into it, is this issue still open?

**Comment by anandthakker** [comment]
Yes, still open!

**Comment by jay-manday** [comment]
Cooool sure thing, does this entail cross reffing [style-spec.js](https://github.com/mapbox/mapbox-gl-js/blob/6465c04107f34dceb2c16bfd824fdf8c3380fc53/docs/pages/style-spec.js) with [the expression tests](https://github.com/mapbox/mapbox-gl-js/tree/f839a8c25725cf799bf9026e76792128893024f2/test/integration/expression-tests) just curious on where is a good place to start? is there some type of reg-ex search you'd typically use to make the process go quicker? to clarify this issue is just making sure there is parity between the style-specs for methods and the docs, correct?

**Comment by anandthakker** [comment]
> to clarify this issue is just making sure there is parity between the style-specs for methods and the docs, correct?

@jay-manday the docs are generated _from_ the style spec (and [expression_metadata.js](https://github.com/mapbox/mapbox-gl-js/blob/ea28e719f80c760347deabfc799c4bcc7e1feb05/docs/components/expression-metadata.js)), so this issue is about making sure that each expression in the 'registry' exported by [style-spec/expression/definitions/index.js](https://github.com/mapbox/mapbox-gl-js/blob/ea28e719f80c760347deabfc799c4bcc7e1feb05/src/style-spec/expression/definitions/index.js) has a corresponding entry in the [style spec JSON](https://github.com/mapbox/mapbox-gl-js/blob/ea28e719f80c760347deabfc799c4bcc7e1feb05/src/style-spec/reference/v8.json#L2015) and expression-metadata.js

**Comment by jay-manday** [comment]
Thanks for clarifying! Happy to work on it :)
