### ISSUE TITLE
overlay with extrusion not possible

### ISSUE THREAD

**Issue by VNuhaan** [mapbox/mapbox-gl-js#5457]
I have a base layer and an overlay layer, both with buildings (fill-extrusions). Since version 40.0 I see extrusions (buildings) from the base layer pointing thru the overlay layer. It looks like that the drawing of extrusions ignores the layering order.

**Comment by lbud** [comment]
@VNuhaan can you please provide a screenshot or demo of what you're seeing? It's possible what you're describing could be intended behavior: v0.40.0 introduced a breaking rendering change in https://github.com/mapbox/mapbox-gl-js/pull/5101, after which fill-extrusion layers share the same depth space in order to prevent physics-defying rendering like the left example below:
![image](https://user-images.githubusercontent.com/3170312/31567992-faf472ba-b026-11e7-9532-b16f6eb318b0.png)

(This _can_ result in some particular quirks as described in detail at https://github.com/mapbox/mapbox-gl-js/issues/5288#issuecomment-330362168, wherein layer order can determine which extrusions are visible behind other translucent layers.)

**Comment by VNuhaan** [comment]
high resolution overlay:
![overlay](https://user-images.githubusercontent.com/5813554/31634350-7a4fe64a-b2c3-11e7-9ae8-30bd7d10a75c.png)
low resolution base layer:
![base layer](https://user-images.githubusercontent.com/5813554/31634397-a155593c-b2c3-11e7-9174-0696aef50ab1.png)
combined:
![base and overlay](https://user-images.githubusercontent.com/5813554/31634413-b4658a6a-b2c3-11e7-82a4-b19422690418.png)

Maybe it is an idee to combine extrusions of layers that are defined after each other.

**Comment by VNuhaan** [comment]
Any news on this subject?

I think this behavior is indeed due to this #5101. But now I don't understand the layer order anymore. Fill-extrusions has there own ordering, beside all other types which use the layer ordering. The combination looks weird (picture in last screenshot above).

I was planning to add 3D trains in the near future. But without proper layering order it will end up nothing.

Please make it possible to ovelay fill-extrusions that can be smaller than fill-extrusions of layers below and draw the overlaying smaller fill-extrusions.

**Comment by lbud** [comment]
@VNuhaan I'm having a hard time seeing the issue in a static screenshot and diagnosing whether this behavior is incorrect. If you can provide a minimal interactive demo (jsfiddle or something similar) that would be helpful. Thanks!
