### ISSUE TITLE
TypeError: Cannot read property 'resize' of undefined in puppeteer (headless chrome)

### ISSUE THREAD

**Issue by stereobooster** [mapbox/mapbox-gl-js#5460]
**mapbox-gl-js version**: v0.40.0
**os**: OS X El Capitan 10.11.6
**browser**: HeadlessChrome/63.0.3205.0

### Steps to Trigger Behavior

 1. git clone https://gist.github.com/stereobooster/35ca47edbb4b2340a3d92e3c6a32dc4b
 2. cd 35ca47edbb4b2340a3d92e3c6a32dc4b
 3. yarn
 4. yarn test

### Expected Behavior

No exception is thrown

### Actual Behavior

Exception thrown `TypeError: Cannot read property 'resize' of undefined`

```
yarn test
yarn run v1.1.0
$ node index.js
Caught exception: TypeError: Cannot read property 'resize' of undefined
    at e.resize (https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.js:398:5311)
    at new e (https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.js:398:2935)
    at file://mapbox-gl-puppeteer/diagnostics.html:51:23

Done!
```

**Comment by mollymerp** [comment]
Hi @stereobooster , 
Thank you for submitting your issue. I'm sorry you're having trouble using mapbox-gl-js. Could you please use the provided issue template for this issue? It includes spaces for key information like the version of mapbox-gl-js that you're using and exact steps to reproduce the issue. Because these are missing from your report, we cannot diagnose and fix the issue. 

Can you please also provide a self-contained example without external dependencies in as few lines of code as possible to reproduce the error on jsfiddle or jsbin?

**Comment by stereobooster** [comment]
@mollymerp all data is present. Same data, but in template

**mapbox-gl-js version**: v0.40.0

### Steps to Trigger Behavior

 1. git clone https://gist.github.com/stereobooster/35ca47edbb4b2340a3d92e3c6a32dc4b
 2. yarn
 3. yarn start

### Expected Behavior

No exception is thrown

### Actual Behavior

Exception thrown `TypeError: Cannot read property 'resize' of undefined`

**Comment by mollymerp** [comment]
you need to add `headless:false` option because headless chrome does not currently support webgl. `const browser = await puppeteer.launch({headless: false});`

https://github.com/GoogleChrome/puppeteer/blob/2b7951473d329d8e592750d68c61f689d651069b/lib/Launcher.js#L83-L90

**Comment by stereobooster** [comment]
feture request in chromium bugtracker https://bugs.chromium.org/p/chromium/issues/detail?id=617551

**Comment by asafbe** [comment]
Hi,
I'm getting the same error while running on electron 1.6.15 on VM. any idea how to solve this issue? tried to disable GPU call app.disableHardwareAcceleration() with no luck.
