### ISSUE TITLE
Fatal error when running new benchmarks in full bench run

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#5487]
When adding new benchmarks and running the full bench run, benchmarks quit once they reach the new tests and the page disappears completely:
![image](https://user-images.githubusercontent.com/3170312/31800120-5e955480-b4f3-11e7-8402-6d89d2287582.png)

* This does not happen when running _only_ the new test with the hash parameter
* This _does_ happen when running all tests with a `?no-master` parameter.

**Comment by jfirebaugh** [comment]
The error handling in benchmarks_view.js is essentially non-existent right now. I've seen this error before, and what was happening is that one of the benchmarks was throwing an exception, but then instead of presenting the error, the view was trying to present the results. I think if you set a breakpoint at `benchmarks_view.js:364` and look at the variables at that point, there's one that contains the actual error.

**Comment by lbud** [comment]
🤦‍♀️ thanks @jfirebaugh, that was it. I'm adding rejection handlers to all `createMap` invocations to catch map errors better.
