### ISSUE TITLE
Sometimes failed to highlight features

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#5488]
I want to highlight the features when mouse move, but sometime could not succeed.

**mapbox-gl-js version**:
0.40.1
### Steps to Trigger Behavior

https://jsfiddle.net/jingsam/rj16bqa4/2/

### Expected Behavior

Highlight the features that mouse hovers

### Actual Behavior
![qq20171020-124148-hd](https://user-images.githubusercontent.com/1522494/31805538-1aefaee6-b594-11e7-8419-84d0720350a3.gif)

**Comment by kristfal** [comment]
This behavior is expected because you're using a line layer in your base style, so your highlight function is only called when your cursor hovers over the line. 

If you add a transparent fill layer to your base data and listen on that transparent layer, things will work as you expect. [Here](https://jsfiddle.net/rj16bqa4/3/) is a working example.
