### ISSUE TITLE
circle layers with invisible strokes don't render in 0.41.0

### ISSUE THREAD

**Issue by shongololo** [mapbox/mapbox-gl-js#5496]
version 0.41 breaks setLayoutProperty, for example:
```
map.setLayoutProperty('mylayer', 'visibility', 'visible')
```
has no effect with v 0.41 whereas it works perfectly in v 0.40

**Comment by lbud** [comment]
Thanks for your report @shongololo. Can you please create a minimal JSFiddle that reproduces the issue?

**Comment by shongololo** [comment]
Here is a JS fiddle:
https://jsfiddle.net/shongololo/rmxez25s/5/
The example is linked to a mapbox studio map style.

Note that if you change the jsfiddle external resource for `mapbox-gl-js` from version `0.40.1` to version `0.41.0` the map layer toggle stops working.

**Comment by ChrisLoer** [comment]
Thanks for the help @shongololo! The problem was not actually in `setLayoutProperty`, but in the rendering of circle layers.

PR #5429 introduced a change (https://github.com/mapbox/mapbox-gl-js/pull/5429/files#diff-f7d822aac0b25e51513a390117f672bd) that avoids drawing layers that are completely invisible. The `isOpacityZero` logic in `circle_style_layer.js` is slightly wrong, so that if the _stroke_ of a circle is 0-width or transparent, the _whole_ circle will be hidden, even if the _fill_ of the circle is visible.

We'll get a fix out soon.
