### ISSUE TITLE
I want to use mapmyindia vector tile ? i don't want to use openstreet vector tile . in react js

### ISSUE THREAD

**Issue by anujsinghwd** [mapbox/mapbox-gl-js#5517]

**Comment by planemad** [comment]
@anujsinghwd please provide a clear description of your issue per the [contributing guidelines](https://raw.githubusercontent.com/mapbox/mapbox-gl-js/5cee82e4dd0fd14e2a3ddec251b29ff26777e6c4/.github/ISSUE_TEMPLATE.md). If your issue is not a bug or feature request, you might want to ask your question in stackoverflow.

**Comment by anujsinghwd** [comment]
thanks @planemad
