### ISSUE TITLE
Error in Paint benchmark: Uncaught TypeError: Cannot read property 'lineAtlas' of undefined

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5543]
Run `yarn start`, open http://localhost:9966/bench?no-master#Paint, and let it run. Open the console:

```
Uncaught TypeError: Cannot read property 'lineAtlas' of undefined
    at Painter.render (painter.js:276)
    at Map._render (map.js:1460)
```

Bisect says the first bad commit could be any of:
135561825addae07b253bab2167cee72f00f3ac9
3e51b6cf588e47284d9e714477d72a2d476355eb

cc @ChrisLoer @ansis

**Comment by ChrisLoer** [comment]
This is happening because we call `teardown` (and thus remove the map's `style`) while there's a `_render` call queued via `requestAnimationFrame`. Would it make sense to fix this by just putting a guard clause in `_render` to exit if there's no style defined?

This was probably triggered by our changes because the collision animations now require us to keep animating the map a bit after placement reaches steady state.

**Comment by jfirebaugh** [comment]
`teardown` calls `Map#remove`, which should cancel any pending animation frames. It does cancel the `this._frameId` one. Did viewport collision detection add another animation frame callback?

**Comment by ChrisLoer** [comment]
Oh, I see that now. No, we just used the existing `_rerender` which should be covered by that logic. So for one run I did, of the six maps that get created, at the time of `teardown` four of them had a `_frameId` and two of them had a null `_frameId` (which should be fine, if they're done rendering, but should also mean there's no pending `requestAnimationFrame`). The crash happens in a render call with the `_frameId` already set to null... which doesn't look like it's supposed to be able to happen.

Any ideas, @ansis?
