### ISSUE TITLE
Line-dasharray changes when zoom level changes

### ISSUE THREAD

**Issue by bart-1990** [mapbox/mapbox-gl-js#5567]
**mapbox-gl-js version**: 0.40.1

I'm trying to draw a geoJSON line (multiple features) with a paint property line-dasharray of  [0, 4, 3].
This dashed line looks perfect when the map is maximally zoomed in. However when I zoom out, I can see that the dasharray is somehow being recalculated and is giving me unwanted results. I expect the dashes (width and spaces) to look exactly the same at each zoom level. So zooming out should only give me fewer dashes  (because the total length of the line gets shorter) and not different dash lengths and spaces.

In short: I expect the pattern to look like the one of the first image all the time.
**Maximum zoom**
<img width="977" alt="screen shot 2017-10-31 at 16 30 09" src="https://user-images.githubusercontent.com/7540719/32234486-39068112-be5d-11e7-866c-2ead8d465281.png">

**Less zoom**
<img width="852" alt="screen shot 2017-10-31 at 16 30 17" src="https://user-images.githubusercontent.com/7540719/32234694-c605f0fc-be5d-11e7-8a49-f7ddcc864192.png">

**Even less zoom**
<img width="94" alt="screen shot 2017-10-31 at 16 30 42" src="https://user-images.githubusercontent.com/7540719/32234483-38d18da4-be5d-11e7-8875-330708654ff8.png">

If this change in the dashes and their spaces is expected behaviour, is there a way that I can do some calculations so that my dasharray would look exactly the same at each zoom level?

**Comment by ansis** [comment]
@bart-1990 yes, this is currently the expected behavior. The dash/space lengths are exact at round zoom levels (1, 2, 3, etc) but not fractional zoom levels (1.32, 2.89, 3.74, etc).

If we rendered exact dash/space lengths at every fractional zoom level it would look like the dashes slide along the line when you zoom in and out. Imagine zooming in a tiny bit, creating a tiny bit of extra space on the line. You would need to add part of a dash at one end and shift all the other dashes over a bit. This looks really distracting when zooming.

At the time we decided that the not-ideal dash stretching you're seeing was better than the unwanted sliding effect. We've thought about stretching while zooming and resetting when stopping but that probably has it's own set of tradeoffs.

**Comment by bart-1990** [comment]
The comment above makes sense but still my lines look pretty bad when zooming out, especially because they are animated (see the video attached to this comment). I animate the dashes with an interval function which rotates between an array of line-dasharray patterns. Would there be another way to achieve what I'm trying to do?

[route.mp4.zip](https://github.com/mapbox/mapbox-gl-js/files/1437173/route.mp4.zip)

**Comment by kiprou** [comment]
@bart-1990 I have the exact same problem. Tried following the official [ant path demo](https://docs.mapbox.com/mapbox-gl-js/example/animate-ant-path/), and couldn't get it to play nice. At most zoom levels it looks totally wild. Did you ever find a workaround?
