### ISSUE TITLE
Remove "enum" type from documentation

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5577]
We don't really have enums in the expression type system, and I don't think they're adding much clarity in the documentation either. We should just document these properties as having type "string" with some requirements. Our documentation text already lists the possible values, it should just replace "enum" with "string" and format the possible values as string literals:

> #### visibility
> Layout property. Optional [_string_](https://www.mapbox.com/mapbox-gl-js/style-spec/#types-string). One of `"visible"`, `"none"`. Defaults to `"visible"`.

**Comment by jingsam** [comment]
what about "color",?JSON have no color types, they are strings.

**Comment by anandthakker** [comment]
Good point, @jingsam  --  since color is a distinct type in the expression type system, when we encounter string values where a color is expected, we automatically coerce them to color values (using [`to-color`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-types-to-color)), so the problem described here fortunately doesn't extend to colors.

**Comment by jfirebaugh** [comment]
It's true we're using a string representation for colors in JSON. But it is a distinct, full-fledged type in the style specification domain -- certain properties are colors, not just arbitrary strings, and there are expressions operators that require string arguments, or return string results.

**Comment by hyperknot** [comment]
The docs are still linking to the non-existing enum types though, on this link: https://www.mapbox.com/mapbox-gl-js/style-spec/#types-enum
