### ISSUE TITLE
`Heatmap-color` does not update on setPaintProperty()

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapbox-gl-js#5627]
**mapbox-gl-js version**: 0.41.0

### Steps to Trigger Behavior

 1. Create a heatmap layer 
 2. Run map.setPaintProperty('layer', 'heatmap-color', 'new-heatmap-color-expression')

### Expected Behavior

Heatmap changes color the next rendered frame

### Actual Behavior

Heatmap does not change color until running setPaintProperty a second time with a new value for 'heatmap-color-expression'.  

### Minimal Example

https://jsbin.com/wivixowata/edit?html,output

cc @mourner

**Comment by Syntaf** [comment]
Looks like the bug is related to **HeatmapStylerLayer#_applyPaintDeclaration** grabbing a stale `heatmap-color` value on the first change, instead of the intended updated one. The code above will 'work' if you wait around for a later render cycle (then mouse the map or zoom in to cause a map update):

```javascript
_applyPaintDeclaration(name: any, declaration: any, options: any, globalOptions: any, animationLoop: any, zoomHistory: any) {
    super._applyPaintDeclaration(name, declaration, options, globalOptions, animationLoop, zoomHistory);
    if (name === 'heatmap-color') {
        console.log(this.colorRampData);
        const len = this.colorRampData.length;
        var self = this;
        setTimeout(() => {
            for (let i = 4; i < len; i += 4) {
                const pxColor: Color = self.getPaintValue('heatmap-color', {heatmapDensity: i / len, zoom: -1});
                // the colors are being unpremultiplied because getPaintValue returns
                // premultiplied values, and the Texture class expects unpremultiplied ones
                self.colorRampData[i + 0] = Math.floor(pxColor.r * 255 / pxColor.a);
                self.colorRampData[i + 1] = Math.floor(pxColor.g * 255 / pxColor.a);
                self.colorRampData[i + 2] = Math.floor(pxColor.b * 255 / pxColor.a);
                self.colorRampData[i + 3] = Math.floor(pxColor.a * 255);
            }
            self.colorRamp = RGBAImage.create({width: 256, height: 1}, self.colorRampData);
            self.colorRampTexture = null;
            console.log(self.colorRampData);
        }, 500);
    }
}
```

Seems like the 'Main Thread / worker split' section of `ARCHITECTURE.md` is still a WIP, so I'm not quite sure how the different threads are interacting within the code. Is the above information of any use to you guys? Or was that pretty obvious from the start :P
