### ISSUE TITLE
map.getStyle() after map.setFilter(id, null) returns invalid Style JSON

### ISSUE THREAD

**Issue by NicolasMinghetti** [mapbox/mapbox-gl-js#5637]
**mapbox-gl-js version 0.41.0**:

### Steps to Trigger Behavior

 1. Add a source and layer to mapboxGL
 2. Set the filter of the layer to null
 3. map.setStyle(map.getStyle()); throws an error

https://jsbin.com/simifaf/2/edit?html,js,console,output

### Expected Behavior

Set a filter to null with map.setFilter() is allowed by mapboxGL https://github.com/mapbox/mapbox-gl-js/pull/4777
map.setStyle() should allow layers to have filter: null

### Actual Behavior

map.setStyle() throws an error if a layer has its filter to null

**Comment by anandthakker** [comment]
@NicolasMinghetti thanks for reporting this issue, and for including a test case!

It's true that `Map#setFilter()` accepts `null` as a way to remove a layer's filter.   However, `Map#setStyle()` (and, similarly, `Map#addLayer()`) expect layers that conform to the [Mapbox GL Style Specification](https://www.mapbox.com/mapbox-gl-js/style-spec#layer-filter), which doesn't currently allow for filter to be `null`.

If you want to remove a layer's filter via `setStyle`, you can do so by _omitting_ the `filter:` property from the layer (rather than setting it to `null` or `undefined`)

**Comment by jrd** [comment]
But then `map.getStyle()` should conform to the **Mapbox GL Style Specification**.
Why `getStyle()` returns layers with a filter attribute value as null?

You're right, `setStyle()` is doing the right job, but `getStyle()` does not.

**Comment by anandthakker** [comment]
Ah - good point @jrd -- I'll reopen this and change the title to reflect that issue.
