### ISSUE TITLE
Add 'anchor' option for Markers

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5640]
Following up from https://github.com/mapbox/mapbox-gl-js/pull/4751, it would be nice to add an 'anchor' option for `Marker`, similar to the one in `Popup`: https://github.com/mapbox/mapbox-gl-js/blob/f11b7640a2b6d589ef8d2d7297c4d9167ae94f47/src/ui/popup.js#L37-L42

**Comment by jay-manday** [comment]
Happy to work on this if no one has it in their queue! I can see this being pretty helpful for myself and other users as well.

**Comment by anandthakker** [comment]
@jay-manday I don't think anyone's claimed it yet, so please feel free!

> Do we want to export a MarkerOptions type as done in popup as well?

Couldn't hurt!

**Comment by jay-manday** [comment]
Hi @anandthakker I've been working on this today and I think I made a bit of progress though a little stumped as to why my tests are failing. 

I'm getting an `Cannot read property 'anchor' of undefined` in testing. 

When you get a chance would you mind taking a look? I've tried a few things like setting default anchor and also did some snooping in the test file for marker.js but a little unsure of how best to proceed.

[Here's where i'm at :/](https://github.com/mapbox/mapbox-gl-js/commit/c9e6b40bb43542c3b550d8b26cb58b16ce5cae10)

Thanks for taking the time to review!

**Comment by jay-manday** [comment]
Hi @anandthakker 

I thiiiink i have things working as needed though would love a review of my work before making a PR to the master branch on your end. I did some digging on the origins of the issue was a pretty cool learning experience! 🌀💡🎉✨ 

Heres the work done on my brach:
https://github.com/jay-manday/mapbox-gl-js/pull/2/commits/47d1243057b5b4e6324ee0508051ad4f7499eca0

I also went ahead and manually wrote the test for the marker file too. n_n

**Comment by andrewharvey** [comment]
Hi @jay-manday nice to see you implementing this! Feel free to go ahead and open that PR as that's where the review typically takes place, even if you feel it's not 100% ready, you can just mention it's a WIP.

The options for Popup's anchor are   `'top'`, `'bottom'`, `'left'`, `'right'`, `'top-left'`, `'top-right'`, `'bottom-left'`, and `'bottom-right'. I think that's what we should implement for the Marker anchor.

**Comment by jay-manday** [comment]
Hi @andrewharvey, totally! I'll make a PR and we can further discuss the work so far. Thanks for pointing me in the right direction as to the desired anchor options. 

I think I went down a wrong turn with my reasoning, while investigating how the marker renders onto the map and made the assumption that we wanted to anchor the marker via pixel values rather than css. I will definitely will factor this into my PR. n_n
