### ISSUE TITLE
Discussion about releasing incremental patch updates / bug fixes

### ISSUE THREAD

**Issue by shongololo** [mapbox/mapbox-gl-js#5659]
This is not a bug or a feature request, but a request to please discuss / consider releasing incremental patch updates more frequently - i.e. bug fixes between the minor version updates.

For example, no updates have been released since version `0.41`. In the space of the intervening month several bugs have been resolved but it doesn't appear these will be available until `0.42`.

**Comment by jfirebaugh** [comment]
Hi @shongololo, thanks for the feedback. I understand the desire to get bug fixes as soon as possible, and we do releases as fast as our resources allow. We're aiming for a 4-6 week release cadence. On that cadence, we choose the release number based on what changes have been made since the prior release -- if there are significant new features, or breaking changes, we increment the minor version number, otherwise we increment the patch version number.

**Comment by shongololo** [comment]
Any chance of a two week release cycle? There seems to be solid momentum in general with plenty of bug fixes and new features along the way. Would just be nice to have access to bug fixes more quickly otherwise in some cases we end up going two months without an upgrade / access to new features.
