### ISSUE TITLE
Issue with mouse events on layers with "icon-anchor": "bottom"

### ISSUE THREAD

**Issue by QuentinFchx** [mapbox/mapbox-gl-js#5717]
**mapbox-gl-js version**: 0.42.1

### Steps to Trigger Behavior
[jsbin reproducing the issue](http://jsbin.com/nekumiqoce/edit?html,console,output)
 1. Add a layer whose `icon-anchor` layout property is set to `bottom`
 2. Add listeners to mouse events
 3. Hover an icon

### Expected Behavior
It should trigger `mouseenter` when you enter the icon (even if it's translated to match the anchor position) then nothing while your cursor in inside the zone.

### Actual Behavior
It triggers `mouseenter` and `mouseleave` each time you move your mouse in the zone.

**Comment by jfirebaugh** [comment]
The popup that's triggered is positioned such that it appears underneath the cursor. Since the popup is now between the cursor and the map feature, this triggers the `leave` event. Then the popup closes. The next mouse event triggers an `enter` event, and the cycle repeats.

To avoid this behavior, ensure that the popup is positioned clear of the cursor.

**Comment by QuentinFchx** [comment]
Alright thank you, I should've seen that 🙄.
I did not pay attention to the `pointer-events: auto` set on the popup-content, I'll override that for my use-case.
Sorry for the inconvenience 😅
