### ISSUE TITLE
Unable to set layer ordering

### ISSUE THREAD

**Issue by aabhishekbindal** [mapbox/mapbox-gl-js#5809]
Hi Team,

I am using Mapbox Studio, where I am loading multiple overlays on a map. Also there are use cases for overlapping overlays (Points/Polygons/ Polylines).

I want to keep my calls as asynchronous, and still want to set the orders of particular layers. What is the best way to achieve this?

**Comment by Scarysize** [comment]
There are two ways to achieve the correct layer ordering:

1. Move a layer after it has been added with `map.moveLayer`: https://www.mapbox.com/mapbox-gl-js/api/#map#movelayer
2. Or define where in the layer stack the layer should be added by supplying a `beforeLayer` as a second parameter when calling `map.addLayer(options, beforeLayer)`.

**Comment by aabhishekbindal** [comment]
@Scarysize What if I am not sure about whether the beforeLayer has been added or not ? (because at  present, adding layer is asynchronous in my application)
Is there any other way to manipulate the ordering based upon any single entity lets say z-offset term discussed here : https://github.com/mapbox/mapbox-gl-js/issues/3993

**Comment by jfirebaugh** [comment]
No, you'll need to use either `moveLayer` or the `beforeLayer` parameter.

**Comment by hmendezm** [comment]
Hu Guys.
 I am using moverLayer but it looks like it does not take effect the new order. My situation is that the user has controls to allow to add a layer to the map. The user can choose any kind of combination but the layer should be ordered according to business rules. for instance, if you add the traffic information layer and after zip code information layer. The user should be able to hover traffic and see information and hover zip code and see the information. The problem is the zip code layer cover traffic layer so I need always to the traffic layer in the top of zipcode. I also used layer beneath but it is not working. I checked the layer array and the order is ok but the map is not reflecting the order.
Best
hmendezm

**Comment by BoJIbFbI4** [comment]
Hi, 
Same here!
We have controls to drag&drop layers in list. In my case not moveLayer for every single layer doesn't work, and [before] (Angular) also.

**Comment by elliotclements** [comment]
Any update on this, I'm trying to use movelayer but it has no effect?

I check that my layers have loaded then run the movelayer function but my maps layers do not order correctly. Mapbox 3.14.0

**Comment by RodrigoTxx** [comment]
> Any update on this, I'm trying to use movelayer but it has no effect?
> 
> I check that my layers have loaded then run the movelayer function but my maps layers do not order correctly. Mapbox 3.14.0

i was working on the same issue, i have done the layer order and it  work just fine i add a  metadata  for timestamp and order the layers using the time they are add, i'm working now in just reorder the layers with a visual interface so i can put the layers the way i want changing  the order before they are add. i'm using Vue3/nuxt3.
