### ISSUE TITLE
return visibility in featuresAt()

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-js#582]
<code>map.featuresAt()</code> currently returns all layers for that point, even if they are not visible because of collisions. We should either not return hidden layers for those points or return with a <code>visible: false</code> key.

@ansis @jfirebaugh @mourner

**Comment by jfirebaugh** [comment]
Agreed. I think the default should be to omit hidden features, with an option to include them. Having the visibility available as a property on the resulting features is also a good idea.

**Comment by mcwhittemore** [comment]
Hidden features might be a thing people are using currently (intentionally or not) so providing the hidden attribute is the safest bet.

**Comment by steinbachr** [comment]
+ 1

**Comment by peterqliu** [comment]
+1 to a configurable option. having a `featuresAt` that matches visibility is useful when building interactivity with map elements. but when you're using the map as an interface to access the underlying dataset, retrieving the full data is useful

**Comment by musicformellons** [comment]
+1

**Comment by ansis** [comment]
`featuresAt` is replaced by `queryRenderedFeatures` and `querySourceFeatures`. `queryRenderedFeatures` only returns visible features. Symbols hidden because of collisions are not returned. `querySourceFeatures` can be used to get features independent of styling. I don't think we need an option for including hidden features right now.
