### ISSUE TITLE
Does cluster support vector tiles?

### ISSUE THREAD

**Issue by Roxyi** [mapbox/mapbox-gl-js#5856]
Hi, 

I found this example about cluster: [Create and style clusters](https://www.mapbox.com/mapbox-gl-js/example/cluster/)

I tried to add vector tiles source but it did not work. I wonder if the cluster supports vector tiles or if I wanna cluster points data from vector tiles, is there a way to do so?

Thanks

**Comment by jfirebaugh** [comment]
No, clustering requires special processing that is only possibly with GeoJSON sources at this time.

**Comment by Captain-Oski** [comment]
Any plan to push this special processing at work ? Thank

**Comment by matthieugayon** [comment]
what about that ? https://github.com/mapbox/vt2geojson

**Comment by waissbluth** [comment]
Are there any plans to implement this? Even if the clustering math is limited on a per-tile basis

**Comment by asmith13194** [comment]
Two years, any updates on this feature or are we still limited to used geoJson sources at this time

**Comment by csimpi** [comment]
nooo I'm bummed, just refactored the whole site using mapbox tiles instead of loading our big GeoJSON on client level all the time.... clustering should work with vector-tiles too

**Comment by rayer10** [comment]
"You can cluster data to put into a vector tile source using Tippecanoe, but can not create a cluster from a vector tile source on the fly without some custom code." We ended up using Tippecanoe to add clusters to vector tiles.

Great thanks to @ ryanbaumann

Link: https://github.com/mapbox/mapboxgl-jupyter/issues/71#issuecomment-411771580

**Comment by chinthakaherath** [comment]
Any updates on this feature or are we still limited to using geoJson sources?

**Comment by gcontrerasj** [comment]
Hello, have been any update on this feature? Thanks

**Comment by AndreyPhilippov** [comment]
Hello! Any updates?

**Comment by thejasonxie** [comment]
If you have the raw data in your postgis database, you can cluster it in real time.

Refer to this [clustering method](https://www.crunchydata.com/blog/postgis-clustering-with-dbscan?utm_source=dlvr.it) in postgis with the following the [distances in meters per zoom](https://wiki.openstreetmap.org/wiki/Zoom_levels) for the cluster radius. Then just return that data in tiles.

Because clustering can be very expensive at lower zoom levels, you can just return pre-compute at lower zoom level and return real time at higher zoom level.
