### ISSUE TITLE
avoid duplicating vector tile requests when renderWorldCopies is true

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#5897]
**mapbox-gl-js version**: 0.42.0

### Steps to Trigger Behavior

Load a map at zoom 0 where you can see multiple worlds rendered the 0/0/0 tile is downloaded multiple times, eg https://jsbin.com/ducekuz/1/edit?html,output (and see the network requests)

When setting `renderWorldCopies: false` like in https://jsbin.com/qulecek/edit?html,output the 0/0/0 vector tile is only downloaded once.

### Expected Behavior

The exact same tile should only be downloaded once.

### Actual Behavior

The exact same tiles are downloaded multiple times.

**Comment by andrewharvey** [comment]
- This should be partially nullified from a bandwidth perspective since the browser will serve the cached response.
- With `renderWorldCopies: false` the heap snapshot is 28.4M
![selection_810](https://user-images.githubusercontent.com/117278/34190996-0a6af628-e598-11e7-87ae-d687e8044c96.png)

- With `renderWorldCopies: true` the heap snapshot is 30.1M
![selection_811](https://user-images.githubusercontent.com/117278/34190991-05367434-e598-11e7-86df-b4556ac99dc7.png)


I'm not sure if it's doubling up the same tile data for different worlds or not, and if so if it's possible to de-dupe this. Tested with v0.43.0-beta.1

**Comment by ansis** [comment]
Thanks for opening this issue! Tiles copies need to be processed slightly differently to make symbols placement correct. The simplest way to handle this internally was to load an entirely separate copy of the tile. While this does result in some duplicate work, it doesn't really matter too much because it's a minor difference and no worse than the usual case of a viewport full of unique tiles. And as you noted, the browser cache eliminates the duplicate network request.
