### ISSUE TITLE
Tools to generate terrain RGB tiles

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#5969]
Since v0.43.0 supports raster-dem source, are there any tools to generate terrain RGB tiles? If Mapbox uses private tools, is there any plan to open source it, like tippecanoe?

**Comment by jfirebaugh** [comment]
cc @dnomadb

**Comment by dnomadb** [comment]
@jingsam yes, the tool we used to generate our `terrain-rgb` layer is open sourced over at: https://github.com/mapbox/rio-rgbify.

A caution -- because terrain tiles are by nature heavier than traditional vector or image raster tiles, you may run into problems uploading via the mapbox upload api depending on the precision -- or "interval" -- that you specify for the output, and on the complexity of the data you are attempting to encode.
