### ISSUE TITLE
Scroll zoom performance regresssion in v0.43.0

### ISSUE THREAD

**Issue by Wykks** [mapbox/mapbox-gl-js#5985]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

Use mouse scroll to zoom without pausing for about 2 second in 0.43.0
Do the same in version 0.42.2

### Expected Behavior

Smooth zooming

### Actual Behavior

The zooming is not smooth since version 0.43.0

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?

**Comment by Wykks** [comment]
Sure!
v0.43.0: http://jsfiddle.net/ygzqtoru/ 
v0.42.2: http://jsfiddle.net/ygzqtoru/1/

**Comment by jfirebaugh** [comment]
For me, there's no observable difference in scroll zoom performance between those two (Chrome 63.0.3239.132, 2017 MacBook Pro 13-inch).

Can you provide more details about your configuration, or attach a screen recording or profiling results that show the difference?

**Comment by ashleyclough** [comment]
I've noticed the issue as well in our own maps and confirm that I see the same problem in the fiddles that @Wykks has made - but only when zooming using the wheel on the Logitech mouse my Mac Pro. The behaviour is consistent in Safari, Chrome & Firefox. Using a touch pad to zoom appears to give a consistent response. Specifically: in 0.42.2 and previous, zooming with a the wheel would continue if you let it free-wheel under its own inertia, in 0.43.0 zooming stops immediately. Initially I'd put it down to issues with the logitech but it's now clear something changed in the move to 0.43.0.

**Comment by Wykks** [comment]
Doing about the same mouse scroll:
In v0.43.0:
![v0_43_0](https://user-images.githubusercontent.com/1236069/34822493-72753f18-f6c7-11e7-8887-19bbab20a103.gif)
in v0.42.2:
![v0_42_0](https://user-images.githubusercontent.com/1236069/34822498-77087dc4-f6c7-11e7-881a-1e98689e5d8a.gif)
It's not just about zoom speed, in v0.43.0 in you scroll very fast, the map doesn't really zoom, mapbox-gl seems to skip a lot of scroll in this version

**Comment by planemad** [comment]
Tried the v0.43.0 fiddle and seems pretty smooth. OSX+Chrome

![new1](https://user-images.githubusercontent.com/126868/34824939-7a8f8bb6-f6f6-11e7-8569-ffea5486f49a.gif)

**Comment by indus** [comment]
Seeing the same problem: Firefox 58, Windows

**Comment by indus** [comment]
Could this be a result of the reducion of the resolution of performance.now due to spectre (maybe some of us have patched browsers others not)?
https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/handler/scroll_zoom.js#L97

**Comment by ashleyclough** [comment]
Direct comparison in the same page: https://parallel.co.uk/zoom-test/ - v0.42.2 on left, v0.43.0 in the right. Performance difference is most acute in Chrome.

**Comment by indus** [comment]
I'm guessing this makes the difference: https://github.com/mapbox/mapbox-gl-js/commit/f599e50442e14b14dcb15a9508b06c39406762ab#diff-a840fbd98a2cde4bf645379553bc5a0c

**Comment by jfirebaugh** [comment]
Can someone try https://github.com/mapbox/mapbox-gl-js/compare/fix-5985 and tell me if that resolves the issue? I still can't reproduce it myself, but that seems like a plausible cause.

**Comment by indus** [comment]
@jfirebaugh While the patch looks reasonable, there is still the same noticible difference for me compared to older versions

**Comment by jfirebaugh** [comment]
Ok, I'm out of ideas then. If it's not that, then I'm skeptical that it's related to the `performance.now` changes. The scroll zoom behavior has used `performance.now` [since its inception](https://github.com/mapbox/mapbox-gl-js/commit/75aab6d39fa4d221db3c2b2e82df39f816287c5e#diff-e60957272552aeccdb45f65d82d523e1R47).

**Comment by pathmapper** [comment]
> When I use the mouswheel as fast as I can in v0.43.0 I only get small zoom effect. Looks like events if too frequent get dropped. Not so in v0.42.2.

Can reproduce this issue with Chromium on Linux (2 different Logitech mice), but **also** in v0.42.2.
Tried the following to count the number of times the mousheel is scrolled:
https://jsfiddle.net/kh3ovk8L/

For me it looks like this issue is not new since v0.42.2 and can't find an older release where this issue doesn't exist (got also the impression that this issue is worse in v0.43.0, but this is only a feeling).

**v0.42.2 - fast scroll** 

![v42_2_fast_12](https://user-images.githubusercontent.com/20856381/34906426-f435048c-f86d-11e7-89d1-25090908786b.gif)

**v0.42.2 - slow scroll** 

![v42_2_slow_12](https://user-images.githubusercontent.com/20856381/34906438-2f3f44d4-f86e-11e7-8b10-75b68db5126d.gif)
