### ISSUE TITLE
Glitchy rendering of MultiPolygon (no overlaps, renders fine in geojson.io)

### ISSUE THREAD

**Issue by nselikoff** [mapbox/mapbox-gl-js#6069]
**mapbox-gl-js version**: v0.44.0

### Steps to Trigger Behavior

I have a GeoJSON MultiPolygon consisting of four non-overlapping polygons that is rendering strangely as I zoom in and out:

![glitchy-sweden](https://user-images.githubusercontent.com/1994207/35463064-c9d7da4e-02bc-11e8-8ff9-2fe730ab74c7.png)

Demo exhibiting glitchy rendering: https://jsfiddle.net/2gxyn07q/

### Expected Behavior

![normal-sweden](https://user-images.githubusercontent.com/1994207/35463067-cbfa2d2c-02bc-11e8-9b53-dbb904ef2eb6.png)

Demo (via geojson.io) showing expected rendering: http://bl.ocks.org/d/b2579096f6bd5b098cd8f7dcdfe8db3d

### Actual Behavior

See https://jsfiddle.net/2gxyn07q/

**Comment by mollymerp** [comment]
hi @nselikoff thanks for using mapbox. Although this is technically valid GeoJSON, it doesn't follow the 'right-hand rule' for polygon coordinate winding order as seen on http://geojsonlint.com/, and that is a requirement for use in mapbox-gl-js due to how we tesselate geometries for rendering (using [earcut](https://github.com/mapbox/earcut))

more about that here: https://macwright.org/2015/03/23/geojson-second-bite#winding

**Comment by nselikoff** [comment]
Brilliant, thank you @mollymerp

**Comment by nselikoff** [comment]
@mollymerp I've updated the GeoJSON using geojson-rewind to follow the right-hand rule, and it passes geojsonlint.com, but is still exhibiting the same rendering issue. See https://jsfiddle.net/2gxyn07q/3/

Can you take another look please?

**Comment by mollymerp** [comment]
hmm @mourner do you think this is the same bug as #4922 ?
