### ISSUE TITLE
map.queryRenderedFeatures used on polygon returning inconsistent array of coordinates.

### ISSUE THREAD

**Issue by gorbypark** [mapbox/mapbox-gl-js#6070]
When moving the mouse around a polygon, map.queryRenderedFeatures is returning an array of coordinates that changes.  Here is a [jsfiddle](https://jsfiddle.net/eqdpfv6p/4/) with a working example showing the issue.  It's simply displaying a polygon, and if the mouse is moved into the right most corner, the returned features coordinates array changes length. 
   
If a dev tools console is opened, the demo will console.log the area of the polygon (using turf) as well as the feature array which can be drilled down into which shows the clearly the returned array is changing.  Anecdotally it is happens more often when there's a corner less than 90 degrees.
```
map.on('mousemove', function(e) {
  var features = map.queryRenderedFeatures(e.point, {
    layers: ['maine']
  });
  console.log(features[0]);
});
```

Tested with 0.44, 0.43 and 0.41 and all are showing the same behaviour.

**Comment by pathmapper** [comment]
I think this is expected behavior, because for zoom level 5 in your jsfiddle the polygon is tiled so your "right most corner" is located in a different tile: https://jsfiddle.net/eqdpfv6p/5/

![image](https://user-images.githubusercontent.com/20856381/35483044-8619ee0a-043d-11e8-9c05-db45d8d5416b.png)

If you zoom further out to have the polygon located in one tile, the `console.log` is the same for the whole feature: https://jsfiddle.net/eqdpfv6p/6/

See also the documentation for `queryRenderedFeatures`: 
https://www.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures

To get the correct area of the polygon you should use `turf.area` on your source polygon and not on a result of `queryRenderedFeatures`.

**Comment by gorbypark** [comment]
> I think this is expected behavior, because for zoom level 5 in your jsfiddle the polygon is tiled so your "right most corner" is located in a different tile: https://jsfiddle.net/eqdpfv6p/5/

I don't know how I missed that in the docs!  Thanks.
