### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by namibian15** [mapbox/mapbox-gl-js#6085]
**mapbox-gl-js version**: 0.44.0

Using a tried and tested vector data set, v 0.44.0 is on average 2 times slower compared to v 0.42.2. It is unclear to me where the problem actually lies. We have seen this performance degradation creep into versions subsequent to 0.42.2.

Thanks for a great product!

**Comment by mollymerp** [comment]
Hi @namibian15, 
Thank you for submitting your issue. Could you please use the provided issue template for this issue? It includes spaces for key information like the version of mapbox-gl-js that you're using and exact steps to reproduce the issue and, ideally, a minimal test case. Because these are missing from your report, we cannot diagnose and fix the issue.
