### ISSUE TITLE
Issue with loading static .mbtiles on Django local development

### ISSUE THREAD

**Issue by yoursweater** [mapbox/mapbox-gl-js#6087]
When I attempt to load my .mbtiles layer I run into a weird 304 error on my Django app:

```
map.on('load', function(e) {
   map.addLayer({
     'id': '06geojson',
     'type': 'fill',
     'source': {
       'type': 'vector',
       'url': '/static/data/us_census_tracts/06.mbtiles'
     },
     'source-layer': '06geojson',
     'paint': {
         'fill-color': '#000000'
      }
  })
})
```
Results in: GET /static/data/us_census_tracts/06.mbtiles HTTP/1.1" 304 0

This is what I see in my console: {type: "error", target: t, isSourceLoaded: true, source: {…}, sourceId: "06geojson"}

Does the Mapbox API have some sort of issue with loading .mbtiles? Or am I trying to load this layer in the wrong way?

**Comment by ttsirkia** [comment]
I'm not totally sure about this but I think you cannot use mbtiles as a vector source. They can contain many layers etc. To use vector like that, it should be in JSON format. If you want to use mbtiles, it is possible to run a server such as https://github.com/klokantech/tileserver-gl which can host the mbtiles file and serve it as a proper source for Mapbox GL. In that case, too, it would be `source` instead of `layer`.

**Comment by mollymerp** [comment]
Hi @yoursweater – thanks for using Mapbox!
@ttsirkia is correct, you cannot use an `.mbtiles` file as a vector tile source because the `.mbtiles` format represents an entire tileset (every single tile that has data in that tileset, for every zoom level) – you will need to either upload your `.mbtiles` file to [Mapbox Studio](mapbox.com/studio) or set up your own tile server as @ttsirkia suggests. For a local development tile server, mbview is an easy tool https://github.com/mapbox/mbview
