### ISSUE TITLE
Shaking image icon

### ISSUE THREAD

**Issue by Jinkwon** [mapbox/mapbox-gl-js#6096]
**mapbox-gl-js version**: 0.44.0

### Steps to Trigger Behavior

 1. https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/
 2. Shaking image icon.
 3. Attached example gif file

![shaking](https://user-images.githubusercontent.com/1798916/35792091-b46f816e-0a8e-11e8-83ae-fc03abf55649.gif)

### Expected Behavior
Text label is fine, but image icon is shaking little bit.

### Actual Behavior
Not shaking.

**Comment by jfirebaugh** [comment]
I believe what you are seeing is the result of a design compromise between placing icons exactly at their geographic location, and aligning them to the pixel grid. When a gesture such as a drag is in progress, we icons are placed exactly at their geographic location and rendered with antialiasing. This avoids "shaking" during the gesture. When the gesture ends, we snap the icon to the pixel grid, so that it renders sharply when the map is static.

As this is inherently a design compromise, we're unlikely to change the existing behavior without a concrete proposal for an alternative which has consensus as superior approach, so I'm going to close this issue.
