### ISSUE TITLE
Polyline and Multiline GeoJSON Rendering issue Mapbox Gl v0.42.0

### ISSUE THREAD

**Issue by aabhishekbindal** [mapbox/mapbox-gl-js#6105]
When I try to load polyline and multi line geojson files, they are drawn distorted Mapbox GL

****mapbox-gl-js version (v0.42.0):**

### Steps to Trigger Behavior
 1. Load the GeoJSON from here:  https://drive.google.com/drive/folders/1efcV_c1xwJyZyi39ttpfkOoQZFiff66H?usp=sharing
 2. Load the GeoJSON files (LineString and MultiLineString) using Mapbox JS GL.
 3. Drawn shape is in distorted view. (attached in screenshot.). 
Console gives the error rror: 
WebGL warning: Disallowing antialiased backbuffers due to blacklisting.
map.js:1372:19
XML Parsing Error: not well-formed

![polyline](https://user-images.githubusercontent.com/5121761/35910639-435b330c-0c1d-11e8-844f-26c6114e57f1.png)
![multilinestring](https://user-images.githubusercontent.com/5121761/35910640-43819fce-0c1d-11e8-99f2-2891d1daa4b5.png)

### Expected Behavior
1. Load the GeoJSON from here: https://drive.google.com/drive/folders/1efcV_c1xwJyZyi39ttpfkOoQZFiff66H?usp=sharing
2. These GeoJSON files are parsed correctly in google maps or other maps application. It is drawn correctly in http://geojson.io

### Actual Behavior
1. These should be drawn as lines and polylines.

**Comment by mollymerp** [comment]
Hi there, 
Thank you for using Mapbox!
I was not able to reproduce your issue after testing the GeoJSON you provided. In your screenshots, it looks like you're drawing layers of `type: "fill"` when you want `type: "line"` so that might be the problem. If you issue persists, please double check your GeoJSON using http://geojsonlint.com/ or a similar tool and open a new issue with a minimal, self-contained test case on jsbin.com
