### ISSUE TITLE
Setting tolerance for a vector source

### ISSUE THREAD

**Issue by nitro89** [mapbox/mapbox-gl-js#6129]
Hello, 

I use the latest MapBox GL JS version.

The simplification of MapBox GL is creating large gaps in my data,
I have seen that there is a "tolerance" parameter in the geojson source section.

Is there a way to set the tolerance parameter for a vector source from PostGIS?

Thanks.

**Comment by anandthakker** [comment]
Hi @nitro89 -- once a vector tileset has been created, there's no way to control simplification, because it's already happened.  Depending on how you're creating your tileset, this is something you might be able to control during that process.   https://github.com/mapbox/tippecanoe is one tool that allows quite a lot of control over how vector tiles are produced from source data.

**Comment by nitro89** [comment]
@anandthakker Thanks for the info! I guess I should check the parameters of Geowebcache.
