### ISSUE TITLE
Allow queryRenderedFeatures to optionally avoid features that extend past the map bounds

### ISSUE THREAD

**Issue by pwilczynski** [mapbox/mapbox-gl-js#6157]
## Motivation
We currently do postfilter on the results of [queryRenderedFeatures](https://www.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures) to optionally remove features that extend past the viewport of the map. It would be nice to have this available as one of the Options in the queryRenderedFeatures call.

Currently, API consumers can postfilter, just like us, but it's definitely a bit of application logic that would be nice to push down to Mapbox.

## Examples
Zoomed out, queryRenderedFeatures would return the polygon:
<img width="250" alt="screen shot 2018-02-13 at 5 22 46 pm" src="https://user-images.githubusercontent.com/833760/36183464-3ee5984c-10e3-11e8-902a-0ce8c2d16fd4.png">

Zoomed in, queryRenderedFeatures would not return the polygon:
<img width="250" alt="screen shot 2018-02-13 at 5 23 00 pm" src="https://user-images.githubusercontent.com/833760/36183467-408517f4-10e3-11e8-9a60-a3cc363a8a93.png">

**Comment by jfirebaugh** [comment]
Hey @pwilczynski, thanks for the suggestion. It's always a tricky balance between rich feature support and the ongoing costs that supporting a feature at the library level requires (testing, documentation, maintenance, library "bloat").

In this case, absent a strong indication that this is a feature that would be widely used, my feeling is that this seems like fairly application-specific logic, so I think it's best that it continue to be implemented at the application level as a postfilter, rather than as a library option.

**Comment by pwilczynski** [comment]
@jfirebaugh: interestingly enough, we found a pretty big bug with using `queryRenderedFeatures` today that seems to be related to the internals of how MGLJS does its rendering and tiling.

Our code looks basically like this:
http://jsfiddle.net/pwilczynski/3wjybdf5/35/

Unfortunately, because of how the viewport and line simplification works in mapbox gl js, it's quite hard to make this work at the client level.

See some specific cases here:
- [Zoomed out](http://geojson.io/#id=gist:pwilczynski/be70718416abbef388dab7031419796b&map=7/40.535/-103.854): selection works correctly (can't select polygon)
- [Zoomed very far in](http://geojson.io/#id=gist:pwilczynski/23b0ae26c63b8cf5634e5c8818ee9032&map=12/40.5932/-103.8108): selection works correctly (can't select polygon) 
- [Middle Zoom](http://geojson.io/#id=gist:pwilczynski/5b1bd2d485b085252e8e650729c0c1d8&map=9/40.6338/-104.0570): selection is a quagmire because our query-rendered features polygon is only a tile-sliced piece of the polygon.

At this point, I don't actually know how to do this effectively do this...we have ids, and so we can probably figure out a way to make a somewhat expensive call, but this feels pretty unperformant in the long-term - seems like to do this correctly we'll need to get it in the actual library or have a way to get the full geometry for the feature? Any other advice?

**Comment by pwilczynski** [comment]
Note that the specific "Feature" that gets console.logged is actually different as you pan and zoom around the polygon in the jsfiddle.

**Comment by lbud** [comment]
> selection is a quagmire because our query-rendered features polygon is only a tile-sliced piece of the polygon.

Right, `queryRenderedFeatures` queries the internal features that have been rendered — that is, after they've been tiled. Mapbox GL tiles GeoJSON sources into vector tile-like data structures so that they may be rendered in the same way as vector tiles. After that point we treat all vector-based sources the same, and it wouldn't be practical to, say, attempt to make assumptions about which cross-tile features to try to stitch together in a vector source. It would be theoretically possible to do so for GeoJSON sources, seeing as we still have the original data, but that would break the paradigm of treating all vector sources equally, so we leave it to users to specify their exact desired behavior on the client side. We also don't propagate the full GeoJSON feature geometry into each tiled feature as that would lead to redundancy/unnecessary bloat.

As you've discovered, there are a bunch of good tips in https://github.com/mapbox/mapbox-gl-js/issues/5040, and an example of a somewhat similar behavior [on our examples page](https://www.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures-around-point/): like those, you'll need to leverage the unique identifiers you have for your original geometry features to coalesce the tiled features you're looking for.

> Unfortunately, because of how the viewport and line simplification works in mapbox gl js, it's quite hard to make this work at the client level.

we believe in you! :)

**Comment by pwilczynski** [comment]
In case the code is useful for anyone else, I got this to work by using:
```
const viewportPolygon = this.getViewportPolgyon();
const shouldSelect = false;
const turfPolygon: turfHelpers.Feature = 
    turfHelpers.polygon((feature.geometry.coordinates as geojson.Position[][]), { name: "polygon" });
if (booleanWithin(turfPolygon, viewportPolygon)) {
        shouldSelect = true;
} else {
    const pixelSpaceBoundingBox = [this.map.project(this.map.getBounds().getNorthEast()),
        this.map.project(this.map.getBounds().getSouthWest())];
    const unionFeature =
        this.map.queryRenderedFeatures(pixelSpaceBoundingBox,
            {layers: [feature.layer.id], filter: ["all",
                ["!=", "id", feature.properties.locator],
                ["==", "$type", "Polygon"]]})
        .map(f => turfHelpers.polygon((f.geometry as geojson.Polygon).coordinates as geojson.Position[][]))
        .reduce((result, feature) => union(result, feature) as turfHelpers.Feature<turfHelpers.Polygon>);
    const viewportOverlapPolygon = booleanOverlap(viewportPolygon, unionFeature);
    const viewportWithinPolygon = booleanWithin(viewportPolygon, unionFeature);
    if (viewportOverlapPolygon && !viewportWithinPolygon) {
        shouldSelect = true;
    }
```
