### ISSUE TITLE
Mouseenter and mouseleave triggered multiple times while moving on a feature

### ISSUE THREAD

**Issue by phiphou** [mapbox/mapbox-gl-js#6163]
With version >= 0.42, when I point my mouse onto a feature with text and image, event is triggered multiple time when I move the mouse on the feature. For instance, when pointing to an "o", mouseleave is triggered when pointing on the center of the "o".  The same for Icon image, mouseleave is triggered when pointing on un-painted parts.

Any idea ?

**Comment by anandthakker** [comment]
Thanks for reporting this issue!

Could you please provide self-contained example reproducing this issue?   Having an example to work with will make it much more likely that we can successfully diagnose and solve the problem.

**Comment by phiphou** [comment]
Here is a simple example. 

[https://jsfiddle.net/vgt4ukzo/](https://jsfiddle.net/vgt4ukzo/)

Just move your mouse on the "Lorem" marker, either the text or the icon.

If you switch back to 0.41 you got the expected behavior (text in blue when hovered).

0.42 and earlier don't work as expected

**Comment by jfirebaugh** [comment]
Starting in 0.42, labels from different sources now collide with each other. So when you add the hover layer, it hides the original layer due to collision detection, which triggers a mouseleave event (which hides the hover layer, which triggers mouseenter...).

You can restore the previous behavior by setting `"icon-ignore-placement"` and `"text-ignore-placement"` to `true`:

https://jsfiddle.net/d8qs32pw/

**Comment by phiphou** [comment]
Your right but I still cannot hovering the text, works just for the icon.

**Comment by jfirebaugh** [comment]
Tracking that in #6146.

**Comment by phiphou** [comment]
Ok, thanks for your contribution, will wait this bug is fixed ;)

**Comment by phiphou** [comment]
Will 0.45 support the 0.41 behavior without setting setting `"icon-ignore-placement"` and `"text-ignore-placement"` on the markers layer to true ?
