### ISSUE TITLE
queryRenderedSymbols does not sort features

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#6184]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. load a symbol layer with collision detection disabled + overlapping symbols
 2. use `on('click', layer, ...` to invoke `queryRenderedFeatures` on the symbol layer
 3. 

### Expected Behavior

`e.features[0]` is the topmost rendered featured (and subsequent features are sorted in z order) per
https://github.com/mapbox/mapbox-gl-js/blob/38c7250da7b5153c531d0b5b8ff4a2f07f9ab863/src/ui/map.js#L747-L748

### Actual Behavior

`e.features[0]` is not always the topmost feature

![motivate](https://user-images.githubusercontent.com/2425307/36289640-da432168-1275-11e8-9208-c6c958d581c0.gif)

looks like we sort non-symbol features, but don't sort symbol features:

https://github.com/mapbox/mapbox-gl-js/blob/38c7250da7b5153c531d0b5b8ff4a2f07f9ab863/src/data/feature_index.js#L118-L126

**Comment by ChrisLoer** [comment]
@ansis Do you know the origins of that documentation? I'm not sure what it means by "topmost rendered feature" -- it looks like the sorting is based on the order in which items are inserted into the `FeatureIndex` by `*Bucket.populate`... which is closely related to the draw/z-order but not strictly the same especially across tiles?

But the recent divergence of symbol behavior from non-symbol behavior is because of the sorting here:

https://github.com/mapbox/mapbox-gl-js/blob/859d4a93d639359c64edeb345cfbb2922a9d97e2/src/data/bucket/symbol_bucket.js#L635

I think we'll need to do something like store the sort indices generated there and use them for sorting the `matchingSymbols` results in `queryRenderedFeatures`

**Comment by ansis** [comment]
@ChrisLoer yep, you're right about it being similar but not always right. The tile boundary bug might have existed when it was added, or we might have changed how querying works at tile boundaries (do we index points outside of tile edges or do we do padded queries across tile boundaries).

Your suggested fix sounds right

**Comment by ChrisLoer** [comment]
I think I can build a good fix for this on top of PR #6497...

**Comment by ChrisLoer** [comment]
Fixed in #6497.
