### ISSUE TITLE
Automatic string coercion for "concat" and text-field

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#6190]
**mapbox-gl-js version**: `0.44`

It is common to want to use numbers as strings, especially in the `text-field` input. One use-case is to display number values on contour lines. This doesn't work:

```json
["get", "ele"]
```

The proper expression is as follows:
```json
["to-string", ["get", "ele"]]
```

For all users, this is pretty confusing, and doesn't seem necessary:

- JS developers are used to numbers being treated like strings in cases like this, so I expect this will be a common stumbling block when implementing any expression on a string field.
- In Studio, we can work around the current design by automatically wrapping all return values in the UI in `to-string`, but it adds complexity and just feels unnecessary.

**Comment by jfirebaugh** [comment]
This is only really an issue for `text-field`, right? The other string-valued properties require values that are non numeral strings. (There's a corner case if you're using images with a numeric names in `icon-image` or `*-pattern`, but that seems uncommon.)

**Comment by samanpwbb** [comment]
> This is only really an issue for text-field, right?

Mostly, but also effects image properties. For example, stylesheets often compose the name of a sprite image by looking at the # of characters in a data field. Would be nicer to be able to write `get('type') & '-' & length(get('name'))` instead of `get('type') & '-' & to-string(length(get('name')))`.

**Comment by jfirebaugh** [comment]
I think that would be an issue with expression-jamsession? `["concat", ["get", "type"], "-", ["length, ["get", "name"]]]` should work fine.

**Comment by jfirebaugh** [comment]
Ah, it doesn't. That's a bug in `"concat"` -- it should wrap arguments with implicit assertions like any other operator.

**Comment by jfirebaugh** [comment]
Ah, that doesn't work. Okay, let's expand this to a request for `"concat"` to do auto-coercion.

**Comment by samanpwbb** [comment]
Another issue with the current implementation:

![screen shot 2018-04-12 at 5 43 02 pm](https://user-images.githubusercontent.com/108094/38711191-05e75724-3e79-11e8-87b7-46780c4f759c.png)

`to-string` inside a `coalesce never returns null. If I remove the `to-string`, I get what I expect:

![screen shot 2018-04-12 at 5 43 10 pm](https://user-images.githubusercontent.com/108094/38711184-fdb918f8-3e78-11e8-8fdf-09de35cbb3e5.png)

**Comment by samanpwbb** [comment]
It would be great to add automatic string coercion __*-image__ values as well as text-field.

**Comment by 1ec5** [comment]
> JS developers are used to numbers being treated like strings in cases like this, so I expect this will be a common stumbling block when implementing any expression on a string field.

This has also come up as a point of confusion for iOS developers, though the examples I’ve seen could’ve been mitigated through clearer documentation and error messages at the time.

**Comment by anandthakker** [comment]
Some examples of undesirable results if we always did implicit conversion for strings:
 - `["match", ["get", "x"], "1", "yes", "no"]` would then evaluate to `"yes"` for both `{"x": 1}` and `{"x": "1"}`
 - `["match", ["get", "x"], "", "yes", "no"]` would evaluate to `"yes"` for all three of `{}`, `{"x": ""}`, and `{"x": null}`

Not sure if this is worse than the confusion that might be caused by having sometimes auto-coercion / sometimes assertion 🤔

**Comment by 1ec5** [comment]
The examples in https://github.com/mapbox/mapbox-gl-js/issues/6190#issuecomment-385742869 point to a possible need for a distinction between `==` and `===` if we were to perform automatic string coercion. Then again, maybe `match` isn’t relevant here: in JavaScript and other languages, `switch` has `===` semantics.

**Comment by nickidlugash** [comment]
A related issue I've come across in styles that use Mapbox Streets data:

We are getting these warnings thrown:
`Expected value to be of type string, but found null instead.`

...because it is common for `text-field` values similar to `["get", "name"]` to evaluate to `null`. With the previous token syntax, `{name}` did not seem to throw this error. It seems ineloquent to require an explicit coercion here (or to require coalesces with an empty string).

> Is there any reason to not add an automatic string coercion for the text-field, icon-image, and *-pattern properties while we figure out what kind of string coercion we want to do in other cases?

I think this would solve our issues 👍
