### ISSUE TITLE
Add type conversion to identity function -> expression migration script

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#6195]
**mapbox-gl-js version**: `0.44.1`

in https://github.com/mapbox/mapbox-gl-js/blob/3c04bbe2a8e1cdcd74b8037e49ebbf808fac6ee8/src/style-spec/function/convert.js#L56-L79, there's some type conversion for enums and colors, but type conversion expressions to should wrapped around values for all types, like strings, numbers, and booleans.

**Comment by jfirebaugh** [comment]
Not sure I understand the request. Can you give an example or two?

**Comment by jfirebaugh** [comment]
Note that per https://www.mapbox.com/mapbox-gl-js/style-spec/#function-default, identity functions do not do auto-conversion to and from strings and other types. For example, if the feature property value is a number but the style property has type string, then the default value (either from the function, or the spec default) is used, rather than converting the feature property value to a string.

**Comment by samanpwbb** [comment]
> Identity functions do not do auto-conversion to and from strings and other types.

Ohhh, in that case, we're probably fine closing this. Was concerned about regressions from, say,
  `{ "type": "identity", "property": "elevation" }` to `['get','elevation]`, but the former didn't render anything anyway.
