### ISSUE TITLE
slow performance on Android webview with many (>700, <1000)  custom markers.

### ISSUE THREAD

**Issue by tryadelion** [mapbox/mapbox-gl-js#6212]
hello, i just started trying mapbox and i have found that the performance levels of it with a dense amount of markers is quite low compared to other services.
I'm using the latest release ( installed 30 minutes ago) on npm.

marker creation code:
```
var el = document.createElement('div');
    el.className = 'marker';
    el.style.backgroundImage = 'url(https://upload.wikimedia.org/wikipedia/commons/1/11/BlackDot.svg)';
    el.style.backgroundSize = "100% auto";
    el.style.width = '32px';
    el.style.height = '32px';

    el.addEventListener('click',()=> {
        this.onMarkerClick(m);
    });

    // add marker to map
    var marker = new mapboxgl.Marker(el)
        .setLngLat({lng: m.longitude,lat: m.latitude})
        .addTo(this.map);
```
amount of markers: ~781.

platform:  Cordova webview, javascript source running over angular 5 (but with the mapbox code excluded to make sure it's not the source of the performance issue);

Device: generic android device with 2GB ram, 600-series snapdragon cpu processor.

**Comment by jfirebaugh** [comment]
For best performance with large numbers of markers, we recommend using a [symbol](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol) or [circle](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-circle) layer rather than `Marker`. See the following for examples:

* [Style circles with a data-driven property](https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/)
* [Display popup on click](https://www.mapbox.com/mapbox-gl-js/example/popup-on-click/)

**Comment by tryadelion** [comment]
isn't there any way really to overcome this? your circles are SVG, can't we load a SVG instead? what's the difference between 700 2kb markers and 700 2kb circles?

**Comment by jfirebaugh** [comment]
No, circles are rendered with WebGL, not SVG. WebGL rendering is what permits high performance on hundreds or thousands of features.
