### ISSUE TITLE
Clarify IE11 support

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#6305]
[This page](https://www.mapbox.com/help/mapbox-browser-support/) seems to go out of its way to avoid saying that Mapbox-GL-JS supports any version of IE. 

>Like Mapbox Studio, Mapbox GL JS is supported in all modern browsers. The same requirements for Mapbox Studio [Safari 9+, Chrome, FF, Edge 13+] apply to Mapbox GL JS.

Yet [this IE11 bug report](https://github.com/mapbox/mapbox-gl-js/issues/5857) was labelled "release blocker" and fixed.

Can I assume from this that IE11 is indeed supported, and if so, may I ask how long that is likely to be the case?

**Comment by stevage** [comment]
Another thing particularly confusing about that page is that the first paragraph declares "all modern browsers" synonymous with Safari 9+, Chrome, FF, Edge 13+; yet the last paragraph says that "most modern browsers" includes IE8. Maybe better not to use the term "modern browser" at all?

**Comment by joedjc** [comment]
We have found that older versions of both Edge and IE11 don't seem to be supported. Edge needs to be >v38

**Comment by jfirebaugh** [comment]
Sufficiently recent versions of IE11 and Edge are supported, providing the underlying hardware and drivers can support WebGL. Due to the incomplete information available from Microsoft about precisely which versions support the necessary features or fix the relevant browser bugs, and the hardware and driver dependencies of WebGL, we can't make blanket statements like "IE11 is supported". Our best effort to pin down precisely whether Mapbox GL JS is supported or not is encoded in [`supported`](https://www.mapbox.com/mapbox-gl-js/api#supported), which is also available in a [standalone module](https://github.com/mapbox/mapbox-gl-supported).

**Comment by stevage** [comment]
IMHO it would be useful for a developer like me to see what you just said on that page. Even if it's "We try to support the latest version of IE11, but it's a lower priority."

The test page (and http://mapbox.github.io/mapbox-gl-supported/) were not super helpful to me as I didn't actually have access to an IE11 on which to test.

**Comment by Justin-Singh125125** [comment]
I found a work around to this issue. Instead of using the new updated version of Mapbox I ended up using the old outdated one called Mapbox.js on old browsers. The  mapboxgl.supported() did not work so I had to dig deeper until I found out we could do this. 
`  if (mapboxgl.supported.prototype.constructor.name === "e") {
   // use newer browsers, mapboxgl.js
}
else{
   //use older browsers, mapbox.js
}
`
