### ISSUE TITLE
Race Condition in vector_tile_worker_source

### ISSUE THREAD

**Issue by samwyma** [mapbox/mapbox-gl-js#6308]
**mapbox-gl-js version**: 0.44.1

### Explanation

The reloadTile function in [vector_tile_worker_source.js](https://github.com/mapbox/mapbox-gl-js/blob/31d92db36398cddbf8a511af261861460770d894/src/source/vector_tile_worker_source.js#L150) has a race condition, at least as far as I can tell. If three requests are placed to reloadTile, one after another, then if the third request is placed after the first has finished, but while the second is still processing, then the callback for the third request (i.e. the latest one) will never be called.

We're using the renderer of this project in a [fork](https://github.com/landtechnologies/Mapbox-vector-tiles-basic-js-renderer) and the assumption we've made when using the worker thread is that the last request made to the worker will always resolve. Are we assuming correctly that this should be the case?

I'm pretty sure the fix for this is to change this line:
`workerTile.reloadCallback = callback;`
to this:
`workerTile.reloadCallback = done.bind(workerTile);`

But I'm not sure if the above would break anything in the wider codebase, since we're only using parts of the renderer.

### Steps to Trigger Behavior

1. Have relatively large tiles which take a non-trivial amount of time to parse
2. Get them to parse frequently (e.g. by changing filters) and then stop and wait. Do this until the map hangs when rendering.

### Expected Behavior

The map renders without timing out.

### Actual Behavior

The rendering times out.

**Comment by jfirebaugh** [comment]
Your analysis looks correct. To spell it out explicitly, since it took me a while to work out, suppose:

1. `reloadTile` is called when the current status is `done`. `workerTile.parse` is passed the callback `done.bind(workerTile)`. (`done` captures `callback` in its closure.) Parsing begins.
2. `reloadTile` is called a second time. `reloadCallback` is set to `callback`.
3. Parsing finishes and the bound `done` from step 1 is called. `reloadCallback` is set, so `parse` is called again with the callback from step 2.
4. `reloadTile` is called a third time. `reloadCallback` is set to (the new) `callback`.
5. Parsing triggered by step 3 completes, and calls the callback from step 2. This is just a regular callback, not a bound `done`, so the `reloadCallback` set in step 4 is left hanging.
