### ISSUE TITLE
Canvas source initialization from HTML element, instead of element id

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapbox-gl-js#6372]
**mapbox-gl-js version**: 0.44.1

# Background

The Canvas source type supports initialization from a canvas HTML element `id` only.  https://www.mapbox.com/mapbox-gl-js/style-spec#sources-canvas-canvas

# Feature Request

Allow initialization of Canvas source from an HTML canvas element, the same way that a mapboxgl map object can be bound directly to an HTML element https://www.mapbox.com/mapbox-gl-js/api/#map.

# Use case

Canvas elements in an application framework do not have an HTML `id` element.  Adding HTML unique `id`s to each Canvas element would add complexity to the application, instead of just creating the canvas element and passing to the Canvas source.

cc @lbud

**Comment by lbud** [comment]
This is definitely feasible. It would mainly entail:
* Changing CanvasSource so that it can optionally [read directly from the element](https://github.com/mapbox/mapbox-gl-js/blob/6b848e5f6bcb1188d51691c456054dc8095c053d/src/source/canvas_source.js#L78) if `options.canvas` is an `HTMLCanvasElement`, and omitting the canvas element from [`serialize`](https://github.com/mapbox/mapbox-gl-js/blob/6b848e5f6bcb1188d51691c456054dc8095c053d/src/source/canvas_source.js#L182) in that case
* Modifying the [`CanvasSource#canvas` specification](https://github.com/mapbox/mapbox-gl-js/blob/6b848e5f6bcb1188d51691c456054dc8095c053d/src/style-spec/reference/v8.json#L429) to accept _either_ a string or HTMLCanvasElement. Currently there are no other union types in the spec — all `type` values are either a single string-represented type or an enum type represented by an object — so we'd need to determine the best way to represent a union type and validate it
