### ISSUE TITLE
The onRemove method in the map control was not triggered when I removed the map.

### ISSUE THREAD

**Issue by shanligang** [mapbox/mapbox-gl-js#6378]
**mapbox-gl-js latest**:

### Steps to Trigger Behavior

 1.The onRemove method in the map control was not triggered when I removed the map.
 2.The onAdd method Can be triggered

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. Unfortunately, you haven't provided enough information for us to be able to help you. When opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer. In particular, for issues such as this we will almost always need you to provide a minimal working example that demonstrates the issue. If you can provide those things, please feel free to open a new issue.
