### ISSUE TITLE
Security Error on WebWorker IE11 Win8.1

### ISSUE THREAD

**Issue by droachrkn** [mapbox/mapbox-gl-js#6384]
This is an exact duplicate of issue #4358 which is closed but apparently still an issue.

IE 11, Windows 8.1 Mapbox throws a "Security Error on WebWorker". 

Deps: 
"mapbox-gl": "^0.44.1"

Still an issue, not remedied. 
No clear fix provided in the docs despite boasting IE11+ support.

Steps to replicate:
Take this domain: https://www.mapbox.com/mapbox-gl-js/example/check-for-support/
Open IE 11, Windows 8.1.
Paste said domain.
Dumpster fire.

**Comment by deefour** [comment]
Just my experience:

I grabbed a Windows 8.1 VM from modern.ie a while back. It comes with a 'pre-release' version of IE11 (though there is no obvious mention of this I saw in IE itself) - version 11.0.9600.16384

I had to run windows software updates. One of these upgrade IE to version 11.0.9600.18763 and the web worker issues were resolved 👍

**Comment by droachrkn** [comment]
Agreed; however, if you state IE 11+, that should cover the gamut of IE11. 

Unfortunately, the audience I need to serve largely browses with this particular version + OS combo... 
I can't tell an older crowd to download a pre-release of IE for Windows 8.1 and revisit our site.

@mapbox needs to clean up their docs and really offer a detailed support chart so teams like mine don't invest in subscriptions and services unknowing of these support gaps and lack of knowledge.

**Comment by jfirebaugh** [comment]
@droachrkn, thanks for the report. Can you clarify the behavior you're seeing when you go to https://www.mapbox.com/mapbox-gl-js/example/check-for-support/ with an affected version of IE? Do you see an alert saying "Your browser does not support Mapbox GL", or something else? And can you provide the exact version of IE in use? (Lastly, please don't use language such as "dumpster fire" when describing issues you'd like addressed. Not only is it disrespectful to the authors and maintainers, it's doesn't provide the detail necessary to diagnose the issue, making it less likely to be resolved.)

To clarify the expected behavior here, it's that [`mapbox.supported()`](https://www.mapbox.com/mapbox-gl-js/api#supported) returns false on versions of IE11 that trigger this security error (and therefore that the example alerts "Your browser does not support Mapbox GL"). These versions of IE does not have key [WebWorker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) functionality that Mapbox GL JS requires.

If you saw somewhere in the documentation that indicated IE11 is supported unconditionally, let me know and I'll correct it. That's not the case -- some versions are, and some versions aren't. `mapbox.supported()` is intended to provide a way to determine if it is supported, and https://github.com/mapbox/mapbox-gl-js/pull/5801 (pulling in https://github.com/mapbox/mapbox-gl-supported/pull/15) should have fixed https://github.com/mapbox/mapbox-gl-js/issues/4358, by causing `mapbox.supported()` to return false in this particular case.
