### ISSUE TITLE
Mapboxgl and mapbox together in a page throwing 'L' is not define

### ISSUE THREAD

**Issue by ankit6883** [mapbox/mapbox-gl-js#6414]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.In my one page, I am using mapbox-gl and map box in map box I used leaflet 
 2.first time anyone will render when I changed visualizer (mean mapboxgl to mapbox) its throwing 'L' is not defined
 3.Individual both are working fine, on request I am loading files

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. Unfortunately, you haven't provided enough information for us to be able to help you. When opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer. In particular, for issues such as this we will almost always need you to provide a minimal working example that demonstrates the issue. If you can provide those things, please feel free to open a new issue.
