### ISSUE TITLE
Update style spec validation error messages to refer to "data expressions" rather than "property expressions"

### ISSUE THREAD

**Issue by AntonPilyak** [mapbox/mapbox-gl-js#6482]
**mapbox-gl-js version**: 0.44.2

### Steps to Trigger Behavior

 1. try to use an expression in 'line-dasharray' property
 2. get an exception 'line-dasharray: property expressions not supported'

### Expected Behavior
Quote from the [documentation:](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions)
'The value for **any** layout property, **paint property**, or filter may be specified as an expression. An expression defines a formula for computing the value of the property using the operators described below.' 
According to this, expressions should be supported for any property.

### Actual Behavior
Expressions are not supported

**Comment by anandthakker** [comment]
Thanks for reporting this issue @AntonPilyak.  This is a bug in our documentation: instead of saying, "property expressions not supported", the error message should say, "_data_ expressions not supported."  (See https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions for description of a "Data expression.")

The underlying problem is that `line-dasharray` currently does not support data-driven styling.  You can track data-driven styling support here: https://github.com/mapbox/mapbox-gl-js/issues/4434

Retitling this issue to track the documentation bug
