### ISSUE TITLE
map.fire 'click' event will crash Marker

### ISSUE THREAD

**Issue by yangdonglai** [mapbox/mapbox-gl-js#6607]
**mapbox-gl-js version**: 0.44.1

### Steps to Trigger Behavior

 1.add a Marker to map
 2.map.fire 'click' event

### Expected Behavior
nothing happen
### Actual Behavior
web error

**Comment by yangdonglai** [comment]
this bug happen because the target create by map.fire has no originalEvent
![image](https://user-images.githubusercontent.com/17786362/39612950-711a9a28-4f96-11e8-9482-1fa6ed34b0bd.png)

**Comment by yangdonglai** [comment]
#6608  a simple fix

**Comment by jfirebaugh** [comment]
Hmm, I'm not convinced this is a bug in GL JS. Why are you calling `map.fire('click')`? That's something that the map should do internally when an actual click event is received.

We're trying to discourage the use of `map.fire` externally, especially with pre-existing events like `click`, because it leads to issues like this. See https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#%EF%B8%8F-breaking-changes.

**Comment by jfirebaugh** [comment]
> use queryRenderedFeatures directly

Yes, that's what I would suggest too. However:

> the point I use is out of the screen ,so sometime the queryRenderedFeatures return empty array

Right, that's the documented behavior of queryRenderedFeatures -- it only works for features of currently loaded tiles. If querying features outside of the current viewport is essential, you'll need to use a different solution, like a server-side query or side-loading data.
