### ISSUE TITLE
popup off screen until map move event

### ISSUE THREAD

**Issue by gorbypark** [mapbox/mapbox-gl-js#6619]
**mapbox-gl-js version**:
0.45.0-beta.1

**browser**:
Chrome

### Steps to Trigger Behavior

 1. Create pop up on a point
 2. Click pop up near edge of viewport

### Expected Behavior
Pop up doesn't cut off itself
### Actual Behavior
Pop up pops off the screen.  As soon as there's a map move event, the pop up corrects itself to a position that's not off the edge of the screen.  I haven't tested all events to see which cause the correction, but a mapmove does for sure.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by jfirebaugh** [comment]
By design, programmatically setting the location via `Popup#setLatLng` does not automatically wrap the provided location so that it's on screen; you have to option to do that (or not) before calling `setLatLng`. Hopefully that allows you to fix the issue. If not, please provide a minimal example. Thanks!

**Comment by benjamintd** [comment]
I believe that the issue is that a popup whose content is set with `setDOMContent` might overflow out of the map, instead of having its anchor correctly computed from the start. A `mousemove` event triggers the recomputation of the anchor, but not the initial addition to the map. 

I don't have a minimal reproduction yet, but here's the code I'm using (in React):

```

import { centroid } from "@turf/turf";
import mapboxgl from "mapbox-gl";
import { useEffect, useRef } from "react";
import { createRoot } from "react-dom/client";

import { useMapState } from "~/core";

function useMapHoverTooltip<T extends JSX.IntrinsicAttributes>(
  Component: React.FC<T>
) {
  const popup = useRef(
    new mapboxgl.Popup({
      closeButton: false,
      closeOnClick: false,
      offset: 10,
      className: "font-sans-serif text-base"
    })
  );
  const hoveredItem = useMapState(state => state.hoveredItem);
  const map = useMapState(state => state.current);

  useEffect(() => {
    if (map && hoveredItem && hoveredItem.feature) {
      const popupNode = document.createElement("div");
      document.getElementById("__next")!.appendChild(popupNode);
      const root = createRoot(popupNode);
      root.render(<Component {...(hoveredItem.feature.properties as T)} />);

      popup.current
        .setDOMContent(popupNode)
        .setLngLat(
          centroid(hoveredItem.feature).geometry.coordinates as [number, number]
        )
        .addTo(map);

      return () => {
        root.unmount();
        popupNode.remove();
      };
    } else if (map && !hoveredItem) {
      popup.current.remove();
    }
  }, [hoveredItem, map]);
}

export default useMapHoverTooltip;
```

And here's a video of the behavior: 


https://user-images.githubusercontent.com/11202803/197816865-f0e5607a-8b11-4cb3-9158-987dad01b8a9.mov

**Comment by dariobertini** [comment]
Hi,

we facing the same issue as reported by @benjamintd.
 @jfirebaugh, is this a valid issue o should be reopened?

**Comment by VikaBondareva** [comment]
> Hi,
> 
> we facing the same issue as reported by @benjamintd. @jfirebaugh, is this a valid issue o should be reopened?

It is still issue

**Comment by hbuhrer** [comment]
also running into this issue with nuxt. Any updates?

**Comment by beccyv** [comment]
Also have this issue. Does anyone have a solution yet please?

**Comment by niklebe** [comment]
still an issue!
