### ISSUE TITLE
id specification

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6651]
**mapbox-gl-js version**: 0.45.0

### Question
What is the specification of the feature's id field and how can I generate one in a supported manner? I tried using `uuidv4()` from `uuid/v4` but mapbox-gl-js silently removes it. If I set it to `123` it stays.

I see that draw uses `hat`, yet mapbox-gl-js removes `hat()` as well.

I have the following questions:
1. What is the specs of the id field?
2. What function can I use to generate one within specs?
3. Is this going to change in the future, and if so will it be documented in a release notes?
4. Is using id-s on GeoJSON sources helping the performance of `setData()`?

**Comment by mourner** [comment]
The issue is that GeoJSON supports both string and number ids, while we have to convert the data to Vector Tile format prior to rendering, and the latter [only supports unsigned integers](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L32). We want to fix that eventually, but it requires a non-trivial change. Tracking this issue in #2716.
