### ISSUE TITLE
Add easeTo function to Markers

### ISSUE THREAD

**Issue by modvd** [mapbox/mapbox-gl-js#6676]
Hi,

Is there any way you could add an easeTo function or anything similar to Markers ? I need to move a Marker from one point to another in a certain amount of time. In the android API this is possible but I can't seem to find how to do it in the GL JS version.

Thanks !

**Comment by jfirebaugh** [comment]
Hi @modvd -- I don't think we're likely to add this as built in functionality, but it's something you can implement yourself using a timer and [`Marker#setLngLat`](https://www.mapbox.com/mapbox-gl-js/api#marker#setlnglat). It would be similar to [this example](https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-line/) but using Marker rather than a GeoJSON source.

**Comment by modvd** [comment]
The problem is I have a Marker that I have to move from one LatLng to another about every second. Like in a navigation app. So I don't know how to do that with this example because I can't know all the points in advance.

**Comment by modvd** [comment]
Any ideas ? I really need a way to do this...
