### ISSUE TITLE
Pixel-mediated radii for heatmaps can be misleading, in a Mercator projection

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#6716]
This is a bit of a finer point that I haven't seen previously. It's broadly accepted that Mercator projects objects near the poles to be much further apart, than ones at the equator.

However, by measuring heatmap radii in pixels, we're also handling *intensity* in Mercator-projected pixels, too. Equidistant objects at the poles will render as *less hot* than ones at the equator.

<img width="580" alt="screen shot 2018-05-23 at 2 44 11 pm" src="https://user-images.githubusercontent.com/4551508/40422627-9f27dfaa-5e98-11e8-9278-0f7691ef8ffc.png">

*Two pairs of points, spaced equally apart but appear to be of different heat due to latitude difference*

1) While spatial distortion should be basic knowledge when dealing with Mercator, should intensity distortion be part of the basic understanding, as well? 

2) If not, should we scale radii by latitude / measure it in some real-world distance unit?

cc/ @mourner @ryanbaumann

**Comment by ryanbaumann** [comment]
Agree, this is misleading from a data understanding perspective.  Specifying heatmap-radius in real world coordinates (km) would make sense to me.

**Comment by mourner** [comment]
The way I see it, GL heatmaps are NOT supposed to be viewed in geographical context — they're designed as a mostly **visual data exploration tool**, not one for precise GIS analysis, because the latter is ill-suited in the context of an interactive map. Consequently, what you see is a kernel density of points _on the screen_, not the globe.

Having radius specified in real world coordinates completely defies the purpose of the heatmap on a GL map because it no longer adapts to your map view, so if you see a balanced heatmap on a low zoom, you'll only see a blurry blurb when zooming in, and if you pick a good radius for a higher zoom, the low zoom representation will not give you a good idea of data distribution while also performing very poorly (due to the amount of kernels that have to be rendered). You can still do it if necessary with an expression that exponentially scales the radius with zoom, but it won't be useful in the context of an interactive map. In this way, heatmap is similar to the clustering feature — having the same set of clusters for the whole zoom range there isn't useful as well.

I'd prefer not to address the Mercator distortion issue as well because we have to commit to a single concept for the heatmap layer — mixing two different contexts (geographical and screen representations) in one can lead to a lot of confusion. When designing the feature, I committed to the latter.
