### ISSUE TITLE
Counting map tile downloads to track costs.

### ISSUE THREAD

**Issue by thunderkid** [mapbox/mapbox-gl-js#6723]
**mapbox-gl-js version**:
0.45
### Question
I want my web app to be able to track the number of map tiles downloaded to a user's browser, since I have to pay for these so I'd like to monitor them in real time on a per-user basis and potentially throttle or discourage over-active users. I'm doing this with
```
        this.map.on('data', stuff => {
            numTilesLoaded++;
          }
```
Is this giving a correct count for the number of tiles that I'll be billed for by, eg, mapbox? This is giving higher numbers than I expected - when I open up a map that takes up most of the browser window, it apparently loads 96 tiles immediately, and if simulate a mildly curious user by zooming in and out and panning around for one minute then the total number of tiles exceeds 1000.
Based on the mapbox pricing model of $0.50 per 1000 map views (which is 4000 or 15000 tiles depending on how you interpret the pricing docs), this would run to a few dollars per active-user-hour. That seems very wrong, so I'm wondering whether my counting method is incorrect. Thanks.

### Links to related documentation
Not sure. Maybe in `this.map.on('data'...)`.

**Comment by dave11mj** [comment]
Hey ~

I am not sure what `data` would be counting, but if you want some numbers to compare against I would suggest looking into [intercepting network requests](https://stackoverflow.com/questions/20621084/how-to-get-list-of-network-requests-done-by-html) similar what the dev tools show. I can usually see the tiles in the dev tools network tabs.

This is what my dev tool would look like for a full screen sample map similar to the "getting started" example.
![image](https://user-images.githubusercontent.com/6619371/40449798-a44ce368-5ea7-11e8-8b03-e8185c04b7d3.png)

One extra bonus you could add is tracking if they are loaded from cache or not, since in theory you may not be charged for tiles loaded from the browser cache (?)

**Comment by ryanhamley** [comment]
Hi @thunderkid. Your approach will not give you an accurate count of the number of tiles loaded. The `data` event follows the `dataloading` event which is fired `when any map data (style, source, tile, etc) begins loading or changing asyncronously`. So listening for the `data` event will also include events for your style, sources and other data, not just the map tiles. `data` events which pertain to a tile will have a `tile` and `coord` property that you could filter by, but they will fire for changes to tiles (such as adding a new source) as well as downloading a tile.

The Map options parameter includes a `transformRequest` property which allows you to pass in a callback that will be run before the map makes a request for an external URL. You may be able to capture the tile URLs this way. I'm going to close the ticket since I don't think there's anything actionable on our end, but I hope this helps.

**Comment by thunderkid** [comment]
Thanks @ryanhamley, that seems to work. I'm now getting 12 tiles on first load, which seems more plausible. In case it helps anyone the code I'm using is basically this:
```
    componentDidMount() {
        ...
        this.map = new MapboxGl.Map({
            ...
            zoom: 7,
            transformRequest: (url, resourceType) => {
              if (resourceType == 'Tile') 
                numTilesLoaded++;
            }
        })

```
