### ISSUE TITLE
Fill extrusion rendering issue with tileset containing features per zoom level

### ISSUE THREAD

**Issue by StephaneAlie** [mapbox/mapbox-gl-js#6754]
**mapbox-gl-js version**: 0.45.0

**browser**: Chrome 66.0.3359.181

### Steps to Trigger Behavior

 1. Open the jsfiddle demo below.
 2. Zoom and pan around Houston.
 3. Switching layer to 2d and back to 3d momentarily "fixes" the rendering, but zooming / panning triggers the issue again (the rendering issue only happens with the fill-extrusion layer even though both layer are rendering using the same tileset).

### Link to Demonstration

https://jsfiddle.net/9ou7r119/5/

### Expected Behavior
Map should not render tiles from lower zoom level
### Actual Behavior
Map renders tiles from lower zoom level.

This is most likely a variant of #6560

**Comment by ryanbaumann** [comment]
Thanks for ticketing with a minimal example, @StephaneAlie.  

This bug seems to be specific to `fill-extrusion` layers.  Changing the example @StephaneAlie provided to a `fill` layer type, instead of a `fill-extrusion` layer type with  `fill-extrusion-height` set to zero, fixes the low-zoom tiles still loaded & rendered issue.

cc/ @lbud @jfirebaugh

**Comment by jfirebaugh** [comment]
Thanks for the report! I'm consolidating all the issues related to this bug in #6768.

**Comment by chloekraw** [comment]
@StephaneAlie - we merged https://github.com/mapbox/mapbox-gl-js/pull/6803 into v0.49 of gl-js which should have fixed 90% of the bugs captured in https://github.com/mapbox/mapbox-gl-js/issues/6768. Let us know if you're still seeing a bug in your application after upgrading to the latest version.
