### ISSUE TITLE
Hot and cold: bipoloar heatmaps

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#6785]
## Motivation

I would like to make a heatmap where points can interact adversarially to negate each other, to produce a heatmap with both a "cold" and a "hot" extreme. This is not possible in the current  implementation, because weights must necessarily be *positive* and *additive*.

## Design Alternatives

We can get maybe halfway there by splitting positive and negative points into separate heatmap layers, and stacking the two, but this does not produce a cancelling effect when blending.

## Design

The most obvious design, initially, is to allow negative values for `heatmap-weight`. To make this more explicit, can also optionally extend `heatmap-color` 's domain from [0,1] to [-1, 1].

cc/ @mourner

**Comment by andrewharvey** [comment]
So this could unlock something like @ericfischer's https://www.mapbox.com/labs/twitter-gnip/locals/ but as a heatmap instead of dotmap.

**Comment by mourner** [comment]
Extending property domains is not a problem, but actual blending is more difficult because it happens on the GL shader side. I'm not sure it's technically possible.

**Comment by peterqliu** [comment]
@mourner interesting, is the GL shader structured so that it can only add, but not subtract weights of proximal points?

**Comment by mourner** [comment]
@peterqliu we'll probably have to sort all the values into two different sets, one positive and the other negative, then render two alpha textures separately instead of one, and then add an additional pass that blends them with `GL_FUNC_SUBTRACT`, which could be badly supported across GL implementations. Another way would be trying to blend negative half-float values, but that won't work on machines that don't support the float extensions. So this will add a lot of implementation complexity, along with style-spec complexity, for a pretty rare use case, so I'm on the fence about the feature.

**Comment by poestencreasey** [comment]
Hi was there any progress on this? We are looking to use for a sentiment map where users upvote or downvote locations.

**Comment by peterqliu** [comment]
@poestencreasey all progress is tracked on this ticket

**Comment by peterqliu** [comment]
> So this will add a lot of implementation complexity, along with style-spec complexity, for a pretty rare use case, so I'm on the fence about the feature.

seeing use case more commonly now https://stackoverflow.com/questions/56760786/how-to-set-mapbox-heatmap-color-by-data-value#

**Comment by mourner** [comment]
Looks like this is too difficult to implement, and considering this isn't a highly requested feature, I'm inclined to close as stale.
