### ISSUE TITLE
False positive detection of missing CSS

### ISSUE THREAD

**Issue by mike-marcacci** [mapbox/mapbox-gl-js#6820]
e6a0604f79bd35ade360bd9c611efb56e76e7fc7 changed mapbox to use a console warning instead of on-screen styles to notify the developer that the styles weren't loaded. This is a great change, but does suffer from false-positives. I am bundling the js and css, which may be part of the issue.

It's only a minor annoyance, since it's just in the console :) but figured I'd send a note.

**mapbox-gl-js version**: v0.46.0-beta.1

**browser**: Chrome 67.0.3396.87 (MacOS)

### Steps to Trigger Behavior

 1. load css and js via webpack
 2. view the map

### Link to Demonstration
https://www.boltline.org

### Expected Behavior
No warning in console

### Actual Behavior
Warning in console

**Comment by jfirebaugh** [comment]
Chrome doesn't seem to be able to debug the minified source on boltline.org. Could you please create a minimal, non-minified example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by jfirebaugh** [comment]
Ah, never mind, it's just really slow. It looks like the issue is that you're using a DOM fragment as the map container, so document stylesheets aren't applied at the point of the check.

To support this case, we could move the check into the render loop and only do it if `this._missingCSSCanary.ownerDocument.body.contains(this._missingCSSCanary)`.

**Comment by mike-marcacci** [comment]
This appears to be fixed in `v0.48.0`. Thanks!
