### ISSUE TITLE
accessToken sometimes isn't automatically replaced in examples

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#6855]
I'm finding many times loading any of the [example](https://www.mapbox.com/mapbox-gl-js/examples) pages, the access token isn't being set (yes I'm logged in), it appears like

    mapboxgl.accessToken = '<your access token here>';

Refreshing the page I see the `<your access token here>` get replaced with my access token, so I'm guessing it might be due to the timing the second time as resources are cached? But not sure, has anyone else noticed this?

**Comment by jfirebaugh** [comment]
I'm not able to reproduce this.

@davidtheclark, this would suggest that [`onUser`](https://github.com/mapbox/mapbox-gl-js/blob/54947953b622decb1f100b7039e00930d8a0dda8/docs/components/example.js#L86) isn't being called in some cases. Does that ring any bells?

**Comment by davidtheclark** [comment]
When I land on a page directly or refresh, I see the access token replaced (as @andrewharvey did). But when I move from one example to another (which is via client-side routing) I see `<your access token here>` again. This seems to a consistent reproduction. So the problem is that the current method of populating that placeholder doesn't work with client-side routing.

The `onUser` callback is only going to be called on that initial page load — that explains why the placeholder is not replaced when you switch pages. Can you try using `MapboxPageShell.afterUserCheck(callback)`, instead? I can chat with you about more details.
