### ISSUE TITLE
How to manually fire popups ? 

### ISSUE THREAD

**Issue by Bastiendmt** [mapbox/mapbox-gl-js#6874]
Hi,

I've been strugling for a while so I'm coming for help here.

Here's my situation

I have a map with few markers in it and a an html table listing all data about points on the map.

I would to like to simulate a click on a marker opening the popup related when I click data in my table.

So far, my problem is that I can't find a way to differentiate my markers and I can't lunch a popup with the method
`map.fire("click", {lngLat: coordinates});`

Even though its seems to click but not openning the popup. I also get the error 
"Uncaught TypeError: Cannot read property 'target' of undefined"

I assume I would need in the first position to give a name to each of my markers and secondly lunch popups using respective name markers.

If anyone can help me, it would be great.
Thanks

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. I suggest opening the popup directly via [`addTo(map)`](https://www.mapbox.com/mapbox-gl-js/api/#popup#addto) rather than trying to do it indirectly via simulating a click event. For further "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by UdayMallikarjun** [comment]
I'm trying to do the same.
Is there any fix for this?

**Comment by ryanhamley** [comment]
@UdayMallikarjun 

This is more of a general programming issue than something that can be built into the library. There's a few approaches that could conceivably be used, but you'll have to figure out what works best for your particular setup. A quick idea could be to create a marker for each element in the table and save it so that it can be accessed when the table element is clicked and the popup can be opened. If you need some guidance, please contact [Mapbox support](https://www.mapbox.com/contact/) or ask your question on Stack Overflow.

**Comment by DeividZavala** [comment]
if it helps anybody else, I faced the same requirement and I found the solution in this way, the comment that @ryanhamley did help a lot along with this example:

https://jsfiddle.net/kmandov/eozdazdr/

In my case I wanted to display the popup if the user swiped in a slider, the slider component was apart from the map so what I did was store the marker and the popup as an array of objects.

```js
const [mapElements, setMapElements] = useState(null)
      
const mapElements = dataSet.map((data, index) => {
    const popup = new mapboxgl.Popup()...
    const marker = new mapboxgl.Marker()...

   return { marker, popup }
})
setMapElements(mapElements)
```

And as the example shows and also the suggestion of @jfirebaugh , on the swipe event:

```js
// I used swiperjs for the carousel

const onActiveIndexChange = (swiper) => {
    mapElements[swiper.previousIndex].popup.remove()
    mapElements[swiper.activeIndex].popup.addTo(mapInstance)
}
```

Also, it is important to mention that I stored the map instance as you can see above to have it available in different parts.

Probably is not the best way to do it but it worked for me haha.

Hope it helps someone else
