### ISSUE TITLE
Webpack bundled code does not work

### ISSUE THREAD

**Issue by swernerx** [mapbox/mapbox-gl-js#6890]
**mapbox-gl-js version**: 0.46.0
**browser**: any, e.g. Chrome
**webpack**: 4.13.0

### Steps to Trigger Behavior

 1. Use a pretty standard Webpack v4 config
 2. Bundling for production
 3. See code crashing: `Uncaught ReferenceError: e is not defined`

<img width="677" alt="bildschirmfoto 2018-06-29 um 13 05 50" src="https://user-images.githubusercontent.com/145201/42089396-3212d24a-7b9d-11e8-9dd0-6fc6ce59fead.png">

It throws directly in the top area of the code.

There are actually a few issues in the distribution for this JS library. I figure it was just not build with Webpack in mind, but probably for more legacy tools like Browserify.

```js
import mapboxgl from "mapbox-gl"
```

This is how the code (inside some blobs) looks like after bundling with Webpack:

```
var sharedChunk = {};
(function(t) {
    var r = "undefined" != typeof window ? window : void 0 !== e ? e : "undefined" != typeof self ? self : {};
    function i(t) {
        return t && t.__esModule && Object.prototype.hasOwnProperty.call(t, "default") ? t.default : t
    }
    function n(t, e) {
        return t(e = {
            exports: {}
        }, e.exports),
        e.exports
    }
    var o = self.performance && self.performance.now ?
```

BTW: Webpack also seems to refer to the source files inside the package - which is probably not your intention. But even explicitly choosing the distribution library via

```js
import mapboxgl from "mapbox-gl/dist/mapbox-gl-dev.js"
```

or 

```js
import mapboxgl from "mapbox-gl/dist/mapbox-gl.js"
```

leads to the same error.

It seems related to the way MapBox is loading it's internal dependencies.

**Comment by swernerx** [comment]
Work-around: In our React app we now switched to using React Helmet for dynamically loading the required scripts/styles from inside the head section:

```js
<Helmet>
  <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js" />
  <link
    rel="stylesheet"
    src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css"
  />
</Helmet>
```

**Comment by ryanhamley** [comment]
Hi @swernerx thanks for using Mapbox and sorry to hear you're having this problem. There's discussion of issues (and several possible solutions) surrounding the GL JS library with Webpack and Uglify in #4359 and a good explanation of this particular issue in [this comment](https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-303880888). In general, Mapbox GL JS does work with ES modules. I built a Vue app this week using Webpack 4, Uglify and the latest 0.46 release of GL JS and can confirm that `import mapboxgl from 'mapbox-gl'` works as expected there. I'm going to close this since discussion has been on-going in the other ticket but if your issue persists, feel free to contribute to that discussion.
