### ISSUE TITLE
full height and width map in ios 

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/mapbox-gl-js#6967]
Hi, 
I am using ionic 3 with angular 5 to develop application. I want full height and width map. 

I have given below css: 
#map {
        height: 100%;
        width: 100%;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0; 
        margin: 0;
        padding: 0; 
        position: absolute!important;
        overflow: hidden!important;
    }

it is working fine in android and in ios sometime not taking full height and width. 

I checked element taking full height and width but canvas not taking full heigh and width. 

anyone have idea. 
![screenshot](https://user-images.githubusercontent.com/20280498/42731204-722f8c0a-8819-11e8-94a5-1c88c722859a.jpg)

**Comment by ryanhamley** [comment]
Hi @ansarikhurshid786 thanks for using Mapbox and sorry to hear you're having issues. A common issue with using 100% height and width with Mapbox GL JS is that the container is not fully rendered before the map is constructed so the map will be rendered to whatever size the container originally is. You can often fix this by calling `map.resize()` after the container is fully rendered.

I encourage you to check out our guides and resources at https://www.mapbox.com/help/ or ask your question on a forum like Stack Overflow. Due to the volume of issues and limited engineering resources, we are unable to provide additional support here on GitHub.
