### ISSUE TITLE
Safari renders black tiles around raster layer

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-js#6986]
**mapbox-gl-js version**: v0.46.0

**browser**: Safari 11.1.1 (13605.2.8)

### Steps to Trigger Behavior

 1. Upload geojson to mapbox studio
 2. Render layer
 3. Black tiles at the background in Safari

### Link to Demonstration

https://jsfiddle.net/nwx4poe0/9/

![image](https://user-images.githubusercontent.com/988471/42886535-7e1b2fc0-8aac-11e8-81e1-4aff47bdcdbe.png)

**Comment by bravecow** [comment]
If necessary I can provide a minimal example on jsbin 😏

**Comment by bravecow** [comment]
This Mapbox example have same issue:

https://www.mapbox.com/mapbox-gl-js/example/adjust-layer-opacity/

![image](https://user-images.githubusercontent.com/988471/42889647-9ee00f62-8ab3-11e8-8ab1-b034646c6df0.png)

**Comment by asheemmamoowala** [comment]
@bravecow you are seeing the black pixels because  Safari doesnt support the `webp` image format. In this case the Mapbox API detects the browser and sends `jpeg` files which do not support transparent pixels. 

Have you considered using the [Image source](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-image) for your images? That should allow displaying a `.png` file with transparency in all browsers.

**Comment by bravecow** [comment]
How to serve GeoTIFF with PNG tiles described here: https://www.mapbox.com/help/troubleshoot-raster-transparency-issues/
