### ISSUE TITLE
Changing interface orientation stops GeolocateControl location follow me

### ISSUE THREAD

**Issue by dieterdreist** [mapbox/mapbox-gl-js#7053]
**mapbox-gl-js version**:
v0.47.0 and previous

**browser**:
mobile safari (ios), latest stable

### Steps to Trigger Behavior

 1. with "show my position and map follow me" activated, rotate the device

### Link to Demonstration
any map

e.g. 
https://jsbin.com/libehaziqo/edit?html,output

### Expected Behavior
keeps following

### Actual Behavior
stops following as if the used had panned the map.

**Comment by andrewharvey** [comment]
I can confirm this is a bug. This happens because when `trackResize` is true (which is the default) then when the device orientation changes you naturally have resized the map container so this map.resize method is called:

https://github.com/mapbox/mapbox-gl-js/blob/97a78c3264cdc316724ca6912a598f8bafd0f513/src/ui/map.js#L475-L499

However that then fires `movestart`. According to the API `movestart` is,

> Fired just before the map begins a transition from one view to another, as the result of either user interaction or methods such as Map#jumpTo.

We use `movestart` to detect when the user pans the map so to cancel the following behaviour of the geolocate control, however in this case since the map has transitioned from one view to another due to the orientation change, then `movestart` fires and the tracking is cancelled.

https://github.com/mapbox/mapbox-gl-js/blob/97a78c3264cdc316724ca6912a598f8bafd0f513/src/ui/control/geolocate_control.js#L297

I suppose the solution here to to listen on other events:

> touchstart
> dragstart
> zoomstart
> rotatestart
> pitchstart
> boxzoomstart


But care must be taken to ensure we cover all the interaction scenarios, and even then I'm not sure how we'll detect when someone calls flyTo or other camera methods in the API, as naturally we should stop tracking in those circumstances also.

**Comment by arindam1993** [comment]
Hi @andrewharvey 👋 

I took a different approach to fixing it, #8736 , please review 🙏 .
