### ISSUE TITLE
Marker click event is not overwriting between layers.

### ISSUE THREAD

**Issue by agiratech-mani** [mapbox/mapbox-gl-js#7101]
Hai Guys,

Am using Mapbox one my client projects. Here I have facing one issue with click event.

Actually I have using two layers to load two different type of data layer 2 is over lapping layer 2. And each layer have markers with relative click events. 

Issue is when both layer1 and layer2 markers are in same coordinates layer2 marker is over lapping layer1's marker. But while click on layer2 marker it is also triggering layer1 click event. How to prevent this?

My Code:

```
map.addLayer({
  id: 'layer1',
  type: 'circle',
  source: 'allPanels',
  'source-layer': self.mapLayers['allPanels']['source-layer'],
  minzoom: 7,
  paint: {
    'circle-opacity': 0.2,
    'circle-radius': {
      'base': 2,
      'stops': [[9, 2], [11, 4]]
    },
    'circle-color': '#878787'
  }
});
map.on('mouseenter', 'layer1', function () {
  self.map.getCanvas().style.cursor = 'pointer';
});
map.on('mouseleave', 'layer1', function () {
  self.map.getCanvas().style.cursor = '';
});
map.on('click', 'layer1', function(){
	console.log("clicked layer 1")
});

map.addLayer({
  id: 'layer2',
  type: 'circle',
  source: 'allPanels',
  'source-layer': self.mapLayers['allPanels']['source-layer'],
  minzoom: 7,
  paint: {
    'circle-opacity': 0.2,
    'circle-radius': {
      'base': 2,
      'stops': [[9, 2], [11, 4]]
    },
    'circle-color': '#878787'
  }
});
map.on('mouseenter', 'layer2', function () {
  self.map.getCanvas().style.cursor = 'pointer';
});
map.on('mouseleave', 'layer2', function () {
  self.map.getCanvas().style.cursor = '';
});
map.on('click', 'layer2', function(){
	console.log("clicked layer2")
});
```

Any one can help me.
Thanks,
Mani

**Comment by ryanhamley** [comment]
Hi @agiratech-mani Thanks for using Mapbox GL JS! The issue here is that your markers are actually rendered in the canvas and aren't DOM elements, so a click event can't be applied to them in the traditional JS sense. The library has some internal logic to simulate these events but a click event will be applied to any features at a given location on the map. You can try using the [Marker](https://www.mapbox.com/mapbox-gl-js/api#marker) class which creates actual DOM elements.

Also, please note that this issue tracker is for reporting bugs and feature requests. "How to" questions are generally better asked on Stack Overflow or by contacting [support](https://www.mapbox.com/contact/support/).
