### ISSUE TITLE
Enable consistent sorting across tile boundaries

### ISSUE THREAD

**Issue by lilykaiser** [mapbox/mapbox-gl-js#7111]
This ticket is to track requests for/work on:
- Enable consistent sorting across tile boundaries for symbol layers
- Enable consistent sorting across tile boundaries for circle layers
![](https://d2mxuefqeaa7sj.cloudfront.net/s_F0289770F7454833D1C84F6943025C1CB07D3120406A1BED3D9CE7564FA4FC91_1533849003016_43156477-3c4821ca-8f48-11e8-86a2-aa98d65082e0.png)

The fact that we can't maintain sort order for symbol layers that cross tile boundaries is a known regression and byproduct of viewport collision detection. You can see some of the design discussion of the tradeoffs involve at https://github.com/mapbox/mapbox-gl-js/pull/5150#issuecomment-326438377

For circle layers, this appears to be an older issue.

**Comment by ChrisLoer** [comment]
@mourner or @ansis, do you have ideas on how we could best approach this? Also are there other layer types besides circles and symbols that are affected? The two approaches I have in mind are:

- Make a (more expensive) draw mode for circle/symbol layers that tries to calculate padding for the layer so that symbols/circles likely to overlap get included in tiles on both sides of the boundary (would we do this at the GeoJSONSource level?). Turn on tile clipping and then draw the same symbol in both tiles.
- Some sort of "mega tile" merging to avoid tile boundaries. Win because of fewer draw calls, loss because of having to re-upload everything in the viewport whenever one tile changes.

Neither seem like an obvious great solution to me...
