### ISSUE TITLE
Marker also dragging while drag map

### ISSUE THREAD

**Issue by Rajavelu** [mapbox/mapbox-gl-js#7119]
When drag map, marker also dragging. How its possible?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3033600/44033329-afd16a4a-9f27-11e8-8c75-8fac5a4c4484.gif)

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. Unfortunately, you haven't provided enough information for us to be able to help you. When opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer. In particular, for issues such as this we will almost always need you to provide a minimal working example that demonstrates the issue. If you can provide those things, please feel free to open a new issue.
