### ISSUE TITLE
Live waves and water flow

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#721]
Probably not a top priority in the roadmap, but now, with all the capabilities of WebGL, it would be awesome to have "live" ocean and/or lake waves like Cesium (https://cesiumjs.org/2013/02/15/Cesium-Terrain-Tutorial/).

Something related that perhaps is a bit more useful (i.e. not just for aesthetics) would be to render actual water flow direction in creeks and rivers.

**Comment by ansis** [comment]
Support for this would come indirectly as either:

- a custom layer type implemented outside of mapbox     https://github.com/mapbox/mapbox-gl-js/issues/281
- a terrain mesh with lighting that can be programatically updated    https://github.com/mapbox/mapbox-gl-js/issues/1489

I'll close this issue since I think those two will cover the core mapbox-gl-js part of this.

**Comment by mglonnro** [comment]
This issue is closed, and there are now custom layers and new terrain features, but: should it be technically possible to implement waves and water flow as a custom layer at the moment? Or in any other way? I've failed in my own attempts :)
