### ISSUE TITLE
Stop Mapbox from re-rendering

### ISSUE THREAD

**Issue by romucci** [mapbox/mapbox-gl-js#7225]
Is there a way to keep the Mapbox from re-rendering with each route-change? :D

**Comment by ryanhamley** [comment]
Hi @romucci thanks for using Mapbox. We would need more information to know how to properly respond to your issue. In the future, when you open an issue, please fill out the fields present in the default issue template as that will help us in diagnosing the issue.

Additionally, this issue queue is for tracking bugs with the GL JS library. While we can't diagnose your problem based on your question, it sounds like you're having a problem with routing in a third-party framework such as Angular or React. This is outside of the scope of support Mapbox can offer so I'd suggest asking your question on a forum such as Stack Overflow to get better help.

If it turns out you can reproduce a bug in the GL JS library itself in a standalone JSBin, please feel free to open another issue.

**Comment by trusktr** [comment]
You can stop the map's rendering like this: https://github.com/mapbox/mapbox-gl-js/issues/12625
