### ISSUE TITLE
Updating a layer's circle-radius doesn't change the result of queryRenderedFeatures

### ISSUE THREAD

**Issue by haywoodsloan** [mapbox/mapbox-gl-js#7298]
**mapbox-gl-js version**: 0.49.0

**browser**: Chrome (69.0.3497.100), Edge (42.17134.1.0)

### Steps to Trigger Behavior

 1. Add a circle layer with a radius 'x' to the map
 2. Use setPaintProperty to update the circle-radius of the layer to 'y'
 3. Call queryRenderedFeatures for the circle layer at a point between radius 'x' and 'y'
 4. No features are returned, but if the circle layer was added to the map with radius 'y' originally the point feature will be returned

### Link to Demonstration

https://jsbin.com/seficiwufi/edit?html,css,js,console,output

### Expected Behavior

queryRenderedFeatures should return the point feature when called for a screen point within the circle layer's new radius

### Actual Behavior

queryRenderedFeatures only returns the point feature when called for a screen point within the circle layer's original radius

**Comment by peterqliu** [comment]
Something weird's going on. In trying to debug this, I found that setting `visibility: none` on the circle layer *does* make the feature turn up with `queryRenderedFeatures` (https://jsbin.com/xacixavemu/1/edit?html,css,js,console,output) Two weird things:

- that non-visible layers turn up with queryRenderedFeatures, at all
- that the visibility setting affects how (whether?) the paint property gets updated for qRT

**Comment by ryanhamley** [comment]
Related tickets: 
- https://github.com/mapbox/mapbox-gl-js/issues/6833
- https://github.com/mapbox/mapbox-gl-js/issues/5686

Per https://github.com/mapbox/mapbox-gl-js/issues/5686 I think I'd actually expect the layer with `visibility:none` to not show up when queried so that's an interesting result.

**Comment by asheemmamoowala** [comment]
@haywoodsloan Thanks for the jsbin. This is indeed an interesting find. It is not a bug though 😞. The reason that `queryRenderedFeatures` is not working in this case is because it lags behind the newly added layer. The new source and layer are added after the inital load, but are also trhemselves added asynchronously.

In your demo code the `queryRenderedFeatures` for the increased radius is being called 250ms after the style has loaded. But this timer is firing before the newly added `Test-Circle-Layer` is loaded.

An alternative way to implement the query without a timeout is described in this [#4222(comment)](https://github.com/mapbox/mapbox-gl-js/issues/4222#issuecomment-279446075)
