### ISSUE TITLE
Support keeping symbols upright when they are at a specific point with a specific orientation.

### ISSUE THREAD

**Issue by mkv123** [mapbox/mapbox-gl-js#7402]
## Motivation

I would like to place text in a specific point and with a specific orientation, but such that the text would not be shown upside down.

For example a long beach, it would be nice to be able to place text, so it is shown at an orientation somewhat parallel to the coastline (though not wiggling along it exactly), but so that if the map is rotated, the text isn't upside down. 

There are many other cases as well, where it would be useful to be able to specify the orientation, but in a way where it would switch 180 degrees to not be upside down.

## Design Alternatives
Alternative 1: Change icon-keep-upright and text-keep-upright layout property to also work when symbol-placement is point. 

Alternative 2: Give map view rotation as a variable to expressions, and let the user write a custom expression to adjust the orientation.

## Design

There are benefits to both: 

Alternative 1, is what I expected to work already. From a sdk-user point of view, it seems strange that keep-upright isn't valid when you have a symbol placed at a point with a specified orientation.
 
Alternative 2 allows for more flexible use, as then any data driven property can be changed based on the map rotation.

### Implementation

Style spec change.

**Comment by mollymerp** [comment]
For this use case, we recommend adding a line geometry (via GeoJSON source for example) along where you'd like your label to be placed, and then using `symbol-placement: "line"`. This is how Mapbox Streets places labels for rivers and lakes:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/2425307/46836483-76e6de00-cd66-11e8-9b30-84c8fc29788f.png">

<img width="611" alt="image" src="https://user-images.githubusercontent.com/2425307/46836509-9e3dab00-cd66-11e8-8f28-be4f876af7b4.png">

If this does not satisfy your request, please re-open the issue with more details about your desired behavior.

**Comment by mkv123** [comment]
@mollymerp : I guess I should have been more clear with my original request, but I have tried this solution and it does not work for many cases, which prompted me to open this ticket. Let me explain what my experience to clarify:

Initially I have a data set with labels with a given size and orientation that I would like to move to Mapbox. 

Attempts and failures:
1) Add a point, use data-driven to set orientation, mark keep-upright, doesn't work, since it isn't a line.
2) Change data to have a short line instead of the point to make text appear at right spot and to support keep-upright. Doesn't work as text doesn't fit on the line.
3) Change data to have long line, now fits until I zoom out or have longer text, then doesn't fit again.
4) Change data to have a really really long line, notice that content repeats, use a really really long symbol-spacing value to prevent repeats. Unfortunately now tile splitting is breaking the line, causing 1) text not to be at the right spot, 2) text repeating again.

After really, really trying to use the line based approach, in order to get a centered title with an orientation that keeps upright, I have failed.  

Please consider re-opening this issue, as the suggested workaround has been tried but even with a multitude of tries did not yield the hoped for result.

**Comment by mollymerp** [comment]
@mkv123 Sorry to hear you've been having difficulty with this. Have you tried `symbol-placement: "line-center"` ? https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-symbol-placement

**Comment by mkv123** [comment]
@mollymerp No, line-center wasn't available at the time. However, if I understand correctly, the process of tile generation cuts geometries at tile borders (+ some buffer),  correct? I cannot directly see how line-center would not be affected by the same issues as the normal line placement when the long line crosses two or more tiles (exceeding the buffer).

**Comment by mkv123** [comment]
@mollymerp: Please consider re-opening this ticket. This is something we actually need, and as far as I know none of the (quite hacky tbh) workarounds actually work for us.

@ansis: If you have any pointers where this could be implemented in code, I could even try to take a stab at it.

**Comment by ChrisLoer** [comment]
> the process of tile generation cuts geometries at tile borders (+ some buffer), correct?

Yeah, that's right. If you're using a GeoJSON source, you can control the buffer size, although it will affect everything in that source (https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson-buffer). If you're using tools like tippecanoe to make tiles, you can be more explicit about allowing the lines for a specific layer to be large relative to the tile size. This is what we use in our core styles for cases like the "label roughly following a coastline" case you mention. Although including a buffer is necessary if you want the label to cross over tile boundaries, we don't have a clear idea of any use cases where you'd need to extend a label more than one full tile buffer on either side (so the size of three tiles, or 512x3 => 1536 pixels).

I understand it's frustrating to work with these limitations, and I agree that there's no fundamental reason `text-keep-upright` wouldn't be expected to work with point labels.

Your "alternative 2" proposal (expose something like a "bearing" expression) would be awesome, but unfortunately it'd also be somewhat architecturally difficult. Evaluating expressions is relatively expensive, so we don't do it on every frame -- even though zoom (and bearing) can change on every frame. We put special limitations on "zoom" expressions so that zoom-based interpolation can be done in the shader. We could replicate the same approach for "bearing", but it wouldn't be possible to have any property that depended on both zoom and bearing, because we wouldn't be able to make an interpolation function for them.

I took a look at implementing "alternative 1". You can get an idea for how you would do it by looking at:

https://github.com/mapbox/mapbox-gl-js/blob/321a3695a6c068a1cfd58629ed9d8dcb333b8bbd/src/shaders/symbol_sdf.vertex.glsl#L90-L100

In that logic, you could see if the rotation applied went out of your "upright" range, and then just add 180 degrees to do the flip. However, there are several further issues you'd have to deal with:

- In the shader, you don't know the `text-rotate` value for the symbol. That's currently calculated as a layout property at tile generation time, encoded in the layout vertex coordinates, and then discarded. You don't have a way to re-build it in the shader -- if you wanted to get this information into the shader, you'd need to promote `text-rotate` to work like a paint property, meaning that when it's data-driven there are extra "paint vertex arrays" uploaded to the shader to allow the shader to know per-feature values.
- The logic above is only used for labels draw in the viewport plane (i.e. "non pitched"). For labels drawn in the plane of the map, you'd have to come up with different rotation logic based on the map plane.
- To extend our current 'text-keep-upright' logic to point labels, you'd also have to include support for scripts that support vertical writing modes. Because the glyphs can actually be different between vertical and horizontal writing modes, this requires doing layout twice for each symbol, uploading both versions to the GPU, and then choosing at draw time which version to show.

The second two concerns probably aren't a big problem for you, but I think the first would still take a moderate amount of work to implement.

Unfortunately, as it stands, I don't see the cost:value ratio of this feature as high enough to get onto our roadmap any time soon. This may be because we don't see the value of what you're doing well enough -- or why using `line-center` doesn't work for you. More screenshots, example data, example tiles, etc. are always welcome!
