### ISSUE TITLE
Vector and raster switching, loading efficiency problem

### ISSUE THREAD

**Issue by Niumeng1** [mapbox/mapbox-gl-js#7467]
**mapbox-gl-js version**:0.50.0

### Question
After loading the default map style, I switched to a raster map, and I used setStyle ('...'), but found that the map data was all reloaded and could not be compared to Google Map Switching.

How can I improve the efficiency of switching (base map)?

### Links to related documentation

1.mapSL.setStyle('/../styles/root.json');

2.mapSL.setStyle('/verctor_Sate/root.json');

**Comment by ChrisLoer** [comment]
Hi @Niumeng1, thanks for using Mapbox. We can't provide general support for Mapbox GL via GitHub issues, but as a quick pointer, if you want to keep the data in memory you could try making a single style that included both raster and vector layers, and then switch which layers you bring to the front. I don't expect it would be a very useful thing to do, however, since the browser will already cache raster tiles for you, so reloading map data shouldn't actually be very expensive.
