### ISSUE TITLE
Setting transition in immediate succession ignores changes.

### ISSUE THREAD

**Issue by SnailBones** [mapbox/mapbox-gl-js#7492]
**mapbox-gl-js version**: 1.4.0

**browser**: Tested on Chrome and Firefox

I'm trying to make a circle transition that occurs every time an icon is clicked. The code controlling the transition is as follows:

```
// This should instantly set the radius to 0
      map.setPaintProperty('selected', 'circle-radius-transition', {duration: 0});
      map.setPaintProperty('selected', 'circle-radius', 0);
//This radius should then grow
      map.setPaintProperty('selected', 'circle-radius-transition', {duration: 4000});
      map.setPaintProperty('selected', 'circle-radius', 80);
```

### Link to Demonstration

https://codepen.io/snailbones/pen/ZqVrKG?editors=0110

### Expected Behavior

 The radius should swell from zero every time this code is called.

### Actual Behavior

In practice, the first two lines are ignored. The radius transitions from its defined value, and then does not change.

I have found a hacky workaround, which is to wrap the last two lines in a short timer. This will work most of the time, bit not always.
```
      map.setPaintProperty('selected', 'circle-radius-transition', {duration: 0});
      map.setPaintProperty('selected', 'circle-radius', 0);
setTimeout(function () {
      map.setPaintProperty('selected', 'circle-radius-transition', {duration: 1000});
      map.setPaintProperty('selected', 'circle-radius', 80);
    }, 10);
```

**Comment by ryanhamley** [comment]
Hey @SnailBones thanks for using Mapbox. I forked your example and played around with it a bit as you can see here: https://codepen.io/rsh412/pen/MPLxOJ?editors=0110

If you click around enough, you can see that sometimes without the timer, you can still produce the correct animation effect and sometimes with the timer, you get the unexpected behavior, all of which points to a timing issue. The layer simply doesn't always have time to update itself before a new click. As you can see in my fork of your pen, instead of using a timer, I used `requestAnimationFrame` which leads to more consistent behavior because the transition will always happen on the next frame. I'd suggest that this isn't really a bug. You can see that we use `requestAnimationFrame` for a lot of animation effects such as in [this example](https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-line/). The library uses `requestAnimationFrame` for animation timing internally as well. Hope this helps.

**Comment by SnailBones** [comment]
Thanks @ryanhamley!
