### ISSUE TITLE
wierd behavior when returning coords of a mouseovered polygon

### ISSUE THREAD

**Issue by primvla** [mapbox/mapbox-gl-js#7510]
version: mapbox-gl.js v0.50.0
browser: all (i guess)

Link to Demonstration: https://codepen.io/gescom/pen/QZROeL

Approach the green poly and observe returned coordinates.  They are not the same as in the original source. And they change further when hovered towards the right section of the green poly (area below the blue rectangle I put there for the reference).

Expected Behavior: I need the script to return the actual coordinates as set in the Layer. I need to replicate coords in the properties array now, but that is cumbersome. I can work with approximate values that are returned, but the values returned when approached from the right are way off.

cheers!
p.

**Comment by ryanhamley** [comment]
Hi @primvla this turns out to be a tile buffer issue. The quick answer is that you can fix this by increasing the tile [buffer](https://www.mapbox.com/mapbox-gl-js/style-spec#sources-geojson-buffer) size on your GeoJSON property from the default size of 128 to 256.

`queryRenderedFeatures` is not guaranteed to return an entire polygon. When a GeoJSON layer is added to the map, it is tiled. If `queryRenderedFeatures` is applied on a polygon that crosses a tile boundary, only the portion that is within the tile where `queryRenderedFeatures` is called will be returned. The caveat is that each tile has a buffer on it and any feature area within that buffer will also be included in the polygon returned by `queryRenderedFeatures`.

I [forked your pen](https://codepen.io/rsh412/pen/GYVqpN) and simplified it to make it a bit clearer what's going on. Notice how if you zoom out so that the polygon is fully within one tile, you no longer see the behavior of the coordinates not matching the corners. With the polygon crossing a tile boundary, if you uncomment line 16, you'll see that the entire polygon is now returned when hovering over it from the right-hand tile. That's because the entire polygon is now within the buffer.

As for the order of the coordinates in the array returned by `queryRenderedFeatures`, it's reversed from the source's coordinates array. I believe this is caused by the fact that polygons are drawn in counterclockwise winding order.

**Comment by primvla** [comment]
Wow, great, thanks!
