### ISSUE TITLE
current yarn.lock file is incompatible with node version 10.11.0

### ISSUE THREAD

**Issue by booo** [mapbox/mapbox-gl-js#7524]
**mapbox-gl-js version**:  999a8d99dfbf875b0acc20381d40f21c3ab41dfc (master)

**browser**: -

**node.js version**: v10.11.0

### Steps to Trigger Behavior

 1. cd /tmp
 2. git clone https://github.com/mapbox/mapbox-gl-js
 3. yarn install

### Excerpt from yarn output

`
...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.11.0"
error Found incompatible module
...
`

### Expected Behavior

`Yarn install` should run without errors on node.js v10.11.0

### Actual Behavior

Yarn fails to run properly because of an outdated yarn.lock

### Proposed Solution

Update the yarn.lock file with `yarn upgrade`. What's your policy on updating the yarn.lock file? I can prepare a pull request with an update if you like.

**Comment by ryanhamley** [comment]
Thanks for the report @booo We're working on it here https://github.com/mapbox/mapbox-gl-js/pull/7519 Just investigating a couple of issues before merging it.

**Comment by ryanhamley** [comment]
Ah, this is actually two slightly different issues. The `yarn.lock` file is now updated to reflect the change to JSDOM, but that wasn't what was causing the `The engine "node" is incompatible with this module` error. There appears to be a dependency somewhere installing `upath@1.0.4` which is incompatible with Node 10. This issue was [fixed in v1.0.5](https://github.com/anodynos/upath/pull/15) of upath but whatever package is using it hasn't updated. We can run `yarn upgrade` to update all of our packages which results in the huge `yarn.lock` diff we tried to avoid in #7519. In the meantime, `yarn upgrade` or `yarn --ignore-engines install` both produce the desired result.

**Comment by booo** [comment]
`Yarn why upath` should tell you by which package the upath is used.

As far as I understand the `yarn upgrade` documentation it should be possible to upgrade individual packages with e.g. `yarn upgrade upath`. See https://yarnpkg.com/lang/en/docs/cli/upgrade/

If you remove the first occurrence of upath in the yarn.lock file and run `yarn install` you get a minimal change to the yarn.lock file.
