### ISSUE TITLE
Is there a limitation on number of layers ?

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#7593]
**mapbox-gl-js version**:

### Question
I added more than 4900 layers into the map with 12 sources. Then the map displays broken styles such as disordered-layers. (like it should be 1/2/3 but 3/2/1 ordered, or style is ignored). So, I just tried to reduce the number of ~~sources~~ layers. When the number of layers is 4679, everything works as expected. Is there a limit of valid number of layers?

the result is like this,
normal case(layers.length <= 4679):
![image](https://user-images.githubusercontent.com/7428017/48538698-76f37400-e8f8-11e8-9a77-543d5c100923.png)
abnormal case:
![image](https://user-images.githubusercontent.com/7428017/48538731-9094bb80-e8f8-11e8-97da-473b33567a53.png)

**Comment by kkaefer** [comment]
There's no explicit limit to the number of layers a style may have. Instead, it depends on a number of factors influence how many layers you can use at the same time: We're using the depth buffer to control what pixels get drawn in case of overlapping polygons or lines. The depth buffer has a limit to how precise it can be; on some systems it's just 16 bits.

Regardless of whether Mapbox GL can support 4,900 layers or not on your GPU, the fact that you have 4,900 layers means that you may be misusing the library: Could you please describe the use case for having 4,900 layers? Generally Mapbox GL works better and faster the fewer layers you have, since every layer translates to a WebGL draw call, which uses CPU and GPU time.

**Comment by cs09g** [comment]
Thanks for the explanation, I'm testing few ways of creating data. One of the way is to create data per each section of the map. so every data is including almost all set of layers. So, the number of layers became (number of whole set of layers) * (number of section).
I better create the data in one file or create the data per layers but sections!

**Comment by kkaefer** [comment]
Yeah, that sounds like a good first step. Assuming you have 4900 layers evenly distributed over your twelve sources, that'd still be more than 400 layers. Most styles we use have an order of magnitude fewer layers.

**Comment by cs09g** [comment]
FYI,
I have about 1000 layers for whole map, but I divide the section like this to improve the speed of generating mbtiles.
_1_|_5_|___|___
_2_|_6_|___|___
_3_|_7_|___|___
_4_|_8_|___|___
so each section had many of same layers(id). as the map couldn't have same id though it's in different source, I appended each section number ahead of layerid: 1.bg_layer, 1.fill_layer, 1.line_layer, 2.bg_layer, 2.line_layer, ...  -> the result made 4900 layers.(some is not used for some section so the number is not 12000).
