### ISSUE TITLE
Anti-aliasing fails with fill-image

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#768]
Vis-a-vis solid-color polygons. Most apparent at coastlines.

**Comment by ansis** [comment]
We need a new patterned outline shader to fix this. The shader would be similar to the `outline` shader but would read the correct color value from a texture just like the `pattern` shader.

**Comment by peterqliu** [comment]
Updated example at https://api.mapbox.com/styles/v1/peterqliu/cimdq8c4j00gk9lm1aeon9bay.html?title=true&access_token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g#14.95732842875686/31.394041930859558/-81.27884342612008/0

**Comment by ansis** [comment]
osx has a useful feature that lets you zoom in and magnify pixels that could be useful for this.
- open the *Accessibility* system preferences
- check *Use scroll gesture with modifier keys to zoom*
- **un**check *Smooth images*

You should now be able to use `control` + scrolling to zoom in on pixels.

**Comment by ansis** [comment]
@mollymerp It's sounds like you already have a good idea about how to approach this. In case it helps, this is how I'd break it down:
- I'd duplicate the outline shader `shaders/outline.*.glsl` and set it up in `js/render/painter/use_program.js`
- modify `js/render/draw_fill.js` so that it uses the new pattern outline program to render a solid red outline for all fill patterns. much of [this](https://github.com/mapbox/mapbox-gl-js/blob/cb305e11d474fb1d30644eacd024def46156da1b/js/render/draw_fill.js#L25-L52) and `drawStroke` might need to be duplicated
- the red outline should now show up when you render your test case
- switch the test case to a pattern with a lot of sharp color variation
- copy the relevant parts of the pattern shader to the pattern outline shader, update `js/render/painter/use_program.js`, and then set it up in `/js/render/draw_fill.js`.

**Comment by mollymerp** [comment]
working on this in #2372

**Comment by ansis** [comment]
merged in #2372
