### ISSUE TITLE
Does `geocoder.on("result", ...)` fire twice for each request

### ISSUE THREAD

**Issue by loganpowell** [mapbox/mapbox-gl-js#7688]
**mapbox-gl-js version**:0.52.0-beta.1

### Question

I'm trying to fire a function off that loads a new layer after `geocoder.on("result", getSomeData())`

If you take a look at this example (open console):

https://loganpowell.github.io/census-js-examples/examples/with-mapbox-gl_geocoding/index.html

(type in any place in the USA, then - after a result you'll see a choropleth - then click anywhere and the event seems to be triggered again)

and the line in question:

https://github.com/loganpowell/census-js-examples/blob/master/examples/with-mapbox-gl_geocoding/src/index.js#L116

### Links to related documentation

I figured this was possible by looking at this example:

https://www.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/

**Comment by andrewharvey** [comment]
@loganpowell This is an issue in the mapbox-gl-geocoder plugin, which is being tracked at https://github.com/mapbox/mapbox-gl-geocoder/issues/99 which is in turn an upstream issue tracked in https://github.com/tristen/suggestions/issues/13. You're welcome to help resolve the issue. I wasn't able to work out how to do this without breaking IE11 support.

I'll close this issue here to keep the discussion over on those other tickets.
