### ISSUE TITLE
map.getLayer() throws TypeError on map unmount instead of returning undefined if layer does not exist

### ISSUE THREAD

**Issue by mattgif** [mapbox/mapbox-gl-js#7775]
**mapbox-gl-js version**: 0.52.0

**browser**: Chrome

### Steps to Trigger Behavior
1. Mount Map component (React)
2. Unmount Map component

Occurring since updating to react 16.6.0 and react-redux 6.0.0.

### Expected Behavior
`this.style.getLayer(o)` returns undefined, component unmounts gracefully. 

### Actual Behavior
`this.style.getLayer(o)` throws TypeError

**Comment by mourner** [comment]
GL JS doesn't have to conform to React app conventions — it's the responsibility of the developer, so if `getLayer` throws an error, you should wrap it with a try/catch. #7776 is not a suitable fix because there are many other style-related map methods that it doesn't touch, and we want to be consistent — either throw an error or fail silently in all of them.
