### ISSUE TITLE
Unpredictable state when using custom layers

### ISSUE THREAD

**Issue by Pessimistress** [mapbox/mapbox-gl-js#7801]
**mapbox-gl-js version**:
0.52

**browser**:
Chrome

### Actual Behavior

`Painter.renderLayers` leaves the gl context in unpredictable states.

Multiple bugs have been reported on the deck.gl integration in the past because Mapbox arbitrarily changes the context parameters:

https://github.com/uber/deck.gl/pull/2409
https://github.com/uber/deck.gl/pull/2574

The latest behavior observed was that Mapbox leaves the `colorMask` in different states depending on whether the layer above the custom layer is visible:

https://github.com/uber/deck.gl/issues/2602

### Expected Behavior

- Painter should reset all context parameters after itself.
- The "default" parameters should be documented.

**Comment by Pessimistress** [comment]
Here's a list of parameters we need to reset after `Painter.renderLayers`:

- `depthMask`
- `colorMask`
- `depthTest`
- `depthRange`

**Comment by ansis** [comment]
@Pessimistress sorry about the delay looking into this!

Is sounds like deck.gl is rendering into the context outside of a custom layer's `render` method. Is this avoidable? Before a custom layer's `render` method is called we set appropriate values for these depth and color properties.

Currently no values are reset after a map finishes rendering because we are assuming that no one renders into the context outside of a custom layer's `render` and `prerender` methods.

Does deckgl render outside of the `render` method in order to work around something?

**Comment by Pessimistress** [comment]
deck.gl renders into a frame buffer for picking. This is needed for the hover/click callbacks and auto highlighting features.

**Comment by ansis** [comment]
Ahh, that makes sense! We'll fix this by resetting these settings after rendering.

**Comment by jamiebordewyk** [comment]
@ansis Did this work or do you have update?

**Comment by ansis** [comment]
I've opened a PR for this change here: https://github.com/mapbox/mapbox-gl-js/pull/8132
