### ISSUE TITLE
Overlapping Markers - Offset

### ISSUE THREAD

**Issue by JayGazal** [mapbox/mapbox-gl-js#7903]
Hi Guys, i hope you can help with my problem, i have custom markers on my map for an app on iOS, the problem is that when two markers are in the same location, then one overlaps the other. Is there an option where the marker would offset and move to the side so that no overlapping happens?

We implemented clustering, but even then, once you zoom to the max, the markers appear over each other. 

Look at this below example of a map to see how they solved the problem here, but it's not Mapbox
https://jawj.github.io/OverlappingMarkerSpiderfier/demo-3.html

any answers will be a huge help! thank you.

**Comment by ryanhamley** [comment]
Hi @JayGazal thanks for using Mapbox. Currently there is not a built-in way to do this but the `getClusterExpansionZoom`, `getClusterLeaves` and `getClusterChildren` methods of [GeoJSON sources](https://docs.mapbox.com/mapbox-gl-js/api/#geojsonsource) should be helpful in achieving this. Also see https://github.com/mapbox/mapbox-gl-js/issues/7120 for a possible solution.

**Comment by tomasdev** [comment]
@ryanhamley any hints on how? those methods require a cluster_id...

#7120 shows a solution (spiderify) that places marker not even close to their actual location. 

Would it be useful to have a new `symbol` type, "html" given HTML can be converted to image via use of `<svg>` and `<canvas>`?

In the end, what @JayGazal (or at least I do) needs is knowing how the cluster is calculated, that way we can create our own clusters of markers without relying on addSource and addLayer (given those are very limited into what they show)

**Comment by ryanhamley** [comment]
Hi @tomasdev I think you're saying that you'd like to have clustered HTML markers that exist outside the map (e.g. not GeoJSON added with addSource and addLayer)? That'd be something you'd have to implement yourself but I can give you a couple ideas that may be useful.

One of my coworkers here at Mapbox wrote up a [great blog post](https://blog.mapbox.com/clustering-properties-with-mapbox-and-html-markers-bb353c8662ba) on clustering HTML markers by properties which goes into some detail about how the clustering works. 

The source code for clustering is [here](https://github.com/mapbox/mapbox-gl-js/blob/47925a62ff1fd3d7e666afeaf54e513e49713129/src/source/geojson_source.js#L198-L246) but really GL JS just outsources clustering to the [Supercluster library](https://github.com/mapbox/supercluster). You could potentially use the Supercluster library on its own but it may be difficult to synchronize with the map.

Finally, we do have a [`canvas` source](https://docs.mapbox.com/mapbox-gl-js/api/#canvassource) that you could make use of if you'd like to draw into a canvas layer that sits above the map.

Spiderifying the markers is something that you'd have to implement in your app since we have no built in way to do that. Our [support team](https://support.mapbox.com/hc/en-us) may also be able to help if you have further questions on how to achieve your desired effect. Hope this helps!

**Comment by tomasdev** [comment]
Oh, my!
@ryanhamley you're the G.O.A.T.

These are all VERY useful resources (especially the canvas source, which I didn't see on the Style docs for `type`)

Thank you very much man!

**Comment by arenarium-dev** [comment]
Hey, dont know if its still relevant, but Ive been building a plugin for mapbox and other map providers that enables you to organize a large number of custom markers.

![Image](https://github.com/user-attachments/assets/f1e24653-1a44-4edf-86ad-d4853e6e0df4)

You can chek it out at: [https://arenarium.dev/?demo=bookings](https://arenarium.dev/?demo=bookings)
