### ISSUE TITLE
Legend dissapers after I load map

### ISSUE THREAD

**Issue by rd16395p** [mapbox/mapbox-gl-js#8003]
Hello,

Following this example;
https://docs.mapbox.com/help/tutorials/choropleth-studio-gl-pt-2/

My legend disappears after I load the map. I can not find any examples or documentation to fix this. 

I am using these following versions;

<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />

Any help would be appreciated, and I can share my code if needed. I am new to mapbox.

**Comment by ryanhamley** [comment]
Hi @rd16395p sorry to hear you're having trouble. Unfortunately, there's not enough here for us to help. If you think this is a bug in Mapbox GL JS itself, please create a minimal reproduction of the problem on a site like JSBin. Given that the legend is just a piece of HTML outside of the map though, I suspect this isn't an issue with GL JS. Since this issue tracker is for reporting bugs in the library and requesting features, I'm going to close this for now on that assumption. You're welcome to supply the reproduction if you think otherwise and we can reevaluate. For general how-to questions, we recommend posting on a site like Stack Overflow. Thanks!
