### ISSUE TITLE
Give Geolocation Control Marker Pitch Alignment Properties

### ISSUE THREAD

**Issue by JohnCLo** [mapbox/mapbox-gl-js#8034]
Currently when the geolocation control marker is added to the map, the blue marker has no options to change color or set pitch such as "circle-pitch-alignment": "map". For aesthetic purposes, it may be useful for the marker to have more paint options that are exposed to a normal circle type layer.

Current:
<img width="399" alt="Screen Shot 2019-03-13 at 11 21 56 PM" src="https://user-images.githubusercontent.com/1709234/54331227-05e27580-45e7-11e9-901c-b73c93a79229.png">

**Comment by andrewharvey** [comment]
The dot is implemented as a Marker (https://github.com/mapbox/mapbox-gl-js/blob/c60597408379e2bf196118b0466e017806d3b958/src/ui/control/geolocate_control.js#L284) so you can't use the normal pitch-alignment capabilities of using a Circle from the style spec, this would need to be implemented by watching the pitch change and updating the CSS of the Marker.

Originally the dot was done as a Circle, but due to issues with injecting this into the users style, we made it a Marker.

**Comment by mourner** [comment]
Fixed by #10817
