### ISSUE TITLE
flyTo example: Uncaught TypeError: Cannot read property 'call' of undefined 

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#807]
Click the "Fly" button several times in succession and this error is generated.

**Comment by jinlong25** [comment]
Hi @jfirebaugh,

I'm creating an animated map using flyTo() method to fly to a series of points in a geojson file. It seems this error still occurred when I call the flyTo() method the 3rd time.

Here is a [fiddle](http://jsfiddle.net/jinlong/u3qg84c6/5/) I created. After the error occurred, the map will still continue if I click/drag on the map. Just wonder if it's a bug. Thanks!

**Comment by jfirebaugh** [comment]
@jinlong25 Thanks for the test case. This is indeed another bug in `flyTo`. I have a fix in the works for v0.8.0. A workaround for now is to delay the calls to `flyTo` with `setTimeout`:

```
function fly(coord) {
    setTimeout(function() { map.flyTo([coord[1], coord[0]], 16) }, 0);
};
```

**Comment by jinlong25** [comment]
Thanks a lot, @jfirebaugh!

**Comment by StianOek** [comment]
Hey!

few years has passed since the last comment on this thread. hopefully someone will see this :) 

I'm using the useMap hook for the "react-map-gl": "^7.0.10"

and i invoke it like in the docs description : const { current: map } = useMap();

With the code below i get the "Uncaught TypeError: Cannot read properties of undefined (reading 'flyTo')"
```
const handleLocations = (item) => {
    // eslint-disable-next-line react-hooks/rules-of-hooks

    map.flyTo({ center: [52, 32] });

    console.log(item[1], item[0]);
  };
  
   onClick={() => handleLocations(data[item].coords)}
  
```

I cant seem to work this out. 

Fingers crossed for that someone see this :)

**Comment by Atlasestate** [comment]
Would like to have this fixed

**Comment by gabrielmaxgb** [comment]
Hi, @StianOek !
This solution worked for me: https://github.com/visgl/react-map-gl/tree/7.0-release/examples/viewport-animation

If camera transition is all that you want I think it can help.
