### ISSUE TITLE
optimize=true causing Error: Unimplemented type: 3

### ISSUE THREAD

**Issue by VierenV** [mapbox/mapbox-gl-js#8101]
**mapbox-gl-js version**: 0.53.0

**browser**: Chrome 72.0.3626.121

### Expected Behavior

There is an option which allows optimizing mapbox style : https://docs.mapbox.com/help/glossary/style-optimized-vector-tiles/
When this option is actived (ie when optimize=true is provided), Mapbox processes server side rendering and compression to improve performances. 

### Actual Behavior

Mapbox was running well since 10 months on our website. Since yesterday we have errors when getting tiles. The http request is fine and we get content from Mapbox, however a javascript error pops when processing the tile. From #1567 I understand that it could be related to gzip compression. However using directly the mapbox plugin I do not handle myself http headers.

Error :
Uncaught Error: Unimplemented type: 3

### Example 

http://jsfiddle.net/3m067shk/

**Comment by mapsam** [comment]
Hi @VierenV - thank you for reporting this. I'm taking a look now. Seems related to https://github.com/mapbox/mapbox-gl-js/issues/8099

**Comment by vitaliyhayda** [comment]
Just had this issue after adding custom SVG icons. Had to disable optimize parameter as a temporary fix.

**Comment by mapsam** [comment]
@VierenV I've pushed a fix out to our servers and confirmed your jsfiddle is loading tiles again with `optimize=true`. Please confirm you're seeing the same! If you notice any intermittent issues it's likely due to tile caching on our edge server. In the meantime, as @vitaliyhayda mentioned, removing `optimize=true` will avoid the issue.

Appreciate your patience - and apologies for the inconvenience.

**Comment by VierenV** [comment]
It is working great ! Thank you for your reactivity @mapsam
