### ISSUE TITLE
Ability to set values for each side of "text-halo-width" and "icon-halo-width"

### ISSUE THREAD

**Issue by vitaliyhayda** [mapbox/mapbox-gl-js#8103]
Not all icons or text are symetrical... For example, in my use case, the angle arrow with 6px "text-halo-width" has 2.7x more halo space behind it then in front.

![Image of Yaktocat](https://i.postimg.cc/hPX5kz8r/Screen-Shot-2019-03-31-at-09-36-32.png)

Ideally text-halo-width and icon-halo-width would function in the same way as CSS margin or padding. If 1 value provided - then same for all sides, if 2 or 4 values - then it's specific for each side. It might also make sence to rename the property to *-halo-dimentions or *-halo-size

**Comment by peterqliu** [comment]
This seems nontrivial given [how we do SDF halos](https://blog.mapbox.com/drawing-text-with-signed-distance-fields-in-mapbox-gl-b0933af6f817), but @kkaefer may know more about that

Also, CSS margins make sense on a rectilinear DOM element, but how do we define top/left/bottom/right on a glyph, say the letter `S`? Where does one side end and the next begin, on a shape that isn't a rectangle?

**Comment by peterqliu** [comment]
closing, in absence of better ideas

**Comment by kkaefer** [comment]
@vitaliyhayda it looks like the halo isn't actually a halo in this case, but a rectangle around the glyph. This is because the halo radius is too big. I understand that you're looking to draw a really wide halo in this case, but there's an implementation limit to how wide the halo can be. I recommend using an icon that includes the "halo"/outline in this case.
