### ISSUE TITLE
Re-export supercluster

### ISSUE THREAD

**Issue by sheerun** [mapbox/mapbox-gl-js#8114]
## Motivation

Some packages that wrap mapboxgl like https://github.com/alex3165/react-mapbox-gl need to use supercluster to manually cluster markers, to do so they depend on supercluster which results in duplicated dependency being bundled (once in minimized mapboxgl and once for supercluster that react-mapbox-gl uses). It would be nice if mapbox re-exported supercluster functionality so react-mapbox-gl could use it directly instead of depending on it

### Implementation

Just one extra named export in src/index.js that exports supercluster

**Comment by mourner** [comment]
I don't think we should re-export an internal dependency. Supercluster is 2.8KB gzipped — it's not worth increasing API surface in GL JS and complicating things to save 2.8KB.

Also, generally I'd recommend against using Supercluster manually with GL JS. The built-in one is superior in performance (because it happens on the worker side), integrates with the expression system for features like property aggregation, etc.
