### ISSUE TITLE
Setting map marker from click event causes strange artifacts appearing on map in VueJS

### ISSUE THREAD

**Issue by ako977** [mapbox/mapbox-gl-js#8146]
**mapbox-gl-js version**: 0.53.1

**browser**: Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Implement mapbox in VueJS Single Page Application
 2. Select feature on marker
 3. Selected feature triggers click event with `this.currentMap.on('click', layerId, callbackFunc)`
 4. callbackFunc runs the function described below to set the marker on the map. The artifacts only appear when the marker is set on the map, not on the click event
 5. The map is removed and listeners destroyed, but creating a new mapbox instance still shows the artifacts; only a full browser reload clears it until the feature is clicked again

The features are on a layer made of a defined source (below):

```
{
      'type': 'FeatureCollection',
      'features': [{
        'type': 'Feature',
        'geometry': {
          'type': 'Point',
          'coordinates': [X, Y]
        },
        'properties': o
      }, ...]
    }
```

and a layer defined below:

```
{
        'id': <layerId>,
        'type': 'circle',
        'source': <sourceId>,
        'minzoom': <displayAtZoomLevel>,
        'icon-allow-overlap': true,
        'paint': {
          // make circles larger as the user zooms from <displayAtZoomLevel> to z22
          'circle-radius': {
            'base': 2,
            'stops': [[<displayAtZoomLevel>, 3], [22, 180]]
          },
          // https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-match
          'circle-color': '#fff',
          'circle-stroke-width': 1,
          'circle-stroke-color': '#204da2'
        }
      }
```

### Expected Behavior

Map should appear as normal with a marker

<img width="556" alt="Screen Shot 2019-04-11 at 10 34 57 PM" src="https://user-images.githubusercontent.com/1375416/56008383-1f401580-5caa-11e9-9837-5ea56bf41dea.png">

### Actual Behavior

Map shows scrambled artifacts especially on roads, etc. when Map marker is added using the following code:

```
setMarker (markerContext, { lng, lat }, requestRouteCallback) {
    let lngLat = [Number(lng), Number(lat)]
    if (lngLat.length) {
      const marker = new mapboxgl.Marker().setLngLat(lngLat).addTo(this.currentMap)
      if (markerContext === 'start') {
        if (this.startEndMarkers.start) {
          this.startEndMarkers.start.remove()
        }
        this.startEndMarkers.start = marker
      } else if (markerContext === 'end') {
        if (this.startEndMarkers.end) {
          this.startEndMarkers.end.remove()
        }
        this.startEndMarkers.end = marker
      }
      this.currentMap.flyTo({ center: lngLat, zoom: 12, curve: 2 })
    }
}
```

Map shows this:

<img width="712" alt="Screen Shot 2019-04-11 at 9 44 34 PM" src="https://user-images.githubusercontent.com/1375416/56008189-5235d980-5ca9-11e9-815e-efea0a7b0627.png">

Is this something to do with only VueJS or Single Page Applications?
I tried to find some sort of "refresh/redraw" function in the Mapbox GL API but could not find anything.

Just curious if anyone has encountered this before?

**Comment by ryanhamley** [comment]
Hi @ako977 nothing immediately jumps out to me as a potential issue but this

> The map is removed and listeners destroyed, but creating a new mapbox instance still shows the artifacts; only a full browser reload clears it until the feature is clicked again

makes me suspect that the issue is with the data you're supplying to GL JS, not GL JS itself. You may try wiping or resetting the source data that's used to instantiate a new map instance in order to nail down the data as the cause. It looks like you're probably trying to create a dashed pathway to the marker? If that's the case, then I'd assume there's something going haywire in the path algorithm and it's updating the styling of all streets.

Unfortunately, we don't have the capacity to help you debug a SPA application so I'm going to close this given my suspicion that it's not a bug in GL JS. If you ultimately determine that there is a bug in GL JS, you can reply to this issue with a minimal reproduction of the bug (e.g. without Vue). In the meantime, we recommend Stack Overflow for general how-to questions and you can always try [Mapbox support](https://www.mapbox.com/contact/support/). Thanks!

**Comment by ako977** [comment]
Thanks for the reply. Your comment on the dashed pathway and source data helped to somehow pinpoint it down to this occurring on a click AND the map panning or zooming in/out. If no movement occurs, the artifacts do not appear after the click. I will post this question also on StackOverflow.
