### ISSUE TITLE
Fetching sprite fails: 404 errors on loading style created in Studio

### ISSUE THREAD

**Issue by bestofcoding** [mapbox/mapbox-gl-js#8197]
**mapbox-gl-js version**: 0.53.0

**browser**: Chrome Version 74.0.3729.108 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. In Mapbox Studio, create a new style by starting blank
 2. Change the color and opacity of the background layer
 3. Add a new layer and use data from [Natural Earth Data](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries/) as a source by uploading it
4. Go back to the 'style' tab and change the color of this layer
5. Publish it (not as new)
6. View it in the browser by using the Share URL, open the console to see the errors

### Link to Demonstration

[Example map with Share URL](https://api.mapbox.com/styles/v1/infoqualitystuff/cjuwxhpe005vy1flx4y2erqiz.html?fresh=true&title=true&access_token=pk.eyJ1IjoiaW5mb3F1YWxpdHlzdHVmZiIsImEiOiJjanVtbXRrY2UyYnVkM3lvYXk3ZGkzb3ZjIn0.GvEdw9B1dpcsl7WUKgQx9g#0.0/0.000000/0.000000/0)

### Expected Behavior

No errors.

### Actual Behavior

404 Errors because it is trying to fetch sprite files that apparently aren't there.

**Comment by ryanhamley** [comment]
Hi @bestofcoding this is the expected behavior when creating a blank style. A sprite URL is always created but by default it will point to a non-existent resource on a blank style. You will have to manually add a sprite sheet by clicking the `Images` tab in the control panel in the upper right corner of the screen, as shown in this screenshot.

<img width="435" alt="Screen Shot 2019-04-25 at 12 18 08 PM" src="https://user-images.githubusercontent.com/4523080/56762312-72a76e80-6754-11e9-924d-06d426d5eae4.png">
