### ISSUE TITLE
How to custom mapboxgl-canvas's style?

### ISSUE THREAD

**Issue by ajiko** [mapbox/mapbox-gl-js#8204]
**mapbox-gl-js version**:

**Comment by ajiko** [comment]
![image](https://user-images.githubusercontent.com/33706930/56859031-6c64fc80-69b7-11e9-9be3-9017132b429a.png)
I want to make canvas's position as static, for some reasons, it come with "position: absolute;" and show as picture above.

**Comment by ryanhamley** [comment]
This issue tracker is for reporting bugs and requesting new features in GL JS. For how to questions, we recommend Stack Overflow or contacting Mapbox support.

While it's possible to override GL JS' CSS settings, I'd recommend against doing so directly, especially the canvas, since many positioning features are dependent on the canvas' position. If you need to make the map less than full screen, you're better off putting the map into a non-full screen container element.
