### ISSUE TITLE
Don't zoom the map if scroll is initiated outside of the map

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#824]
The idea is to track scroll events on the document and disable scroll zooming if there was a scroll event outside of the map in the last N ms. cc @tatsvc

**Comment by tmcw** [comment]
We've done this in the past with stuff like [deadsea](https://github.com/mapbox/deadsea). It's possible and actually works pretty well: the whole of deadsea is:

```js
(function(context) {
    var deadsea = {};

    function isFamily(parent, child) {
        if (parent === child) return true;
         var node = child.parentNode;
         while (node !== null) {
             if (node === parent) {
                 return true;
             } else {
                 node = node.parentNode;
             }
         }
         return false;
    }

    deadsea.blockScrollInto = function(el) {
        var locked = true;
        // This is not compatible with IE.
        if (!window.addEventListener) return this;

        function handleMouseWheel(e) {
            if (!isFamily(el, e.target)) {
                locked = true;
            } else if (locked) {
                e.stopPropagation();
            }
        }

        window.addEventListener('mousewheel', handleMouseWheel, true);
        window.addEventListener('DOMMouseScroll', handleMouseWheel, true);

        el.addEventListener('mousemove', function mousemove(e) {
            locked = false;
        }, false);

        return this;
    };

    this.deadsea = deadsea;
})(this);
```

The effectiveness of this approach vanished when Mapbox switched embeds to iframes: there's no way to do a similar trick with iframes.

**Comment by mourner** [comment]
Closing as stale.

**Comment by DanielHeath** [comment]
Pretty unfortunate that everyone has to work around this (or more likely, leave it and have a poor scrolling UX)

**Comment by stevage** [comment]
Oh, this would be great. I had a bunch of maps embedded in a long scrollable page ([here](https://opencouncildata.github.io/Datasite/)), but it was virtually unusable, because it was so hard to scroll past them. I had to add a buffer to the sides so you could use those as a kind of footpath to avoid the map holes. :)

**Comment by lipis** [comment]
Any news on this one..?

**Comment by stevage** [comment]
Another approach I've seen on some websites is that mouse scroll is always page scroll, and zoom requires ctrl+scroll. When you scroll over the map, a message appears telling you to hold ctrl if you want to zoom. That worked pretty well.

**Comment by timoto** [comment]
I have a page where mouse scroll is always page scroll and opted for onscreen +/- for zoom.

However the map still requires a "footpath" margin for use on a touch screen.

Unless I'm missing something there doesn't appear to be a way to differentiate say 1 finger scrolls page vs 2 fingers together move map, 2 fingers opposing directions zooms.

Did anyone else find a solution to touch ?

**Comment by andrewharvey** [comment]
> Another approach I've seen on some websites is that mouse scroll is always page scroll, and zoom requires ctrl+scroll. When you scroll over the map, a message appears telling you to hold ctrl if you want to zoom. That worked pretty well.

￼￼There's now a ticket for that #6884.

**Comment by abelvarga** [comment]
I did not address the problem of designing the necessary layer informing the user on using the CTRL key. I may add that later, after our designer comes up with something nice and our company allows it to be part of my PR. Until then, solutions are welcome!

Also the easiest way to make this work until PR is merged and not using our fork, is this:

```javascript
document.querySelector('canvas.mapboxgl-canvas').addEventListener('wheel', (ev) => {
  if (ev.ctrlKey) return

  ev.stopImmediatePropagation()
})
```

This will allow the document to scroll when scrolling without theCTRL key pressed.

**Comment by bardrotzer** [comment]
I guess this is a bit late, but I'll add a solution for late visitors looking for possible answers.

Our scenario was that our maps can be embedded in a page as an iframe, or embedded as elements directly in the page. We do not know the nature of the parent page and have no control whatsoever of the environment. 

How we solved the problem was to add onfocus and onblur events to the element containing the map.

```html
<div id="map" onfocus="focusEvent" onblur="blurEvent"></div>
```

The onBlur and onFocus events will turn the scrollWheel property on and off.

In the main Map Script

```javascript
// adds mouse scroll when the user clicks the map
focusEvent = () => { // or function onfocus() {
  map.scrollWheelZoom.enable();
};
// removes mouse scroll when the user clicks the map
blurEvent = () => {// or function onfocus() {
  map.scrollWheelZoom.disable();
}
```

Hope this helps anyone trying to achieve the same as us.

Happy mapping

**Comment by andrewharvey** [comment]
I don't know what behaviour others are seeing, but for me if I start scrolling outside the map and continue scrolling through the map it will still only scroll the page and not zoom the map. If I stop scrolling and start again on the map it will zoom, but if I don't stop it will just scroll the page which is nice. I think this is alright because increasing that time any more would be too much in the other direction scrolling the page when I want to zoom the map.

**Comment by chapmanjacobd** [comment]
I'm also having trouble with something similar to this. I'm not sure if it is exactly the same issue but I would like to disable zooming if the map is zoomed out and the user is scrolling out and enable zooming if the user has already scrolled to the top and are continuing to scroll up (like they are expecting the map to zoom in) does that make sense?

It would be nice if this behavior was already built-in to mapbox-gl-js as an option.

https://stackoverflow.com/questions/62441249/zoom-in-map-when-at-top-of-page-scroll-page-when-map-is-zoomed-out
