### ISSUE TITLE
Adding Layer in the MAP is removing street names. (codesandbox inside)

### ISSUE THREAD

**Issue by ReactGirl** [mapbox/mapbox-gl-js#8316]
I'm trying to just add a circle in the middle of the map, however I noticed that it is removing information about street names as soon as the data layer is added. I just want to keep the street names and all the information on the map.

I created a repository just to demonstrate this issue, any help would be very appreciated.

[example in codesandbox.io](https://codesandbox.io/s/mapboxdatalayer-f1hdw)

With datalayer: (streets name is being removed)
<img width="972" alt="Screenshot 2019-06-04 at 00 25 52" src="https://user-images.githubusercontent.com/29104515/58840910-708fd400-865f-11e9-80d3-ec90cd2542b5.png">

Without:
<img width="969" alt="Screenshot 2019-06-04 at 00 26 15" src="https://user-images.githubusercontent.com/29104515/58840913-72f22e00-865f-11e9-9eba-3b312d3b4eb7.png">

**Comment by ryanhamley** [comment]
Hi @ReactGirl you're adding an image as a symbol layer which is colliding with the street labels underneath it. Consequently, the street labels are faded out and removed from the map since your image has a higher priority in the collision index. To fix this, you can update `myLayer.layout` to include `"icon-ignore-placement": true` which allows symbols that collide with your image to be placed normally.

**Comment by ReactGirl** [comment]
Thank you very much!!!!!!!!!!
