### ISSUE TITLE
custom source and tile display

### ISSUE THREAD

**Issue by skywalkershen** [mapbox/mapbox-gl-js#8409]
Hi, I'm currently trying to implement a feature like this:

Serving custom data to each tile, and customize display for data on each tile, like the demo below.
https://jsfiddle.net/skywalkershen/nze7ovxs/

Instead of using fake data as in the demo, I would like to send request to self-hosted server for tile data, and display them in table layout on each tile. For leaflet gridlayer, I have full access to tile layout using canvas as well as requesting and handling data. 

To implement this in mapbox-gl , I think I can only use raster or vector tile for the source, yet none of them can be used to pass json data. And for display, I know it is possible to use expression in layer layout and paint to customize data in the source, yet that's more for filtering/calculating values/setting styles like color. I failed to find a way to do something like adding text with custom position.

If possible, please help me with some ideas of how to implement this in mapbox. Thank you.

**Comment by mourner** [comment]
Beyond what's shown with `map.showTileBoundaries = true`, you can currently only do this with a [Custom WebGL Layer](https://docs.mapbox.com/mapbox-gl-js/api/#customlayerinterface) — e.g. by drawing on a regular 2D canvas and then rendering it as a texture on top of the map.

Another hacky way to do this would be to dynamically generate a GeoJSON source with vertical/horizontal lines and text labels.

We're currently not planning to add more convenient ways to do this because it would overly complicate the API and the implementation.

**Comment by skywalkershen** [comment]
Thanks for the follow up. May I know whether there is a way to make custom webgl layer work in tile layer manner?  Like requesting data and rendering  each MercatorCoordinate xyz in current view and triggering update on move/zoom?

Thank you.

**Comment by mourner** [comment]
@skywalkershen currently we don't expose it nicely, but there's a hacky way to do it — see a rough example here of getting coordinates: https://bl.ocks.org/andrewharvey/9490afae78301c047adddfb06523f6f1

**Comment by skywalkershen** [comment]
Thank you for the example. I managed to get the tile coordinates in current view, yet I don't quite get how to map the tile xyz to the position of current view on gl content. If possible, could you please shed some light on it? Thank you.
