### ISSUE TITLE
Map can't be printed on Firefox

### ISSUE THREAD

**Issue by life777** [mapbox/mapbox-gl-js#8561]
Hi,

I found an issue with printing map in firefox:

**mapbox-gl-js version**: v1.1.1

**browser**: Firefox 68 (I tested on Linux and Windows)

### Steps to Trigger Behavior

 1. Open any example with map in firefox 68 (latest)
 2. Try to print it

### Link to Demonstration
https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

### Expected Behavior
![Screenshot from 2019-07-26 11-26-19](https://user-images.githubusercontent.com/891497/61962768-48a25a00-af98-11e9-9520-1fe3cf2147bc.png)

### Actual Behavior
![Screenshot from 2019-07-26 11-27-38](https://user-images.githubusercontent.com/891497/61962809-640d6500-af98-11e9-8a9b-7fa1f2d20f01.png)

Thanks a lot for you work. Mabox gl is awesome.

**Comment by andrewharvey** [comment]
If you create your mapboxgl.Map with `preserveDrawingBuffer: true` (see API docs), then the map will be printed.

I'm not sure if there's anything else mapboxgl could do internally to address this as setting preserveDrawingBuffer I believe gives worse performance so that's why it's not enabled by default.

**Comment by life777** [comment]
You are right. Thanks a lot. 
Found this bug in bugzilla connected with this problem (I guess it won't be fixed because it's there 6 years): https://bugzilla-dev.allizom.org/show_bug.cgi?id=976173
