### ISSUE TITLE
newline character not respected if text-max-width is set to zero

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#8575]
**mapbox-gl-js version**: 1.1.0

**browser**: _not browser specific_

### Steps to Trigger Behavior

 1. Use a newline character `\n` in a text field value
 2. Set `text-max-width` to zero

### Link to Demonstration

https://jsbin.com/zawiyegehe/1/edit?html,output

### Expected Behavior

Text wraps to second line after newline character:
<img width="249" alt="Screen Shot 2019-07-29 at 1 23 05 PM" src="https://user-images.githubusercontent.com/108094/62079661-09784100-b204-11e9-9ae0-e675f9d9e263.png">

### Actual Behavior

Text does not wrap:
<img width="273" alt="Screen Shot 2019-07-29 at 1 23 08 PM" src="https://user-images.githubusercontent.com/108094/62079671-0da45e80-b204-11e9-9585-a773b1305400.png">

**Comment by mourner** [comment]
Good catch! Looks like we skip determining line breaks entirely if `max-width` is not set (regressed in #3725): 

https://github.com/mapbox/mapbox-gl-js/blob/4ffd0e2c6cbdf4f2d96b89f79a816012eba66329/src/symbol/shaping.js#L353-L354

**Comment by ryanhamley** [comment]
@malwoodsantoro and I have been working on this bug together and I wanted to capture what we've discovered so far.

The proximate culprit is the check noted above

```
if (!maxWidth)
    return [];
```

Removing this check however runs into a related issue caused by this bit of code.

https://github.com/mapbox/mapbox-gl-js/blob/master/src/symbol/symbol_layout.js#L186-L188

If `symbol-placement` is set to `line` or `line-center`, `text-max-width` is set to zero. This makes sense since text that follows a line shouldn't have breaks, but removing the `if (!maxWidth)` check causes the line to break on every whitespace character - exactly the opposite of what we want. This is confirmed by numerous failing line rendering tests if the `if` statement is removed.

A perhaps more correct way to write the `if` statement would be something like this:
```
// disable line breaking entirely on text-along-a-line
// point placed symbols will always be shaped
if (symbolPlacement !== 'point') {
    return [];
}
```

The only problem with this is that `shaping.js` does not have access to the `layout` instance or the `symbol-placement` property so we'll have to pass that in. Mal and I will work on submitting a PR in our meeting next week.

cc @asheemmamoowala
