### ISSUE TITLE
RTL text in text-field property becomes invisible

### ISSUE THREAD

**Issue by masoud2vg** [mapbox/mapbox-gl-js#8622]
Hi. I want to change the text-field property of layers. I can do it with LTR languages but when I use RTL text to change the town label for example, it doesn't show the text on map.
What's the problem?

**Comment by peterqliu** [comment]
@masoud2vg can you make a test case?

**Comment by masoud2vg** [comment]
these are the steps that I've done to demonstrate the problem, first I set a ltr work on cities and it works.

map.setLayoutProperty('place-city', 'text-field', 'ltr')

[ltr cities label](https://drive.google.com/file/d/1wiA0nU8sT1yqXr5hdNN6QHqozyl0od6T/view?usp=sharing)

then I use this command to set 'س' letter to cities label but because it's rtl it cannot show it.

map.setLayoutProperty('place-city', 'text-field', 'س')

[rtl cities label](https://drive.google.com/file/d/1vbM_YuCAnsPPPcfpqU1r6DiuZThAgdaV/view?usp=sharing)

**Comment by asheemmamoowala** [comment]
@masoud2vg you can use [this example](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/) to see how to include the RTL text plugin in your GL-JS map.

Closing this now, because there is not other actionable information in this ticket. Feel free to re-open with a minimal test case (using http://jsbin.com or similar) if you do feel you have found a bug.

Thanks!
