### ISSUE TITLE
setFeatureState Throws Error

### ISSUE THREAD

**Issue by econ24** [mapbox/mapbox-gl-js#8634]
**mapbox-gl-js version**: v1.2.1

**browser**: Chrome Version 70.0.3538.77 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Add vector tile source S
 2. Add 2 layers, layer A and layer B, both using the same source-layer from vector tile source S
 3. use setFeatureState on layer A
4. remove layer B
5. use setFeatureState on layer A

### Link to Demonstration

https://jsbin.com/yuruvibiqa/edit?html,js,output

I removed my mapboxgl.accessToken.
The error occurs after the setTimeout function removes a layer.

### Expected Behavior

setFeatureState works as intended.

### Actual Behavior

setFeatureState throws the following error:

Uncaught TypeError: Cannot read property 'queryRadius' of undefined
    at Ou.setFeatureState (tile.js:464)
    at Vu.coalesceChanges (source_state.js:154)
    at i.prepare (source_cache.js:170)
    at ao.render (painter.js:340)
    at r._render (map.js:1753)
    at map.js:1837

**Comment by asheemmamoowala** [comment]
@econ24 Thank you for reporting this issue. I am not able to reproduce the bug in the jsfiddle. It looks like the style used in the demo is private and cannot be accessed by other access tokens.

Could you provide a demo with a public style or one that uses a mapbox style or other simplified style where this issue can be reproduced.

**Comment by econ24** [comment]
Sorry about that. I updated the jsfiddle with an access key I found here: https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
It works for me using the key found on that example page.

**Comment by econ24** [comment]
I updated the fiddle with a public style. I don't believe the mapbox account I am using is an enterprise account so the tileset should be public.

**Comment by verbeeckjan** [comment]
I experience this bug too. It is very annoying when switching between layers by adding and removing them.

**Comment by cammanderson** [comment]
We are experiencing the same issue. Appears to be happening through switching layers and use of feature state.

**Comment by lpmcampos** [comment]
I'm facing this issue as well, under the same conditions of @econ24.
Mapbox GL version I'm using is v0.54.0 but I've tried also with v1.6.0 which presents the same behavour...

![image](https://user-images.githubusercontent.com/45602012/71526180-869c0500-28cd-11ea-9cbe-196af86dd3b7.png)

**Comment by asheemmamoowala** [comment]
Did a little investigation to understand what is causing this issue. 

When a layer is removed, it is marked for removal and then processed on the next render by updating the grouping of layers in the works by these two chunks

https://github.com/mapbox/mapbox-gl-js/blob/4f0ab92b28df6cc6ea00280ddc079a4fc9fbd55b/src/style/style.js#L375-L381

https://github.com/mapbox/mapbox-gl-js/blob/4f0ab92b28df6cc6ea00280ddc079a4fc9fbd55b/src/source/worker.js#L88-L91

The update layer index is not re-applied to the tiles though, so existing buckets on the main thread continue to hang on to removed layer ids and are being processed unneccesarily at: 

https://github.com/mapbox/mapbox-gl-js/blob/4f0ab92b28df6cc6ea00280ddc079a4fc9fbd55b/src/source/tile.js#L394-L397

The shortcut to fix this would be to add a `null` guard on `painter.style.getLayer(id)` before further processing for that layer id. But this does not solve the root cause, which is that tiles and  buckets on the main thread have not been notified of removed layers. This may also be true of updated layers, but I have not confirmed that as of yet.
