### ISSUE TITLE
release-queso: Performance regression in "Animate a point" example

### ISSUE THREAD

**Issue by ahk** [mapbox/mapbox-gl-js#8671]
**mapbox-gl-js version**:
release-queso

**browser**:
IE11, Edge, macOS Chrome (likely all platforms)
Especially bad on IE11/Edge

### Steps to Trigger Behavior

 1. Checkout `release-queso` branch.
 2. Build the minified production version of `gl-js`
 3. Run the documentation server to get locally hosted examples using `release-queso`
 4. Navigate to `dev-hostname:8080/mapbox-gl-js/example/` on your preferred browser

### Expected Behavior
Example runs at interactive framerate.

### Actual Behavior
Example runs at sub ~1hz on Edge and IE11, flickers and hitches on other platforms.

**Comment by arindam1993** [comment]
@ahk  and I discovered the problem. Its a regression cased by https://github.com/mapbox/mapbox-gl-js/pull/8633.

The framerate for the rest of the scene interaction is fine, its not caused by any `gl` or any main thread computation.  Initial suspicion is using `setTimeout(..,0)` in the worker is adding inconsistent delays to the geo-json decoding causing animation jank.
