### ISSUE TITLE
Vulnerability in package esm

### ISSUE THREAD

**Issue by johannesSolvr** [mapbox/mapbox-gl-js#8672]
The version of esm you use has a vulnerability. Will this package be upgraded to fix this vulnerability?
![Screenshot 2019-08-22 at 10 01 47](https://user-images.githubusercontent.com/48016171/63497524-3696d700-c4c4-11e9-8dee-e03779ec60df.png)

**Comment by mourner** [comment]
This dependency was moved to `devDependencies`, so it won't show up in vulnerability warnings starting with the next version. See #8450 for more background on why we can't upgrade it yet. You shouldn't worry about it anyway because the "vulnerability" is completely irrelevant in the context `esm` is used in in GL JS.
