### ISSUE TITLE
Mixing remote and local fonts

### ISSUE THREAD

**Issue by honjo2** [mapbox/mapbox-gl-js#8704]
**mapbox-gl-js version**: v1.3.0

If **localIdeographFontFamily** is "'Hiragino Mincho ProN'".
Japanese(Kanji & Hiragana & Katakana) labels is local font.
But, Alphabet & Numbers labels is remote font.
![スクリーンショット 2019-08-29 17 32 58](https://user-images.githubusercontent.com/437640/63924781-d7b4fd00-ca83-11e9-89f1-f80d7a2fe6f2.png)

If **localIdeographFontFamily** is false.
All labels is remote font.
![スクリーンショット 2019-08-29 17 33 19](https://user-images.githubusercontent.com/437640/63924809-e8fe0980-ca83-11e9-8fd6-bbd87965d4ad.png)

Is this a specification?

**Comment by kkaefer** [comment]
@honjo2 This is by design: `localIdeographFontFamily` only affects ideographs from the Chinese, Japanese, and Korean glyph ranges. All other glyphs will be rendered with remote/server-generated glyphs. We use [TinySDF](https://github.com/mapbox/tiny-sdf) to generate the signed distance fields we use to render glyphs locally. Unfortunately, there is no cross-platform API for retrieving all of the necessary glyph metrics (in particular width and baseline) to produce correct spacing. CJK characters are typically monospaced, or at least only have glyphs with identical width. TinySDF doesn't detect or query the glyph width; it uses a heuristic to guess the correct width. In practice, this produces acceptable results. However, mixing CJK with non-CJK glyphs that are based on a different font might produce a mismatched look. We recommend using a neutral font with a matching baseline.

**Comment by honjo2** [comment]
'Hiragino Mincho ProN'(local font) includes alphabet and numbers.
<img width="1137" alt="スクリーンショット 2019-08-31 12 16 00" src="https://user-images.githubusercontent.com/437640/64058732-78bdc800-cbea-11e9-960f-ec43f7d2b21f.png">
So, I want display all with local font.

**Comment by kkaefer** [comment]
Yes, it includes latin characters, but JavaScript doesn't have a way to access the _metrics_ (e.g. width, ascender, spacing) of local fonts.

**Comment by honjo2** [comment]
I understand, Thanks.
Is this design the same for mapbox-gl-native?

**Comment by kkaefer** [comment]
Yes, however, in mapbox-gl-native, we have the ability to access font metrics because we can read the actual files and have access to platform-native APIs. There's no implementation that actually does that though.

**Comment by honjo2** [comment]
I got it thank you.

**Comment by exotfboy** [comment]
@kkaefer: If we use the same font in `localIdeographFontFamily` and remote font server, can they result in a same look and feel?

**Comment by asheemmamoowala** [comment]
> If we use the same font in localIdeographFontFamily and remote font server, can they result in a same look and feel?

Yes this should work. There may be minute differences between the server-delivered and locally rendered font data based on how they are processed into SDFs.
