### ISSUE TITLE
MapboxGL JS and wkthtmltopdf compatibility

### ISSUE THREAD

**Issue by buszu** [mapbox/mapbox-gl-js#8719]
Hey, I have an issue with integrating MapboxGL and wkhtmltopdf.

The page renders well in the browser, however when trying to convert to PDF I'm getting following error: `ReferenceError: Can't find variable: mapboxgl`.

Please find attached html:
```
<!doctype html>
<html>

<head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mapbox-gl/1.3.0/mapbox-gl.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mapbox-gl/1.3.0/mapbox-gl.js"></script>
</head>

<body>
  <div id="map" style="width: 640px;height: 300px;"></div>

  <script>
    try {
      mapboxgl.accessToken = "TOKEN_HERE";
      var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [-74.50, 40],
        zoom: 9
      });
    } catch(e) {
      var map = document.getElementById('map');
      map.innerHTML = e;
    }
  </script>
</body>

</html>
```

As far as I know the underlaying "browser" for wkhtmltopdf is Qt WebKit so maybe it's about supporting it. Any workaround ideas?

**Comment by arindam1993** [comment]
Hello @buszu ,

I don't think we intend to support weird forks of webkit. 
It seems like in your case the `<script src=` tag itself wasn't processed. Looking through the `wkthtmltopdf` issues seems like they have a few open issues about webgl based rendering libraries not working.
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2721
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1742

The only helpful information I can give you is that, chromium headless mode has good webgl support with an automatic software rasterizer fallback, and might be the best path for you to take to get this to work.

Closing this issue since theres nothing we can do on our end.
