### ISSUE TITLE
Symbols with `icon-text-fit` and `text-offset`

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#8722]
### Expected Behavior

I would expect collision rules to be governed by `text-offset` when a symbol layer is using `icon-text-fit`.

### Actual Behavior

Here's an example of a layer using `text-offset` vs a layer using `text-offset` and `icon-text-fit`. I would expect the text-offset value to continue to not force a collision with the icon below:

![text-offset-with-icon-fit](https://user-images.githubusercontent.com/61150/64210047-37d6e500-ce70-11e9-912a-867d008645cf.gif)

---

**mapbox-gl-js version**: v1.2.0
**browser**: Chrome `Version 76.0.3809.132 (Official Build) (64-bit)`

### Link to Demonstration

https://api.mapbox.com/styles/v1/tristen/cjzu99z8h00qp1co0srxwywwn.html?fresh=true&title=true&access_token={TOKEN}#7.9/43.797847/-79.658695

**Comment by chloekraw** [comment]
We discovered that we weren't manipulating the collision boxes correctly when `icon-text-fit` was used with `text-variable-anchor` and `text-writing-mode` when working on the fix for https://github.com/mapbox/mapbox-gl-js/issues/8583. 

It looks like we didn't add a render test for `text-offset` (https://github.com/mapbox/mapbox-gl-js/pull/8625/files); thus, I'm not sure that we can confirm whether https://github.com/mapbox/mapbox-gl-native/pull/15367 fixes this issue too. (@ansis is working on the JS port.)

@alexshalamov could you add two render tests: one for using `icon-text-fit` with `text-offset` and another one for `icon-text-fit` with `text-variable-anchor` and `text-radial-offset` ?

**Comment by lukasmartinelli** [comment]
@chloekraw What's the ETA for this?

**Comment by asheemmamoowala** [comment]
@lukasmartinelli There is a potential fix for this already in GL-Native, and the JS port is in progress. Confirmation is needed that they correctly address this issue as well.

Both those should be available in the upcoming release.

**Comment by alexshalamov** [comment]
@chloekraw added new render tests in https://github.com/mapbox/mapbox-gl-js/pull/8747

**Comment by kkaefer** [comment]
This is fixed by https://github.com/mapbox/mapbox-gl-js/pull/8741
