### ISSUE TITLE
contextmenu event not working in ios (webview). 

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/mapbox-gl-js#8728]
I am using ionic frame work 3 and using mapbox gl js. 

I am using following code : 

oMap.on("contextmenu", function(event){
console.log(event); 
});

It is working fine in android and browser chrome, safari but not working in ios(wkwebview). I am trying since mapbox gl js 0.47.

**Comment by arindam1993** [comment]
Hi @ansarikhurshid786,
This is an issue with iOS Safari wherein it does not trigger the `contextmenu` event on the underlying element.

You could potentially implement something like this
https://stackoverflow.com/questions/29228999/jquery-contextmenu-event-not-working-in-ios-8-2/33778163#33778163
to to detect the long-press as a contextmenu event.

Closing since this is something we can't handle on our end, I'm sorry 😞 .

**Comment by clementmas** [comment]
@arindam1993, are you sure it's just a iOS Safari issue? I have the same problem with other browsers and also on Android. See https://github.com/mapbox/mapbox-gl-js/issues/10179
