### ISSUE TITLE
Security: Upgrade esm 3.0.84 to 3.1.0

### ISSUE THREAD

**Issue by baptistemanson** [mapbox/mapbox-gl-js#8744]
Github security reports started to report a security exception on esm 3.0.84, which mapbox depends on: https://snyk.io/vuln/SNYK-JS-ESM-72880
Upgrading to estm to 3.1.0 should be sufficient.
**mapbox-gl-js version**: latest

**browser**: any

### Steps to Trigger Behavior

 1. "yarn why esm" on a project depending on mapbox
 2. check https://snyk.io/vuln/SNYK-JS-ESM-72880

**Comment by mourner** [comment]
This dependency was moved to devDependencies, so it won't show up in vulnerability warnings starting with the most recent version. See #8450 for more background on why we can't upgrade it yet. You shouldn't worry about it anyway because the "vulnerability" is completely irrelevant in the context `esm` is used in in GL JS.
