### ISSUE TITLE
Layer is not render in the coordinates. Layer is off of the location.

### ISSUE THREAD

**Issue by hmendezm** [mapbox/mapbox-gl-js#8762]
**mapbox-gl-js version**:
 "mapbox-gl": "^1.3.1",
### Question

I have a layer with custom icon. When I added the source and the layer I notice that the layer is far from the coordinates of the source. Any idea why does the layer is not in the coordinate?

Layer:
 'id': 'pivotal-layer-point',
      'type': 'symbol',
      'source': 'pivotal-point',
      'layout': {
        'icon-image': 'pulsing-dot'
      }
Source
{
      'type': 'FeatureCollection',
      'features': [{
        'type': 'Feature',
        'geometry': {
          'type': 'Point',
          'coordinates': [center.lng, center.lat]
        },
        'properties': {}
      }]
    };

Custom icon:
const size = 150;
    const pulsingDot = {
      width: size,
      height: size,
      data: new Uint8Array(size * size * 4),

      onAdd: function () {
        const canvas = document.createElement('canvas');
        canvas.width = this.width;
        canvas.height = this.height;
        this.context = canvas.getContext('2d');
      },

      render: function () {
        const duration = 1000;
        const t = (performance.now() % duration) / duration;

        const radius = size / 2 * 0.3;
        const outerRadius = size / 2 * 0.7 * t + radius;
        const context = this.context;

        // draw outer circle
        context.clearRect(0, 0, this.width, this.height);
        context.beginPath();
        context.arc(this.width / 2, this.height / 2, outerRadius, 0, Math.PI * 2);
        context.fillStyle = 'rgba(255, 200, 200,' + (1 - t) + ')';
        context.fill();

        // draw inner circle
        context.beginPath();
        context.arc(this.width / 2, this.height / 2, radius, 0, Math.PI * 2);
        context.fillStyle = 'rgba(255, 100, 100, 1)';
        context.strokeStyle = 'white';
        context.lineWidth = 2 + 4 * (1 - t);
        context.fill();
        context.stroke();

        // update this image's data with data from the canvas
        this.data = context.getImageData(0, 0, this.width, this.height).data;

        // keep the map repainting
        that._map.triggerRepaint();

        // return `true` to let the map know that the image was updated
        return true;
      }
    };

Best 
Henry

**Comment by vakila** [comment]
Hi @hmendezm , thanks for using Mapbox! 

To better understand your issue, it would be really helpful to see a live example in [JSbin](https://jsbin.com), [JSfiddle](https://jsfiddle.net/), etc. That way we can see how you are defining the style & instantiating the `Map` object, and what behavior you're seeing vs. what you expect. 

Please note that this issue tracker is for reporting bugs and requesting features in GL JS. It sounds like your question is asking for general help with using our tool(s), so in that case [Stack Overflow](https://stackoverflow.com/questions/tagged/mapbox-gl-js) or [Mapbox Support](https://support.mapbox.com) would be the best places to ask for help.

If you do think this is a bug, please respond with the following so that we can investigate: 
- link to a minimal demonstration of your code/style. We recommend using https://jsbin.com.
- links to the specific section(s) of the documentation where you would have expected to find an answer to this question

Thanks! :heart:

**Comment by langer-man** [comment]
https://www.npmjs.com/package/easy-drawing
another view

**Comment by vakila** [comment]
@langer-man Thanks for the link, but I'm not entirely sure how this relates to the original post/issue with using mapbox-gl-js - could you please elaborate?
