### ISSUE TITLE
How to add mouse move event on a wms layer example in mapbox gl js?

### ISSUE THREAD

**Issue by pandeyshashank** [mapbox/mapbox-gl-js#8769]
**mapbox-gl-js version**: 1.1.0

### Question
I want to add mousemove event on a wms layer example in this https://docs.mapbox.com/mapbox-gl-js/example/wms/ but was unable to do so. Is there any way to do so, to get the coordinates under the layer.

**Comment by ryanhamley** [comment]
Hi @pandeyshashank You can add an event listener to a wms layer just as you would any other layer

```
map.on('mousemove', 'wms-layer', function () {...});
```

The issue is that the event listener only fires on *features* within a layer. The WMS layer in that example does not have any features embedded in its tiles so the listener is never fired. It is being added and checked properly though.

The `on` method is defined here https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/map.js#L774 and you can see the check for features specifically in these lines:

https://github.com/mapbox/mapbox-gl-js/blob/3d6d2b440c89199dfc38f0a2b109588f1f264ac8/src/ui/map.js#L815-L819

Hope this helps. Also, please note that this issue tracker is for reporting bugs and requesting features in GL JS. For general "how to" questions, we recommend asking on Stack Overflow or contacting Mapbox Support. Thanks!
