### ISSUE TITLE
Emojis and special characters not displayed in symbol labels

### ISSUE THREAD

**Issue by dancherb** [mapbox/mapbox-gl-js#8773]
As initially discussed in the repo for the React Native SDK, and judged to be an upstream issue:
https://github.com/nitaliano/react-native-mapbox-gl/issues/1407

(any workarounds would be appreciated in the meantime!)

**Comment by vakila** [comment]
Hi @dancherb, thanks for using Mapbox!

I believe react-native-mapbox uses Mapbox's mobile SDKs for iOS & Android, for which the appropriate place to file a bug report would be [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native).

That said, if you think this bug is also present here in mapbox-gl-js, to help us look into the issue it would be extremely useful if you can provide the information requested in our [bug report template](https://github.com/mapbox/mapbox-gl-js/issues/new?template=Bug_report.md), in particular a working minimal example using mapbox-gl-js (rather than react-native-mapbox as used in the examples in https://github.com/nitaliano/react-native-mapbox-gl/issues/1407). We recommend posting on a site such as jsbin.com if possible. :heart:

**Comment by dancherb** [comment]
Thanks for the helpful reply, will close for now :)
