### ISSUE TITLE
Map not rendered in jQuery dialog (canvas allocated normally, rest of layout broken)

### ISSUE THREAD

**Issue by bgaspic** [mapbox/mapbox-gl-js#8782]
**mapbox-gl-js version**: 0.49
**browser**: Chrome 76.0.3809.132

### Steps to Trigger Behavior

Please open this page (jsbin.com or otherwise), and click on the button:

[mapboxgl-in-dialog.txt](https://github.com/mapbox/mapbox-gl-js/files/3635451/mapboxgl-in-dialog.txt)

It's a self-contained HTML demonstrating the issue, but GitHub only lets me upload it as txt.
Please put your token in the above, I'm not sure how to get a "public" token.

### Expected Behavior

Allocates canvas inside dialog, and shows the map in it.

### Actual Behavior

While the **canvas** is allocated just fine inside that dialog,
I can see that the layout of the **other controls** is broken,
and the **map shows nothing**.

![mapboxgl-in-dialog](https://user-images.githubusercontent.com/24604993/65319614-593e0d80-dba0-11e9-85d5-00b7efd3e2c0.png)

**Comment by bgaspic** [comment]
I noted that the `<canvas .mapboxgl-canvas>` is allocated normally (sized **568x300** in my example),
while its **parent** `<div .mapboxgl-canvas-container>` sizes to **568x0**
and **grandparent** `<div .mapboxgl-map>` sizes to **568x0** too.

Why does the canvas-container *not* size to contain the child canvas?

**Comment by ryanhamley** [comment]
This is an issue with the specific layout of your dialog. If you manually set a height on the map container with dev tools, you can see that the map has loaded. The problem is that the dialog is being created before the map is instantiated, so the dialog does not inherit the map's height. This is something you'll have to debug, but you may want to refer to https://github.com/mapbox/mapbox-gl-js/issues/3265 to see some discussion of this issue and potential solutions. If you continue having issues, we recommend posting questions to Stack Overflow or contacting Mapbox Support. Thanks!

**Comment by bgaspic** [comment]
Thank you Ryan. You're correct; a manual setting of CSS height on `#map` does make the map render.
I was surprised that `.mapboxgl-canvas-container` does not accomodate the `.mapboxgl-canvas`, or that the lot doesn't expand to fill the vertical space left by the jQuery dialog's `min-height` -- whereas it *does* expand to the horizontal space left by the dialog.
Anyway, I'm able to make it work with manual height override; it's just that a beginner user like me will not grasp the logic of why the one override is necessary and the other one is not.
