### ISSUE TITLE
mapbox : vector polygon getting error as fill-color: color expected, array found

### ISSUE THREAD

**Issue by pravinpa** [mapbox/mapbox-gl-js#8847]
I want to show polygon on map with different color shades as per density. I am referring - https://docs.mapbox.com/mapbox-gl-js/example/data-join/

And trying to implement as -

"fill-color": expression

But getting error as -

.paint.fill-color: color expected, array found

We are using mapbox version - https://api.mapbox.com/mapbox-gl-js/v0.38.0/mapbox-gl.js

But, if I use new version - https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.js, its working fine. But, as some application dependency I have to use v0.38.0, so how I can resolve this issue for version v0.38.0

Please help on this.

**Comment by ryanhamley** [comment]
The error means that whatever value you're supplying to `fill-color` is not producing a correct color value; it's instead returning an array. Beyond that, we can't give you any more concrete advice because you have not supplied a minimal example showing the issue. If you think this is a bug in GL JS, you can respond to this ticket with an example. However, we cannot provide general support in this issue tracker. For answers to "how-to" questions and help debugging, please contact [Mapbox support](https://support.mapbox.com/hc/en-us).
