### ISSUE TITLE
Cannot read property 'point' of null

### ISSUE THREAD

**Issue by Jumperok** [mapbox/mapbox-gl-js#8890]
Hello

For some reason we get the error: "Cannot read property 'point' of null".

Our airbrake backtrace looks like:
node_modules/mapbox-gl/dist/mapbox-gl.js:33 in point
node_modules/mapbox-gl/dist/mapbox-gl.js:33 in ie
node_modules/mapbox-gl/dist/mapbox-gl.js:33 in $t
node_modules/mapbox-gl/dist/mapbox-gl.js:33 in Ji
node_modules/mapbox-gl/dist/mapbox-gl.js:33 in t
node_modules/mapbox-gl/dist/mapbox-gl.js:33 in renderLayer
node_modules/mapbox-gl/dist/mapbox-gl.js:33 in render
node_modules/mapbox-gl/dist/mapbox-gl.js:33 in _render

We think this error occurs from https://github.com/mapbox/mapbox-gl-js/blob/master/src/symbol/projection.js#L270 this place.

**Comment by kkaefer** [comment]
@Jumperok thanks for reporting an issue. However, we need a little more information to debug this:

- What version of Mapbox GL JS are you using?
- In what situation do you see this error? Is it reproducible? If so, providing a minimal example that reproduces it would be very helpful.
- Adding source maps to get the original error locations helps in providing a better stack trace.

**Comment by jonseppanen** [comment]
We also experience this issue.
Specifically, it occurs during very high zoom levels on **text symbol layers** for **line sources** that have the:
`"symbol-placement": "line-center"`
Attribute set.

Once you zoom very far in, then try to zoom back out, you get spammed with this error. Likely occurs because it is trying to get a point from a line source.

Removing the symbol placement settting prevents the issue.

**Comment by oscarfonts** [comment]
Had same issue, error coming from this line:
https://github.com/mapbox/mapbox-gl-js/blob/v1.13.0/src/symbol/projection.js#L322
mapbox-gl 1.13.0 (via react-map-gl 5.2.11)

At some point, a `glyph` is null on `placeGlyphsAlongLine` function.

Same conditions as @jonseppanen high zoom level, zooming in/out quickly with mouse wheel. Tilted map increases chances of getting it.

**Comment by jonseppanen** [comment]
@kkaefer is this enough information to re-open this issue?

**Comment by ryanhamley** [comment]
@jonseppanen are you able to provide a minimal example of the bug on JSBin or something similar?

**Comment by oscarfonts** [comment]
Tried to setup a minimal example on my own, but haven't been able to reproduce the error in a simple setup, so far.

I'm suspecting the error, in my case, may be caused by the usage of react-map-gl, which doesn't do smooth zoom transitions on mousewheel, but discrete jumps. Still not sure though.

@jonseppanen are you using react-map-gl by chance? It'd be great if you managed to provide an example.

**Comment by ricardoekm** [comment]
Same issue here, using  react-map-gl. Did anyone manage to solve this?

**Comment by simonprovost** [comment]
@ricardoekm Any luck? @YashasaveeKesarwani99  too?
