### ISSUE TITLE
Dash array patterns should not start at the beginning of connected line segments

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#8900]
## Motivation

If a dash array pattern is applied to a LineString of joined line segments (i.e. road segments with [`structure:tunnel` vs `structure:none`](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/#--road---structure-text)) the result looks incorrect and discontinuous.

<img width="330" alt="Screen Shot 2019-10-24 at 12 35 12 PM" src="https://user-images.githubusercontent.com/61150/67507570-24b8e800-f65d-11e9-9c28-868ea5f94236.png">

_Here's a JSFiddle of the test case_: https://jsfiddle.net/tristen/o3jd81r7/

Instead of beginning a dash array pattern at the beginning of a new line segment, it would be great if it took into account the entire geometry

## Design Alternatives

Adjust the data. When line segments should be styled the same, join geometries together. But this is not always a feasible thing to do.

## Design

The line would be displayed as continuous. Here's a before vs after 

| Before | After |
| --- | --- | 
| <img width="330" alt="Screen Shot 2019-10-24 at 12 35 12 PM" src="https://user-images.githubusercontent.com/61150/67506799-b7588780-f65b-11e9-9717-33390f2f9c38.png"> | <img width="330" alt="Screen Shot 2019-10-24 at 12 40 56 PM" src="https://user-images.githubusercontent.com/61150/67506800-b7588780-f65b-11e9-8e7d-6babc33c5b2d.png"> |

**Comment by arindam1993** [comment]
I don't think gj-js should handle this, mainly because the the rules for doing last-moment geometry fixing like this in a renderer have to be somewhat arbitrary, special-cased and computationally expensive. Previously we have considered something similar for fill-extrusions but decided against it.
https://github.com/mapbox/mapbox-gl-js/pull/8600

There are a number of questions that need to be answered when trying to line joining like this, none of which have clear answers
1. Should it only join lines in the same `FeatureCollection`
2. Should it only join lines that are placed in-order in the same `FeatureCollection`, or consider all lines?
3. What floating point threshold should be used to compare points to consider them as equivalent?

**Comment by tristen** [comment]
@arindam1993 Thanks for the response and yeah; that makes sense. Closing.
