### ISSUE TITLE
fitBounds is not accurate when map container is resized

### ISSUE THREAD

**Issue by jacknkandy** [mapbox/mapbox-gl-js#8920]
### Background

I am attempting to build custom full screen functionality for a map. Our project will require a user to create and "design" a map, which is later captured and exported as part of a PDF. 

The default map size presented to the user reflects the size and aspect ratio of the map image that will appear in the exported PDF. However since it is quite small, we have added in the functionality for the user to toggle a fullscreen version of the map on/off so they will have more granular control during the "design" process.

Since the map will need to show a specific feature in view, the idea was that when the user toggles the fullscreen map on/off the map will adjust and scale to keep the feature in view. However, I am having issues maintaining the feature in view since using the `fitBounds` function seems to be inaccurate.

I am assuming that due to the change in aspect ratio of the map container, `fitBounds` should scale the map to fit in the "shorter" side of the bounding box (e.g. if the new container is wider, the map should scale to fit to the height of the original bounding box, if the new container is narrower, the map should scale to fit to the width of the original bounding box). However this does not seem to be the case.

I would assume this issue is related to the change in aspect ratio. I have attempted to solve this issue by calculating the necessary vertical or horizontal padding based on whether the new container is wider or narrower, but it does not seem to solve the issue.

It appears that the `fitBounds` function is maybe not working as I expect it to.

I'm not sure if there is another way of achieving what I am after, and/or if there is an issue/misunderstanding of how `fitBounds` works.

**mapbox-gl-js version**: 1.4.1

**browser**: Chrome 76

### Steps to Trigger Behavior

 1. Get the current map bounds using the `map.getBounds()` function
 2. Update the size of the map container
 3. Wait until DOM has updated and then trigger map resize using `map.resize()`
 4. Once the `resize` event has completed, set the map bounds using the `map.fitBounds()`

### Link to Demonstration

https://jsfiddle.net/jacknkandy/0yxv9t5s/ (Version 1 - Simple)
https://jsfiddle.net/jacknkandy/jbaqy0kL/ (Version 2 - With padding)

In either JSFiddle, if you click on the toggle fullscreen button repeatedly, you will see that the map progressively zooms out, which demonstrates that the bounds are not being set as expected once the map container is resized.

### Expected Behavior

Map bounds are consistent and accurately reflect the bounds of the map before it was resized

### Actual Behavior

Map bounds are inaccurate and does not reflect the bounds of the map before it was resized. This causes the map to progressively zoom out until the features are no longer visible

**Comment by cs09g** [comment]
I think your code should be refactored as:
https://jsfiddle.net/cs09g/4098ypw5/

it works as expected.

**Comment by rreusser** [comment]
I think there are a couple recent issues which need investigation regarding bounds and padding (#11006, #11004), but that the above does appear to be working as expected. If you change the aspect ratio back and forth and continuously try to fit the previous aspect ratio's bounding box, then you will indeed find that you zoom the map out.

A workaround might be to modify the padding to enforce a square aspect ratio for both maps. I believe the bounds would then work as expected.

A version which would not require modifying padding would be to use the [unproject()](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#unproject) function to compute the latitude and longitude of points on the screen, similarly so that you could work out the math and ensure that you are always computing the bounding box of a square and also fitting the bounds of a square.

Here's a worked example: https://jsfiddle.net/1ft679ok/3/

It's not the most elegant, but here is my approach:

```js
  setTimeout(() => {
    map.once('resize', () => {
      const {width, height} = map.getContainer().getBoundingClientRect();
      const minDimension = Math.min(width, height);
      const topLeft = map.unproject({
        x: 0.5 * (width - minDimension),
        y: 0.5 * (height - minDimension)
      }).toArray();
      const bottomRight = map.unproject({
        x: 0.5 * (width + minDimension),
        y: 0.5 * (height + minDimension)
      }).toArray();

      map.fitBounds([topLeft, bottomRight]);
    });

    map.resize();
  });
```

I'll close this issue since maybe further improvements would fall under a feature request rather than strictly a bug.
