### ISSUE TITLE
Displaying waypoints as they are in google maps

### ISSUE THREAD

**Issue by bbantsadze** [mapbox/mapbox-gl-js#8926]
![image](https://user-images.githubusercontent.com/54099764/67866379-4b39c000-fb42-11e9-9a51-ad823048dd4e.png)
I am setting the waypoint, but its not displayed as it is on the google map (point B). Does mapbox support displaying waypoints? And if it does, then how is it possible?

```
    this.map = new mapboxgl.Map({container: 'map'});
    this.map.on('load', () => {
        const directions = new MapboxDirections({
          accessToken: this.accessToken,
          unit: 'metric',
          profile: 'mapbox/driving',
          flyTo: false,
          controls: {
            inputs: false,
            instructions: false,
            profileSwitcher: false
          }
        });
        directions.setOrigin([this.startLng, this.startLat]);
        if (this.wayPoints && this.wayPoints.length) {
          directions.removeWaypoint(0);
          this.wayPoints.forEach((w, i) => {
            directions.addWaypoint(i, [w.lon, w.lat]);
          });
        }
        directions.setDestination([this.endLng, this.endLat]);
        this.map.addControl(directions);
    });
```

**Comment by andrewharvey** [comment]
Hi — thanks for using Mapbox. This repo is for reporting issues, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please refer to our [help documentation](https://www.mapbox.com/help/), ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox), or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).

Since you've already asked this at https://stackoverflow.com/questions/58628758/displaying-waypoints-in-mapbox-as-they-are-in-google-maps I'll close this ticket here.
