### ISSUE TITLE
how to implement "centerMarker"

### ISSUE THREAD

**Issue by mmasomi73** [mapbox/mapbox-gl-js#8934]
how i can implement "_centerMarker_" for choose and get a location from user like that :
http://jsfiddle.net/doktormolle/jcHqt/

**Comment by ryanhamley** [comment]
I'm not entirely sure which part of that demo you're trying to replicate but you can create a marker with a popup like in [this example](https://docs.mapbox.com/mapbox-gl-js/example/set-popup/). It's up to you to set where the marker is located on the map and/or get input from the user. You can use `map.on('click, function () {...})` to place a marker on the map at the site of a user's click. You can see the basic idea in [this example](https://docs.mapbox.com/mapbox-gl-js/example/center-on-symbol/).

Please note for the future, that this issue tracker is for reporting bugs and requesting features for GL JS. We can't offer general support through this channel. For answers to "how to" questions like this, we recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us) or asking your question on Stack Overflow. Thanks!

**Comment by mmasomi73** [comment]
i want to marker is fixed and center of map and change location with drag map and not drag marker

**Comment by ryanhamley** [comment]
You can listen for [`map.on('drag', callbackFn)`](https://docs.mapbox.com/mapbox-gl-js/api/#map.event:dragend) and in the callback function, use [`map.getCenter()`](https://docs.mapbox.com/mapbox-gl-js/api/#map#getcenter) to get the center coordinate of the map. You can then update the position of the marker so that it will smoothly move as the map is panned.
