### ISSUE TITLE
can't get image of '@2x' automatically

### ISSUE THREAD

**Issue by longwind91** [mapbox/mapbox-gl-js#8942]
**mapbox-gl-js version**:  v1.5.0

### Question
 I want to load the clearer raster layer .
When window.devicePixelRatio is 2, the image is a bit fuzzy ,and the request url is like this:
https://a.tiles.mapbox.com/v4/mapbox.satellite/3/2/4.png,
how it can request url like this automatically :
https://a.tiles.mapbox.com/v4/mapbox.satellite/3/2/4@2x.png
I need a clearer image automatically.
My code is here ,and you can test it when window.devicePixelRatio is 2,
  [ https://jsbin.com/wogaquheya/edit?html,output](url)
look forward to  reply, thanks!

**Comment by ryanhamley** [comment]
The issue is that you're providing an array of tiles, not a URL to a TileJSON resource. If no URL is provided, then the [`normalizeTileURL`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/mapbox.js#L109) function which would append the `@2x` suffix simply returns the `tileURL` instead. The reason for this is that we can't be sure that non-Mapbox sources will host `@2x` tiles for us to request. If you want to use Mapbox tiles, then I'd recommend using our default styles. If you'd like to supply your own tiles, you'll have to normalize the tile URLs you provide GL JS.

**Comment by longwind91** [comment]
Many thanks  for reply
>  normalize the tile URLs you provide GL JS
how can i do this，my source code is like this，but it not work
`          sources: {
            "raster-tiles": {
              type: "raster",
              url: "http://127.0.0.1:5502/source.json",
              tileSize: 256
            }
          },`
source.json is copy from official example like this，approximately
`{
   "autoscale": true,
  "bounds": [-180, -85, 180, 85],
  "cacheControl": "max-age=43200,s-maxage=604800",
  "center": [0, 0, 3],
  "created": 1358310600000,
  "id": "mapbox.satellite",
  "mapbox_logo": true,
  "maxzoom": 22,
  "minzoom": 0,
  "modified": 1520409600000,
  "name": "Mapbox Satellite",
  "private": false,
  "scheme": "xyz",
  "tilejson": "2.2.0",
  "tiles": [
    "https://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png",
    "https://b.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}@2x.png"
  ],
  "webpage": "https://a.tiles.mapbox.com/v4/mapbox.satellite/page.html"
}`
I really appreciate all your help！

**Comment by ryanhamley** [comment]
Can you just use the Mapbox satellite style which will load these tiles and automatically normalize them? Like in [this example](https://docs.mapbox.com/mapbox-gl-js/example/satellite-map/).

**Comment by longwind91** [comment]
ok，I will try，thanks

**Comment by ryanhamley** [comment]
If you're using standard Mapbox tiles, you're much better off using Mapbox styles since this sort of thing happens automatically. If you need to use your own tiles, then you might want to use the `tiles: []` property in a source. You'd have to do normalization yourself. If you need further assistance with implementing things like that, I'd recommend contacting [Mapbox support](https://support.mapbox.com/hc/en-us).
