### ISSUE TITLE
Traffic data do not update (mapbox.mapbox-traffic-v1)

### ISSUE THREAD

**Issue by george2seven** [mapbox/mapbox-gl-js#8952]
**mapbox-gl-js version**: latest

### Question

I am building a web app in which a map loads (successfully) and traffic information are added.  All by using available examples for mapbox-gl-js.  

Every 60 seconds there are a series of http requests that are fetching tile updates ("...vector.pb...").

However the traffic data seems to stay the same and no updates are ever reflected on the map.

Location I am trying Bratislava/Slovakia.

Can you please any clues as to why this might be happening?

Thanks

PS The same happens if I use the following gist
https://mapbox.github.io/mapbox-gl-traffic/examples/mapbox-light.html#14.55/48.16516/17.17295

**Comment by george2seven** [comment]
Hello,

Are there any updates?

note: We rely heavily for a demo we are building on this functionality.

Thank you

**Comment by ryanhamley** [comment]
Hi @george2seven I've been looking into this and I believe that the plugin is working as expected. The traffic tiles update once per minute but the data doesn't change very much so it's hard to see traffic updating "live". But if you let the map update for awhile, you can see changes. This makes sense since traffic really doesn't change that much at a city-wide level in any given minute.

You can see a before and after in these photos that shows the map has updated. This is a difference of about 10 minutes.

<img width="883" alt="Screen Shot 2019-11-13 at 3 21 41 PM" src="https://user-images.githubusercontent.com/4523080/68814566-03309800-062e-11ea-9d08-3664780f3151.png">
<img width="884" alt="Screen Shot 2019-11-13 at 3 33 57 PM" src="https://user-images.githubusercontent.com/4523080/68814567-03c92e80-062e-11ea-8438-26be16807563.png">

**Comment by george2seven** [comment]
Hello @ryanhamley,

Thanks for the update, however, although I do see in your screen-shots some updates, in the example mentioned in my initial posting, the traffic data have not changed for at least the last 10 days which is as you can understand not possible.

The [link](https://mapbox.github.io/mapbox-gl-traffic/examples/mapbox-light.html#14.55/48.16516/17.17295) I shared before points/zooms to a specific part of the Bratislava city (Slovakia).

In that map, for example, a specific part of a street (150ft long at the most), is all the time red (high traffic), at least for the last 10 days that I am monitoring this.  But in reality and in comparing with other services and the fact that this street is outside our offices, I can assure that most of the time is without traffic :) 

I also see the minute by minute pull of data but no changes.  

![Opera Snapshot_2019-11-14_060951_mapbox github io](https://user-images.githubusercontent.com/2806934/68828552-5e9e6c80-06a6-11ea-9309-d1c30a3e24b9.png)

Can you please have a look again and in particular the location on my link/screen?

Thank you very much

**Comment by george2seven** [comment]
In an additional effort to support your investigation I have replicated your test for Bratislava:

![1](https://user-images.githubusercontent.com/2806934/68829977-b5a64080-06aa-11ea-9b5a-6d1f5a25a200.png)

![2](https://user-images.githubusercontent.com/2806934/68829989-bfc83f00-06aa-11ea-8e24-26c6cf16948c.png)

*the screens were taken 20 minutes apart and the time is close to 7AM (morning weekday traffic is starting)

Thanks

**Comment by ryanhamley** [comment]
@george2seven I took another look at this and talked to a member of our telemetry team and we couldn't find anything wrong. The map you linked to has obviously updated since the last time I looked at it, so I still believe things are working properly. We do have data for Bratislava that should update roughly every 8 minutes. My guess is that traffic patterns simply weren't changing very quickly. However, if you do continue to experience this issue, please let us know so that we can dig a little deeper and determine if there's a more subtle problem with our traffic data or the plugin. Thanks for using Mapbox!

**Comment by george2seven** [comment]
It is working from yesterday. Thanks!
