### ISSUE TITLE
Can fill-extrusion type support outlline?

### ISSUE THREAD

**Issue by qkaibo** [mapbox/mapbox-gl-js#8980]
![image](https://user-images.githubusercontent.com/20093077/68956283-b6ea8100-0802-11ea-8d7e-f25c05de1615.png)

I changed mapbox  native code to support fill-extrusion-outline  in android system when use fill-extrusion type 

It looks very fashion and pretty than no outline.

Can you support in mapbox-gl ? I hope this feature will be supported in the official release!

**Comment by ryanhamley** [comment]
Hi @qkaibo unfortunately, this is not something we're likely to support any time soon. This property was considered when fill extrusions were implemented but it was rejected because of concerns about anti-aliasing. You can see some discussion in https://github.com/mapbox/mapbox-gl-js/issues/4231#issuecomment-278429274. Barring a major overhaul of the way we implement fills and fill extrusions, we're unlikely to expand support for `-outline` properties.
