### ISSUE TITLE
can I still use leaflet library and ask for mapbox gl tiles?

### ISSUE THREAD

**Issue by novaknole** [mapbox/mapbox-gl-js#8983]
Hi. 

I am using leaflet and mapbox as tile layer.  as far as I know, it's a good thing that I don't use mapbox.js because its support is no more active. So I am using leaflet. Now, if I want to switch to map loads, what Should I do? should I stop using leaflet and start using mapbox GL js?  or I can just use mapbox's gl tiles and put it into leaflet's tile and that will be all? 

Thank you

**Comment by kkaefer** [comment]
Yes, the Mapbox API supports rendering raster tiles from Mapbox GL Style Sheets created with studio that can be used with Leaflet. See https://docs.mapbox.com/api/maps/ for endpoints. However, we recommend using Mapbox GL JS for its benefits over Raster tiles (seamless zoom, interactivity, runtime styling, ...) and because Mapbox GL JS is billed by map load rather than by tile request. See https://www.mapbox.com/pricing/ for more information.

Also note that this issue tracker is for reporting bugs and feature requests in the library, not a general support forum. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). Thank you!
