### ISSUE TITLE
map.removeImage and map.addImage do not update rendered map

### ISSUE THREAD

**Issue by elifitch** [mapbox/mapbox-gl-js#9004]
I'm attempting to update an image by calling `map.removeImage` and then `map.addImage` in sequence. The reasoning behind this is that we want to be able to change icon sizes on the fly in Mapbox Studio, and `map.updateImage` fails if the update is of a different size than the original icon. I'm not aware of any way to update an image to one of a different size other than removing it and then adding a new image of the same ID.

If there's a workaround, some other way to update an image when its size changes, it'd be an enormous help to hear about it!

**mapbox-gl-js version**: v1.5.0

**browser**: Chrome 78, Firefox 70.0.1

### Steps to Trigger Behavior

 1. Add an image to the map via `map.addImage`.
 2. Remove that image from the map via `map.removeImage`.
 3. See no visible change in the map.
 4. Attempt to add an image via `map.addImage` with the same ID as the one just removed.
 5. See no visible change in the map.

### Link to Demonstration
https://codepen.io/elifitch/pen/3ea68096aec96ec9521cc26fef066569?editors=0110

**This demo has a few buttons.**
1. Removes the original rainbow image and replaces it with a pink one. Expect this to fail.
1. Remove the images from the map. Expect this to fail.
1. Add images of the same ID to the map. Expect this to fail.
1. Switch from the raindbow image to the pink image via `map.updateImage`. Expect this to succeed!

### Expected Behavior
I'd expect to see the map immediately update with the removed image. I'd expect to be able to update an image by removing it then adding another image of the same ID.

### Actual Behavior
Rendered map does not update when calling `map.removeImage`.

cc @mapbox/studio @mapbox/map-design-team

**Comment by ansis** [comment]
I agree that we should add do this but we need to do it carefully so that it doesn't kill performance.

We would need to track which layers used which images so that we know which layers need to be updated. Without tracking this we would need to destroy the map each time an image is added.

> If there's a workaround, some other way to update an image when its size changes, it'd be an enormous help to hear about it!

Right now you need to clear and reparse tiles for the entire map. There are internal apis that do this but the only external way of doing this would be to `map.setStyle(styleWithoutLayers); map.setStyle(realStyle)`. Yeah... not great
