### ISSUE TITLE
Map does not adjust to orientation change on iPad

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-js#9010]
**mapbox-gl-js version**: 1.5

**browser**: Safari iOS

### Steps to Trigger Behavior

 1. Create a map inside a container with auto width and height (full screen)
 2. Open map on iPad in landscape mode
 3. Rotate iPad to portrait mode

### Expected Behavior

Map adjusts to new height of map container.

### Actual Behavior

The Mapbox logo is pushed to the bottom when orientation is changed, but the map itself remains only visible inside the height from the landscape mode. Between de map and the mapbox logo is a white space visible. So the map keeps its height from the landscape mode when you rotate the iPad.

**Comment by ansis** [comment]
@nijs9 can you try adding [`"trackResize": true`](https://docs.mapbox.com/mapbox-gl-js/api/#map) to your map initialization? If the container at some other time you can also call `map.resize()` to resize the map.

---

@mourner should `trackResize` default to `true`? I'm not seeing any discussion about that in the original pr https://github.com/mapbox/mapbox-gl-js/pull/2591

**Comment by mourner** [comment]
> @mourner should `trackResize` default to `true`? I'm not seeing any discussion about that in the original pr #2591

It's already true by default. I'm not sure it's fired when orientation changes though — let's check.

**Comment by kkaefer** [comment]
I looked into this and it's not something that we can fix easily in Mapbox GL JS itself because it depends on how Mapbox GL JS is embedded into a web page.

Safari assumes a different viewport when in landscape mode, both on iPhone and on iPad. Specifically, they add a padding on the left and right side that isn't accessible to anything from the website; 

Here's the default measurement with a screen ruler: 808 pixels wide, starting from past the notch, excldsing the padding on the right side. On the vertical side, however, the page starts _behind_ the top bar (and also behind the tab bar if present) and goes all the way to the bottom: 808 pixels wide, and 414 pixels tall.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/52399/69970594-c82fcf00-151e-11ea-95bb-b4d29ddbc747.png">

There is a way to get rid of the left and right padding: Safari interprets the HTML viewport metatag and setting `<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />` makes it go away.

The vertical offset is a lot more difficult. https://benfrain.com/the-ios-safari-menu-bar-is-hostile-to-web-apps-discuss/ discusses how the Safari menu bar works. There's also a module called [`ios-inner-height`](https://github.com/tylerjpeterson/ios-inner-height) that uses a trick to compute the same height regardless of whether the page was loaded with or without address bar/tab bar. However, it returns the actual height of the page (which is taller than the visible content) so the attribution would be hidden too.

**Comment by ImanMh** [comment]
@kkaefer I have the same issue but even in a more complicated scenario, when i load mapbox is a page with position set to fixed, after I rotate the phone to landscape and then back to portrait the map canvas does not resize to correct size and takes half of the page only. Is it possible to create a workaround for this issue like calling a mapbox method to update the sizes after rotate until we find a good solution for this problem?

**Comment by ImanMh** [comment]
@ryanhamley I thought this is the same issue too but the other issue I mentioned only happens when you add the page to home screen. Safari browsing is fine, however maybe one fix can take care of both.

**Comment by ImanMh** [comment]
@nijs9 Try this https://github.com/mapbox/mapbox-gl-js/commit/d6dddef47351dabf4489fa21bb7d0fe0d1d68115

might fix your problem as well. I'm just waiting for next release.

**Comment by ImanMh** [comment]
@sgolbabaei jan, I appreciate if you can consider https://github.com/mapbox/mapbox-gl-js/commit/d6dddef47351dabf4489fa21bb7d0fe0d1d68115 as a hotfix.

**Comment by ImanMh** [comment]
@ryanhamley You might missed the comments after you closed this issue. Can you take a look at https://github.com/mapbox/mapbox-gl-js/commit/d6dddef47351dabf4489fa21bb7d0fe0d1d68115 and see if it fixes the problem. It's almost a month I'm waiting for this fix. Let me know if this fix won't be merged. Thank you.

**Comment by ryanhamley** [comment]
@ImanMh It looks like that change was merged but it just missed the cutoff for v1.11.0 last month. The fix is in the `main` branch so it should be included as part of our upcoming v1.12.0 release. We're reworking our release schedule so I won't give an exact date for this release, but a beta should be out by the end of the month. In the meantime, you can test the fix by using the `main` branch of GL JS directly.

**Comment by ryanhamley** [comment]
I believe this was fixed by https://github.com/mapbox/mapbox-gl-js/pull/9652 so I'm going to close it. If this issue persists in Safari, please let us know and we can re-open this ticket.
