### ISSUE TITLE
Translucent fill-extrusion completely occludes other fill-extrusions inside

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#9046]
I'm hoping to render an semi-opaque fill-extrusion layer which is geographically inside a very translucent layer. In these examples:

1. Top red cylinder: 90% opacity, base elevation is just above the height of the buildings.
2. Bottom red cylinder: 30% opacity, height is the same as the buildings, base 0.
3. Buildings: varying opacity, base 0.

The two cylinder layers are "above" the buildings layer in the style.

This is what it looks like if it the buildings are 0% opaque:

![Screen Shot 2019-11-29 at 10 47 33 am](https://user-images.githubusercontent.com/678344/69835510-3f066700-1296-11ea-84a1-1b1740392596.png)

With 50% building opacity, the bottom cylinder is no longer rendered:

![Screen Shot 2019-11-29 at 10 48 08 am](https://user-images.githubusercontent.com/678344/69835528-50e80a00-1296-11ea-8fe8-3f77327791e2.png)

Even with 1% opacity, the bottom cylinder is not rendered:

![Screen Shot 2019-11-29 at 10 46 31 am](https://user-images.githubusercontent.com/678344/69835534-5e04f900-1296-11ea-8622-b5e6dd591472.png)

I guess this is a fundemental issue with the way compositing is done? Ideally the bottom cylinder layer would still be visible through/above the building layer.

My use case is wanting to visually link the top cylinder (representing a rooftop bar) with its label on the ground (this particular bar is literally named "Rooftop Bar" :)), because of the limitations of #3993.

**Comment by ansis** [comment]
> I guess this is a fundamental issue with the way compositing is done?

Yep, in

**Comment by ansis** [comment]
> I guess this is a fundamental issue with the way compositing is done?

Yep, in order to get semi-transparent blending working correctly you generally have to draw pixels in the order of the distance from the camera. This would mean sorting all triangles across all 3d layers. We haven't tried that but it would likely be too expensive. There are some techniques that sacrifice accuracy to be able to draw out of order ([weighted order independent transparency](https://casual-effects.blogspot.com/2014/03/weighted-blended-order-independent.html)). This problem affects most 3d rendering.

But you may be able to work around this because of how our rendering works:
- buildings from previous layers can shine through buildings from later layers
- buildings in the same layer never shine through each other
- buildings from later layers never shine through previous layers

Putting the solid red column in a separate layer that comes before other layers should work in this case.

**Comment by stevage** [comment]
Thanks, that's really useful - it wouldn't have occurred to me that putting the layer *underneath* might actually make it show. I'll try that.
