### ISSUE TITLE
Line width not adjusting according to fractional zoom levels

### ISSUE THREAD

**Issue by dpdiliberto** [mapbox/mapbox-gl-js#9058]
I (and a customer who wrote in about this originally) am running into an issue where the line width for roads is set to 0 until zoom 12.1, but they are beginning to appear at zoom 12. In Studio I made the following settings:

![image](https://user-images.githubusercontent.com/19141701/70100361-51f69f80-15e6-11ea-89dd-a173595fc1f6.png)

I translated this to [this jsfiddle](https://jsfiddle.net/3tganepc/) (please note that you seem to have to zoom in then out for the line width to be visible at z12) using this expression:

> 'line-width': [
> "interpolate",
> ["exponential", 1],
> ["zoom"],
> 0,
> 0,
> 12.1,
> 0,
> 12.49,
> [
> "match",
> ["get", "class"],
> "street",
> 0.01,
> 0
> ],
> 12.5,
> [
> "match",
> ["get", "class"],
> "street",
> 2,
> 0
> ],
> 13,
> [
> "match",
> ["get", "class"],
> "street",
> 2,
> 0
> ],
> 14,
> [
> "match",
> ["get", "class"],
> "street",
> 3,
> 0
> ],
> 15,
> [
> "match",
> ["get", "class"],
> "street",
> 4,
> 0
> ]
> ]

And am seeing this:

![image](https://user-images.githubusercontent.com/19141701/70100456-a7cb4780-15e6-11ea-9f46-0cdec0572c87.png)

Please let me know if this is expected behavior with line widths and factional zoom levels, or if it is a bug that may be able to be fixed.

**mapbox-gl-js version**: 1.5.0

**browser**: Chrome

**Comment by kkaefer** [comment]
I can reproduce this issue, but I'm afraid that we probably won't be able to fix it quickly.

This issue occurs if data-driven properties are used (in this case, you're accessing the `class` property from every feature). When values change per feature (= data-driven styling), we re-encode the data we upload to the GPU. To support interpolation, we include two values, a "from" and a "to" value so that we can interpolate between them as the user zooms in or out. However, we sample those values at integer zoom levels, which means we're sampling `0` for z12, and `2` for z13, and the values between integer zoom levels get ignored for data-driven values.

To fix this issue, we'd have to change our system of uploading new data at integer zoom levels to dynamically determining the stops in a layer. This can get pretty complex since the actual stops could be data-driven as well.
