### ISSUE TITLE
"once" event on specific layer throws an error

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#9059]
**mapbox-gl-js version**:
v1.5.0

**browser**:
latest chrome

### Steps to Trigger Behavior

 1. add geojson layer
 2. add `once` event on the layer
 3. dispatch the event

### Link to Demonstration
https://jsfiddle.net/cs09g/3rdf45ox/

### Expected Behavior
the handler should be fired once.

### Actual Behavior
error message in console

BTW, is `once` method deprecated? It's missing from API docs.

**Comment by kkaefer** [comment]
@cs09g the demo you linked doesn't include a callback function. That means the code that's trying to invoke the function fails. However, it looks like the linked JSFiddle might be incomplete. Can you check that it is indeed what you intended to post?

**Comment by cs09g** [comment]
@kkaefer oops, could you check the fiddle again? click the gray line on the map.

FYI, the missing code is
```javascript
map.once("click", "route", (e) => {
  console.log(e);
});
```

**Comment by kkaefer** [comment]
The syntax allowing specifying the layer ID is only implemented for `on`, not for `once`. It's a little bit unfortunate since the Map object's `on` method overrides the `Evented` class' `on` method, inserting the `layerId` parameter in the middle. No such override exists for `once`, which is why it's not listed on the API documentation.

**Comment by ryanhamley** [comment]
There's an open PR to add this exact functionality if you'd like to give it a review @kkaefer. I worked on it with the author so I can't review it as well.
