### ISSUE TITLE
Add fallback for sources

### ISSUE THREAD

**Issue by vince1995** [mapbox/mapbox-gl-js#9074]
Currently it's possible to add multiple resource URLs to the source option in the style. That's good but mapbox is treating them only as load balancer. But my team want to add a fallback if the first server is down or overloaded. Would be great if there's an option to handle this.

**Comment by kkaefer** [comment]
The concept of "fallback URLs" doesn't generally exist for things on the web; e.g. an `<img src="...">` tag doesn't have a fallback URL.

A little bit of background: Mapbox GL supports multiple URLs to circumvent a low per-hostname connection limit for HTTP < 2 connections on some browsers. Using multiple hostnames can make loading a map faster due to more connections being used, but it can also make it slower because additional hostnames need to be resolved via DNS.

As you mentioned, Mapbox GL distributes requests across all hostnames rather than using them as a "fallback", because it's not clear when a server is "down" or "overloaded": We could measure the time it takes to receive a response and have a cut-off time when we switch over to a secondary server. However, slow response times or connection timeouts don't have to mean that a server is down; usually it's the user's connection which is at fault.

If you know your server is prone to get overloaded, we recommend using a CDN or other kind of caching proxy to ease the load. Mapbox endpoints for enterprise customers are [covered by our SLA](https://www.mapbox.com/legal/sla#[aa]).
