### ISSUE TITLE
default benchmark page is broken

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#9078]
**mapbox-gl-js version**: master

**browser**: all

### Steps to Trigger Behavior

 1. yarn run start-bench
 2. open `http://localhost:9966/bench/versions`

### Expected Behavior

Benchmarks run.

### Actual Behavior

It tries loading `https://s3.amazonaws.com/mapbox-gl-js/v1.7.0-dev/benchmarks.js` and errors.

It looks like this is caused by us switching to `-dev` versions in package.json.

**Comment by arindam1993** [comment]
Along with the `-dev` postfix, I think the problem is its trying to find the benchmark build for the latest release, which is one increment behind whats in package.json. 
The benchmark build for `v.17.0` doesn't exist on S3 yet because that tag hasn't been created yet
I have a quick fix that works ^^
