### ISSUE TITLE
'in' Expression with array throws validation error

### ISSUE THREAD

**Issue by helenezspeer** [mapbox/mapbox-gl-js#9098]
When using the new 'in' expression with an array, I get a validation error and the layer doesn't appear. When using a string, it works as expected.

**mapbox-gl-js version**: 1.6.0

**browser**: Chrome 78.0.3904.108

### Steps to Trigger Behavior

 1. Create a vector style layer with the following values:
```
'type': 'fill',
'source-layer': 'geometries',
'paint': {
	'fill-color': [
		'case',
		['in', 'e', ['h', 'e', 'l', 'l', 'o']],
		'purple',
		'transparent'
	]
}
```
 Result: The layer doesn't appear, and I get this error in the console: 
```
Error
    at Object.kn [as emitValidationErrors] (mapbox-gl.js?e192:29)
    at Be (mapbox-gl.js?e192:33)
    at i._validate (mapbox-gl.js?e192:33)
    at i.addLayer (mapbox-gl.js?e192:33)
    at r.addLayer (mapbox-gl.js?e192:33)
    at VueComponent.$_addLayer (VectorLayer.js?b94f:83)
    at VueComponent.$_deferredMount (VectorLayer.js?b94f:61)
    at VueComponent.created (VectorLayer.js?b94f:42)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4213)
```
 2. Replace last input of the expression with a string value:
```
['in', 'e', 'hello']
```
Result: Style appears as expected with no errors.

### Expected Behavior
I would expect the 'in' expression to work with either a string or an array as the final value.

**Comment by arindam1993** [comment]
@ryanhamley could you please help out `in` here? 😛

**Comment by ryanhamley** [comment]
Hi @helenezspeer thanks for trying out the new expression! The `in` operator does work with both strings and arrays, but in your example, you need to tell the expression parser that `['h', 'e', 'l', 'l', 'o']` is an array literal, otherwise it will be interpreted as an expression with an unknown operator `'h'`. See the updated example below and note the `['literal', ...]` part. This is only needed when you directly supply an array literal to the operator. If you did something like `['in', 'e', ['get', 'arr']]` where `arr` was `['h', 'e', 'l', 'l', 'o']`, then you wouldn't need to specify that it's an array since it's being returned as the literal value of a `get` expression. Hope that helps!

```
'type': 'fill',
'source-layer': 'geometries',
'paint': {
	'fill-color': [
		'case',
		['in', 'e', ['literal', ['h', 'e', 'l', 'l', 'o']]],
		'purple',
		'transparent'
	]
}
```

**Comment by helenezspeer** [comment]
Thanks so much!!
