### ISSUE TITLE
raster broken by OffscreenCanvas on chrome on MacMini 

### ISSUE THREAD

**Issue by astojilj** [mapbox/mapbox-gl-js#9100]
After 85517f0560b199cc5c2e09e50085aabb6de27b78, debug/satellite.html shows black tiles on macos 10.15.1 on Chrome. No error in console.

Works fine on Firefox and Safari on the same hardware. Render tests pass.
 
Mac Mini 2018 3.2 GHz 6-Core Intel Core i7 (Intel UHD Graphics 630 1536 MB)
Chrome Version 78.0.3904.108 (Official Build) (64-bit)

Expected (works fine when `offscreenCanvasSupported()` returns `false`):
![Screen Shot 2019-12-12 at 20 05 02](https://user-images.githubusercontent.com/549216/70737347-f7aeba80-1d1a-11ea-8d6d-8bf6f0d28e27.png)

Actual:

![Screen Shot 2019-12-12 at 20 04 09](https://user-images.githubusercontent.com/549216/70737357-fbdad800-1d1a-11ea-9021-c9e884c4b141.png)

cc @arindam1993 @kkaefer

**Comment by astojilj** [comment]
Edit:
There is no issue noticeable in hillshade.html. RGBA images are all black in debug/image.html, debug/multiple.html...

Works fine when `offscreenCanvasSupported()` returns `false`.

**Comment by arindam1993** [comment]
Can confirm this is happening on any browser that supports `OffscreenCanvas+ImageBitmap`, was a result of a major derp wherein the `ImageBitmap` type check wasn't added in `Texture`. 
This worked fine for everything else (icons, glyphs, hillshade) because we transform those textures into our internal `RGBAImage` or `AlphaImage` types.

Fix is out in #9103
