### ISSUE TITLE
Undefined ID using `promoteId` with GeoJSON

### ISSUE THREAD

**Issue by yuletide** [mapbox/mapbox-gl-js#9119]
**mapbox-gl-js version**: `master` as of today

**browser**: `chrome` 

### Steps to Trigger Behavior

 1. Load GeoJson source with `promoteID`
 2. Mouseover/Mousemove return `id: undefined`
 3. 

### Link to Demonstration

Minimal example based on existing `debug/featurestate.html` https://gist.github.com/yuletide/7221802c9569903639fa336cda7395b0#file-featurestatesetdata-html

https://jsbin.com/

### Expected Behavior
`feature.id` returned based on `filename` property
### Actual Behavior
`feature.id: undefined`

cc @mourner 
https://github.com/mapbox/mapbox-gl-js/pull/8987

**Comment by asheemmamoowala** [comment]
@yuletide The `promoteId` value in the `addSource` [call](
https://gist.github.com/yuletide/7221802c9569903639fa336cda7395b0#file-featurestatesetdata-html-L70-L74).

For a geojson source, `promoteId` should directly point to the feature attribute name:
```
    "promoteId": "filename"
```

The project based syntax allows specifying multiple source layer and attribute name pairs for vector tile sources.

This is the documentation that will go live when this feature is in a public release: 

https://github.com/mapbox/mapbox-gl-js/blob/057203ab8ae8be1eca89d97e6a8073c79e8e8d18/src/style-spec/reference/v8.json#L320-L323

Let us know if it needs further clarification.

**Comment by hmendezm** [comment]
Hi guys, a quick question, I have feature Ids that are alphaNumeric and I get errors because all the ids are defined to undefined somewhere in Mapbox. My guess is the Mapbox tries to convert them to numbers. I try to use promoteId but the feature Id is not in the properties. is it a way to reuse the feature Id as promoteId? I do not have control of the geojson because it is third party.

Best,
hmendez
