### ISSUE TITLE
Mapbox GL JS Image Overlay Coordinates Precision Issue

### ISSUE THREAD

**Issue by laithalzyoud** [mapbox/mapbox-gl-js#9158]
I'm facing a precision issue with Mapbox GL JS when placing an image overlay on the map with 4 corners coordinates, there is a shift from the expected position by 50-250 m. To reach this conclusion and find this bug, the projection of the image was compared to Leaflet and QGIS, both of them shows the same position of the image but Mapbox GL JS is showing a shift. 

I think this may be a bug in the framework that needs to be fixed. I'm using React Mapbox GL JS and was able to recreate this issue using Mapbox GL JS library within a normal html file. So most probably it's not being caused by React.

To recreate the issue try to overlay an image on the map using Mapbox, Leaflet and QGIS and then compare the results.

**mapbox-gl-js version**: 1.4.0

**browser**: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Add an image overlay to Mapbox GL JS using 4 coordinates
```
map.addSource("imageTest", {
"type": "image",
"url": "/DIR/TO/IMAGE",
"coordinates": [
    [LON1,LAT1],
    [LON2,LAT2],
    [LON3,LAT3],
    [LON4,LAT4]
]
})

map.addLayer({
"id": "overlay",
"source": "imageTest",
"type": "raster"
})

```
 2. Geo reference the same image using GDAL Georeferencer on QGIS  with the same coordinates and use QGIS to load the resulting GeoTIFF.

 3. Overlay the image using Leaflet Distortable Image https://github.com/publiclab/Leaflet.DistortableImage 
 4. Compare the 3 projections, a shift shall be observed only with the Mapbox projection and on the y axis most probably.

### Expected Behavior

All of these methods should yield the same results.

### Actual Behavior

Mapbox is showing a major shift sometimes up to 250 meters for an image with a swath of 3 km.

Check this screenshot: (QGIS left, Mapbox center, Leaflet right)

![photo_2020-01-07_18-08-05](https://user-images.githubusercontent.com/46904854/71985375-8986e600-323b-11ea-99fe-180ee9f83eaa.jpg)

**Comment by mourner** [comment]
Thanks for the report, @LaithAlzyoud! Would you be able to provide a live minimal test case for this (e.g. on JSFiddle)? This would help us diagnose the issue.

**Comment by LaithAlzyoud** [comment]
> Thanks for the report, @LaithAlzyoud! Would you be able to provide a live minimal test case for this (e.g. on JSFiddle)? This would help us diagnose the issue.

Thank you for your reply @mourner. 

Here is a JSFiddle overlaying the image using Mapbox GL JS:
https://jsfiddle.net/laithzyoud/hmpv5ury/
And here is JSFiddle overlaying the image using Leaflet:
https://jsfiddle.net/laithzyoud/dnm7c42k/

I'm already in contact with @pjleonard37 by email and he is following up with me on this issue, and I sent him a GeoTIFF to preview it on QGIS that also shows how the image is projected in the same way as Leaflet and there is something weird happening in Mapbox.

I've tried multiple images other than this image and the shift is not consistent between them, sometimes it's 50 meters, sometimes it's 150 meter, and sometimes more.

I've been trying to debug the Mapbox GL JS library code to see where the shift is happening, but everything looks normal until a `VertexBuffer` is created using WebGL from the raster `boundsArray`, I'm not very experienced in WebGL so I didn't actually get into the WebGL pipeline. But my humble assumption is that some truncation is happening when the buffer is being processed in the GPU.

**Comment by baziz** [comment]
@mourner @LaithAlzyoud do you have an eta on this?  thanks for discovering this!

**Comment by LaithAlzyoud** [comment]
Hello again @mourner @pjleonard37, recently I observed that the corners are actually the same for the image in both frameworks; Mapbox GL JS and Leaflet. Apparently there is something wrong in the way the image is being warped/transformed to the calculated position.

I'm willing to dedicate a decent amount of time to debug and solve this. Can you give me some reference on how this was implemented and what part of the library is responsible for warping the image?

 You can find two screenshots for the projection done in both frameworks at the same center and zoom level, by toggling between them you can see how the corners are fixed and the image is warped in a wrong way. 

![Leaflet](https://user-images.githubusercontent.com/46904854/78149027-325d6f80-743e-11ea-8d73-e8085f710bab.png)
![Mapbox](https://user-images.githubusercontent.com/46904854/78149046-35f0f680-743e-11ea-8bf5-2b2f902bb664.png)

**Comment by asheemmamoowala** [comment]
> I'm willing to dedicate a decent amount of time to debug and solve this. Can you give me some reference on how this was implemented and what part of the library is responsible for warping the image?

@LaithAlzyoud Thank you for offering to take a look. 

Image sources are placed on the map by converting their corner coordinates to the tile coordinates at an ideal tile zoom.  The code for this is in two methods: 
[ImageSource#serCoordinates](https://github.com/mapbox/mapbox-gl-js/blob/2faf0ab6ba4e8267cf7f82fdcea9bd73554cf184/src/source/image_source.js#L178) and [ImageSource#getCoordinatesCenterTileID](https://github.com/mapbox/mapbox-gl-js/blob/2faf0ab6ba4e8267cf7f82fdcea9bd73554cf184/src/source/image_source.js#L282)

Based on your examples, another area to look at would be where we set the texture parameters when drawing the raster layer: 

https://github.com/mapbox/mapbox-gl-js/blob/2faf0ab6ba4e8267cf7f82fdcea9bd73554cf184/src/render/draw_raster.js#L53-L67

**Comment by LaithAlzyoud** [comment]
Hello @asheemmamoowala. Thank you for your reply.

Like I mentioned above, the corners are perfectly matching in comparison with Leaflet, so I don't think this is an image placement issue, rather it's related to how the image is warped/transformed to that correct position. Maybe you can give me some reference in [transform.js](https://github.com/mapbox/mapbox-gl-js/blob/2faf0ab6ba4e8267cf7f82fdcea9bd73554cf184/src/geo/transform.js) that is related to wrapping the image overlay?

**Comment by nigelnye** [comment]
Any update on this? After updating the jsfiddle source above, it still seems to be an issue in v1.11.1. Thanks

**Comment by mourner** [comment]
This turned out to be a very interesting issue. The coordinate precision is correct in GL JS; the problem is with the way we do texture mapping between corners, as can be seen on this comparison of GL JS vs Leaflet.DistortableImage:

https://user-images.githubusercontent.com/25395/137971891-7c7adc33-54ac-43e7-91f2-3f6d224710e9.mov

This didn't come up often because users typically use strictly top-down images, where corners are aligned as a rotated rectangle. However, when they are not, we need to overlay the image as if it were looked at an angle in 3D space — a perspective transformation. Instead, we're doing a simple linear interpolation for the texture over two triangles, which leads to distortion.

[These two section of the Wikipedia article on texture mapping](https://en.wikipedia.org/wiki/Texture_mapping#Affine_texture_mapping) explain the issue and a possible solution pretty well.  Basically, the middle image below is the situation we have in GL JS:

![image](https://user-images.githubusercontent.com/25395/137973921-e2940436-ed17-4348-a23b-b9bf2764cac9.png)

The solution to this is two-fold. We can change how we interpolate uv texture mapping values in the raster shader by following recommendations in the "Perspective correctness" section of the article, using reciprocals. However, for that we need to calculate "depth" values for each of the corners to pass to the shaders.

To do that, we can take clues from [this article on computing CSS matrix3d](https://franklinta.com/2014/09/08/computing-css-matrix3d-transforms/) that does this by solving a set of linear equations. This is essentially what Leaflet.DistortableImage does to position the image with CSS — a very clever plugin.

So this seems like a pretty involved fix with a lot of math involved, but an exciting one and definitely something we have to do!
