### ISSUE TITLE
queryRenderedFeatures inside a Polygon

### ISSUE THREAD

**Issue by thezealousfool** [mapbox/mapbox-gl-js#9211]
## Motivation

I have a layer of polygons and when clicked I want to query features inside that polygon for a different layer.

## Design Alternatives

queryRenderedFeatures as of now requires specifying a bounding box (southwest and northeast points). queryRenderedFeatures could take an Array of coordinates and limit the features only to the area of the polygon.

## Design

No new APIs added. We can just pass the polygon coordinates from the event handler to the queryRenderedFeatures function.

### Mock-Up

queryRenderedFeatures(Array<PointLike>): if Array.length > 2 then treat it as a polygon and return rendered features inside of the polygon.

**Comment by stevage** [comment]
It's fairly easy to achieve this by filtering the returned features through Turf's `booleanPointInPolygon()`. Is there any particular advantage to Mapbox-GL-JS doing that work? It would probably just have to do the same thing right?

**Comment by kkaefer** [comment]
This API only accepts a rect because our spatial index only supports lookups in rects. I recommend @stevage's approach: compute the bounding box of your geometry, pass that into `queryRenderedFeatures`, then use a point in polygon algorithm to determine whether it is in your polygon. You can use [Turf](https://turfjs.org/) for this.
