### ISSUE TITLE
Remove documentation of deprecated filter syntax

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#9227]
Now that there is the new `in` expression, everything that was possible with the old filter syntax is now easily possible with expressions, simply by replacing key with ["get", key]. (Except "none" which is just ["!", ["any", ...]]

So, perhaps time to completely remove it from the mapbox-gl documentation site. (Or move it to some other dumping ground...)

A few reasons to get rid of the documentation for the old filter syntax:

1. To stop new people adopting it, and hence smoothing the path to dropping support for it totally.
2. To make navigating the documentation easier, and avoid accidentally reading the wrong thing. (This happens to me fairly often). 

Although I kind of miss the simpler syntax, the similarity with the new syntax (yet total lack of compatibility between) is really problematic at times.

(From #9222)

**Comment by ryanhamley** [comment]
@stevage I have some good news for you. The @mapbox/docs team just pushed an update to our docs site which largely solves this problem (I promise I didn't know about this an hour ago when I asked you to make this issue!).

The filter docs are now hidden in a dropdown menu under the `Other` header which is clearly marked as `Legacy`.

<img width="129" alt="Screen Shot 2020-01-23 at 2 47 00 PM" src="https://user-images.githubusercontent.com/4523080/73030893-7a816580-3def-11ea-978a-45dca378a409.png">

Additionally, the docs are now broken up into individual pages so there's no confusion between expressions and filters when searching the page for e.g. "in". Sorry to have you open a new issue unnecessarily but at least this problem is solved.

**Comment by stevage** [comment]
Wow, that's excellent! Such timing - life is weird like that sometimes.
