### ISSUE TITLE
Is "{name}" syntax deprecated in text-field?

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#9244]
I was a bit surprised to discover that `{name}` syntax is not supported in the new `['format']` function, and is not documented in `text-field` (anymore?)

Is it officially deprecated? Are we meant to be doing `'text-field': ['get', 'name']` now?

If not:

- it should probably be documented?
- perhaps it should be supported in `['format']` ?

**Comment by ryanhamley** [comment]
Yes, that implicit lookup syntax is officially deprecated. It should still work in older properties such as `text-field`, but we recommend using expressions instead of the `{name}` syntax. We even updated an example that was using this syntax to use `"text-field": ["get", "title"]` as seen in https://github.com/mapbox/mapbox-gl-js-docs/pull/134/files

**Comment by stevage** [comment]
Ah thanks. I always interpreted "text-field" as meaning, the name of the field (ie, attribute) that will be shown, so it's slightly confusing...but cool. More consistent this way.
