### ISSUE TITLE
Size of the map on Ionic 

### ISSUE THREAD

**Issue by Alezco05** [mapbox/mapbox-gl-js#9297]
I'm trying to make width and height equal to 100%, but the class **mapboxgl-canvas** has a default value, and I don't know how to overwrite it.

**CSS**
```
 #map {
  height: 100%;
  width: 100%;
  }
```
**HTML**
```
<ion-header>
  <ion-toolbar>
    <ion-title>
      Tab 2
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <div id="map"></div>
</ion-content>
```
**TYPESCRIPT**

```
export class Tab2Page implements OnInit {

  constructor() {}
  title = 'view';
  map: Mapboxgl.Map;
  ngOnInit() {
    (Mapboxgl as any).accessToken = environment.mapboxKey;
    this.map = new Mapboxgl.Map({
      container: 'map', // container id
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [-74.810913, 10.985246], // LNG, LAT
      zoom: 14 // starting zoom
    });

    // Add zoom and rotation controls to the map.
    this.map.addControl(new Mapboxgl.NavigationControl());
  }
```

It works for me in Angular but in Ionic it doesn't work for me. The map is always 400px witdh and 300px height

**Comment by ryanhamley** [comment]
Hi @Alezco05 thanks for using Mapbox GL JS. Unfortunately, this looks like a problem specific to your Ionic app setup, not GL JS. In general, if the height/width is not being set to 100%, it means that the parent element probably does not have a set height/width. You may need to do something [this like](https://forum.ionicframework.com/t/css-height-100-ignored-in-ion-content/31142) but I'm not familiar with Ionic's structure

Since this isn't a GL JS issue, we can't offer any further support through this channel. For future "how to" questions, we recommend contacting [Mapbox support](https://support.mapbox.com/hc/en-us) or asking on Stack Overflow.

**Comment by Alezco05** [comment]
But when I put the app in full screen in the browser or open the developer tools, if it is placed 100%

**Comment by Alezco05** [comment]
> 
> 
> Hi @Alezco05 thanks for using Mapbox GL JS. Unfortunately, this looks like a problem specific to your Ionic app setup, not GL JS. In general, if the height/width is not being set to 100%, it means that the parent element probably does not have a set height/width. You may need to do something [like this](https://forum.ionicframework.com/t/css-height-100-ignored-in-ion-content/31142) but I'm not familiar with Ionic's structure
> 
> Since this isn't a GL JS issue, we can't offer any further support through this channel. For future "how to" questions, we recommend contacting [Mapbox support](https://support.mapbox.com/hc/en-us) or asking on Stack Overflow.

But when I put the app in full screen in the browser or open the developer tools, if it is placed 100%, not temporarily but permanently until you restart the page or the server

**Comment by Alezco05** [comment]
> 
> 
> Hi @Alezco05 thanks for using Mapbox GL JS. Unfortunately, this looks like a problem specific to your Ionic app setup, not GL JS. In general, if the height/width is not being set to 100%, it means that the parent element probably does not have a set height/width. You may need to do something [like this](https://forum.ionicframework.com/t/css-height-100-ignored-in-ion-content/31142) but I'm not familiar with Ionic's structure
> 
> Since this isn't a GL JS issue, we can't offer any further support through this channel. For future "how to" questions, we recommend contacting [Mapbox support](https://support.mapbox.com/hc/en-us) or asking on Stack Overflow.

But when I put the app in full screen in the browser or open the developer tools, if it is placed 100%, not temporarily but permanently until you restart the page or the server
![2](https://user-images.githubusercontent.com/37370433/74481197-4b0ac980-4e80-11ea-9841-c79a526876e1.png)
![3](https://user-images.githubusercontent.com/37370433/74481200-4ba36000-4e80-11ea-9984-b03422c3f6ae.png)

**Comment by ryanhamley** [comment]
I don't think that's surprising. It's changing the layout and styling of your app and/or calling `map.resize()`, which you could try doing manually after initialization. This is still almost certainly an issue with Ionic or your app layout specifically. I would guess that if you inspect the map container in Chrome Dev Tools, you'll see that it doesn't have a height or width or both. If it does and the map isn't filling it, `map.resize()` should fix the issue. Otherwise, this isn't something we can help debug via Github. You can try contacting Mapbox Support if you continue having issues.

**Comment by aasutossh** [comment]
> calling `map.resize()`, which you could try doing manually after initialization

and how do you know if the map is initialized (using plain JS).
I have a map, that's hidden at first and only visible when user clicks something (I'm using bootstrap nav tabs, and have a tab dedicated to map). map.on("load") works if the map is not loaded, and I switch to the map tab. But it doesn't work if I switch to map tab after a while.
![image](https://user-images.githubusercontent.com/18498932/107321795-4b599700-6acb-11eb-8e58-ae2c58d4fa67.png)

**Comment by cyberkepper** [comment]
In HTML try to control tab interaction with an event like example with material tab : (selectedIndexChange)="onTapChange($event)" on the parent  div and when u got the index of selected tab u must turn a flag setted at mapbox component child to true, if u do that works perfect. The problem is about the load flow of the dom, if u can control that when u click on the tab, the child component loads fine.

**Comment by calbanc** [comment]
implements map on ionViewDidEnter()
