### ISSUE TITLE
Not able to Order layers 

### ISSUE THREAD

**Issue by hmendezm** [mapbox/mapbox-gl-js#9351]
**mapbox-gl-js version**:1.8.1

### Question
Hi Guys.
I am using moverLayer but it looks like it does not take effect the new order. My situation is that the user has controls to allow to add a layer to the map. The user can choose any kind of combination but the layer should be ordered according to business rules. for instance, if you add the traffic information layer and after zip code information layer. The user should be able to hover traffic and see information and hover zip code and see the information. The problem is the zip code layer cover traffic layer so I need always to the traffic layer in the top of zipcode. I also used layer beneath but it is not working. I checked the layer array and the order is ok but the map is not reflecting the order.
Best
hmendezm

**Comment by ryanhamley** [comment]
We need more information to help. When submitting a bug report, we require a minimal reproduction of the bug (using a site like JSBin) so that we can debug the problem. If this is a "how to" question, please contact [Mapbox support](https://support.mapbox.com/hc/en-us). If you can supply a minimal reproduction of a GL JS bug, please respond to this ticket with it and I will re-open this issue. Thanks!
