### ISSUE TITLE
How to move the dot element produced by geolocate control

### ISSUE THREAD

**Issue by CSFlorin** [mapbox/mapbox-gl-js#9402]
**mapbox-gl-js version**: 1.8.1

### Question

I don't see docs on how to move the user location point manually. I can't find how to get the reference to that object.
![image](https://user-images.githubusercontent.com/9855031/76384174-6e0f8880-631b-11ea-835b-0da42eaf0672.png)

I suppose I'm asking two questions:
* How do I get a reference to the object that I can drag?
* How do I programmatically update the location of that object?

### Links to related documentation

This shows how to move a point you create https://docs.mapbox.com/mapbox-gl-js/example/drag-a-point/

**Comment by andrewharvey** [comment]
The GeolocateControl is designed to show the users location on the map, could you elaborate a bit more on the use case for letting the user drag it or programatically updating the location?

Since your use case sounds quite specific, do you think it would be better to just create your own Marker that has the same style? then you can set the location and make it draggable.

**Comment by CSFlorin** [comment]
Hey @andrewharvey Thanks for the response! That should work just as well. Could you help me with these 2 follow-ups:
* How do I disable the default marker?
* Where is the source for it so I can replicate it?

**Comment by ryanhamley** [comment]
@CSFlorin The Geolocate Control makes use of the Javascript [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API). It's not something unique to Mapbox. The source code for the Mapbox control is in https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/control/geolocate_control.js. There's not really any way to move the marker because that's not the purpose of the API. 

If you need something that can easily be dragged around, you can achieve this with either a [symbol layer](https://docs.mapbox.com/mapbox-gl-js/example/drag-a-point/) or an [HTML marker](https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/). You'll have to style them yourself. If you want to use CSS to do that, you'll need to use the HTML marker.

As far as disabling the dot, you would have to not use the geolocate control. You can make a custom control using this [IControl interface](https://docs.mapbox.com/mapbox-gl-js/api/#icontrol) which can implement a draggable marker/symbol to do whatever behavior you need.
