### ISSUE TITLE
Icontrol _container HTMLDivElement can't be updated

### ISSUE THREAD

**Issue by CSFlorin** [mapbox/mapbox-gl-js#9420]
I'm implementing a control per https://docs.mapbox.com/mapbox-gl-js/api/#icontrol

The reference to the object returned by my custom control is not updated when it should be.

Here is how my control looks:

```
export const logoControl = (theme: any) => {
  const _container = document.createElement("div");
  _container.id = "logoControl";
  _container.innerHTML = theme.palette.type;

  const onAdd = (map: any) => {
    return _container;
  };

  const result = {
    // _map, // not important for this example
    _container,
    onAdd,
    onRemove: () => {
    // not important for this example
    }
  };

  return result;
};
```

When `theme` is updated, this is re-executed. I know so because I log `result` and see it changes, but the control is not actually updated with this new value. The only way I can see to overcome this is to remove the control and then re-add it, but that seems wrong. The control's new value should be used.

**mapbox-gl-js version**: 1.8.1

**browser**: Chrome Version 80.0.3987.122 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Add a control: `map.addControl(useMemo(() => logoControl(theme, map), [theme]), "bottom-left");` (this is React for reference)
 2. Update the reference for the object passed in.
 3. See that it is not actually updated.

### Link to Demonstration

Although it's recommended, I don't have the time at the moment to do this. I hope I explained myself pretty clearly above :)

### Expected Behavior

The control should visually change when we update the reference to the object passed in.

### Actual Behavior

The control remains static.

**Comment by CSFlorin** [comment]
Been looking at the source at `src/ui/map.js:493`,

```
addControl(control: IControl, position?: ControlPosition) {
        if (position === undefined && control.getDefaultPosition) {
            position = control.getDefaultPosition();
        }
        if (position === undefined) {
            position = 'top-right';
        }
        if (!control || !control.onAdd) {
            return this.fire(new ErrorEvent(new Error(
                'Invalid argument to map.addControl(). Argument must be a control with onAdd and onRemove methods.')));
        }
        const controlElement = control.onAdd(this);
        this._controls.push(control);

        const positionContainer = this._controlPositions[position];
        if (position.indexOf('bottom') !== -1) {
            positionContainer.insertBefore(controlElement, positionContainer.firstChild);
        } else {
            positionContainer.appendChild(controlElement);
        }
        return this;
    }
```

So because the DOM element returned by `onAdd` is DOM, it seems React can't update it per https://reactjs.org/docs/state-and-lifecycle.html

Wondering if something could be done to accept a JSX element as well and render that in React if provided.

**Comment by ryanhamley** [comment]
Hi @CSFlorin I'm not sure exactly what problem you're encountering. You shouldn't need to call `onAdd` directly because it's called by `addControl`.

If you need to update the control, you can add more methods to your custom control class and call them. For example, the `ScaleControl` has a `setUnit` method which updates the UI to show different units of measure. The control class will need to be responsible for updating itself. There shouldn't need to be any special React code for dealing with the control container element.

https://github.com/mapbox/mapbox-gl-js/blob/2e3ffcd118c55970f809148b83de5992c1e2a4e4/src/ui/control/scale_control.js#L79-L82

We don't officially support React but we strive to make GL JS as compatible as possible and many React apps use GL JS. I don't think there's anything GL JS can do on our end so I'm going to close this ticket. If you need more information on creating a custom control, contact Mapbox support or post on Stack Overflow.

**Comment by CSFlorin** [comment]
Ok I see that example keeps a reference to the DOM element and updates the inner HTML. I can work with that. Thanks
