### ISSUE TITLE
Date support in expressions

### ISSUE THREAD

**Issue by edcolcode** [mapbox/mapbox-gl-js#9436]
1.8.0

### Question
There is a plan to include date support in expressions?
I want to filter features by using a date property but I need to perform a convertion due the date feature property is stored in a string format.

**Comment by ryanhamley** [comment]
Yes, we've discussed this internally and it was part of the original expression language plan https://github.com/mapbox/mapbox-gl-js/issues/6484. The implementation of expressions has been a bit piecemeal as we've had time around other issues and based on demand. I think this request makes sense but we don't have a timeline for when it will be introduced. I'm going to close this ticket since #6484 already captures this feature request. Thanks!

**Comment by edcolcode** [comment]
Thanks.

**Comment by 3zzy** [comment]
Wondering if there's any ETA, the other ticket hasn't been update in a while either. Thanks!
