### ISSUE TITLE
name_zh-Hant contains some Simplified Chinese

### ISSUE THREAD

**Issue by kk12837** [mapbox/mapbox-gl-js#9456]
Hi mapbox,

Is there a way to fix this?

Thanks

Keith

**Comment by ryanhamley** [comment]
Hi can you please fill out the issue template completely with an example of the issue you're seeing, including a live, minimal example? We need that in order to diagnose the issue and provide potential solutions.

**Writing a good bug report:**
 - Make the issue title a succinct but specific description of the unexpected behavior. Bad: "Map rotation is broken". Good: "map.setBearing(...) throws a TypeError for negative values"
 - Include a link to a minimal demonstration of the bug. We recommend using https://jsbin.com.
 - Ensure you can reproduce the bug using the latest release.
 - Check the console for relevant errors and warnings

**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1.
 2.
 3.

### Link to Demonstration



https://jsbin.com/

### Expected Behavior

### Actual Behavior

**Comment by kk12837** [comment]
Sorry, I will fix it.

mapbox-gl-js version: 1.8.1

browser: Chrome 80.0.3987.149

Steps to Trigger Behavior

Using name_zh-Hant as data field in the mapbox studio.

Link to Demonstration

Expected Behavior

The map will show Traditional Chinese Sprites.

Actual Behavior

The map shows some Traditional Chinese Sprites.
