### ISSUE TITLE
MapBox Navigation Control

### ISSUE THREAD

**Issue by Sowmya-Sukhanand** [mapbox/mapbox-gl-js#9623]
I've implemented a custom mapbox style and have a navigation control in it.Now i want to position the navigation control to 'top-right'.It ain't reflecting no matter what.The controls are being displayed at the bottom of the map.It is fixed in its position
![image](https://user-images.githubusercontent.com/55222218/80175941-b9a09c00-8614-11ea-93c2-46dbb6fc22bc.png)

**Comment by ryanhamley** [comment]
@Sowmya-Sukhanand Thanks for using GL JS. Unfortunately, a screenshot is not enough information to help you diagnose the problem. 

This appears to be a CSS issue since it should by default appear in the `top-right` corner. It's likely that the positioning is being ignored or overridden due to missing the GL-JS CSS file or conflicting CSS positioning/display rules in your outer container. I think it's unlikely that this is a bug in the control and since there's no example, I'm going to go ahead and close this issue. If you need further assistance, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).
