### ISSUE TITLE
Marker symbol location jitters when zooming in slowly

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#9626]
I noticed this weird thing while zooming in slowly on Mapbox Streets in 1.9.1. The town point symbol locations jitter randomly back and forth while the labels remain steady.

![wander-towns2](https://user-images.githubusercontent.com/678344/80214576-6cf1ab00-867e-11ea-8a8d-77acd94be852.gif)

**Comment by pathmapper** [comment]
This happens also with `easeTo` instead of `zoom` as reported in https://github.com/mapbox/mapbox-gl-js/issues/8614#issuecomment-524204725.

**Comment by stevage** [comment]
Oh, interesting. I should say that I witnessed this on FireFox on MacOS.

**Comment by arindam1993** [comment]
@pathmapper Yep you are totally on point, we intentionally snap symbols to the pixel grid so that they're sharp.

Some browsers internally do this for HTML elements as well, which causes HTML markers to have similar jitter on firefox, but not chrome.

We actually have a fix in-progress already it alleviates this issue by snapping to the grid over-time instead of instantaneously.
https://github.com/mapbox/mapbox-gl-js/pull/8738


Closing since this is already a known.

**Comment by stevage** [comment]
Thanks for the update!
