### ISSUE TITLE
Unclustered-points have id: undefined

### ISSUE THREAD

**Issue by pierreferry** [mapbox/mapbox-gl-js#9637]
**mapbox-gl-js version**: 1.10 (latest)

**browser**: any

### Steps to Trigger Behavior

 1. Open codepen link, open codepen console 
 2. Click on any unclustered point (any little blue circle)
 3. Witness the lack of id in the console

### Link to Demonstration

https://codepen.io/cptrooster/pen/PoPjOwN

This demonstration has been made using "Create and style Cluster" example from https://docs.mapbox.com/mapbox-gl-js/example/cluster/.  I just added a `console.log` inside a click handler.

### Expected Behavior
Unclustered point should have an id.
I'm trying to handle hover effect for those points with feature-state, but since they have no id it's impossible.

### Actual Behavior
Unclustered point have `id: undefined`

**Comment by arindam1993** [comment]
@pierreferry this is intentional, we don't auto-generate feature-ids incase user's need to specify their own.

But we do have `generateId` and `promoteId` https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-generateId to do this as you need.

I tried this out with your codepen and it fixed the problem. 
Closing.
