### ISSUE TITLE
Better labeling algorithm that works with tilt

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#964]
@ansis lets discuss the labeling algorithm that works well in perspective view here. 

- What options do we have for labeling behavior? 
- What are the potential costs of each option? 
- What are the usability concerns?

The first stage was horizontal labels. As the second stage, I think keeping labels projected to the map surface with the same zoom/rotation behavior as plain 2D is fine. Is this blocked by something?

**Comment by ansis** [comment]
dump of  my notes on labelling:

Currently, for each label, we precompute zoom range and a rotation range it can be shown. Trying to precompute everything is a bad idea because it isn't precise enough for dense placement in rotated views, because it is slow.

We should precompute less and rerun collision detection when the view changes. The collision detection would be asynchronous and it would just reuse the old collision data until the new one is visible.

At one extreme we could recompute on every frame.
Or we could compute the zoom range for each label at the current rotation and update whenever you rotate.
Or something else.

Things we want:
- denser label placement in general
- much denser label placement for rotated views
- support for tilt
- faster
- fast enough for serverside rendering (or have a faster version with identical results)
- ability to redo placement on the fly, for example when toggling label layers


If we recompute on the fly we'll need some way of using the updated collision stuff. We could
- update the actual buffers with the new data
- use a texture to lookup placement info and update only that


The current approach is slow also because we
- generate all possible individual glyphs for all segments they appear on before we check for collisions
- we use many small boxes to represent curved road labels. A more direct representation could be faster.


Showing overlapping labels for a brief time is ok.
Using simplified label shapes to speed up placement is a good idea.

**Comment by ljbade** [comment]
@ansis Everything sounds good to me, particularly denser labelling.

It will be interesting so see what algorithm you eventually use/pick to be really fast.

**Comment by kapadia** [comment]
After getting background on the problem from @ansis and @mourner, we decided that a good first step is to improve the performance of the current implementation. One concern has been that the density of labels is too low, but this looks to be associated with another bug #986.

Curved label collisions are currently checked by detecting collisions between the bounding box of each glyph in a label. This results in running `Collision.getPlacementScale` and `Collision.getPlacementRange` over a large number of objects. To improve performance, we'll simplify the bounding boxes around each glyph with fewer boxes that approximate the same area. The result should be a smaller set of objects that `Collisions` will run against.

**Comment by ljbade** [comment]
what algo is used for collisions currently?

**Comment by mourner** [comment]
@ljbade https://www.mapbox.com/blog/placing-labels/

**Comment by ljbade** [comment]
Cool, be awesome if you published your improvements as an academic paper.

**Comment by kapadia** [comment]
Last week we started a new repo to help address the performance of the current labeling approach. The idea is to use fewer bounding boxes to detect collisions - the current approach is a little wasteful. [bboxify-labels](https://github.com/mapbox/bboxify-labels) accepts a polyline, anchor, and label length to produce a series of bounding boxes that approximate the position of a label on a polyline.

@ansis has started experimenting with the library, and made a nice visualization of the bounding boxes that are active at a particular zoom level.

![](https://cloud.githubusercontent.com/assets/1421652/6235914/d560704a-b69a-11e4-8bf2-c9ac837e888e.png)

Next steps: 

 * fix bbox spacing on some segments https://github.com/mapbox/bboxify-labels/issues/1
 * the density of boxes is a function of line angle. this needs to be tuned so that we're not wasteful in the number of bboxes produced https://github.com/mapbox/bboxify-labels/issues/2

**Comment by ansis** [comment]
pull request here: https://github.com/mapbox/mapbox-gl-js/pull/1079
