### ISSUE TITLE
fitBounds() with bearing and uneven padding causes unexpected results

### ISSUE THREAD

**Issue by waissbluth** [mapbox/mapbox-gl-js#9641]
Hi, when using fitBounds() with a bearing and a one-sided padding, the results are not what I was expecting.

This does not seem to be documented, but I expected the padding options to be relative to the viewport and not to the map. If this result is actually expected, would it be possible to add an additional padding option about whether the padding should be rotated with the bearing or not? Alternative, I suspect I could do some rotation math to achieve the desired result.

**mapbox-gl-js version**: v1.10.0

**browser**: Chome for Mac 81.0.4044.113

### Steps to Trigger Behavior

 1. call `map.fitBounds(bbox, {bearing: 90, padding: {left: 100}})`

### Link to Demonstration

https://jsfiddle.net/vkupemwc/1/

### Expected Behavior
The bbox to be shown with padding on the left

### Actual Behavior
The padding is actually on the bottom

**Comment by arindam1993** [comment]
🤦 
Looks like the hard-coding to 0 for bearing came back over the course of some refactors.
https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/camera.js#L495


A workaround I can suggest since you seem to want to use it for floating UI elements is to to use the `persistent` padding that we recently added.
https://docs.mapbox.com/mapbox-gl-js/example/offset-vanishing-point-with-padding/


It has a slightly different effect when compared to `fitBounds` because it offsets the vanishing point of the map. Calls to `fitBounds` will respect this persistent padding.

**Comment by waissbluth** [comment]
Thank you @arindam1993. As I was trying to work around this issue I think I might have encountered [another one](https://github.com/mapbox/mapbox-gl-js/issues/9643). Could you please advise? 

Could you share an expected timeline to fix this issue, so that we can assess wether to keep trying to work around it or wait for a fix?

Thanks!

**Comment by arindam1993** [comment]
The second issue is not a bug, I've added an explanation in that thread. With regards to this fix we don't have a timeline at this point, but a PR is always welcome :)

As I pointed out earlier, the hard coding of the bearing to 0 in https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/camera.js#L495 is causing the issue.

**Comment by stevage** [comment]
I just ran into this too. Looking forward to the PR being accepted!
