### ISSUE TITLE
Load map of mapbox on function call

### ISSUE THREAD

**Issue by Sowmya-Sukhanand** [mapbox/mapbox-gl-js#9642]
Hi am working with the rendering of mapbox in angular framework.Right now the issue what am facing is that i cannot load the map in the browser.
I have defined a function in where i've given all the required to load the map and iam calling the function from a html div container after validating a condition.The control goes into the function but the error is that it is not identifying the container property of the map.

my html code:
    <div id="map" style="margin-top: 370px;" *ngIf="result;then loadMap()"></div>

my script:
loadMap(){
    this.map=new Map({
      
      container:document.getElementById('map') , 
      style: 'mapbox://styles/mapbox/streets-v11',
      center: { lng: -102.380979, lat: 35.877742 },
      zoom: 9,
      pitch: 20,
      attributionControl: false
      });
      this.map.addControl(
        new NavigationControl({
          showZoom: true,
          showCompass: true
        }),
        'bottom-right'
      );
  }

Also,is it really possible to load map with a function call or am i just wasting my time here.
![image](https://user-images.githubusercontent.com/55222218/80593736-54e3a800-8a3f-11ea-9ecf-fd8c0b3e954c.png)

**Comment by ryanhamley** [comment]
The container can be either a string (e.g. `'map'`) or an `HTMLElement` so using `getElementById` works. See https://jsbin.com/faxikihoti/edit?html,output for an example of this.

The likeliest explanation given that you're using Angular is that the DOM is not fully created by the time the map is created so that `document.getElementById('map')` is returning `null`. I'd suggest logging the value of `document.getElementById('map')` to ensure that it's actually getting the element or just simplify it and use the ID string 'map'. If that isn't working, you'll need to figure out where in the Angular lifecycle it's safe to access DOM elements.

Note that this issue tracker is for reporting bugs and requesting features. Unfortunately, we can't offer support via this channel, so if you require further help, we recommend asking your question on Stack Overflow or contacting [Mapbox support](https://support.mapbox.com/hc/en-us). Thanks.
