### ISSUE TITLE
Long text strings rendering incorrectly when text-anchor is not "center"

### ISSUE THREAD

**Issue by benderlidze** [mapbox/mapbox-gl-js#9657]
It was close here https://github.com/mapbox/mapbox-gl-js/issues/1531 
but I am still getting this issue with 1.10.0 
https://jsfiddle.net/benderlio/hyo9n8ab/6/

**Comment by ryanhamley** [comment]
The underlying cause is shown in https://github.com/mapbox/mapbox-gl-js/issues/1531#issuecomment-174649437

>When the offset from the anchor is added to the buffers there aren't enough bits to store the full value so it ends up wrapping.

As noted in https://github.com/mapbox/mapbox-gl-js/issues/1531#issuecomment-375413894

>It's still possible to make labels that break, so we may run into this again, but I'm hoping this will be good enough and for now we don't have any plans to make further changes.

I think we probably aren't going to increase the max label width further, especially since there's a number of other strategies for dealing with this issue. If you remove the `text-anchor` (or just change it to the default value of "center"), this issue goes away. You could also break your line up with explicit newline characters (e.g. `\n`) to create 2 or more lines. I'm going to close this since there's already a main ticket for this issue (albeit one that's closed). Unless we see a number of issues with this that couldn't be solved in other ways, we're unlikely to take more action.
