### ISSUE TITLE
Some dashed lines render crooked 

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#967]
I'm not sure exactly what the issue is, but some dashed lines that have sharp angles in the geometry look like this (click image for larger view):

![screen shot 2015-01-29 at 2 22 04 pm](https://cloud.githubusercontent.com/assets/5607844/5964604/784cf58a-a7c3-11e4-97ad-dfdd8a88d10a.png)

This style looks fine for straight lines:

![linedash-not-straight](https://cloud.githubusercontent.com/assets/5607844/5964621/9acda906-a7c3-11e4-9f19-e5a27a0d9729.png)

Here's the written style:

```
}, {
    "id": "road_path_steps",
    "type": "line",
    "source": "mapbox",
    "source-layer": "road",
    "filter": ["==", "type", "steps"],
    "paint": {
      "line-color": "#bba",
      "line-dasharray": [0.3, 0.2],
      "line-width": {
        "base": 1.3,
        "stops": [[15, 1.5], [20, 10]]
      }
    }
```

This issue existed before the big line-dash refactor, but it seems a bit worse now. @ansis Any ideas?

**Comment by ljbade** [comment]
@ansis How are you interpolating the texture coords in the line triangles?

**Comment by ansis** [comment]
Yeah, this has been [around for a while](https://github.com/mapbox/mapbox-gl-js/issues/60#issuecomment-26272987). I don't think this would have gotten worse with the recent dash work because the part that causes the problem hasn't changed.

@nickidlugash the best workaround is to use `"line-join": "butt"` or `"line-join": "round"`.


The tessellated line looks something like this: 
![screen shot 2015-01-29 at 1 48 01 pm](https://cloud.githubusercontent.com/assets/1421652/5966953/ab9ed562-a7bd-11e4-95ca-3484d03a142d.png)

A fragment's position in the dash pattern is calculated using the fragment's distance along the line.
At every corner there are two vertices, the inner one and the outer one. Both have the same distance value, even though one is actually closer than the other. This change in distance depends on the linewidth. To be able to adjust for the difference we would need to stop sharing vertices between triangles in neighboring line segments (because the adjustment is positive on one side of the corner, and negative on the other) and add a bit more information to each vertex.

It would be nice to default to `"line-join": "butt"` or `"line-join": "round"` for dashed lines, but we can't do that because dashes are paint properties and linejoins are layout properties.

**Comment by ljbade** [comment]
@ansis you sure you can't correct the skew in the shader? If you know the x texture coord, then you might be able to adjust y to account for the different lengths.

**Comment by ansis** [comment]
@ljbade you would need to skew in different directions based on which side of the corner you are on. If the vertex is shared between triangles on both sides you can't do this. So you'd have to use separate vertices, which might be ok, but it would double the number of vertices.

**Comment by ljbade** [comment]
Ah I see.

**Comment by bhousel** [comment]
Hey @ansis, I'm just really trying to understand this issue in more detail.

If we tessellate the lines like this, we can still make tristrips out of them and we can know each fragment's position along the line because vertices exist along the centerline in each grouping of 4 triangles.  It does increase the # of vertices, but tristrips are fast.   Would this fix the issue?

<img width="431" alt="screenshot 2016-01-14 22 31 16" src="https://cloud.githubusercontent.com/assets/38784/12344745/b32b0cf0-bb0e-11e5-89e8-0a539ff553de.png">

**Comment by ansis** [comment]
@bhousel I don't think that would, because the extra middle vertex wouldn't help you know the "real" distance along the line at the corners. The value at the middle of the line is already correct

**Comment by lucaswoj** [comment]
> To be able to adjust for the difference we would need to stop sharing vertices between triangles in neighboring line segments (because the adjustment is positive on one side of the corner, and negative on the other) and add a bit more information to each vertex.

Do you think there is a way we could solve the problem by adding an additional attribute to each vertex?

**Comment by ansis** [comment]
> Do you think there is a way we could solve the problem by adding an additional attribute to each vertex?

On top of adding another attribute (or finding a way to pack it into existing attributes) we'd have to add more vertices. The corner vertices are shared between segments, but if the slant is fixed the corner vertices need to be separate because the need to set different "distance along the line" varying values. This would fix the slant but would create potential artifacts at corners since the "distance along the line" would only be continuous in the middle of the line.

It's hard to explain with words. I should try drawing it out

It's hard to make dashed lines look nice at corners even conceptually.
