### ISSUE TITLE
RTL Plugin has unclear documentation for and usage of error callback

### ISSUE THREAD

**Issue by jacksonlauren** [mapbox/mapbox-gl-js#9689]
In the documentation for setting up the RTL text plugin, it [states](https://github.com/mapbox/mapbox-gl-js/blob/master/src/index.js#L206):
`{Function} callback Called with an error argument if there is an error.`

This seems to imply that the callback will only get called if there is an error. That is not consistent with the actual usage of the callback in the code. The user provided error callback gets called on plugin state changes, just with a null error argument

The callback is hooked up to a function called `triggerPluginCompletionEvent` ([here](https://github.com/mapbox/mapbox-gl-js/blob/184b75d98c79df913cf31cdc256aa45e15df4bfe/src/source/rtl_text_plugin.js#L30-L39)) and calling the user-provided callback is not gated on the `error` parameter being non-null

Further down in `rtl_text_plugin.js` is the first call to `triggerPluginCompletionEvent`, which **does** gate calling `triggerPluginCompletionEvent` on the error being non-null ([here](https://github.com/mapbox/mapbox-gl-js/blob/master/src/source/rtl_text_plugin.js#L87-L88))

But in `style.js`, `triggerPluginCompletionEvent` is also hooked up to a callback for `syncRTLPluginState`([here](https://github.com/mapbox/mapbox-gl-js/blob/fb6d18d25ce19b2a7c03014fab2f74db25336acc/src/style/style.js#L171-L180)), but this time it **is not** gated on the provided error being non-null. When you look into the implementation of `syncRTLPluginState` in `worker.js`([here](https://github.com/mapbox/mapbox-gl-js/blob/fb6d18d25ce19b2a7c03014fab2f74db25336acc/src/source/worker.js#L156-L173)), you can see that there is a possibility of it passing back a null error message on success

This inconsistency on usage of the error callback that the user provided when setting up the RTL plugin can cause users to unnecessarily log successful plugin state changes as errors, and muddy their logs

**Comment by ryanhamley** [comment]
Hi @jacksonlauren thanks for the clear write up on the issue. The callback is not supposed to be called only on error. Check out this example in our internal RTL plugin debug page

https://github.com/mapbox/mapbox-gl-js/blob/08d5fb2d066d4fa48830132527693c4abbec3050/debug/rtl.html#L49-L61

You can see that this example anticipates that `err` could be null. This is obviously a trivial example, but one can imagine handling the successful loading case as well in some way (e.g. moving the map to an area with RTL text or adding a POI layer with RTL labels).

The reason for the callback to be gated on error here

https://github.com/mapbox/mapbox-gl-js/blob/08d5fb2d066d4fa48830132527693c4abbec3050/src/source/rtl_text_plugin.js#L87-L92

is so that the plugin can fail fast without triggering unnecessary activity on the worker.

I don't believe we'll want to change the behavior of the plugin. The pattern shown above in the debug example is a workaround for handling null errors. I will leave this ticket open as a request for clearer documentation on the plugin callback (cc @mapbox/docs)

**Comment by jacksonlauren** [comment]
That works! As long as it's clear that the callback could be called on success as well, that would be good. At the moment, the callback itself is defined in the code as being of type "ErrorCallback", and the documentation isn't the most clear.

If this is changed to be more clear that it isn't an ErrorCallback, and that it will also be called on success as well as error, that would clear up confusion and be great!

Thanks for looking into it!
