### ISSUE TITLE
What is the best strategy for markers and popups?

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#971]
Hello,

This is more of a question. Right now mapbox-gl-js seem to have support for markers only in the context of GeoJSON layers (see example https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/). With the featureAt API, it looks like you can do interactions but you need to handle a few things manually.
There doesn't seem to be any example with an API close to leaflet, with methods such as addMarker / bindPopup, etc.

What is the mapbox's strategy around this for mapbox-gl-leaflet? Is it using @mourner 's mapbox-gl-leaflet (https://github.com/mapbox/mapbox-gl-leaflet) and just make use Leaflet existing API on top of the mapbox-gl-js layer? It does work but because the systems behave differently (animation, rotation, etc.), the result is a bit jaggy and doesn't feel smooth at all.

Thanks,
Fabien

**Comment by mourner** [comment]
I think the strategy is eventually making Mapbox GL JS API much easier to use for tasks like this — adding easier marker/interaction-related methods, revising the sprites API in the style spec, adding basic popup support #325 etc. It's more challenging to do right than in Leaflet because technologies are so different, but it's doable. We've just focused on core challenges like rendering and style specification up till now, but we'll be gradually shifting focus to more API work as essential core issues are being tackled.

`mapbox-gl-leaflet` is more of a fun proof of concept than something that's will be encouraged for GL JS use.

**Comment by fnicollet** [comment]
I see, thanks :)

If mapbox-gl-leaflet could have a better "sync" with the mapbox-gl layer, it would be an actually very useful proof of concept. I use it in my application and that's the only problem with it (along with rotation)

Fabien
