### ISSUE TITLE
Calling setData on geojson sources causes flickering

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-js#973]
`source.setData` is being called on mousemove in this example:

![draw](https://cloud.githubusercontent.com/assets/1577766/5985089/8c17eec4-a892-11e4-899b-917e1169b7b5.gif)

**Comment by mourner** [comment]
@edenh yes, because on ever setData, you need to send it to the worker, process it and send back. We could make this a bit better by not removing the line until the main thread gets new processed data.

For a smoother experience on specific use cases like this where data is very small and coordinates don't get away from the current tile too much, but needs to be rendered fast, we could implement an alternative code path that completely avoids worker communication and tiling. It would need a different API though. @ansis what do you think?

**Comment by robschley** [comment]
This would also help us. We have some use cases that require manipulating a very small amount of data via the setData API and flickering/lag is noticeable.

**Comment by mourner** [comment]
Grabbing this today.

**Comment by mourner** [comment]
@robschley try now!

**Comment by robschley** [comment]
@mourner The flicker is gone when using the `setData()` API, it is still a little jumpy if the setData API is called frequently but it does not flicker all the data which is a huge improvement. I wonder if it would be possible to animate/transition when using `setData()`? I suspect that would be a lot of work but it might be something to add to the backlog. Thanks for tackling this issue!

**Comment by mourner** [comment]
@robschley hmm, can you demonstrate the jumpiness with a JSFiddle? I haven't seen that.

**Comment by samarth1sharma** [comment]
Instead of using icon, use mapbox marker.
Dynamically vary the latLng of the marker by requesting animation with the help of requestAnimationFrame() function and a very smooth animation can be produced.
Works perfectly fine for me!.

The problem with mapbox icon is that its custom setData() method takes sometime to update the source and so the next animation frame is requested before the data is updated in the source.This causes flickering.
Using mapbox marker, this can be solved.
And then background-image css property can be used to assign a custom image to the marker.

**Comment by github0013** [comment]
http://turfjs.org/
may be the key.

https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-route/
https://qiita.com/amay077/items/8f0a415035816217b922
