### ISSUE TITLE
"SecurityError: The operation is insecure" in Firefox private mode

### ISSUE THREAD

**Issue by aclueless** [mapbox/mapbox-gl-js#9790]
Using Firefox on Fedora 32, when in private mode, visit: https://docs.mapbox.com/mapbox-gl-js/api/, Firefox show two errors, but my personal app only show:

> SecurityError: The operation is insecure.

As far as I remember, this did not occur with previous version of Firefox. I don't know if Firefox did something wrong. But I think it's better to start inspecting mapbox-gl-js before reporting to Firefox (at least to find out which operation cause the issue)?

**Comment by ryanhamley** [comment]
This doesn't appear to be specific to Fedora. I see the same warning in Firefox on MacOS Catalina when in private mode. It appears to be due to how Firefox's private mode handles service workers https://bugzilla.mozilla.org/show_bug.cgi?id=1429714

That being said, I don't see this warning when I open a map application directly in Firefox private mode so I believe this is specific to the docs website, not the library. Therefore, I don't think this is something that needs to be fixed on our end.

**Comment by aclueless** [comment]
Hey, my personal app is **not a docs website** :grin:, but it creates the map from wasm and it show the warning. So I don't think *it's specific to the docs website*.

**Comment by ryanhamley** [comment]
Ah I tested with an older version of GL JS that didn't show this problem. The issue starts with e86649397d595709656158b04143a6fc8fbfeaea. When running the map in Firefox private mode after that commit, you see `Error: can't serialize object of unregistered class` and the map is broken. The map is fixed in 70087e3f8629f1927818f673ab854f93b5906662 with the `SecurityError: The operation is insecure.` warning. Presumably, the introduction of the cache system for tiles necessitated by v1.0.0 led to an error in some cases when fetching tiles. That error initially wasn't handled leading to the broken map. When it was handled, we got the SecurityError instead. I'm not sure there's a workaround for this though or what, if any, impact it has. @ansis what do you think?
