### ISSUE TITLE
Mapbox performance problems

### ISSUE THREAD

**Issue by Bur0** [mapbox/mapbox-gl-js#9850]
Hi,

I'm using `mapbox-gl-js` in my React app which has a lot of layers. Created all layers at once and toggle visibility (show/hide) them when it's needed. My code:

```
data.map((item) => {
  let id = `region-${item.id}`;
  map.addSource(id, {
    type: "geojson",
    data: item.geojson,
  });
  map.addLayer({
    id: id,
    type: "fill",
    layout: {},
    source: id,
    paint: {
      "fill-color": "red",
      "fill-opacity": 1,
    },
  });
});
```

Problem here is app performance gets slower and slower when displaying layers by zooming or moving around. It's about 5-10 FPS in Chrome Dev Tools.

How can I optimize it? I couldn't find any workaround so far. Any help is appreciated.

**Comment by mourner** [comment]
Due to the way GL JS works under the hood, the number of layers has a severe impact on performance. So your only option for improving performance is to reduce the number of layers, e.g. by having a single layer and utilizing expressions and filters to style or toggle features differently depending on their properties.
