### ISSUE TITLE
mapbox webgl transform instabilities at high zoom levels

### ISSUE THREAD

**Issue by gazcredible** [mapbox/mapbox-gl-js#9871]
**mapbox-gl-js version**:
"https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.js"
**browser**:
chrome 83.0.4103 osx

### Steps to Trigger Behavior
 1. Load custom-style-layer demo  https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/
 2. zoom into edge of triangle
 3. observe transformed point of triangle moving randomly

### Link to Demonstration
youtu.be/4VzoMxAe57c 

https://jsbin.com/

### Expected Behavior
Zooming should be as stable as GeoJSON & three.js examples
https://docs.mapbox.com/mapbox-gl-js/example/geojson-line/

**Comment by arindam1993** [comment]
This isn't a bug, but happens because the data being rendered here is in global mercator co-ordinates, the origin for which is with the top left corner of the entire world.

With GeoJSON, we split it into tiles internally, and set the origin of the data to be the top left corner of each tile which resolves this issue.
