### ISSUE TITLE
Enabling animation/flyto for geolocate control

### ISSUE THREAD

**Issue by marionram** [mapbox/mapbox-gl-js#9887]
**mapbox-gl-js version**: 1.10.1

Hi. I'm using [GeolocateControl](https://docs.mapbox.com/mapbox-gl-js/example/locate-user/) to locate the user's location in the map. However, once I click the geolocate button, it jumps to the point rather than doing the camera animation. At first I thought this was related to the flyto animation but my code looks the one in the [slowly fly to a location](https://docs.mapbox.com/mapbox-gl-js/example/flyto-options/) example and geolocate control still jumps to the point. 

The code I'm using for geolocate control is basically what's on the example from the documentation 

`var geoctrl = new mapboxgl.GeolocateControl({
     positionOptions: {
        enableHighAccuracy: true
     },
     trackUserLocation: true
  }); 

this.map.addControl(geoctrl);`

I'm new to mapbox so this is probably a silly mistake I made, but I haven't been able to find much information on how to enable this animation or what is causing the animation to not show up so I'm stuck.
Any help on this would be appreciated.

**Comment by andrewharvey** [comment]
The GeolocateControl does a smooth fly to animation out of the box. If you're not seeing this it's probably because you've turned on an OS or browser setting to reduce animations and hence https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion is set. Mapbox GL JS will respect the user's preference to reduce non-essential motion.

If you consider the motion essential, you can tell the GeolocateControl that the animation is essential https://docs.mapbox.com/mapbox-gl-js/api/properties/#animationoptions and it will ignore the browsers preference.

```js
map.addControl(
  new mapboxgl.GeolocateControl({
    positionOptions: {
      enableHighAccuracy: true
    },
    trackUserLocation: true,
    fitBoundsOptions: {
      essential: true
    }
  })
);
```

per the documentation at https://docs.mapbox.com/mapbox-gl-js/api/markers/#geolocatecontrol

**Comment by marionram** [comment]
Hey Andrew, thanks for your response. I double checked that animations are enabled on windows and they were off so that fixed it. It's interesting that I implemented the flyto example and that one shows the animation no problem, yet geolocate didn't. Either way, the issue is resolved. Thank you

**Comment by andrewharvey** [comment]
> I implemented the flyto example and that one shows the animation no problem, yet geolocate didn't. Either way, the issue is resolved.

In the flyTo example the options set `essential: true`, whereas the Geolocate Control doesn't set `essential: true` by default.
