### ISSUE TITLE
Get coordinate on click Angular

### ISSUE THREAD

**Issue by Alezco05** [mapbox/mapbox-gl-js#9888]
Hi, I'm trying to get the coordinates when I click my map in Angular, but it returns undefined this is my code
 
HTML

`<div id="map" (click)="getCoords($event)"></div>`

TS
```
      getCoords(e){ 
          console.log(e.lngLat); // undefined
          }
```

**Comment by ryanhamley** [comment]
This is impossible for us to debug given the amount of information here but my guess is that `$event` is an Angular event, not the Mapbox event that contains the `lngLat`. You could log that out to be sure. But probably instead of using the Angular component's click function, you want to do `map.on('click', function (e) {...})` inside the component.
