### ISSUE TITLE
Jest | TypeError: window.URL.createObjectURL is not a function

### ISSUE THREAD

**Issue by ItzaMi** [mapbox/mapbox-gl-js#9889]
**1.11.1**:

### Question
```Jest | TypeError: window.URL.createObjectURL is not a function```

I'm aware that there are solutions like [this](https://github.com/mapbox/mapbox-gl-js/issues/3436#issuecomment-421117409) but due to me being new to this I fail to completely comprehend what I should do to solve.

I don't have any ```setupTest.js``` or ```jest.stubs.js```

Creating them appears to do nothing for my test suites. I'm using [ftw-hourly ](https://github.com/sharetribe/ftw-hourly) for this project and I added **mapbox-gl** and **@mapbox/mapbox-gl-geocoder** as dependencies.

Can someone guide me on how to solve this?

**Comment by ryanhamley** [comment]
Hi @ItzaMi I'm not familiar with the project you're using, but it appears to be based on `create-react-app` which has documentation on testing at https://create-react-app.dev/docs/running-tests. It looks like if you create tests with the naming structure `*.tests.js`, the project should recognize them. That's where I'd put something like `window.URL.createObjectURL = function() {};`.

The issue here is that the [`window` object](https://developer.mozilla.org/en-US/docs/Web/API/Window) is only available in the browser, while tests are run in Node. The workaround simply mocks the `createObjectURL` function that the browser has as an empty function so that Node doesn't throw an error when trying to call it. This also requires including [`JSDom`](https://github.com/jsdom/jsdom) in your tests to mock out the Window and URL objects (JSDom doesn't mock `createObjectURL` which is why the workaround is required).

If you need more help getting things set up, I recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!

**Comment by mbtejeswar** [comment]
> **1.11.1**:
> 
> ### Question
> `Jest | TypeError: window.URL.createObjectURL is not a function`
> 
> I'm aware that there are solutions like [this](https://github.com/mapbox/mapbox-gl-js/issues/3436#issuecomment-421117409) but due to me being new to this I fail to completely comprehend what I should do to solve.
> 
> I don't have any `setupTest.js` or `jest.stubs.js`
> 
> Creating them appears to do nothing for my test suites. I'm using [ftw-hourly ](https://github.com/sharetribe/ftw-hourly) for this project and I added **mapbox-gl** and **@mapbox/mapbox-gl-geocoder** as dependencies.
> 
> Can someone guide me on how to solve this?

HI @ItzaMi 

I am also facing same issue, Can you help on this issue if you were ablet  to resolve this
