### ISSUE TITLE
Text Disappearred When Animating Symbol Layer with Text

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#9905]
**mapbox-gl-js version**:1.11.0

### Question

When animating a dot with text-symbol layer, the text blinked sometimes. There is a demo:  https://jsfiddle.net/aiamjay/9koxvr8g/ 

Can I make it appear all the time?

**Comment by ryanhamley** [comment]
This is caused by label collision. As the label of the symbol comes near the labels of other layers, one of the labels is temporarily hidden to avoid them overlapping. To avoid this, you can change the layer's layout to be

```
            'layout': {
                'text-field': 'hello world',
                'text-allow-overlap': true,
                'text-ignore-placement': true
            }
```

`text-allow-overlap: true` ensures that the text on the rotating symbol will never be hidden and `text-ignore-placement` ensures that the text on the layers below the marker (for example, the country names) won't ever be hidden. You can refer to the [Symbol layer documentation](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#symbol) for further guidance.
