### ISSUE TITLE
Within expression seems broken when used in querySourceFeatures method

### ISSUE THREAD

**Issue by AdriSolid** [mapbox/mapbox-gl-js#9923]
**mapbox-gl-js version**: v1.11.1

**browser**: Chrome

### Steps to Trigger Behavior

 1. Click on 'QuerySourceFeatures' button
 2. Open the console to see the queried features

### Link to Demonstration

[Demo](https://codepen.io/AdriSolid/pen/QWNbobE)

### Expected Behavior

'querySourceFeatures' should throw features when using filters with 'within' expression

### Actual Behavior

'querySourceFeatures' method does not throw features when using the new 'within' expression on filter prop. The Codepen provided is filtering  "routes" layer with the following filter: ["within", maineJSON]
I'm trying to apply same filter to query source features, but always throws an empty array. Other filters works as excepted

Cheers!

**Comment by ryanhamley** [comment]
Thanks for the demo @AdriSolid You're correct that this isn't working right now. I investigated and I don't have a full solution yet but I can outline why it's not working to aid in future work on this issue.

The `within` operator was designed to work with GeoJSON features that are added in a layer. For a line layer, for example, the code looks like this

https://github.com/mapbox/mapbox-gl-js/blob/e1e68a80ca83c3f52ff16b7d3eb1b011027bd2b1/src/data/bucket/line_bucket.js#L152-L155

The `geometry` property is passed to 

https://github.com/mapbox/mapbox-gl-js/blob/e1e68a80ca83c3f52ff16b7d3eb1b011027bd2b1/src/data/bucket/line_bucket.js#L165-L174

The `bucketFeature` is used in the `addFeature` call. This kicks off a chain that results in evaluation of the `within` expression using this `bucketFeature`.

https://github.com/mapbox/mapbox-gl-js/blob/e1e68a80ca83c3f52ff16b7d3eb1b011027bd2b1/src/data/bucket/line_bucket.js#L195

In the `within` expression, the `evaluate` method looks for a `geometry` and `canonicalTileID` before it proceeds with checking the feature. This ensures that the feature is a valid geometry object.

https://github.com/mapbox/mapbox-gl-js/blob/e1e68a80ca83c3f52ff16b7d3eb1b011027bd2b1/src/style-spec/expression/definitions/within.js#L319-L328

In `querySourceFeatures` however, the `feature` is a `VectorTileFeature` because the GeoJSON has been tiled by this point. It's not the same feature as shown above that has the `geometry` and `canonicalTileID` so when the expression is evaluated, it can't get a valid geometry.

https://github.com/mapbox/mapbox-gl-js/blob/e1e68a80ca83c3f52ff16b7d3eb1b011027bd2b1/src/source/tile.js#L293-L317

**Comment by asheemmamoowala** [comment]
cc @zmiao

**Comment by AdriSolid** [comment]
@ryanhamley thanks for your technical answer, I understand what you mean. FYI, it also happens when trying to filter vector tiles layers, something like this, I guess it is the same:

```javascript
const filteredFeatures = map.querySourceFeatures("vector-source", {
  filter: ["within", mask],
  sourceLayer: "points",
}); 
```

**Comment by AdriSolid** [comment]
@zmiao thanks!
