### ISSUE TITLE
Filter with ['any', X, Y] behaving differently from ['any', Y, X]

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#9928]
**mapbox-gl-js version**: 1.12.0

**browser**: FF

### Steps to Trigger Behavior

I have a layer with this filter:

```
                    filter: [
                        "any",
                        ["get", commodity],
                        ["==", ["get", "commodity"], commodity]
                    ]
```

It is rendering as though the second option (`['=='...`) wasn't there.

When I flip the order of the parameters:

```
                    filter: [
                        "any",
                        ["==", ["get", "commodity"], commodity],
                        ["get", commodity],
                    ]
```

it behaves correctly. In this particular data, each point has either a `commodity` field with a value like "Fe", or possibly individual fields: `"Fe": true, "Au": false` etc.

### Link to Demonstration

I'm not in a position to share this data or create a reproducible example right now. However, since this looks like a parsing issue, it should be reproducible from the above.

### Expected Behavior

Order of expressions within an `any` expression should never change the result.

**Comment by mourner** [comment]
@stevage did you look for warnings in the console? It should say `Expected value to be of type boolean, but found null instead.`.

As far as I understand, what happens is `filter` expects a boolean value, and when `["get", commodity]` returns `null` in case there's no such property, the whole expression bails out with an error instead completing.

To make it work, replace `["get", commodity]` with `["boolean", ["get", commodity], false]` so that the expression doesn't fail if the property's not there.
