### ISSUE TITLE
Mapbox Style with Multi-condition query found error

### ISSUE THREAD

**Issue by FreeGIS** [mapbox/mapbox-gl-js#9935]
**mapbox-gl-js version**:v1.12.0

**browser**:google  84.0.4147.125

### Steps to Trigger Behavior

 1. The Style as follow:
`"filter": ['all',[">=", ["to-number",  ["get", "value"]],5],["==", "ybsk", 0]],`
the error was printed:
` layers.flowLayer.filter[1][1]: string expected, array found`
 2. when i used in single condition:
`
"filter": ['all',[">=", ["to-number",  ["get", "value"]],5]],  `
  or 
`"filter": ['all',["==", "ybsk", 0]],  `
the result is ok.
`
Link to Demonstration
[https://output.jsbin.com/rakatiq](https://output.jsbin.com/rakatiq)
So i suspect there is a problem with the style caused by array parsing in mapbox gl API

**Comment by mourner** [comment]
Thanks for the live test case! This happens due to the fact that GL JS still has to support the legacy filter syntax (that was there before expressions were introduced), so we have to use certain heuristics to try to distinguish between the two. In the example above, GL JS detects `["==", "ybsk", 0]` as a legacy filter syntax, because with an expression, you would instead write `["==", ["get", "ybsk"], 0]` (which is the fix you're looking for).

We could try to make it less confusing by improving the heuristics so that it throws a more intuitive error (e.g. "filter[2]: can't compare a string and a number"), but since we're intending to eventually phase out the legacy filter support anyway, I'm inclined to close the issue.

**Comment by FreeGIS** [comment]
Thanks for you help,I have solved this problem。
the error:
`"filter": ['all',
	        ["==", "qbsj", qbsj],
		["==", "ybsk", 0],
		[">=", ["to-number",["get", "value"]],5]
	]`;
the fixed:
"filter": ['all',
		["==", ["get", "qbsj"], qbsj],
		["==", ["get", "ybsk"], 0],
		[">=", ["to-number",["get", "value"]],5]
	]`
`
