### ISSUE TITLE
ANDROID: How can i get the event on click of Markers on map andriod , I've tried "setOnMarkerClickListener" but its deprecated. 

### ISSUE THREAD

**Issue by pavvvan** [mapbox/mapbox-gl-js#9940]
**mapbox-gl-js version**:

### Question

Hi all,

Please suggest me how can handle the event of on MARKER click on map view , I've tried setOnMarkerClickListener but its deprecated  and gone through all the docs , but nothing usefull , am really frustrated .

Please advise me solution for this

Thanks in Advance

**Comment by ryanhamley** [comment]
Hi @pavvvan this is the repo for GL JS, the Javascript library for Mapbox GL. You're looking for https://github.com/mapbox/mapbox-gl-native. For general support and how-to questions however, I'd suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us) directly rather than opening an issue. Thanks!
