### ISSUE TITLE
Incorrect icon sizing when `sdf:true` for image

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#9954]
example: https://jsfiddle.net/2zyx4mrL/

Situation:
I want to use two images for a symbol (background, icon), also want to dynamic style halo and icon color of background.
For this i use `"icon-image": "bg,` and `"text-field": ["format", ["image", "icon"]]` where bg was loaded as sdf

Problems:
 - only with this parameters the images woudnt be shown. Only by setting the `"icon-size": 40` and `"icon-allow-overlap": true, "text-allow-overlap": true,` it would shown.
Maybe at this point the sizing is wrong. 
- If you click in the example over or right next of the icon the feature will be selected.
- Also many icons will be merged together 
![image](https://user-images.githubusercontent.com/7572377/91327794-4f685580-e7c6-11ea-932e-c998788eff84.png)

**Comment by arindam1993** [comment]
Thanks for the report @strech345 , looks like an issue with icon scaling when `sdf:true`. Here's ascreenshot with collision boxes for your example.
<img width="1625" alt="Screen Shot 2020-08-26 at 12 52 18 PM" src="https://user-images.githubusercontent.com/1449257/91350046-ff27ce00-e79a-11ea-8a4b-bb974ddb07d5.png">
There are giant boxes that stretch the entire width of the screen. This causes them to always collide each other out.

Not passing the sdf flag seems to fix the problem.

**Comment by xabbu42** [comment]
As far as i can see, there is no code taking sdf:true in account for the collision boxes. as the example uses icon-size: 40, the huge collision boxes probably are just the result of multipling the icon size of 38px with 40. What we would need is to apply some negative padding before multipling with the icon-size. but neither content in the sprite json nor icon-padding allow negative values. One solution imho would be to have another box in the sprite json similar to content but for collision, which describes the part of the image which can collide. Of course we could also calculate that from the image itself, but perhaps there are use cases for this feature outside of sdf icons?

I can try my hand at a pull request, but I'd rather first have some feedback if my interpretation is correct and that solution has a chance to be accepted.

**Comment by enersis-pst** [comment]
@xabbu42 
for me it doesnt look like a problem of padding. I mean i can set the icon-size to 1, then the collision box is correct but the image size is to small.
The problem is gone by not using sdf or dont use a image inside of the text-field. So it only appears in this case.

**Comment by xabbu42** [comment]
the problem is that an sdf image necessarily includes some padding in the image itself. that is why you have a small image when you set the icon-size to 1 even so the sdf itself is 38px. the collision box should not cover the full 38px*40 (or your 38px*1 for your small case) but only the much smaller box with actual drawn icon after converting back from sdf. negative padding could help to offset that padding included in the sdf image and is potentially simpler than actually determining the correct bbox from the sdf itself.

**Comment by enersis-pst** [comment]
but all fits if i remove the image expression from text-field.

**Comment by xabbu42** [comment]
which is consistent with my theory as the image itself is an sdf image.

**Comment by enersis-pst** [comment]
ok, then maybe i miss understood :-)
here is the working example without the image expresion by the way ;-)
https://jsfiddle.net/Lu23wq0m/7/

**Comment by xabbu42** [comment]
oh so your point is that image-size 40 should not be necessary for the background to be visible. this seems correct and is indeed the root problem here. notice so that even in your example the bounding box does include some padding compared to the visible icon, thats the smaller problem i was talking about and mistakenly thought is the root problem here.

**Comment by enersis-pst** [comment]
> oh so your point is that image-size 40 should not be necessary for the background to be visible. 

right

**Comment by enersis-pst** [comment]
@xabbu42 do you know if this could be easy fixed?

**Comment by strech345** [comment]
Looks for me that with version 3.8 it is working correctly. nice :-)
