### ISSUE TITLE
Collision detection running when it shouldn't?

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-gl-js#9958]
Hi there,

I'm seeing the collision detection working when I *think* it shouldn't, but I could be misunderstanding how this is supposed to work.

I've tried to create a minimal case here:

style:
mapbox://styles/liebrand/ckee9pgbf0p6l19oyzvro3k65

basically I have a symbol layer and set some text (e.g. 'X') for every point. I then allow overlap and ignore placement. As far as I understand, that should mean that it needn't do any collision detection (and should thus not get slowed down by collision detection)?

When I show the collision boxes in the debugger, I notice that when I zoom in/out, all the boxes do flash red when it transitions from one zoom level to the next. Continuing zoom turns them blue again, but surely they should never turn red? E.g. it should never be doing collision detection?

Here's a screenshot of the boxes turning red (note: I'm referring to the boxes around the X's not the placename labels):

![image](https://user-images.githubusercontent.com/23407884/91567015-5f09aa80-e93c-11ea-8e07-fba2ac20bd19.png)

(note: the original issue I have is that a particular style I have is rather slow. I'm suspecting because it has a lot of symbol layers, all of which should not be doing collision detection, but if it *is* doing it, then clearly that would slow things down)

**Comment by ansis** [comment]
I don't think the red boxes are an issue here. When zooming mapbox-gl-js sometimes has to render a parent and child tile that overlap. In this case it needs to hide the symbol from one of those tiles so that it isn't rendered twice. I think that's what the red box means in this case.

If the style seems surprisingly slow (compared to mapbox-streets) please open a separate issue
