### ISSUE TITLE
Having Cluster Label refer to a value from properties

### ISSUE THREAD

**Issue by boldfish1121** [mapbox/mapbox-gl-js#9969]
I have a list of houses with a property called `home_price`. 

I want to set up a cluster layer to cluster each point. 
however, I want the cluster label to show the sum of all the home_price instead of the number of points in the cluster. 

Is this possible to do?

**Comment by ryanhamley** [comment]
I think you're looking for something like what's described in the Clustering Properties section of https://blog.mapbox.com/clustering-properties-with-mapbox-and-html-markers-bb353c8662ba

Since this is a support question, if you need further guidance, please contact [Mapbox Support](http://support.mapbox.com/)

**Comment by SaltyAga** [comment]
@boldfish1121 were you able to find a solution?
