### ISSUE TITLE
Is it possible to display multiple instances of map?

### ISSUE THREAD

**Issue by Rumpelstinsk** [mapbox/mapbox-gl-js#9975]
### Question
I need to display multiple maps on an application. However, it only displays the first 15 instances. The next instances appears as broken imagen and the console shows a warning.

`Too many active WebGL contexts. Oldest context will be lost` 

So:
- Is it possible to show more than 15 instances?
- Is it possible to create a single WebGL Context to be shared across all the instances?
- Removing your canvas from the DOM (removing the parent div for example), will clean the WebGL Context?

**Comment by ryanhamley** [comment]
> Is it possible to show more than 15 instances?

No, this is a browser limitation that we can't control. Even one context per tab will cause this if you have enough tabs open.

> Is it possible to create a single WebGL Context to be shared across all the instances?

Not really. There'd be a lot of contamination and collisions between the data for each map. And it's not possible to do this as an end user since the contexts are created internally to the library.

> Removing your canvas from the DOM (removing the parent div for example), will clean the WebGL Context?

Yes. You can see that the `remove` function calls `extension.loseContext()`.

https://github.com/mapbox/mapbox-gl-js/blob/f2117b4ef501bbab298898e4f6c34083178d519a/src/ui/map.js#L2551-L2583

There's not really a good workaround for having so many maps at once because of the browser limitation. There's a few things that may help depending on your use case:

- only load a map when it scrolls into view
- use a static image map until/unless a fully interactive map is needed (e.g. when a user clicks the map, the static image is replaced with a GL JS map)
- call `map.remove()` when a map is unnecessary (if the route is navigated away from in a SPA or the map is scrolled out of view)

If you need additional support, you can contact [Mapbox Support](http://support.mapbox.com/).
