### ISSUE TITLE
Geometries across 180 or -180 parallel

### ISSUE THREAD

**Issue by NasH5169** [mapbox/mapbox-gl-js#9977]
Hello,

I've made some searches on this subject without found any info.

The geometries (line or polygon) which have vertices west of 180 and east of 180 (or -180) are displayed across all the earth instead of locally.

Please find a very simple example of this issue: https://jsfiddle.net/vstak6c1/

Any workaround or idea?

Thanks!

**Comment by mourner** [comment]
There's no way to tell if you really mean "a line from 179 to -179, spanning the world", or "go the other way because it's closer" — specifications don't define this behavior. So we don't do any heuristics around this. The best workaround is to do it on the data side, e.g. for the example above, do the line from 179 to 181.

**Comment by NasH5169** [comment]
OK. Perfect. I will update my data. Thanks.
